<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddRecordsToCitiesTable2 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('cities')->insert(
            array(
                array('id' => 2001, 'county_id' => '263', 'value' => 'GENERAL GALARZA'),
                array('id' => 2002, 'county_id' => '263', 'value' => 'GUALEGUAY'),
                array('id' => 2003, 'county_id' => '263', 'value' => 'PUERTO RUIZ'),
                array('id' => 2004, 'county_id' => '264', 'value' => 'ALDEA SAN ANTONIO'),
                array('id' => 2005, 'county_id' => '264', 'value' => 'ALDEA SAN JUAN'),
                array('id' => 2006, 'county_id' => '264', 'value' => 'ENRIQUE CARBO'),
                array('id' => 2007, 'county_id' => '264', 'value' => 'ESTACION ESCRIÑA'),
                array('id' => 2008, 'county_id' => '264', 'value' => 'FAUSTINO M. PARERA'),
                array('id' => 2009, 'county_id' => '264', 'value' => 'GENERAL ALMADA'),
                array('id' => 2010, 'county_id' => '264', 'value' => 'GILBERT'),
                array('id' => 2011, 'county_id' => '264', 'value' => 'GUALEGUAYCHU'),
                array('id' => 2012, 'county_id' => '264', 'value' => 'IRAZUSTA'),
                array('id' => 2013, 'county_id' => '264', 'value' => 'LARROQUE'),
                array('id' => 2014, 'county_id' => '264', 'value' => 'PASTOR BRITOS'),
                array('id' => 2015, 'county_id' => '264', 'value' => 'PUEBLO GENERAL BELGRANO'),
                array('id' => 2016, 'county_id' => '264', 'value' => 'URDINARRAIN'),
                array('id' => 2017, 'county_id' => '265', 'value' => 'CEIBAS'),
                array('id' => 2018, 'county_id' => '265', 'value' => 'IBICUY'),
                array('id' => 2019, 'county_id' => '265', 'value' => 'MEDANOS'),
                array('id' => 2020, 'county_id' => '265', 'value' => 'VILLA PARANACITO'),
                array('id' => 2021, 'county_id' => '266', 'value' => 'ALCARAZ'),
                array('id' => 2022, 'county_id' => '266', 'value' => 'BOVRIL'),
                array('id' => 2023, 'county_id' => '266', 'value' => 'COLONIA AVIGDOR'),
                array('id' => 2024, 'county_id' => '266', 'value' => 'EL SOLAR'),
                array('id' => 2025, 'county_id' => '266', 'value' => 'LA PAZ'),
                array('id' => 2026, 'county_id' => '266', 'value' => 'PIEDRAS BLANCAS'),
                array('id' => 2027, 'county_id' => '266', 'value' => 'SAN GUSTAVO'),
                array('id' => 2028, 'county_id' => '266', 'value' => 'SANTA ELENA'),
                array('id' => 2029, 'county_id' => '266', 'value' => 'SIR LEONARD'),
                array('id' => 2030, 'county_id' => '267', 'value' => 'ARANGUREN'),
                array('id' => 2031, 'county_id' => '267', 'value' => 'BETBEDER'),
                array('id' => 2032, 'county_id' => '267', 'value' => 'DON CRISTOBAL'),
                array('id' => 2033, 'county_id' => '267', 'value' => 'FEBRE'),
                array('id' => 2034, 'county_id' => '267', 'value' => 'HERNANDEZ'),
                array('id' => 2035, 'county_id' => '267', 'value' => 'LUCAS GONZALEZ'),
                array('id' => 2036, 'county_id' => '267', 'value' => 'NOGOYA'),
                array('id' => 2037, 'county_id' => '267', 'value' => 'XX DE SETIEMBRE'),
                array('id' => 2038, 'county_id' => '268', 'value' => 'ALDEA MARIA LUISA'),
                array('id' => 2039, 'county_id' => '268', 'value' => 'ALDEA SAN JUAN'),
                array('id' => 2040, 'county_id' => '268', 'value' => 'ALDEA SAN RAFAEL'),
                array('id' => 2041, 'county_id' => '268', 'value' => 'ALDEA SANTA MARIA'),
                array('id' => 2042, 'county_id' => '268', 'value' => 'ALDEA SANTA ROSA'),
                array('id' => 2043, 'county_id' => '268', 'value' => 'CERRITO'),
                array('id' => 2044, 'county_id' => '268', 'value' => 'COLONIA AVELLANEDA'),
                array('id' => 2045, 'county_id' => '268', 'value' => 'COLONIA CRESPO'),
                array('id' => 2046, 'county_id' => '268', 'value' => 'CRESPO'),
                array('id' => 2047, 'county_id' => '268', 'value' => 'EL PALENQUE'),
                array('id' => 2048, 'county_id' => '268', 'value' => 'EL PINGO'),
                array('id' => 2049, 'county_id' => '268', 'value' => 'EL RAMBLON'),
                array('id' => 2050, 'county_id' => '268', 'value' => 'HASENKAMP'),
                array('id' => 2051, 'county_id' => '268', 'value' => 'HERNANDARIAS'),
                array('id' => 2052, 'county_id' => '268', 'value' => 'LA PICADA'),
                array('id' => 2053, 'county_id' => '268', 'value' => 'LAS TUNAS'),
                array('id' => 2054, 'county_id' => '268', 'value' => 'MARIA GRANDE'),
                array('id' => 2055, 'county_id' => '268', 'value' => 'ORO VERDE'),
                array('id' => 2056, 'county_id' => '268', 'value' => 'PARANA'),
                array('id' => 2057, 'county_id' => '268', 'value' => 'PUEBLO BELLOCQ'),
                array('id' => 2058, 'county_id' => '268', 'value' => 'PUEBLO BRUGO'),
                array('id' => 2059, 'county_id' => '268', 'value' => 'PUEBLO GENERAL SAN MARTIN'),
                array('id' => 2060, 'county_id' => '268', 'value' => 'PUEBLO MORENO'),
                array('id' => 2061, 'county_id' => '268', 'value' => 'SAN BENITO'),
                array('id' => 2062, 'county_id' => '268', 'value' => 'SAUCE MONTRULL'),
                array('id' => 2063, 'county_id' => '268', 'value' => 'SAUCE PINTO'),
                array('id' => 2064, 'county_id' => '268', 'value' => 'SEGUI'),
                array('id' => 2065, 'county_id' => '268', 'value' => 'SOSA'),
                array('id' => 2066, 'county_id' => '268', 'value' => 'TABOSSI'),
                array('id' => 2067, 'county_id' => '268', 'value' => 'TEZANOS PINTO'),
                array('id' => 2068, 'county_id' => '268', 'value' => 'VIALE'),
                array('id' => 2069, 'county_id' => '268', 'value' => 'VILLA FONTANA'),
                array('id' => 2070, 'county_id' => '268', 'value' => 'VILLA GOBERNADOR LUIS F. ETCHEVEHERE'),
                array('id' => 2071, 'county_id' => '268', 'value' => 'VILLA URQUIZA'),
                array('id' => 2072, 'county_id' => '269', 'value' => 'GENERAL CAMPOS'),
                array('id' => 2073, 'county_id' => '269', 'value' => 'SAN SALVADOR'),
                array('id' => 2074, 'county_id' => '270', 'value' => 'ALTAMIRANO SUR'),
                array('id' => 2075, 'county_id' => '270', 'value' => 'DURAZNO'),
                array('id' => 2076, 'county_id' => '270', 'value' => 'ESTACION ARROYO CLE'),
                array('id' => 2077, 'county_id' => '270', 'value' => 'GOBERNADOR ECHAGUE'),
                array('id' => 2078, 'county_id' => '270', 'value' => 'GOBERNADOR MANSILLA'),
                array('id' => 2079, 'county_id' => '270', 'value' => 'GOBERNADOR SOLA'),
                array('id' => 2080, 'county_id' => '270', 'value' => 'GUARDAMONTE'),
                array('id' => 2081, 'county_id' => '270', 'value' => 'LAS GUACHAS'),
                array('id' => 2082, 'county_id' => '270', 'value' => 'MACIA'),
                array('id' => 2083, 'county_id' => '270', 'value' => 'ROSARIO DEL TALA'),
                array('id' => 2084, 'county_id' => '271', 'value' => '1 DE MAYO'),
                array('id' => 2085, 'county_id' => '271', 'value' => 'BASAVILBASO'),
                array('id' => 2086, 'county_id' => '271', 'value' => 'CASEROS'),
                array('id' => 2087, 'county_id' => '271', 'value' => 'COLONIA ELIA'),
                array('id' => 2088, 'county_id' => '271', 'value' => 'CONCEPCION DEL URUGUAY'),
                array('id' => 2089, 'county_id' => '271', 'value' => 'HERRERA'),
                array('id' => 2090, 'county_id' => '271', 'value' => 'LAS MOSCAS'),
                array('id' => 2091, 'county_id' => '271', 'value' => 'LIBAROS'),
                array('id' => 2092, 'county_id' => '271', 'value' => 'PRONUNCIAMIENTO'),
                array('id' => 2093, 'county_id' => '271', 'value' => 'ROCAMORA'),
                array('id' => 2094, 'county_id' => '271', 'value' => 'SANTA ANITA'),
                array('id' => 2095, 'county_id' => '271', 'value' => 'VILLA MANTERO'),
                array('id' => 2096, 'county_id' => '271', 'value' => 'VILLA SAN JUSTO'),
                array('id' => 2097, 'county_id' => '271', 'value' => 'VILLA SAN MARCIAL'),
                array('id' => 2098, 'county_id' => '272', 'value' => 'ANTELO'),
                array('id' => 2099, 'county_id' => '272', 'value' => 'MOLINO DOLL'),
                array('id' => 2100, 'county_id' => '272', 'value' => 'VICTORIA'),
                array('id' => 2101, 'county_id' => '273', 'value' => 'ESTACION RAICES'),
                array('id' => 2102, 'county_id' => '273', 'value' => 'INGENIERO MIGUEL SAJAROFF'),
                array('id' => 2103, 'county_id' => '273', 'value' => 'JUBILEO'),
                array('id' => 2104, 'county_id' => '273', 'value' => 'PASO DE LA LAGUNA'),
                array('id' => 2105, 'county_id' => '273', 'value' => 'VILLA CLARA'),
                array('id' => 2106, 'county_id' => '273', 'value' => 'VILLA DOMINGUEZ'),
                array('id' => 2107, 'county_id' => '273', 'value' => 'VILLAGUAY'),
                array('id' => 2108, 'county_id' => '274', 'value' => 'GUADALCAZAR'),
                array('id' => 2109, 'county_id' => '274', 'value' => 'LA RINCONADA'),
                array('id' => 2110, 'county_id' => '274', 'value' => 'LA SOLEDAD'),
                array('id' => 2111, 'county_id' => '274', 'value' => 'LAGUNA YEMA'),
                array('id' => 2112, 'county_id' => '274', 'value' => 'LAMADRID'),
                array('id' => 2113, 'county_id' => '274', 'value' => 'LOS CHIRIGUANOS'),
                array('id' => 2114, 'county_id' => '274', 'value' => 'POZO DE MAZA'),
                array('id' => 2115, 'county_id' => '274', 'value' => 'POZO DEL MORTERO'),
                array('id' => 2116, 'county_id' => '274', 'value' => 'VACA PERDIDA'),
                array('id' => 2117, 'county_id' => '275', 'value' => 'COLONIA PASTORIL'),
                array('id' => 2118, 'county_id' => '275', 'value' => 'FORMOSA'),
                array('id' => 2119, 'county_id' => '275', 'value' => 'GRAN GUARDIA'),
                array('id' => 2120, 'county_id' => '275', 'value' => 'MARIANO BOEDO'),
                array('id' => 2121, 'county_id' => '275', 'value' => 'MOJON DE FIERRO'),
                array('id' => 2122, 'county_id' => '275', 'value' => 'SAN HILARIO'),
                array('id' => 2123, 'county_id' => '275', 'value' => 'VILLA DEL CARMEN'),
                array('id' => 2124, 'county_id' => '276', 'value' => 'BANCO PAYAGUA'),
                array('id' => 2125, 'county_id' => '276', 'value' => 'GENERAL LUCIO V MANSILLA'),
                array('id' => 2126, 'county_id' => '276', 'value' => 'HERRADURA'),
                array('id' => 2127, 'county_id' => '276', 'value' => 'SAN FRANCISCO DE LAISHI'),
                array('id' => 2128, 'county_id' => '276', 'value' => 'TATANE'),
                array('id' => 2129, 'county_id' => '276', 'value' => 'VILLA ESCOLAR'),
                array('id' => 2130, 'county_id' => '277', 'value' => 'INGENIERO GUILLERMO N. JUAREZ'),
                array('id' => 2131, 'county_id' => '278', 'value' => 'BARTOLOME DE LAS CASAS'),
                array('id' => 2132, 'county_id' => '278', 'value' => 'COLONIA SARMIENTO'),
                array('id' => 2133, 'county_id' => '278', 'value' => 'COMANDANTE FONTANA'),
                array('id' => 2134, 'county_id' => '278', 'value' => 'COMUNIDAD ABORIGEN BARTOLOME DE LAS CASAS'),
                array('id' => 2135, 'county_id' => '278', 'value' => 'EL RECREO'),
                array('id' => 2136, 'county_id' => '278', 'value' => 'ESTANISLAO DEL CAMPO'),
                array('id' => 2137, 'county_id' => '278', 'value' => 'FORTIN CABO 1Â° LUGONES'),
                array('id' => 2138, 'county_id' => '278', 'value' => 'FORTIN SARGENTO 1Â° LEYES'),
                array('id' => 2139, 'county_id' => '278', 'value' => 'IBARRETA'),
                array('id' => 2140, 'county_id' => '278', 'value' => 'JUAN G. BAZAN'),
                array('id' => 2141, 'county_id' => '278', 'value' => 'LAS LOMITAS'),
                array('id' => 2142, 'county_id' => '278', 'value' => 'POSTA CAMBIO ZALAZAR'),
                array('id' => 2143, 'county_id' => '278', 'value' => 'POZO DEL TIGRE'),
                array('id' => 2144, 'county_id' => '278', 'value' => 'SAN MARTIN I'),
                array('id' => 2145, 'county_id' => '278', 'value' => 'SAN MARTIN II'),
                array('id' => 2146, 'county_id' => '278', 'value' => 'SUBTENIENTE PERIN'),
                array('id' => 2147, 'county_id' => '278', 'value' => 'VILLA GENERAL GUEMES'),
                array('id' => 2148, 'county_id' => '278', 'value' => 'VILLA GENERAL MANUEL BELGRANO'),
                array('id' => 2149, 'county_id' => '279', 'value' => 'BUENA VISTA'),
                array('id' => 2150, 'county_id' => '279', 'value' => 'EL ESPINILLO'),
                array('id' => 2151, 'county_id' => '279', 'value' => 'LAGUNA GALLO'),
                array('id' => 2152, 'county_id' => '279', 'value' => 'MISION TACAAGLE'),
                array('id' => 2153, 'county_id' => '279', 'value' => 'PORTON NEGRO'),
                array('id' => 2154, 'county_id' => '279', 'value' => 'TRES LAGUNAS'),
                array('id' => 2155, 'county_id' => '280', 'value' => 'CLORINDA'),
                array('id' => 2156, 'county_id' => '280', 'value' => 'LAGUNA BLANCA'),
                array('id' => 2157, 'county_id' => '280', 'value' => 'LAGUNA NAICK-NECK'),
                array('id' => 2158, 'county_id' => '280', 'value' => 'PALMA SOLA'),
                array('id' => 2159, 'county_id' => '280', 'value' => 'PUERTO PILCOMAYO'),
                array('id' => 2160, 'county_id' => '280', 'value' => 'RIACHO HE-HE'),
                array('id' => 2161, 'county_id' => '280', 'value' => 'RIACHO NEGRO'),
                array('id' => 2162, 'county_id' => '280', 'value' => 'SIETE PALMAS'),
                array('id' => 2163, 'county_id' => '281', 'value' => 'COLONIA CAMPO VILLAFAÑE'),
                array('id' => 2164, 'county_id' => '281', 'value' => 'EL COLORADO'),
                array('id' => 2165, 'county_id' => '281', 'value' => 'PALO SANTO'),
                array('id' => 2166, 'county_id' => '281', 'value' => 'PIRANE'),
                array('id' => 2167, 'county_id' => '281', 'value' => 'VILLA KILOMETRO 213'),
                array('id' => 2168, 'county_id' => '282', 'value' => 'EL POTRILLO'),
                array('id' => 2169, 'county_id' => '282', 'value' => 'EL QUEBRACHO'),
                array('id' => 2170, 'county_id' => '282', 'value' => 'GENERAL MOSCONI'),
                array('id' => 2171, 'county_id' => '283', 'value' => 'ABDON CASTRO TOLAY'),
                array('id' => 2172, 'county_id' => '283', 'value' => 'ABRA PAMPA'),
                array('id' => 2173, 'county_id' => '283', 'value' => 'ABRALAITE'),
                array('id' => 2174, 'county_id' => '283', 'value' => 'AGUA DE CASTILLA'),
                array('id' => 2175, 'county_id' => '283', 'value' => 'CASABINDO'),
                array('id' => 2176, 'county_id' => '283', 'value' => 'COCHINOCA'),
                array('id' => 2177, 'county_id' => '283', 'value' => 'LA REDONDA'),
                array('id' => 2178, 'county_id' => '283', 'value' => 'PUESTO DEL MARQUEZ'),
                array('id' => 2179, 'county_id' => '283', 'value' => 'QUEBRALEÑA'),
                array('id' => 2180, 'county_id' => '283', 'value' => 'QUERA'),
                array('id' => 2181, 'county_id' => '283', 'value' => 'RINCONADILLAS'),
                array('id' => 2182, 'county_id' => '283', 'value' => 'SAN FRANCISCO DE ALFARCITO'),
                array('id' => 2183, 'county_id' => '283', 'value' => 'SANTA ANA DE LA PUNA'),
                array('id' => 2184, 'county_id' => '283', 'value' => 'SANTUARIO DE TRES POZOS'),
                array('id' => 2185, 'county_id' => '283', 'value' => 'TAMBILLOS'),
                array('id' => 2186, 'county_id' => '283', 'value' => 'TUSAQUILLAS'),
                array('id' => 2187, 'county_id' => '284', 'value' => 'GUERRERO'),
                array('id' => 2188, 'county_id' => '284', 'value' => 'LA ALMONA'),
                array('id' => 2189, 'county_id' => '284', 'value' => 'LEON'),
                array('id' => 2190, 'county_id' => '284', 'value' => 'LOS NOGALES'),
                array('id' => 2191, 'county_id' => '284', 'value' => 'LOZANO'),
                array('id' => 2192, 'county_id' => '284', 'value' => 'OCLOYAS'),
                array('id' => 2193, 'county_id' => '284', 'value' => 'SAN PABLO DE REYES'),
                array('id' => 2194, 'county_id' => '284', 'value' => 'SAN SALVADOR DE JUJUY'),
                array('id' => 2195, 'county_id' => '284', 'value' => 'TESORERO'),
                array('id' => 2196, 'county_id' => '284', 'value' => 'YALA'),
                array('id' => 2197, 'county_id' => '285', 'value' => 'AGUAS CALIENTES'),
                array('id' => 2198, 'county_id' => '285', 'value' => 'BARRIO EL MILAGRO'),
                array('id' => 2199, 'county_id' => '285', 'value' => 'BARRIO LA UNION'),
                array('id' => 2200, 'county_id' => '285', 'value' => 'EL CARMEN'),
                array('id' => 2201, 'county_id' => '285', 'value' => 'FLEMING'),
                array('id' => 2202, 'county_id' => '285', 'value' => 'LOS LAPACHOS'),
                array('id' => 2203, 'county_id' => '285', 'value' => 'MANANTIALES'),
                array('id' => 2204, 'county_id' => '285', 'value' => 'MONTERRICO'),
                array('id' => 2205, 'county_id' => '285', 'value' => 'PAMPA BLANCA'),
                array('id' => 2206, 'county_id' => '285', 'value' => 'PERICO'),
                array('id' => 2207, 'county_id' => '285', 'value' => 'PILA PARDO'),
                array('id' => 2208, 'county_id' => '285', 'value' => 'PUESTO VIEJO'),
                array('id' => 2209, 'county_id' => '285', 'value' => 'SAN ISIDRO'),
                array('id' => 2210, 'county_id' => '285', 'value' => 'SAN JUANCITO'),
                array('id' => 2211, 'county_id' => '285', 'value' => 'SAN VICENTE'),
                array('id' => 2212, 'county_id' => '286', 'value' => 'APARZO'),
                array('id' => 2213, 'county_id' => '286', 'value' => 'CIANZO'),
                array('id' => 2214, 'county_id' => '286', 'value' => 'COCTACA'),
                array('id' => 2215, 'county_id' => '286', 'value' => 'EL AGUILAR'),
                array('id' => 2216, 'county_id' => '286', 'value' => 'HIPOLITO YRIGOYEN'),
                array('id' => 2217, 'county_id' => '286', 'value' => 'HUMAHUACA'),
                array('id' => 2218, 'county_id' => '286', 'value' => 'PALCA DE APARZO'),
                array('id' => 2219, 'county_id' => '286', 'value' => 'PALCA DE VARAS'),
                array('id' => 2220, 'county_id' => '286', 'value' => 'RODERO'),
                array('id' => 2221, 'county_id' => '286', 'value' => 'TRES CRUCES'),
                array('id' => 2222, 'county_id' => '286', 'value' => 'UQUIA'),
                array('id' => 2223, 'county_id' => '287', 'value' => 'BANANAL'),
                array('id' => 2224, 'county_id' => '287', 'value' => 'BERMEJITO'),
                array('id' => 2225, 'county_id' => '287', 'value' => 'CAIMANCITO'),
                array('id' => 2226, 'county_id' => '287', 'value' => 'CALILEGUA'),
                array('id' => 2227, 'county_id' => '287', 'value' => 'CHALICAN'),
                array('id' => 2228, 'county_id' => '287', 'value' => 'FRAILE PINTADO'),
                array('id' => 2229, 'county_id' => '287', 'value' => 'LIBERTAD'),
                array('id' => 2230, 'county_id' => '287', 'value' => 'LIBERTADOR GENERAL SAN MARTIN'),
                array('id' => 2231, 'county_id' => '287', 'value' => 'MAIZ NEGRO'),
                array('id' => 2232, 'county_id' => '287', 'value' => 'PAULINA'),
                array('id' => 2233, 'county_id' => '287', 'value' => 'PUEBLO LEDESMA'),
                array('id' => 2234, 'county_id' => '287', 'value' => 'YUTO'),
                array('id' => 2235, 'county_id' => '288', 'value' => 'CARAHUNCO'),
                array('id' => 2236, 'county_id' => '288', 'value' => 'CENTRO FORESTAL'),
                array('id' => 2237, 'county_id' => '288', 'value' => 'PALPALA'),
                array('id' => 2238, 'county_id' => '288', 'value' => 'RIO BLANCO'),
                array('id' => 2239, 'county_id' => '289', 'value' => 'CASA COLORADA'),
                array('id' => 2240, 'county_id' => '289', 'value' => 'COYAGUAIMA'),
                array('id' => 2241, 'county_id' => '289', 'value' => 'LAGUNILLAS DE FARALLON'),
                array('id' => 2242, 'county_id' => '289', 'value' => 'LIVIARA'),
                array('id' => 2243, 'county_id' => '289', 'value' => 'LOMA BLANCA'),
                array('id' => 2244, 'county_id' => '289', 'value' => 'NUEVO PIRQUITAS'),
                array('id' => 2245, 'county_id' => '289', 'value' => 'OROSMAYO'),
                array('id' => 2246, 'county_id' => '289', 'value' => 'RINCONADA'),
                array('id' => 2247, 'county_id' => '290', 'value' => 'EL CEIBAL'),
                array('id' => 2248, 'county_id' => '290', 'value' => 'LA TOMA'),
                array('id' => 2249, 'county_id' => '290', 'value' => 'LOS ALISOS'),
                array('id' => 2250, 'county_id' => '290', 'value' => 'LOTEO NAVEA'),
                array('id' => 2251, 'county_id' => '290', 'value' => 'NUESTRA SE?ORA DEL ROSARIO'),
                array('id' => 2252, 'county_id' => '290', 'value' => 'SAN ANTONIO'),
                array('id' => 2253, 'county_id' => '291', 'value' => 'ARRAYANAL'),
                array('id' => 2254, 'county_id' => '291', 'value' => 'ARROYO COLORADO'),
                array('id' => 2255, 'county_id' => '291', 'value' => 'DON EMILIO'),
                array('id' => 2256, 'county_id' => '291', 'value' => 'EL ACHERAL'),
                array('id' => 2257, 'county_id' => '291', 'value' => 'EL PUESTO'),
                array('id' => 2258, 'county_id' => '291', 'value' => 'EL QUEMADO'),
                array('id' => 2259, 'county_id' => '291', 'value' => 'LA ESPERANZA'),
                array('id' => 2260, 'county_id' => '291', 'value' => 'LA MANGA'),
                array('id' => 2261, 'county_id' => '291', 'value' => 'LA MENDIETA'),
                array('id' => 2262, 'county_id' => '291', 'value' => 'MIRAFLORES'),
                array('id' => 2263, 'county_id' => '291', 'value' => 'PALOS BLANCOS'),
                array('id' => 2264, 'county_id' => '291', 'value' => 'PARAPETI'),
                array('id' => 2265, 'county_id' => '291', 'value' => 'PIEDRITAS'),
                array('id' => 2266, 'county_id' => '291', 'value' => 'RODEITO'),
                array('id' => 2267, 'county_id' => '291', 'value' => 'ROSARIO DE RIO GRANDE'),
                array('id' => 2268, 'county_id' => '291', 'value' => 'SAN ANTONIO'),
                array('id' => 2269, 'county_id' => '291', 'value' => 'SAN LUCAS'),
                array('id' => 2270, 'county_id' => '291', 'value' => 'SAN PEDRO'),
                array('id' => 2271, 'county_id' => '291', 'value' => 'SAUZAL'),
                array('id' => 2272, 'county_id' => '292', 'value' => 'EL FUERTE'),
                array('id' => 2273, 'county_id' => '292', 'value' => 'EL PIQUETE'),
                array('id' => 2274, 'county_id' => '292', 'value' => 'EL TALAR'),
                array('id' => 2275, 'county_id' => '292', 'value' => 'PALMA SOLA'),
                array('id' => 2276, 'county_id' => '292', 'value' => 'PUENTE LAVAYEN'),
                array('id' => 2277, 'county_id' => '292', 'value' => 'SANTA CLARA'),
                array('id' => 2278, 'county_id' => '292', 'value' => 'VINALITO'),
                array('id' => 2279, 'county_id' => '293', 'value' => 'CASIRA'),
                array('id' => 2280, 'county_id' => '293', 'value' => 'CIENEGA'),
                array('id' => 2281, 'county_id' => '293', 'value' => 'CIENEGUILLAS'),
                array('id' => 2282, 'county_id' => '293', 'value' => 'CUSI CUSI'),
                array('id' => 2283, 'county_id' => '293', 'value' => 'EL ANGOSTO'),
                array('id' => 2284, 'county_id' => '293', 'value' => 'LA CIENEGA'),
                array('id' => 2285, 'county_id' => '293', 'value' => 'MISARRUMI'),
                array('id' => 2286, 'county_id' => '293', 'value' => 'ORATORIO'),
                array('id' => 2287, 'county_id' => '293', 'value' => 'PAICONE'),
                array('id' => 2288, 'county_id' => '293', 'value' => 'SAN JUAN DE OROS'),
                array('id' => 2289, 'county_id' => '293', 'value' => 'SANTA CATALINA'),
                array('id' => 2290, 'county_id' => '293', 'value' => 'YOSCABA'),
                array('id' => 2291, 'county_id' => '294', 'value' => 'CATUA'),
                array('id' => 2292, 'county_id' => '294', 'value' => 'CORANZULI'),
                array('id' => 2293, 'county_id' => '294', 'value' => 'EL TORO'),
                array('id' => 2294, 'county_id' => '294', 'value' => 'HUANCAR'),
                array('id' => 2295, 'county_id' => '294', 'value' => 'JAMA'),
                array('id' => 2296, 'county_id' => '294', 'value' => 'MINA PROVIDENCIA'),
                array('id' => 2297, 'county_id' => '294', 'value' => 'OLACAPATO'),
                array('id' => 2298, 'county_id' => '294', 'value' => 'OLAROZ CHICO'),
                array('id' => 2299, 'county_id' => '294', 'value' => 'PASTOS CHICOS'),
                array('id' => 2300, 'county_id' => '294', 'value' => 'PUESTO SEY'),
                array('id' => 2301, 'county_id' => '294', 'value' => 'SAN JUAN DE QUILLAQUES'),
                array('id' => 2302, 'county_id' => '294', 'value' => 'SUSQUES'),
                array('id' => 2303, 'county_id' => '295', 'value' => 'COLONIA SAN JOSE'),
                array('id' => 2304, 'county_id' => '295', 'value' => 'HUACALERA'),
                array('id' => 2305, 'county_id' => '295', 'value' => 'JUELLA'),
                array('id' => 2306, 'county_id' => '295', 'value' => 'MAIMARA'),
                array('id' => 2307, 'county_id' => '295', 'value' => 'TILCARA'),
                array('id' => 2308, 'county_id' => '295', 'value' => 'YACORAITE'),
                array('id' => 2309, 'county_id' => '296', 'value' => 'BARCENA'),
                array('id' => 2310, 'county_id' => '296', 'value' => 'EL MORENO'),
                array('id' => 2311, 'county_id' => '296', 'value' => 'PUERTA DE COLORADOS'),
                array('id' => 2312, 'county_id' => '296', 'value' => 'PURMAMARCA'),
                array('id' => 2313, 'county_id' => '296', 'value' => 'TUMBAYA'),
                array('id' => 2314, 'county_id' => '296', 'value' => 'VOLCAN'),
                array('id' => 2315, 'county_id' => '297', 'value' => 'CASPALA'),
                array('id' => 2316, 'county_id' => '297', 'value' => 'PAMPICHUELA'),
                array('id' => 2317, 'county_id' => '297', 'value' => 'SAN FRANCISCO'),
                array('id' => 2318, 'county_id' => '297', 'value' => 'SANTA ANA'),
                array('id' => 2319, 'county_id' => '297', 'value' => 'VALLE COLORADO'),
                array('id' => 2320, 'county_id' => '297', 'value' => 'VALLE GRANDE'),
                array('id' => 2321, 'county_id' => '298', 'value' => 'BARRIOS'),
                array('id' => 2322, 'county_id' => '298', 'value' => 'CANGREJILLOS'),
                array('id' => 2323, 'county_id' => '298', 'value' => 'EL CONDOR'),
                array('id' => 2324, 'county_id' => '298', 'value' => 'LA INTERMEDIA'),
                array('id' => 2325, 'county_id' => '298', 'value' => 'LA QUIACA'),
                array('id' => 2326, 'county_id' => '298', 'value' => 'LLULLUCHAYOC'),
                array('id' => 2327, 'county_id' => '298', 'value' => 'PUMAHUASI'),
                array('id' => 2328, 'county_id' => '298', 'value' => 'SAN JOSE'),
                array('id' => 2329, 'county_id' => '298', 'value' => 'YAVI CHICO'),
                array('id' => 2330, 'county_id' => '299', 'value' => 'DOBLAS'),
                array('id' => 2331, 'county_id' => '299', 'value' => 'MACACHIN'),
                array('id' => 2332, 'county_id' => '299', 'value' => 'MIGUEL RIGLOS'),
                array('id' => 2333, 'county_id' => '299', 'value' => 'ROLON'),
                array('id' => 2334, 'county_id' => '299', 'value' => 'TOMAS M. ANCHORENA'),
                array('id' => 2335, 'county_id' => '300', 'value' => 'ANZOATEGUI'),
                array('id' => 2336, 'county_id' => '300', 'value' => 'LA ADELA'),
                array('id' => 2337, 'county_id' => '301', 'value' => 'ANGUIL'),
                array('id' => 2338, 'county_id' => '301', 'value' => 'SANTA ROSA'),
                array('id' => 2339, 'county_id' => '302', 'value' => 'CATRILO'),
                array('id' => 2340, 'county_id' => '302', 'value' => 'LA GLORIA'),
                array('id' => 2341, 'county_id' => '302', 'value' => 'LONQUIMAY'),
                array('id' => 2342, 'county_id' => '302', 'value' => 'URIBURU'),
                array('id' => 2343, 'county_id' => '303', 'value' => 'SANTA ISABEL'),
                array('id' => 2344, 'county_id' => '304', 'value' => 'BERNARDO LARROUDE'),
                array('id' => 2345, 'county_id' => '304', 'value' => 'CEBALLOS'),
                array('id' => 2346, 'county_id' => '304', 'value' => 'CORONEL HILARIO LAGOS'),
                array('id' => 2347, 'county_id' => '304', 'value' => 'INTENDENTE ALVEAR'),
                array('id' => 2348, 'county_id' => '304', 'value' => 'SARAH'),
                array('id' => 2349, 'county_id' => '304', 'value' => 'VERTIZ'),
                array('id' => 2350, 'county_id' => '305', 'value' => 'ALGARROBO DEL AGUILA'),
                array('id' => 2351, 'county_id' => '305', 'value' => 'LA HUMADA'),
                array('id' => 2352, 'county_id' => '306', 'value' => 'CONHELO'),
                array('id' => 2353, 'county_id' => '306', 'value' => 'EDUARDO CASTEX'),
                array('id' => 2354, 'county_id' => '306', 'value' => 'MAURICIO MAYER'),
                array('id' => 2355, 'county_id' => '306', 'value' => 'MONTE NIEVAS'),
                array('id' => 2356, 'county_id' => '306', 'value' => 'RUCANELO'),
                array('id' => 2357, 'county_id' => '306', 'value' => 'WINIFREDA'),
                array('id' => 2358, 'county_id' => '307', 'value' => 'GOBERNADOR DUVAL'),
                array('id' => 2359, 'county_id' => '307', 'value' => 'PUELCHES'),
                array('id' => 2360, 'county_id' => '308', 'value' => 'ALPACHIRI'),
                array('id' => 2361, 'county_id' => '308', 'value' => 'GENERAL MANUEL J. CAMPOS'),
                array('id' => 2362, 'county_id' => '308', 'value' => 'GUATRACHE'),
                array('id' => 2363, 'county_id' => '308', 'value' => 'PERU'),
                array('id' => 2364, 'county_id' => '308', 'value' => 'SANTA TERESA'),
                array('id' => 2365, 'county_id' => '309', 'value' => 'ABRAMO'),
                array('id' => 2366, 'county_id' => '309', 'value' => 'BERNASCONI'),
                array('id' => 2367, 'county_id' => '309', 'value' => 'GENERAL SAN MARTIN'),
                array('id' => 2368, 'county_id' => '309', 'value' => 'HUCAL'),
                array('id' => 2369, 'county_id' => '309', 'value' => 'JACINTO ARAUZ'),
                array('id' => 2370, 'county_id' => '310', 'value' => 'CUCHILLO CO'),
                array('id' => 2371, 'county_id' => '311', 'value' => 'LA REFORMA'),
                array('id' => 2372, 'county_id' => '311', 'value' => 'LIMAY MAHUIDA'),
                array('id' => 2373, 'county_id' => '312', 'value' => 'CARRO QUEMADO'),
                array('id' => 2374, 'county_id' => '312', 'value' => 'LOVENTUE'),
                array('id' => 2375, 'county_id' => '312', 'value' => 'LUAN TORO'),
                array('id' => 2376, 'county_id' => '312', 'value' => 'TELEN'),
                array('id' => 2377, 'county_id' => '312', 'value' => 'VICTORICA'),
                array('id' => 2378, 'county_id' => '313', 'value' => 'AGUSTONI'),
                array('id' => 2379, 'county_id' => '313', 'value' => 'DORILA'),
                array('id' => 2380, 'county_id' => '313', 'value' => 'GENERAL PICO'),
                array('id' => 2381, 'county_id' => '313', 'value' => 'SPELUZZI'),
                array('id' => 2382, 'county_id' => '313', 'value' => 'TREBOLARES'),
                array('id' => 2383, 'county_id' => '314', 'value' => '25 DE MAYO'),
                array('id' => 2384, 'county_id' => '314', 'value' => 'CASA DE PIEDRA'),
                array('id' => 2385, 'county_id' => '314', 'value' => 'PUELEN'),
                array('id' => 2386, 'county_id' => '315', 'value' => 'COLONIA BARON'),
                array('id' => 2387, 'county_id' => '315', 'value' => 'COLONIA SAN JOSE'),
                array('id' => 2388, 'county_id' => '315', 'value' => 'MIGUEL CANE'),
                array('id' => 2389, 'county_id' => '315', 'value' => 'QUEMU QUEMU'),
                array('id' => 2390, 'county_id' => '315', 'value' => 'RELMO'),
                array('id' => 2391, 'county_id' => '315', 'value' => 'VILLA MIRASOL'),
                array('id' => 2392, 'county_id' => '316', 'value' => 'CALEUFU'),
                array('id' => 2393, 'county_id' => '316', 'value' => 'INGENIERO FOSTER'),
                array('id' => 2394, 'county_id' => '316', 'value' => 'LA MARUJA'),
                array('id' => 2395, 'county_id' => '316', 'value' => 'PARERA'),
                array('id' => 2396, 'county_id' => '316', 'value' => 'PICHI HUINCA'),
                array('id' => 2397, 'county_id' => '316', 'value' => 'QUETREQUEN'),
                array('id' => 2398, 'county_id' => '316', 'value' => 'RANCUL'),
                array('id' => 2399, 'county_id' => '317', 'value' => 'ADOLFO VAN PRAET'),
                array('id' => 2400, 'county_id' => '317', 'value' => 'ALTA ITALIA'),
                array('id' => 2401, 'county_id' => '317', 'value' => 'DAMIAN MAISONAVE'),
                array('id' => 2402, 'county_id' => '317', 'value' => 'EMBAJADOR MARTINI'),
                array('id' => 2403, 'county_id' => '317', 'value' => 'FALUCHO'),
                array('id' => 2404, 'county_id' => '317', 'value' => 'INGENIERO LUIGGI'),
                array('id' => 2405, 'county_id' => '317', 'value' => 'OJEDA'),
                array('id' => 2406, 'county_id' => '317', 'value' => 'REALICO'),
                array('id' => 2407, 'county_id' => '318', 'value' => 'CACHIRULO'),
                array('id' => 2408, 'county_id' => '318', 'value' => 'NAICO'),
                array('id' => 2409, 'county_id' => '318', 'value' => 'TOAY'),
                array('id' => 2410, 'county_id' => '319', 'value' => 'ARATA'),
                array('id' => 2411, 'county_id' => '319', 'value' => 'METILEO'),
                array('id' => 2412, 'county_id' => '319', 'value' => 'TRENEL'),
                array('id' => 2413, 'county_id' => '320', 'value' => 'ATALIVA ROCA'),
                array('id' => 2414, 'county_id' => '320', 'value' => 'CHACHARRAMENDI'),
                array('id' => 2415, 'county_id' => '320', 'value' => 'COLONIA SANTA MARIA'),
                array('id' => 2416, 'county_id' => '320', 'value' => 'GENERAL ACHA'),
                array('id' => 2417, 'county_id' => '320', 'value' => 'QUEHUE'),
                array('id' => 2418, 'county_id' => '320', 'value' => 'UNANUE'),
                array('id' => 2419, 'county_id' => '321', 'value' => 'AIMOGASTA'),
                array('id' => 2420, 'county_id' => '321', 'value' => 'ARAUCO'),
                array('id' => 2421, 'county_id' => '321', 'value' => 'BAÑADO DE LOS PANTANOS'),
                array('id' => 2422, 'county_id' => '321', 'value' => 'ESTACION MAZAN'),
                array('id' => 2423, 'county_id' => '321', 'value' => 'MACHIGASTA'),
                array('id' => 2424, 'county_id' => '321', 'value' => 'SAN ANTONIO'),
                array('id' => 2425, 'county_id' => '321', 'value' => 'TERMAS DE SANTA TERESITA'),
                array('id' => 2426, 'county_id' => '321', 'value' => 'VILLA MAZAN'),
                array('id' => 2427, 'county_id' => '322', 'value' => 'LA RIOJA'),
                array('id' => 2428, 'county_id' => '323', 'value' => 'AMINGA'),
                array('id' => 2429, 'county_id' => '323', 'value' => 'ANILLACO'),
                array('id' => 2430, 'county_id' => '323', 'value' => 'ANJULLON'),
                array('id' => 2431, 'county_id' => '323', 'value' => 'CHUQUIS'),
                array('id' => 2432, 'county_id' => '323', 'value' => 'LOS MOLINOS'),
                array('id' => 2433, 'county_id' => '323', 'value' => 'PINCHAS'),
                array('id' => 2434, 'county_id' => '323', 'value' => 'SAN PEDRO'),
                array('id' => 2435, 'county_id' => '323', 'value' => 'SANTA VERA CRUZ'),
                array('id' => 2436, 'county_id' => '324', 'value' => 'CHAMICAL'),
                array('id' => 2437, 'county_id' => '324', 'value' => 'POLCO'),
                array('id' => 2438, 'county_id' => '325', 'value' => 'ANGUINAN'),
                array('id' => 2439, 'county_id' => '325', 'value' => 'CHILECITO'),
                array('id' => 2440, 'county_id' => '325', 'value' => 'COLONIA ANGUINAN'),
                array('id' => 2441, 'county_id' => '325', 'value' => 'COLONIA CATINZACO'),
                array('id' => 2442, 'county_id' => '325', 'value' => 'COLONIA MALLIGASTA'),
                array('id' => 2443, 'county_id' => '325', 'value' => 'COLONIA VICHIGASTA'),
                array('id' => 2444, 'county_id' => '325', 'value' => 'GUANCHIN'),
                array('id' => 2445, 'county_id' => '325', 'value' => 'LA PUNTILLA'),
                array('id' => 2446, 'county_id' => '325', 'value' => 'LOS SARMIENTOS'),
                array('id' => 2447, 'county_id' => '325', 'value' => 'MALLIGASTA'),
                array('id' => 2448, 'county_id' => '325', 'value' => 'MIRANDA'),
                array('id' => 2449, 'county_id' => '325', 'value' => 'NONOGASTA'),
                array('id' => 2450, 'county_id' => '325', 'value' => 'SAÑOGASTA'),
                array('id' => 2451, 'county_id' => '325', 'value' => 'SAN MIGUEL'),
                array('id' => 2452, 'county_id' => '325', 'value' => 'SAN NICOLAS'),
                array('id' => 2453, 'county_id' => '325', 'value' => 'SANTA FLORENTINA'),
                array('id' => 2454, 'county_id' => '325', 'value' => 'TILIMUQUI'),
                array('id' => 2455, 'county_id' => '325', 'value' => 'VICHIGASTA'),
                array('id' => 2456, 'county_id' => '326', 'value' => 'AICUÑA'),
                array('id' => 2457, 'county_id' => '326', 'value' => 'BANDA FLORIDA'),
                array('id' => 2458, 'county_id' => '326', 'value' => 'GUANDACOL'),
                array('id' => 2459, 'county_id' => '326', 'value' => 'LOS PALACIOS'),
                array('id' => 2460, 'county_id' => '326', 'value' => 'PAGANCILLO'),
                array('id' => 2461, 'county_id' => '326', 'value' => 'SANTA CLARA'),
                array('id' => 2462, 'county_id' => '326', 'value' => 'VILLA UNION'),
                array('id' => 2463, 'county_id' => '327', 'value' => 'ALTO CARRIZAL'),
                array('id' => 2464, 'county_id' => '327', 'value' => 'ANGULOS'),
                array('id' => 2465, 'county_id' => '327', 'value' => 'ANTINACO'),
                array('id' => 2466, 'county_id' => '327', 'value' => 'BAJO CARRIZAL'),
                array('id' => 2467, 'county_id' => '327', 'value' => 'CAMPANAS'),
                array('id' => 2468, 'county_id' => '327', 'value' => 'CHAÑARMUYO'),
                array('id' => 2469, 'county_id' => '327', 'value' => 'FAMATINA'),
                array('id' => 2470, 'county_id' => '327', 'value' => 'LA CUADRA'),
                array('id' => 2471, 'county_id' => '327', 'value' => 'PITUIL'),
                array('id' => 2472, 'county_id' => '327', 'value' => 'PLAZA VIEJA'),
                array('id' => 2473, 'county_id' => '327', 'value' => 'SANTA CRUZ'),
                array('id' => 2474, 'county_id' => '327', 'value' => 'SANTO DOMINGO'),
                array('id' => 2475, 'county_id' => '328', 'value' => 'PUNTA DE LOS LLANOS'),
                array('id' => 2476, 'county_id' => '328', 'value' => 'TAMA'),
                array('id' => 2477, 'county_id' => '329', 'value' => 'CASTRO BARROS'),
                array('id' => 2478, 'county_id' => '329', 'value' => 'CHAÑAR'),
                array('id' => 2479, 'county_id' => '329', 'value' => 'LOMA BLANCA'),
                array('id' => 2480, 'county_id' => '329', 'value' => 'OLTA'),
                array('id' => 2481, 'county_id' => '330', 'value' => 'MALANZAN'),
                array('id' => 2482, 'county_id' => '330', 'value' => 'NACATE'),
                array('id' => 2483, 'county_id' => '330', 'value' => 'PORTEZUELO'),
                array('id' => 2484, 'county_id' => '330', 'value' => 'SAN ANTONIO'),
                array('id' => 2485, 'county_id' => '331', 'value' => 'VILLA CASTELLI'),
                array('id' => 2486, 'county_id' => '332', 'value' => 'AMBIL'),
                array('id' => 2487, 'county_id' => '332', 'value' => 'COLONIA ORTIZ DE OCAMPO'),
                array('id' => 2488, 'county_id' => '332', 'value' => 'MILAGRO'),
                array('id' => 2489, 'county_id' => '332', 'value' => 'OLPAS'),
                array('id' => 2490, 'county_id' => '332', 'value' => 'SANTA RITA DE CATUNA'),
                array('id' => 2491, 'county_id' => '333', 'value' => 'ULAPES'),
                array('id' => 2492, 'county_id' => '334', 'value' => 'AMANA'),
                array('id' => 2493, 'county_id' => '334', 'value' => 'PATQUIA'),
                array('id' => 2494, 'county_id' => '335', 'value' => 'CHEPES'),
                array('id' => 2495, 'county_id' => '335', 'value' => 'DESIDERIO TELLO'),
                array('id' => 2496, 'county_id' => '336', 'value' => 'ALPASINCHE'),
                array('id' => 2497, 'county_id' => '336', 'value' => 'AMUSCHINA'),
                array('id' => 2498, 'county_id' => '336', 'value' => 'ANDOLUCAS'),
                array('id' => 2499, 'county_id' => '336', 'value' => 'CHAUPIHUASI'),
                array('id' => 2500, 'county_id' => '336', 'value' => 'CUIPAN'),
                array('id' => 2501, 'county_id' => '336', 'value' => 'LAS TALAS'),
                array('id' => 2502, 'county_id' => '336', 'value' => 'LOS ROBLES'),
                array('id' => 2503, 'county_id' => '336', 'value' => 'SALICAS'),
                array('id' => 2504, 'county_id' => '336', 'value' => 'SAN BLAS'),
                array('id' => 2505, 'county_id' => '336', 'value' => 'SHAQUI'),
                array('id' => 2506, 'county_id' => '336', 'value' => 'SURIYACO'),
                array('id' => 2507, 'county_id' => '336', 'value' => 'TUYUBIL'),
                array('id' => 2508, 'county_id' => '337', 'value' => 'VILLA SANAGASTA'),
                array('id' => 2509, 'county_id' => '338', 'value' => 'JAGUE'),
                array('id' => 2510, 'county_id' => '338', 'value' => 'VILLA SAN JOSE DE VINCHINA'),
                array('id' => 2511, 'county_id' => '339', 'value' => '10A. SECCION'),
                array('id' => 2512, 'county_id' => '339', 'value' => '11A. SECCION'),
                array('id' => 2513, 'county_id' => '339', 'value' => '1A. SECCION'),
                array('id' => 2514, 'county_id' => '339', 'value' => '2A. SECCION'),
                array('id' => 2515, 'county_id' => '339', 'value' => '3A. SECCION'),
                array('id' => 2516, 'county_id' => '339', 'value' => '4A. SECCION'),
                array('id' => 2517, 'county_id' => '339', 'value' => '5A. SECCION'),
                array('id' => 2518, 'county_id' => '339', 'value' => '6A. SECCION'),
                array('id' => 2519, 'county_id' => '339', 'value' => '7A. SECCION'),
                array('id' => 2520, 'county_id' => '339', 'value' => '8A. SECCION'),
                array('id' => 2521, 'county_id' => '339', 'value' => '9A. SECCION'),
                array('id' => 2522, 'county_id' => '340', 'value' => 'BOWEN'),
                array('id' => 2523, 'county_id' => '340', 'value' => 'CARMENSA'),
                array('id' => 2524, 'county_id' => '340', 'value' => 'GENERAL ALVEAR'),
                array('id' => 2525, 'county_id' => '340', 'value' => 'LOS COMPARTOS'),
                array('id' => 2526, 'county_id' => '341', 'value' => 'GOBERNADOR BENEGAS'),
                array('id' => 2527, 'county_id' => '341', 'value' => 'GODOY CRUZ'),
                array('id' => 2528, 'county_id' => '341', 'value' => 'LAS TORTUGAS'),
                array('id' => 2529, 'county_id' => '341', 'value' => 'PRESIDENTE SARMIENTO'),
                array('id' => 2530, 'county_id' => '341', 'value' => 'SAN FRANCISCO DEL MONTE'),
                array('id' => 2531, 'county_id' => '341', 'value' => 'VILLA HIPODROMO'),
                array('id' => 2532, 'county_id' => '341', 'value' => 'VILLA MARINI'),
                array('id' => 2533, 'county_id' => '342', 'value' => 'BERMEJO'),
                array('id' => 2534, 'county_id' => '342', 'value' => 'BUENA NUEVA'),
                array('id' => 2535, 'county_id' => '342', 'value' => 'CAPILLA DEL ROSARIO'),
                array('id' => 2536, 'county_id' => '342', 'value' => 'COLONIA SEGOVIA'),
                array('id' => 2537, 'county_id' => '342', 'value' => 'DORREGO'),
                array('id' => 2538, 'county_id' => '342', 'value' => 'EL SAUCE'),
                array('id' => 2539, 'county_id' => '342', 'value' => 'GENERAL BELGRANO'),
                array('id' => 2540, 'county_id' => '342', 'value' => 'GUAYMALLEN'),
                array('id' => 2541, 'county_id' => '342', 'value' => 'JESUS NAZARENO'),
                array('id' => 2542, 'county_id' => '342', 'value' => 'LA PRIMAVERA'),
                array('id' => 2543, 'county_id' => '342', 'value' => 'LAS CAÑAS'),
                array('id' => 2544, 'county_id' => '342', 'value' => 'LOS CORRALITOS'),
                array('id' => 2545, 'county_id' => '342', 'value' => 'PEDRO MOLINA'),
                array('id' => 2546, 'county_id' => '342', 'value' => 'PUENTE DE HIERRO'),
                array('id' => 2547, 'county_id' => '342', 'value' => 'RODEO DE LA CRUZ'),
                array('id' => 2548, 'county_id' => '342', 'value' => 'SAN FRANCISCO DEL MONTE'),
                array('id' => 2549, 'county_id' => '342', 'value' => 'SAN JOSE'),
                array('id' => 2550, 'county_id' => '342', 'value' => 'VILLA NUEVA'),
                array('id' => 2551, 'county_id' => '343', 'value' => 'INGENIERO GIAGNONI'),
                array('id' => 2552, 'county_id' => '343', 'value' => 'JUNIN'),
                array('id' => 2553, 'county_id' => '343', 'value' => 'LA COLONIA'),
                array('id' => 2554, 'county_id' => '343', 'value' => 'LOS BARRIALES'),
                array('id' => 2555, 'county_id' => '343', 'value' => 'MEDRANO'),
                array('id' => 2556, 'county_id' => '343', 'value' => 'PHILLIPS'),
                array('id' => 2557, 'county_id' => '343', 'value' => 'RODRIGUEZ PEÑA'),
                array('id' => 2558, 'county_id' => '344', 'value' => 'DESAGUADERO'),
                array('id' => 2559, 'county_id' => '344', 'value' => 'LA PAZ'),
                array('id' => 2560, 'county_id' => '344', 'value' => 'VILLA ANTIGUA'),
                array('id' => 2561, 'county_id' => '345', 'value' => 'BLANCO ENCALADA'),
                array('id' => 2562, 'county_id' => '345', 'value' => 'CAPDEVILA'),
                array('id' => 2563, 'county_id' => '345', 'value' => 'EL ALGARROBAL'),
                array('id' => 2564, 'county_id' => '345', 'value' => 'EL BORBOLLON'),
                array('id' => 2565, 'county_id' => '345', 'value' => 'EL CHALLAO'),
                array('id' => 2566, 'county_id' => '345', 'value' => 'EL PLUMERILLO'),
                array('id' => 2567, 'county_id' => '345', 'value' => 'EL RESGUARDO'),
                array('id' => 2568, 'county_id' => '345', 'value' => 'EL ZAPALLAR'),
                array('id' => 2569, 'county_id' => '345', 'value' => 'JOCOLI'),
                array('id' => 2570, 'county_id' => '345', 'value' => 'LA CIENEGUITA'),
                array('id' => 2571, 'county_id' => '345', 'value' => 'LAS CUEVAS'),
                array('id' => 2572, 'county_id' => '345', 'value' => 'LAS HERAS'),
                array('id' => 2573, 'county_id' => '345', 'value' => 'LOS PENITENTES'),
                array('id' => 2574, 'county_id' => '345', 'value' => 'PANQUEHUA'),
                array('id' => 2575, 'county_id' => '345', 'value' => 'POLVAREDAS'),
                array('id' => 2576, 'county_id' => '345', 'value' => 'PUENTE DEL INCA'),
                array('id' => 2577, 'county_id' => '345', 'value' => 'PUNTA DE VACAS'),
                array('id' => 2578, 'county_id' => '345', 'value' => 'SIERRAS DE ENCALADA'),
                array('id' => 2579, 'county_id' => '345', 'value' => 'USPALLATA'),
                array('id' => 2580, 'county_id' => '346', 'value' => '3 DE MAYO'),
                array('id' => 2581, 'county_id' => '346', 'value' => 'BARRIO ALTO DEL OLVIDO'),
                array('id' => 2582, 'county_id' => '346', 'value' => 'BARRIO JOCOLI II'),
                array('id' => 2583, 'county_id' => '346', 'value' => 'BARRIO LA ESPERANZA'),
                array('id' => 2584, 'county_id' => '346', 'value' => 'BARRIO LA PALMERA'),
                array('id' => 2585, 'county_id' => '346', 'value' => 'BARRIO LA PEGA'),
                array('id' => 2586, 'county_id' => '346', 'value' => 'BARRIO LAGUNAS DE BARTOLUZZI'),
                array('id' => 2587, 'county_id' => '346', 'value' => 'BARRIO LOS JARILLEROS'),
                array('id' => 2588, 'county_id' => '346', 'value' => 'BARRIO LOS OLIVOS'),
                array('id' => 2589, 'county_id' => '346', 'value' => 'BARRIO VIRGEN DEL ROSARIO'),
                array('id' => 2590, 'county_id' => '346', 'value' => 'COSTA DE ARAUJO'),
                array('id' => 2591, 'county_id' => '346', 'value' => 'EL PARAMILLO'),
                array('id' => 2592, 'county_id' => '346', 'value' => 'EL VERGEL'),
                array('id' => 2593, 'county_id' => '346', 'value' => 'INGENIERO GUSTAVO ANDRE'),
                array('id' => 2594, 'county_id' => '346', 'value' => 'JOCOLI'),
                array('id' => 2595, 'county_id' => '346', 'value' => 'JOCOLI VIEJO'),
                array('id' => 2596, 'county_id' => '346', 'value' => 'LAS VIOLETAS'),
                array('id' => 2597, 'county_id' => '346', 'value' => 'VILLA TULUMAYA'),
                array('id' => 2598, 'county_id' => '347', 'value' => 'AGRELO'),
                array('id' => 2599, 'county_id' => '347', 'value' => 'BARRIO ADINA I Y II'),
                array('id' => 2600, 'county_id' => '347', 'value' => 'BARRIO PERDRIEL IV'),
                array('id' => 2601, 'county_id' => '347', 'value' => 'CACHEUTA'),
                array('id' => 2602, 'county_id' => '347', 'value' => 'CARRODILLA'),
                array('id' => 2603, 'county_id' => '347', 'value' => 'CHACRAS DE CORIA'),
                array('id' => 2604, 'county_id' => '347', 'value' => 'COSTA FLORES'),
                array('id' => 2605, 'county_id' => '347', 'value' => 'EL CARMELO'),
                array('id' => 2606, 'county_id' => '347', 'value' => 'EL CARRIZAL'),
                array('id' => 2607, 'county_id' => '347', 'value' => 'EL SALTO'),
                array('id' => 2608, 'county_id' => '347', 'value' => 'LA PUNTILLA'),
                array('id' => 2609, 'county_id' => '347', 'value' => 'LAS CARDITAS'),
                array('id' => 2610, 'county_id' => '347', 'value' => 'LAS COMPUERTAS'),
                array('id' => 2611, 'county_id' => '347', 'value' => 'LAS VEGAS'),
                array('id' => 2612, 'county_id' => '347', 'value' => 'LOS MANANTIALES'),
                array('id' => 2613, 'county_id' => '347', 'value' => 'LUJAN DE CUYO'),
                array('id' => 2614, 'county_id' => '347', 'value' => 'MAYOR DRUMMOND'),
                array('id' => 2615, 'county_id' => '347', 'value' => 'PERDRIEL'),
                array('id' => 2616, 'county_id' => '347', 'value' => 'PIEDRAS BLANCAS'),
                array('id' => 2617, 'county_id' => '347', 'value' => 'POTRERILLOS'),
                array('id' => 2618, 'county_id' => '347', 'value' => 'UGARTECHE'),
                array('id' => 2619, 'county_id' => '347', 'value' => 'VALLE DEL SOL'),
                array('id' => 2620, 'county_id' => '347', 'value' => 'VILLA EL REFUGIO'),
                array('id' => 2621, 'county_id' => '347', 'value' => 'VISTALBA'),
                array('id' => 2622, 'county_id' => '348', 'value' => 'BARRANCAS'),
                array('id' => 2623, 'county_id' => '348', 'value' => 'BARRIO JESUS DE NAZARET'),
                array('id' => 2624, 'county_id' => '348', 'value' => 'COQUIMBITO'),
                array('id' => 2625, 'county_id' => '348', 'value' => 'CRUZ DE PIEDRA'),
                array('id' => 2626, 'county_id' => '348', 'value' => 'EL PEDREGAL'),
                array('id' => 2627, 'county_id' => '348', 'value' => 'FRAY LUIS BELTRAN'),
                array('id' => 2628, 'county_id' => '348', 'value' => 'GENERAL GUTIERREZ'),
                array('id' => 2629, 'county_id' => '348', 'value' => 'LUZURIAGA'),
                array('id' => 2630, 'county_id' => '348', 'value' => 'MAIPU'),
                array('id' => 2631, 'county_id' => '348', 'value' => 'RODEO DEL MEDIO'),
                array('id' => 2632, 'county_id' => '348', 'value' => 'RUSSELL'),
                array('id' => 2633, 'county_id' => '348', 'value' => 'SAN ROQUE'),
                array('id' => 2634, 'county_id' => '348', 'value' => 'VILLA TERESA'),
                array('id' => 2635, 'county_id' => '349', 'value' => 'AGUA ESCONDIDA'),
                array('id' => 2636, 'county_id' => '349', 'value' => 'LAS LEÑAS'),
                array('id' => 2637, 'county_id' => '349', 'value' => 'MALARGUE'),
                array('id' => 2638, 'county_id' => '350', 'value' => 'ANDRADE'),
                array('id' => 2639, 'county_id' => '350', 'value' => 'BARRIO COOPERATIVA LOS CAMPAMENTOS'),
                array('id' => 2640, 'county_id' => '350', 'value' => 'BARRIO RIVADAVIA'),
                array('id' => 2641, 'county_id' => '350', 'value' => 'CUADRO ORTEGA'),
                array('id' => 2642, 'county_id' => '350', 'value' => 'EL MIRADOR'),
                array('id' => 2643, 'county_id' => '350', 'value' => 'LA CENTRAL'),
                array('id' => 2644, 'county_id' => '350', 'value' => 'LA ESPERANZA'),
                array('id' => 2645, 'county_id' => '350', 'value' => 'LA FLORIDA'),
                array('id' => 2646, 'county_id' => '350', 'value' => 'LA LIBERTAD'),
                array('id' => 2647, 'county_id' => '350', 'value' => 'LOS ARBOLES'),
                array('id' => 2648, 'county_id' => '350', 'value' => 'LOS CAMPAMENTOS'),
                array('id' => 2649, 'county_id' => '350', 'value' => 'MEDRANO'),
                array('id' => 2650, 'county_id' => '350', 'value' => 'MUNDO NUEVO'),
                array('id' => 2651, 'county_id' => '350', 'value' => 'REDUCCION DE ABAJO'),
                array('id' => 2652, 'county_id' => '350', 'value' => 'RIVADAVIA'),
                array('id' => 2653, 'county_id' => '350', 'value' => 'SANTA MARIA DE ORO'),
                array('id' => 2654, 'county_id' => '351', 'value' => 'BARRIO CARRASCO'),
                array('id' => 2655, 'county_id' => '351', 'value' => 'BARRIO EL CEPILLO'),
                array('id' => 2656, 'county_id' => '351', 'value' => 'CHILECITO'),
                array('id' => 2657, 'county_id' => '351', 'value' => 'EUGENIO BUSTOS'),
                array('id' => 2658, 'county_id' => '351', 'value' => 'LA CONSULTA'),
                array('id' => 2659, 'county_id' => '351', 'value' => 'PAREDITAS'),
                array('id' => 2660, 'county_id' => '351', 'value' => 'SAN CARLOS'),
                array('id' => 2661, 'county_id' => '352', 'value' => 'ALTO VERDE'),
                array('id' => 2662, 'county_id' => '352', 'value' => 'BARRIO CHIVILCOY'),
                array('id' => 2663, 'county_id' => '352', 'value' => 'BARRIO EMANUEL'),
                array('id' => 2664, 'county_id' => '352', 'value' => 'BARRIO LA ESTACION'),
                array('id' => 2665, 'county_id' => '352', 'value' => 'BARRIO LOS CHARABONES'),
                array('id' => 2666, 'county_id' => '352', 'value' => 'BARRIO NTRA. SRA. DE FATIMA'),
                array('id' => 2667, 'county_id' => '352', 'value' => 'CHAPANAY'),
                array('id' => 2668, 'county_id' => '352', 'value' => 'CHIVILCOY'),
                array('id' => 2669, 'county_id' => '352', 'value' => 'CIUDAD DE SAN MARTIN'),
                array('id' => 2670, 'county_id' => '352', 'value' => 'EL ESPINO'),
                array('id' => 2671, 'county_id' => '352', 'value' => 'EL RAMBLON'),
                array('id' => 2672, 'county_id' => '352', 'value' => 'MONTECASEROS'),
                array('id' => 2673, 'county_id' => '352', 'value' => 'NUEVA CALIFORNIA'),
                array('id' => 2674, 'county_id' => '352', 'value' => 'PALMIRA'),
                array('id' => 2675, 'county_id' => '352', 'value' => 'TRES PORTEÑAS'),
                array('id' => 2676, 'county_id' => '353', 'value' => '25 DE MAYO'),
                array('id' => 2677, 'county_id' => '353', 'value' => 'BARRIO CAMPOS EL TOLEDANO'),
                array('id' => 2678, 'county_id' => '353', 'value' => 'BARRIO ECHEVERRIA'),
                array('id' => 2679, 'county_id' => '353', 'value' => 'BARRIO EL NEVADO'),
                array('id' => 2680, 'county_id' => '353', 'value' => 'BARRIO EMPLEADOS DE COMERCIO'),
                array('id' => 2681, 'county_id' => '353', 'value' => 'BARRIO INTENDENCIA'),
                array('id' => 2682, 'county_id' => '353', 'value' => 'BARRIO LAS ROSAS'),
                array('id' => 2683, 'county_id' => '353', 'value' => 'BARRIO PRIMAVERA'),
                array('id' => 2684, 'county_id' => '353', 'value' => 'CAPITAN MONTOYA'),
                array('id' => 2685, 'county_id' => '353', 'value' => 'CUADRO NACIONAL'),
                array('id' => 2686, 'county_id' => '353', 'value' => 'EL NIHUIL'),
                array('id' => 2687, 'county_id' => '353', 'value' => 'EL SOSNEADO'),
                array('id' => 2688, 'county_id' => '353', 'value' => 'EL TROPEZON'),
                array('id' => 2689, 'county_id' => '353', 'value' => 'GOUDGE'),
                array('id' => 2690, 'county_id' => '353', 'value' => 'JAIME PRATS'),
                array('id' => 2691, 'county_id' => '353', 'value' => 'LA LLAVE NUEVA'),
                array('id' => 2692, 'county_id' => '353', 'value' => 'LAS MALVINAS'),
                array('id' => 2693, 'county_id' => '353', 'value' => 'LOS REYUNOS'),
                array('id' => 2694, 'county_id' => '353', 'value' => 'MONTE COMAN'),
                array('id' => 2695, 'county_id' => '353', 'value' => 'POBRE DIABLO'),
                array('id' => 2696, 'county_id' => '353', 'value' => 'PUNTA DEL AGUA'),
                array('id' => 2697, 'county_id' => '353', 'value' => 'RAMA CAIDA'),
                array('id' => 2698, 'county_id' => '353', 'value' => 'REAL DEL PADRE'),
                array('id' => 2699, 'county_id' => '353', 'value' => 'SALTO DE LAS ROSAS'),
                array('id' => 2700, 'county_id' => '353', 'value' => 'SAN RAFAEL'),
                array('id' => 2701, 'county_id' => '353', 'value' => 'VILLA ATUEL'),
                array('id' => 2702, 'county_id' => '353', 'value' => 'VILLA ATUEL NORTE'),
                array('id' => 2703, 'county_id' => '354', 'value' => 'BARRIO 12 DE OCTUBRE'),
                array('id' => 2704, 'county_id' => '354', 'value' => 'BARRIO MARIA AUXILIADORA'),
                array('id' => 2705, 'county_id' => '354', 'value' => 'BARRIO MOLINA CABRERA'),
                array('id' => 2706, 'county_id' => '354', 'value' => 'LA DORMIDA'),
                array('id' => 2707, 'county_id' => '354', 'value' => 'LAS CATITAS'),
                array('id' => 2708, 'county_id' => '354', 'value' => 'SANTA ROSA'),
                array('id' => 2709, 'county_id' => '355', 'value' => 'BARRIO SAN CAYETANO'),
                array('id' => 2710, 'county_id' => '355', 'value' => 'CAMPO LOS ANDES'),
                array('id' => 2711, 'county_id' => '355', 'value' => 'COLONIA LAS ROSAS'),
                array('id' => 2712, 'county_id' => '355', 'value' => 'EL MANZANO'),
                array('id' => 2713, 'county_id' => '355', 'value' => 'LOS SAUCES'),
                array('id' => 2714, 'county_id' => '355', 'value' => 'TUNUYAN'),
                array('id' => 2715, 'county_id' => '355', 'value' => 'VISTA FLORES'),
                array('id' => 2716, 'county_id' => '356', 'value' => 'BARRIO BELGRANO NORTE'),
                array('id' => 2717, 'county_id' => '356', 'value' => 'CORDON DEL PLATA'),
                array('id' => 2718, 'county_id' => '356', 'value' => 'EL PERAL'),
                array('id' => 2719, 'county_id' => '356', 'value' => 'EL ZAMPAL'),
                array('id' => 2720, 'county_id' => '356', 'value' => 'LA ARBOLEDA'),
                array('id' => 2721, 'county_id' => '356', 'value' => 'SAN JOSE'),
                array('id' => 2722, 'county_id' => '356', 'value' => 'TUPUNGATO'),
                array('id' => 2723, 'county_id' => '356', 'value' => 'VILLA BASTIAS'),
                array('id' => 2724, 'county_id' => '357', 'value' => '25 DE MAYO'),
                array('id' => 2725, 'county_id' => '357', 'value' => 'ALBA POSSE'),
                array('id' => 2726, 'county_id' => '357', 'value' => 'ALICIA BAJA'),
                array('id' => 2727, 'county_id' => '357', 'value' => 'COLONIA ALICIA'),
                array('id' => 2728, 'county_id' => '357', 'value' => 'COLONIA AURORA'),
                array('id' => 2729, 'county_id' => '357', 'value' => 'SAN FRANCISCO DE ASIS'),
                array('id' => 2730, 'county_id' => '357', 'value' => 'SANTA RITA'),
                array('id' => 2731, 'county_id' => '358', 'value' => 'APOSTOLES'),
                array('id' => 2732, 'county_id' => '358', 'value' => 'AZARA'),
                array('id' => 2733, 'county_id' => '358', 'value' => 'BARRIO RURAL'),
                array('id' => 2734, 'county_id' => '358', 'value' => 'ESTACION APOSTOLES'),
                array('id' => 2735, 'county_id' => '358', 'value' => 'PINDAPOY'),
                array('id' => 2736, 'county_id' => '358', 'value' => 'RINCON DE AZARA'),
                array('id' => 2737, 'county_id' => '358', 'value' => 'SAN JOSE'),
                array('id' => 2738, 'county_id' => '358', 'value' => 'TRES CAPONES'),
                array('id' => 2739, 'county_id' => '359', 'value' => '1 DE MAYO'),
                array('id' => 2740, 'county_id' => '359', 'value' => 'ARISTOBULO DEL VALLE'),
                array('id' => 2741, 'county_id' => '359', 'value' => 'CAMPO GRANDE'),
                array('id' => 2742, 'county_id' => '359', 'value' => 'DOS DE MAYO NUCLEO I'),
                array('id' => 2743, 'county_id' => '359', 'value' => 'DOS DE MAYO NUCLEO III'),
                array('id' => 2744, 'county_id' => '359', 'value' => 'KILOMETRO 17 (RUTA 8)'),
                array('id' => 2745, 'county_id' => '359', 'value' => 'NUCLEO I'),
                array('id' => 2746, 'county_id' => '359', 'value' => 'NUCLEO II'),
                array('id' => 2747, 'county_id' => '359', 'value' => 'PUEBLO ILLIA'),
                array('id' => 2748, 'county_id' => '359', 'value' => 'SALTO ENCANTADO'),
                array('id' => 2749, 'county_id' => '360', 'value' => 'BARRIO DEL LAGO'),
                array('id' => 2750, 'county_id' => '360', 'value' => 'BONPLAND'),
                array('id' => 2751, 'county_id' => '360', 'value' => 'CANDELARIA'),
                array('id' => 2752, 'county_id' => '360', 'value' => 'CERRO CORA'),
                array('id' => 2753, 'county_id' => '360', 'value' => 'LORETO'),
                array('id' => 2754, 'county_id' => '360', 'value' => 'MARTIRES'),
                array('id' => 2755, 'county_id' => '360', 'value' => 'PROFUNDIDAD'),
                array('id' => 2756, 'county_id' => '360', 'value' => 'PUERTO SANTA ANA'),
                array('id' => 2757, 'county_id' => '360', 'value' => 'SANTA ANA'),
                array('id' => 2758, 'county_id' => '361', 'value' => 'BARRIO NUEVO GARUPA'),
                array('id' => 2759, 'county_id' => '361', 'value' => 'GARUPA'),
                array('id' => 2760, 'county_id' => '361', 'value' => 'NEMESIO PARMA'),
                array('id' => 2761, 'county_id' => '361', 'value' => 'POSADAS'),
                array('id' => 2762, 'county_id' => '362', 'value' => 'BARRA CONCEPCION'),
                array('id' => 2763, 'county_id' => '362', 'value' => 'CONCEPCION DE LA SIERRA'),
                array('id' => 2764, 'county_id' => '362', 'value' => 'LA CORITA'),
                array('id' => 2765, 'county_id' => '362', 'value' => 'SANTA MARIA'),
                array('id' => 2766, 'county_id' => '363', 'value' => '9 DE JULIO'),
                array('id' => 2767, 'county_id' => '363', 'value' => '9 DE JULIO KILOMETRO 20'),
                array('id' => 2768, 'county_id' => '363', 'value' => 'COLONIA VICTORIA'),
                array('id' => 2769, 'county_id' => '363', 'value' => 'ELDORADO'),
                array('id' => 2770, 'county_id' => '363', 'value' => 'MARIA MAGDALENA'),
                array('id' => 2771, 'county_id' => '363', 'value' => 'NUEVA DELICIA'),
                array('id' => 2772, 'county_id' => '363', 'value' => 'PUEBLO NUEVO'),
                array('id' => 2773, 'county_id' => '363', 'value' => 'PUERTO MADO'),
                array('id' => 2774, 'county_id' => '363', 'value' => 'PUERTO PINARES'),
                array('id' => 2775, 'county_id' => '363', 'value' => 'SANTIAGO DE LINIERS'),
                array('id' => 2776, 'county_id' => '363', 'value' => 'VALLE HERMOSO'),
                array('id' => 2777, 'county_id' => '363', 'value' => 'VILLA ROULET'),
                array('id' => 2778, 'county_id' => '364', 'value' => 'ALMIRANTE BROWN'),
                array('id' => 2779, 'county_id' => '364', 'value' => 'BERNARDO DE IRIGOYEN'),
                array('id' => 2780, 'county_id' => '364', 'value' => 'CABUREI'),
                array('id' => 2781, 'county_id' => '364', 'value' => 'DOS HERMANAS'),
                array('id' => 2782, 'county_id' => '364', 'value' => 'INTEGRACION'),
                array('id' => 2783, 'county_id' => '364', 'value' => 'PIÑALITO NORTE'),
                array('id' => 2784, 'county_id' => '364', 'value' => 'PUERTO ANDRESITO'),
                array('id' => 2785, 'county_id' => '364', 'value' => 'PUERTO DESEADO'),
                array('id' => 2786, 'county_id' => '364', 'value' => 'SAN ANTONIO'),
                array('id' => 2787, 'county_id' => '365', 'value' => 'EL SOBERBIO'),
                array('id' => 2788, 'county_id' => '365', 'value' => 'FRACRAN'),
                array('id' => 2789, 'county_id' => '365', 'value' => 'SAN VICENTE'),
                array('id' => 2790, 'county_id' => '366', 'value' => 'ESPERANZA'),
                array('id' => 2791, 'county_id' => '366', 'value' => 'LIBERTAD'),
                array('id' => 2792, 'county_id' => '366', 'value' => 'PUERTO IGUAZU'),
                array('id' => 2793, 'county_id' => '366', 'value' => 'VILLA COOPERATIVA'),
                array('id' => 2794, 'county_id' => '366', 'value' => 'WANDA'),
                array('id' => 2795, 'county_id' => '367', 'value' => 'ALMAFUERTE'),
                array('id' => 2796, 'county_id' => '367', 'value' => 'ARROYO DEL MEDIO'),
                array('id' => 2797, 'county_id' => '367', 'value' => 'CAA - YARI'),
                array('id' => 2798, 'county_id' => '367', 'value' => 'CERRO AZUL'),
                array('id' => 2799, 'county_id' => '367', 'value' => 'DOS ARROYOS'),
                array('id' => 2800, 'county_id' => '367', 'value' => 'GOBERNADOR LOPEZ'),
                array('id' => 2801, 'county_id' => '367', 'value' => 'LEANDRO N. ALEM'),
                array('id' => 2802, 'county_id' => '367', 'value' => 'OLEGARIO V. ANDRADE'),
                array('id' => 2803, 'county_id' => '367', 'value' => 'VILLA LIBERTAD'),
                array('id' => 2804, 'county_id' => '368', 'value' => 'CAPIOVI'),
                array('id' => 2805, 'county_id' => '368', 'value' => 'CAPIOVICIÑO'),
                array('id' => 2806, 'county_id' => '368', 'value' => 'EL ALCAZAR'),
                array('id' => 2807, 'county_id' => '368', 'value' => 'GARUHAPE'),
                array('id' => 2808, 'county_id' => '368', 'value' => 'MBOPICUA'),
                array('id' => 2809, 'county_id' => '368', 'value' => 'PUERTO LEONI'),
                array('id' => 2810, 'county_id' => '368', 'value' => 'PUERTO RICO'),
                array('id' => 2811, 'county_id' => '368', 'value' => 'RUIZ DE MONTOYA'),
                array('id' => 2812, 'county_id' => '368', 'value' => 'SAN ALBERTO'),
                array('id' => 2813, 'county_id' => '368', 'value' => 'SAN GOTARDO'),
                array('id' => 2814, 'county_id' => '368', 'value' => 'SAN MIGUEL'),
                array('id' => 2815, 'county_id' => '368', 'value' => 'VILLA AKERMAN'),
                array('id' => 2816, 'county_id' => '368', 'value' => 'VILLA URRUTIA'),
                array('id' => 2817, 'county_id' => '369', 'value' => 'BARIO ITA'),
                array('id' => 2818, 'county_id' => '369', 'value' => 'BARRIO CUATRO BOCAS'),
                array('id' => 2819, 'county_id' => '369', 'value' => 'BARRIO GUATAMBU'),
                array('id' => 2820, 'county_id' => '369', 'value' => 'CARAGUATAY'),
                array('id' => 2821, 'county_id' => '369', 'value' => 'LAHARRAGUE'),
                array('id' => 2822, 'county_id' => '369', 'value' => 'MONTECARLO'),
                array('id' => 2823, 'county_id' => '369', 'value' => 'PIRAY KILOMETRO 18'),
                array('id' => 2824, 'county_id' => '369', 'value' => 'PUERTO PIRAY'),
                array('id' => 2825, 'county_id' => '369', 'value' => 'TARUMA'),
                array('id' => 2826, 'county_id' => '369', 'value' => 'VILLA PARODI'),
                array('id' => 2827, 'county_id' => '370', 'value' => 'ALBERDI'),
                array('id' => 2828, 'county_id' => '370', 'value' => 'BARRIO ESCUELA 461'),
                array('id' => 2829, 'county_id' => '370', 'value' => 'BARRIO ESCUELA 633'),
                array('id' => 2830, 'county_id' => '370', 'value' => 'CAMPO RAMON'),
                array('id' => 2831, 'county_id' => '370', 'value' => 'CAMPO VIERA'),
                array('id' => 2832, 'county_id' => '370', 'value' => 'EL SALTO'),
                array('id' => 2833, 'county_id' => '370', 'value' => 'GENERAL ALVEAR'),
                array('id' => 2834, 'county_id' => '370', 'value' => 'GUARANI'),
                array('id' => 2835, 'county_id' => '370', 'value' => 'LOS HELECHOS'),
                array('id' => 2836, 'county_id' => '370', 'value' => 'OBERA'),
                array('id' => 2837, 'county_id' => '370', 'value' => 'PANAMBI'),
                array('id' => 2838, 'county_id' => '370', 'value' => 'PANAMBI KILOMETRO 15'),
                array('id' => 2839, 'county_id' => '370', 'value' => 'PANAMBI KILOMETRO 8'),
                array('id' => 2840, 'county_id' => '370', 'value' => 'SAN MARTIN'),
                array('id' => 2841, 'county_id' => '370', 'value' => 'VILLA BONITA'),
                array('id' => 2842, 'county_id' => '371', 'value' => 'BARRIO TUNGOIL'),
                array('id' => 2843, 'county_id' => '371', 'value' => 'COLONIA POLANA'),
                array('id' => 2844, 'county_id' => '371', 'value' => 'CORPUS'),
                array('id' => 2845, 'county_id' => '371', 'value' => 'DOMINGO SAVIO'),
                array('id' => 2846, 'county_id' => '371', 'value' => 'GENERAL URQUIZA'),
                array('id' => 2847, 'county_id' => '371', 'value' => 'GOBERNADOR ROCA'),
                array('id' => 2848, 'county_id' => '371', 'value' => 'HELVECIA'),
                array('id' => 2849, 'county_id' => '371', 'value' => 'HIPOLITO YRIGOYEN'),
                array('id' => 2850, 'county_id' => '371', 'value' => 'JARDIN AMERICA'),
                array('id' => 2851, 'county_id' => '371', 'value' => 'OASIS'),
                array('id' => 2852, 'county_id' => '371', 'value' => 'ROCA CHICA'),
                array('id' => 2853, 'county_id' => '371', 'value' => 'SAN IGNACIO'),
                array('id' => 2854, 'county_id' => '371', 'value' => 'SANTO PIPO'),
                array('id' => 2855, 'county_id' => '372', 'value' => 'FLORENTINO AMEGHINO'),
                array('id' => 2856, 'county_id' => '372', 'value' => 'ITACARUARE'),
                array('id' => 2857, 'county_id' => '372', 'value' => 'MOJON GRANDE'),
                array('id' => 2858, 'county_id' => '372', 'value' => 'SAN JAVIER'),
                array('id' => 2859, 'county_id' => '373', 'value' => 'CRUCE CABALLERO'),
                array('id' => 2860, 'county_id' => '373', 'value' => 'PARAISO'),
                array('id' => 2861, 'county_id' => '373', 'value' => 'PIÑALITO SUR'),
                array('id' => 2862, 'county_id' => '373', 'value' => 'SAN PEDRO'),
                array('id' => 2863, 'county_id' => '373', 'value' => 'TOBUNA'),
                array('id' => 2864, 'county_id' => '374', 'value' => 'CAVIAHUE'),
                array('id' => 2865, 'county_id' => '374', 'value' => 'COPAHUE'),
                array('id' => 2866, 'county_id' => '374', 'value' => 'EL CHOLAR'),
                array('id' => 2867, 'county_id' => '374', 'value' => 'EL HUECU'),
                array('id' => 2868, 'county_id' => '374', 'value' => 'TAQUIMILAN'),
                array('id' => 2869, 'county_id' => '375', 'value' => 'ALUMINE'),
                array('id' => 2870, 'county_id' => '375', 'value' => 'MOQUEHUE'),
                array('id' => 2871, 'county_id' => '375', 'value' => 'VILLA PEHUENIA'),
                array('id' => 2872, 'county_id' => '376', 'value' => 'AÑELO'),
                array('id' => 2873, 'county_id' => '376', 'value' => 'AGUADA SAN ROQUE'),
                array('id' => 2874, 'county_id' => '376', 'value' => 'SAN PATRICIO DEL CHAÑAR'),
                array('id' => 2875, 'county_id' => '377', 'value' => 'LAS COLORADAS'),
                array('id' => 2876, 'county_id' => '378', 'value' => 'CHOS MALAL'),
                array('id' => 2877, 'county_id' => '378', 'value' => 'TRICAO MALAL'),
                array('id' => 2878, 'county_id' => '378', 'value' => 'VILLA DEL CURI LEUVU'),
                array('id' => 2879, 'county_id' => '379', 'value' => 'PIEDRA DEL AGUILA'),
                array('id' => 2880, 'county_id' => '379', 'value' => 'SANTO TOMAS'),
                array('id' => 2881, 'county_id' => '380', 'value' => '11 DE OCTUBRE'),
                array('id' => 2882, 'county_id' => '380', 'value' => 'ARROYITO'),
                array('id' => 2883, 'county_id' => '380', 'value' => 'BARRIO RUCA LUHE'),
                array('id' => 2884, 'county_id' => '380', 'value' => 'CENTENARIO'),
                array('id' => 2885, 'county_id' => '380', 'value' => 'CUTRAL CO'),
                array('id' => 2886, 'county_id' => '380', 'value' => 'EL CHOCON'),
                array('id' => 2887, 'county_id' => '380', 'value' => 'MARI MENUCO'),
                array('id' => 2888, 'county_id' => '380', 'value' => 'NEUQUEN'),
                array('id' => 2889, 'county_id' => '380', 'value' => 'PLAZA HUINCUL'),
                array('id' => 2890, 'county_id' => '380', 'value' => 'PLOTTIER'),
                array('id' => 2891, 'county_id' => '380', 'value' => 'SENILLOSA'),
                array('id' => 2892, 'county_id' => '380', 'value' => 'VILLA EL CHOCON'),
                array('id' => 2893, 'county_id' => '380', 'value' => 'VISTA ALEGRE NORTE'),
                array('id' => 2894, 'county_id' => '380', 'value' => 'VISTA ALEGRE SUR'),
                array('id' => 2895, 'county_id' => '381', 'value' => 'JUNIN DE LOS ANDES'),
                array('id' => 2896, 'county_id' => '382', 'value' => 'LAGO MELIQUINA'),
                array('id' => 2897, 'county_id' => '382', 'value' => 'SAN MARTIN DE LOS ANDES'),
                array('id' => 2898, 'county_id' => '383', 'value' => 'CHORRIACA'),
                array('id' => 2899, 'county_id' => '383', 'value' => 'LONCOPUE'),
                array('id' => 2900, 'county_id' => '384', 'value' => 'VILLA LA ANGOSTURA'),
                array('id' => 2901, 'county_id' => '384', 'value' => 'VILLA TRAFUL'),
                array('id' => 2902, 'county_id' => '385', 'value' => 'ANDACOLLO'),
                array('id' => 2903, 'county_id' => '385', 'value' => 'HUINGANCO'),
                array('id' => 2904, 'county_id' => '385', 'value' => 'LAS OVEJAS'),
                array('id' => 2905, 'county_id' => '385', 'value' => 'LOS MICHES'),
                array('id' => 2906, 'county_id' => '385', 'value' => 'MANZANO AMARGO'),
                array('id' => 2907, 'county_id' => '385', 'value' => 'VARVARCO'),
                array('id' => 2908, 'county_id' => '385', 'value' => 'VILLA DEL NAHUEVE'),
                array('id' => 2909, 'county_id' => '386', 'value' => 'BARRANCAS'),
                array('id' => 2910, 'county_id' => '386', 'value' => 'BUTA RANQUIL'),
                array('id' => 2911, 'county_id' => '386', 'value' => 'OCTAVIO PICO'),
                array('id' => 2912, 'county_id' => '386', 'value' => 'RINCON DE LOS SAUCES'),
                array('id' => 2913, 'county_id' => '387', 'value' => 'EL SAUCE'),
                array('id' => 2914, 'county_id' => '387', 'value' => 'PASO AGUERRE'),
                array('id' => 2915, 'county_id' => '387', 'value' => 'PICUN LEUFU'),
                array('id' => 2916, 'county_id' => '388', 'value' => 'BAJADA DEL AGRIO'),
                array('id' => 2917, 'county_id' => '388', 'value' => 'LA BUITRERA'),
                array('id' => 2918, 'county_id' => '388', 'value' => 'LAS LAJAS'),
                array('id' => 2919, 'county_id' => '388', 'value' => 'QUILI MALAL'),
                array('id' => 2920, 'county_id' => '389', 'value' => 'COVUNCO CENTRO'),
                array('id' => 2921, 'county_id' => '389', 'value' => 'LOS CATUTOS'),
                array('id' => 2922, 'county_id' => '389', 'value' => 'MARIANO MORENO'),
                array('id' => 2923, 'county_id' => '389', 'value' => 'RAMON M. CASTRO'),
                array('id' => 2924, 'county_id' => '389', 'value' => 'ZAPALA'),
                array('id' => 2925, 'county_id' => '390', 'value' => 'AGUADA DE GUERRA'),
                array('id' => 2926, 'county_id' => '390', 'value' => 'CLEMENTE ONELLI'),
                array('id' => 2927, 'county_id' => '390', 'value' => 'COLAN CONUE'),
                array('id' => 2928, 'county_id' => '390', 'value' => 'EL CAIN'),
                array('id' => 2929, 'county_id' => '390', 'value' => 'INGENIERO JACOBACCI'),
                array('id' => 2930, 'county_id' => '390', 'value' => 'LOS MENUCOS'),
                array('id' => 2931, 'county_id' => '390', 'value' => 'MAQUINCHAO'),
                array('id' => 2932, 'county_id' => '390', 'value' => 'MINA SANTA TERESITA'),
                array('id' => 2933, 'county_id' => '390', 'value' => 'PILQUINIYEU'),
                array('id' => 2934, 'county_id' => '391', 'value' => 'COMICO'),
                array('id' => 2935, 'county_id' => '391', 'value' => 'CONA NIYEU'),
                array('id' => 2936, 'county_id' => '391', 'value' => 'MINISTRO RAMOS MEXIA'),
                array('id' => 2937, 'county_id' => '391', 'value' => 'PRAHUANIYEU'),
                array('id' => 2938, 'county_id' => '391', 'value' => 'SIERRA COLORADA'),
                array('id' => 2939, 'county_id' => '391', 'value' => 'TRENETA'),
                array('id' => 2940, 'county_id' => '391', 'value' => 'YAMINUE'),
                array('id' => 2941, 'county_id' => '392', 'value' => 'ÑORQUINCO'),
                array('id' => 2942, 'county_id' => '392', 'value' => 'LAS BAYAS'),
                array('id' => 2943, 'county_id' => '392', 'value' => 'MAMUEL CHOIQUE'),
                array('id' => 2944, 'county_id' => '392', 'value' => 'OJOS DE AGUA'),
                array('id' => 2945, 'county_id' => '392', 'value' => 'RIO CHICO'),
                array('id' => 2946, 'county_id' => '393', 'value' => 'BAHIA CREEK'),
                array('id' => 2947, 'county_id' => '393', 'value' => 'EL CONDOR'),
                array('id' => 2948, 'county_id' => '393', 'value' => 'EL JUNCAL'),
                array('id' => 2949, 'county_id' => '393', 'value' => 'GUARDIA MITRE'),
                array('id' => 2950, 'county_id' => '393', 'value' => 'LA LOBERIA'),
                array('id' => 2951, 'county_id' => '393', 'value' => 'LOTEO COSTA DE RIO'),
                array('id' => 2952, 'county_id' => '393', 'value' => 'POZO SALADO'),
                array('id' => 2953, 'county_id' => '393', 'value' => 'SAN JAVIER'),
                array('id' => 2954, 'county_id' => '393', 'value' => 'VIEDMA'),
                array('id' => 2955, 'county_id' => '394', 'value' => 'BARRIO UNION'),
                array('id' => 2956, 'county_id' => '394', 'value' => 'CHELFORO'),
                array('id' => 2957, 'county_id' => '394', 'value' => 'CHIMPAY'),
                array('id' => 2958, 'county_id' => '394', 'value' => 'CHOELE CHOEL'),
                array('id' => 2959, 'county_id' => '394', 'value' => 'CORONEL BELISLE'),
                array('id' => 2960, 'county_id' => '394', 'value' => 'DARWIN'),
                array('id' => 2961, 'county_id' => '394', 'value' => 'LAMARQUE'),
                array('id' => 2962, 'county_id' => '394', 'value' => 'LUIS BELTRAN'),
                array('id' => 2963, 'county_id' => '394', 'value' => 'POMONA'),
                array('id' => 2964, 'county_id' => '395', 'value' => 'BARRIO EL PILAR'),
                array('id' => 2965, 'county_id' => '395', 'value' => 'COLONIA SUIZA'),
                array('id' => 2966, 'county_id' => '395', 'value' => 'EL BOLSON'),
                array('id' => 2967, 'county_id' => '395', 'value' => 'EL FOYEL'),
                array('id' => 2968, 'county_id' => '395', 'value' => 'MALLIN AHOGADO'),
                array('id' => 2969, 'county_id' => '395', 'value' => 'RIO VILLEGAS'),
                array('id' => 2970, 'county_id' => '395', 'value' => 'SAN CARLOS DE BARILOCHE'),
                array('id' => 2971, 'county_id' => '395', 'value' => 'VILLA ARELAUQUEN'),
                array('id' => 2972, 'county_id' => '395', 'value' => 'VILLA CAMPANARIO'),
                array('id' => 2973, 'county_id' => '395', 'value' => 'VILLA CATEDRAL'),
                array('id' => 2974, 'county_id' => '395', 'value' => 'VILLA LLAO LLAO'),
                array('id' => 2975, 'county_id' => '395', 'value' => 'VILLA LOS COIHUES'),
                array('id' => 2976, 'county_id' => '395', 'value' => 'VILLA MASCARDI'),
                array('id' => 2977, 'county_id' => '396', 'value' => 'BARRIO COLONIA CONESA'),
                array('id' => 2978, 'county_id' => '396', 'value' => 'BARRIO PLANTA COMPRESORA DE GAS'),
                array('id' => 2979, 'county_id' => '396', 'value' => 'GENERAL CONESA'),
                array('id' => 2980, 'county_id' => '397', 'value' => 'AGUADA GUZMAN'),
                array('id' => 2981, 'county_id' => '397', 'value' => 'CERRO POLICIA'),
                array('id' => 2982, 'county_id' => '397', 'value' => 'EL CUY'),
                array('id' => 2983, 'county_id' => '397', 'value' => 'LAS PERLAS'),
                array('id' => 2984, 'county_id' => '397', 'value' => 'MENCUE'),
                array('id' => 2985, 'county_id' => '397', 'value' => 'NAUPA HUEN'),
                array('id' => 2986, 'county_id' => '397', 'value' => 'PASO CORDOVA'),
                array('id' => 2987, 'county_id' => '397', 'value' => 'VALLE AZUL'),
                array('id' => 2988, 'county_id' => '398', 'value' => 'ALLEN'),
                array('id' => 2989, 'county_id' => '398', 'value' => 'BAJO SAN CAYETANO'),
                array('id' => 2990, 'county_id' => '398', 'value' => 'BARDA DEL MEDIO'),
                array('id' => 2991, 'county_id' => '398', 'value' => 'BARRIO BLANCO'),
                array('id' => 2992, 'county_id' => '398', 'value' => 'BARRIO CALLE CIEGA N? 10'),
                array('id' => 2993, 'county_id' => '398', 'value' => 'BARRIO CALLE CIEGA N? 6'),
                array('id' => 2994, 'county_id' => '398', 'value' => 'BARRIO CANALE'),
                array('id' => 2995, 'county_id' => '398', 'value' => 'BARRIO CHACRA MONTE'),
                array('id' => 2996, 'county_id' => '398', 'value' => 'BARRIO COSTA ESTE'),
                array('id' => 2997, 'county_id' => '398', 'value' => 'BARRIO COSTA LINDA'),
                array('id' => 2998, 'county_id' => '398', 'value' => 'BARRIO COSTA OESTE'),
                array('id' => 2999, 'county_id' => '398', 'value' => 'BARRIO DESTACAMENTO'),
                array('id' => 3000, 'county_id' => '398', 'value' => 'BARRIO EL LABRADOR')
                )
            );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('cities_table_2', function (Blueprint $table) {
            //
        });
    }
}
