<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddRecordsToCitiesTable1 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('cities')->insert(
            array(
                array('id' => 1001, 'county_id' => '146', 'value' => 'MUTQUIN'),
                array('id' => 1002, 'county_id' => '146', 'value' => 'POMAN'),
                array('id' => 1003, 'county_id' => '146', 'value' => 'RINCON'),
                array('id' => 1004, 'county_id' => '146', 'value' => 'SAN MIGUEL'),
                array('id' => 1005, 'county_id' => '146', 'value' => 'SAUJIL'),
                array('id' => 1006, 'county_id' => '146', 'value' => 'SIJAN'),
                array('id' => 1007, 'county_id' => '147', 'value' => 'ANDALHUALA'),
                array('id' => 1008, 'county_id' => '147', 'value' => 'CASA DE PIEDRA'),
                array('id' => 1009, 'county_id' => '147', 'value' => 'CASPICHANGO'),
                array('id' => 1010, 'county_id' => '147', 'value' => 'CHAÑAR PUNCO'),
                array('id' => 1011, 'county_id' => '147', 'value' => 'EL CAJON'),
                array('id' => 1012, 'county_id' => '147', 'value' => 'EL CERRITO'),
                array('id' => 1013, 'county_id' => '147', 'value' => 'EL DESMONTE'),
                array('id' => 1014, 'county_id' => '147', 'value' => 'EL PUESTO'),
                array('id' => 1015, 'county_id' => '147', 'value' => 'FAMATANCA'),
                array('id' => 1016, 'county_id' => '147', 'value' => 'FUERTE QUEMADO'),
                array('id' => 1017, 'county_id' => '147', 'value' => 'LA HOYADA'),
                array('id' => 1018, 'county_id' => '147', 'value' => 'LA LOMA'),
                array('id' => 1019, 'county_id' => '147', 'value' => 'LA PUNTILLA'),
                array('id' => 1020, 'county_id' => '147', 'value' => 'LAMPACITO'),
                array('id' => 1021, 'county_id' => '147', 'value' => 'LAS MOJARRAS'),
                array('id' => 1022, 'county_id' => '147', 'value' => 'LORO HUASI'),
                array('id' => 1023, 'county_id' => '147', 'value' => 'MEDANITOS'),
                array('id' => 1024, 'county_id' => '147', 'value' => 'PALO SECO'),
                array('id' => 1025, 'county_id' => '147', 'value' => 'PUNTA DE BALASTO'),
                array('id' => 1026, 'county_id' => '147', 'value' => 'SAN JOSE BANDA'),
                array('id' => 1027, 'county_id' => '147', 'value' => 'SAN JOSE NORTE'),
                array('id' => 1028, 'county_id' => '147', 'value' => 'SAN JOSE VILLA'),
                array('id' => 1029, 'county_id' => '147', 'value' => 'SANTA MARIA'),
                array('id' => 1030, 'county_id' => '147', 'value' => 'YAPES'),
                array('id' => 1031, 'county_id' => '148', 'value' => 'ALIJILAN'),
                array('id' => 1032, 'county_id' => '148', 'value' => 'BAÑADO DE OVANTA'),
                array('id' => 1033, 'county_id' => '148', 'value' => 'LAS CAÑAS'),
                array('id' => 1034, 'county_id' => '148', 'value' => 'LAVALLE'),
                array('id' => 1035, 'county_id' => '148', 'value' => 'LOS ALTOS'),
                array('id' => 1036, 'county_id' => '148', 'value' => 'MANANTIALES'),
                array('id' => 1037, 'county_id' => '148', 'value' => 'SAN PEDRO'),
                array('id' => 1038, 'county_id' => '149', 'value' => 'ANILLACO'),
                array('id' => 1039, 'county_id' => '149', 'value' => 'ANTINACO'),
                array('id' => 1040, 'county_id' => '149', 'value' => 'BANDA DE LUCERO'),
                array('id' => 1041, 'county_id' => '149', 'value' => 'CERRO NEGRO'),
                array('id' => 1042, 'county_id' => '149', 'value' => 'COPACABANA'),
                array('id' => 1043, 'county_id' => '149', 'value' => 'CORDOBITA'),
                array('id' => 1044, 'county_id' => '149', 'value' => 'COSTA DE REYES'),
                array('id' => 1045, 'county_id' => '149', 'value' => 'EL PUEBLITO'),
                array('id' => 1046, 'county_id' => '149', 'value' => 'EL PUESTO'),
                array('id' => 1047, 'county_id' => '149', 'value' => 'EL SALADO'),
                array('id' => 1048, 'county_id' => '149', 'value' => 'FIAMBALA'),
                array('id' => 1049, 'county_id' => '149', 'value' => 'LA PUNTILLA'),
                array('id' => 1050, 'county_id' => '149', 'value' => 'LA RAMADITA'),
                array('id' => 1051, 'county_id' => '149', 'value' => 'LOS BALVERDIS'),
                array('id' => 1052, 'county_id' => '149', 'value' => 'MEDANITOS'),
                array('id' => 1053, 'county_id' => '149', 'value' => 'PALO BLANCO'),
                array('id' => 1054, 'county_id' => '149', 'value' => 'PAMPA BLANCA'),
                array('id' => 1055, 'county_id' => '149', 'value' => 'PUNTA DEL AGUA'),
                array('id' => 1056, 'county_id' => '149', 'value' => 'SAUJIL'),
                array('id' => 1057, 'county_id' => '149', 'value' => 'TATON'),
                array('id' => 1058, 'county_id' => '149', 'value' => 'TINOGASTA'),
                array('id' => 1059, 'county_id' => '150', 'value' => 'EL BAÑADO'),
                array('id' => 1060, 'county_id' => '150', 'value' => 'EL PORTEZUELO'),
                array('id' => 1061, 'county_id' => '150', 'value' => 'HUAYCAMA'),
                array('id' => 1062, 'county_id' => '150', 'value' => 'LAS TEJAS'),
                array('id' => 1063, 'county_id' => '150', 'value' => 'POLCOS'),
                array('id' => 1064, 'county_id' => '150', 'value' => 'POZO DEL MISTOL'),
                array('id' => 1065, 'county_id' => '150', 'value' => 'SAN ISIDRO'),
                array('id' => 1066, 'county_id' => '150', 'value' => 'SANTA CRUZ'),
                array('id' => 1067, 'county_id' => '150', 'value' => 'SANTA ROSA'),
                array('id' => 1068, 'county_id' => '150', 'value' => 'SUMALAO'),
                array('id' => 1069, 'county_id' => '150', 'value' => 'VILLA DOLORES'),
                array('id' => 1070, 'county_id' => '151', 'value' => 'GANCEDO'),
                array('id' => 1071, 'county_id' => '151', 'value' => 'GENERAL CAPDEVILA'),
                array('id' => 1072, 'county_id' => '151', 'value' => 'GENERAL PINEDO'),
                array('id' => 1073, 'county_id' => '151', 'value' => 'MESON DE FIERRO'),
                array('id' => 1074, 'county_id' => '151', 'value' => 'PAMPA LANDRIEL'),
                array('id' => 1075, 'county_id' => '152', 'value' => 'BARRIO DE LOS PESCADORES'),
                array('id' => 1076, 'county_id' => '152', 'value' => 'COLONIA BENITEZ'),
                array('id' => 1077, 'county_id' => '152', 'value' => 'MARGARITA BELEN'),
                array('id' => 1078, 'county_id' => '153', 'value' => 'HERMOSO CAMPO'),
                array('id' => 1079, 'county_id' => '153', 'value' => 'ITIN'),
                array('id' => 1080, 'county_id' => '154', 'value' => 'COLONIA ABORIGEN'),
                array('id' => 1081, 'county_id' => '154', 'value' => 'MACHAGAI'),
                array('id' => 1082, 'county_id' => '154', 'value' => 'NAPALPI'),
                array('id' => 1083, 'county_id' => '155', 'value' => 'LAS BREÑAS'),
                array('id' => 1084, 'county_id' => '156', 'value' => 'CONCEPCION DEL BERMEJO'),
                array('id' => 1085, 'county_id' => '156', 'value' => 'LOS FRENTONES'),
                array('id' => 1086, 'county_id' => '156', 'value' => 'PAMPA DEL INFIERNO'),
                array('id' => 1087, 'county_id' => '156', 'value' => 'RIO MUERTO'),
                array('id' => 1088, 'county_id' => '156', 'value' => 'TACO POZO'),
                array('id' => 1089, 'county_id' => '157', 'value' => 'GENERAL VEDIA'),
                array('id' => 1090, 'county_id' => '157', 'value' => 'ISLA DEL CERRITO'),
                array('id' => 1091, 'county_id' => '157', 'value' => 'LA LEONESA'),
                array('id' => 1092, 'county_id' => '157', 'value' => 'LAS PALMAS'),
                array('id' => 1093, 'county_id' => '157', 'value' => 'PUERTO BERMEJO NUEVO'),
                array('id' => 1094, 'county_id' => '157', 'value' => 'PUERTO BERMEJO VIEJO'),
                array('id' => 1095, 'county_id' => '157', 'value' => 'PUERTO EVA PERON'),
                array('id' => 1096, 'county_id' => '158', 'value' => 'CHARATA'),
                array('id' => 1097, 'county_id' => '159', 'value' => 'PRESIDENCIA ROQUE SAENZ PENA'),
                array('id' => 1098, 'county_id' => '160', 'value' => 'CHOROTIS'),
                array('id' => 1099, 'county_id' => '160', 'value' => 'SANTA SYLVINA'),
                array('id' => 1100, 'county_id' => '160', 'value' => 'VENADOS GRANDES'),
                array('id' => 1101, 'county_id' => '161', 'value' => 'CORZUELA'),
                array('id' => 1102, 'county_id' => '162', 'value' => 'LA ESCONDIDA'),
                array('id' => 1103, 'county_id' => '162', 'value' => 'LA VERDE'),
                array('id' => 1104, 'county_id' => '162', 'value' => 'LAPACHITO'),
                array('id' => 1105, 'county_id' => '162', 'value' => 'MAKALLE'),
                array('id' => 1106, 'county_id' => '163', 'value' => 'EL ESPINILLO'),
                array('id' => 1107, 'county_id' => '163', 'value' => 'EL SAUZAL'),
                array('id' => 1108, 'county_id' => '163', 'value' => 'EL SAUZALITO'),
                array('id' => 1109, 'county_id' => '163', 'value' => 'FORTIN LAVALLE'),
                array('id' => 1110, 'county_id' => '163', 'value' => 'FUERTE ESPERANZA'),
                array('id' => 1111, 'county_id' => '163', 'value' => 'JUAN JOSE CASTELLI'),
                array('id' => 1112, 'county_id' => '163', 'value' => 'MIRAFLORES'),
                array('id' => 1113, 'county_id' => '163', 'value' => 'NUEVA POMPEYA'),
                array('id' => 1114, 'county_id' => '163', 'value' => 'VILLA RIO BERMEJITO'),
                array('id' => 1115, 'county_id' => '163', 'value' => 'WICHI'),
                array('id' => 1116, 'county_id' => '163', 'value' => 'ZAPARINQUI'),
                array('id' => 1117, 'county_id' => '164', 'value' => 'AVIA TERAI'),
                array('id' => 1118, 'county_id' => '164', 'value' => 'CAMPO LARGO'),
                array('id' => 1119, 'county_id' => '164', 'value' => 'FORTIN LAS CHUÑAS'),
                array('id' => 1120, 'county_id' => '164', 'value' => 'NAPENAY'),
                array('id' => 1121, 'county_id' => '165', 'value' => 'COLONIA POPULAR'),
                array('id' => 1122, 'county_id' => '165', 'value' => 'ESTACION GENERAL OBLIGADO'),
                array('id' => 1123, 'county_id' => '165', 'value' => 'LAGUNA BLANCA'),
                array('id' => 1124, 'county_id' => '165', 'value' => 'PUERTO TIROL'),
                array('id' => 1125, 'county_id' => '166', 'value' => 'CIERVO PETISO'),
                array('id' => 1126, 'county_id' => '166', 'value' => 'GENERAL JOSE DE SAN MARTIN'),
                array('id' => 1127, 'county_id' => '166', 'value' => 'LA EDUVIGIS'),
                array('id' => 1128, 'county_id' => '166', 'value' => 'LAGUNA LIMPIA'),
                array('id' => 1129, 'county_id' => '166', 'value' => 'PAMPA ALMIRON'),
                array('id' => 1130, 'county_id' => '166', 'value' => 'PAMPA DEL INDIO'),
                array('id' => 1131, 'county_id' => '166', 'value' => 'PRESIDENCIA ROCA'),
                array('id' => 1132, 'county_id' => '166', 'value' => 'SELVAS DEL RIO DE ORO'),
                array('id' => 1133, 'county_id' => '167', 'value' => 'TRES ISLETAS'),
                array('id' => 1134, 'county_id' => '168', 'value' => 'CORONEL DU GRATY'),
                array('id' => 1135, 'county_id' => '168', 'value' => 'ENRIQUE URIEN'),
                array('id' => 1136, 'county_id' => '168', 'value' => 'VILLA ANGELA'),
                array('id' => 1137, 'county_id' => '169', 'value' => 'LA CLOTILDE'),
                array('id' => 1138, 'county_id' => '169', 'value' => 'LA TIGRA'),
                array('id' => 1139, 'county_id' => '169', 'value' => 'SAN BERNARDO'),
                array('id' => 1140, 'county_id' => '170', 'value' => 'PRESIDENCIA DE LA PLAZA'),
                array('id' => 1141, 'county_id' => '171', 'value' => 'QUITILIPI'),
                array('id' => 1142, 'county_id' => '171', 'value' => 'VILLA EL PALMAR'),
                array('id' => 1143, 'county_id' => '172', 'value' => 'BARRANQUERAS'),
                array('id' => 1144, 'county_id' => '172', 'value' => 'BASAIL'),
                array('id' => 1145, 'county_id' => '172', 'value' => 'COLONIA BARANDA'),
                array('id' => 1146, 'county_id' => '172', 'value' => 'FONTANA'),
                array('id' => 1147, 'county_id' => '172', 'value' => 'PUERTO VILELAS'),
                array('id' => 1148, 'county_id' => '172', 'value' => 'RESISTENCIA'),
                array('id' => 1149, 'county_id' => '173', 'value' => 'SAMUHU'),
                array('id' => 1150, 'county_id' => '173', 'value' => 'VILLA BERTHET'),
                array('id' => 1151, 'county_id' => '174', 'value' => 'CAPITAN SOLARI'),
                array('id' => 1152, 'county_id' => '174', 'value' => 'COLONIA ELISA'),
                array('id' => 1153, 'county_id' => '174', 'value' => 'COLONIAS UNIDAS'),
                array('id' => 1154, 'county_id' => '174', 'value' => 'INGENIERO BARBET'),
                array('id' => 1155, 'county_id' => '174', 'value' => 'LAS GARCITAS'),
                array('id' => 1156, 'county_id' => '175', 'value' => 'CHARADAI'),
                array('id' => 1157, 'county_id' => '175', 'value' => 'COTE LAI'),
                array('id' => 1158, 'county_id' => '175', 'value' => 'HAUMONIA'),
                array('id' => 1159, 'county_id' => '175', 'value' => 'HORQUILLA'),
                array('id' => 1160, 'county_id' => '175', 'value' => 'LA SABANA'),
                array('id' => 1161, 'county_id' => '176', 'value' => 'ARROYO VERDE'),
                array('id' => 1162, 'county_id' => '176', 'value' => 'PUERTO MADRYN'),
                array('id' => 1163, 'county_id' => '176', 'value' => 'PUERTO PIRAMIDE'),
                array('id' => 1164, 'county_id' => '176', 'value' => 'QUINTA EL MIRADOR'),
                array('id' => 1165, 'county_id' => '176', 'value' => 'RESERVA AREA PROTEGIDA EL DORADILLO'),
                array('id' => 1166, 'county_id' => '177', 'value' => 'BUENOS AIRES CHICO'),
                array('id' => 1167, 'county_id' => '177', 'value' => 'CHOLILA'),
                array('id' => 1168, 'county_id' => '177', 'value' => 'COSTA DE CHUBUT'),
                array('id' => 1169, 'county_id' => '177', 'value' => 'CUSHAMEN CENTRO'),
                array('id' => 1170, 'county_id' => '177', 'value' => 'EL HOYO'),
                array('id' => 1171, 'county_id' => '177', 'value' => 'EL MAITEN'),
                array('id' => 1172, 'county_id' => '177', 'value' => 'EPUYEN'),
                array('id' => 1173, 'county_id' => '177', 'value' => 'FOFO CAHUEL'),
                array('id' => 1174, 'county_id' => '177', 'value' => 'GUALJAINA'),
                array('id' => 1175, 'county_id' => '177', 'value' => 'LAGO EPUYEN'),
                array('id' => 1176, 'county_id' => '177', 'value' => 'LAGO PUELO'),
                array('id' => 1177, 'county_id' => '177', 'value' => 'LELEQUE'),
                array('id' => 1178, 'county_id' => '178', 'value' => 'ACCESO NORTE'),
                array('id' => 1179, 'county_id' => '178', 'value' => 'ASTRA'),
                array('id' => 1180, 'county_id' => '178', 'value' => 'BAHIA BUSTAMANTE'),
                array('id' => 1181, 'county_id' => '178', 'value' => 'BARRIO 25 DE MAYO'),
                array('id' => 1182, 'county_id' => '178', 'value' => 'BARRIO CALETA CORDOVA'),
                array('id' => 1183, 'county_id' => '178', 'value' => 'BARRIO CALETA OLIVARES'),
                array('id' => 1184, 'county_id' => '178', 'value' => 'BARRIO CASTELLI'),
                array('id' => 1185, 'county_id' => '178', 'value' => 'BARRIO CIUDADELA'),
                array('id' => 1186, 'county_id' => '178', 'value' => 'BARRIO GÜEMES'),
                array('id' => 1187, 'county_id' => '178', 'value' => 'BARRIO GASODUCTO'),
                array('id' => 1188, 'county_id' => '178', 'value' => 'BARRIO LAPRIDA'),
                array('id' => 1189, 'county_id' => '178', 'value' => 'BARRIO MANANTIAL ROSALES'),
                array('id' => 1190, 'county_id' => '178', 'value' => 'BARRIO MILITAR - AEROPUERTO MILITAR'),
                array('id' => 1191, 'county_id' => '178', 'value' => 'BARRIO PROSPERO PALAZZO'),
                array('id' => 1192, 'county_id' => '178', 'value' => 'BARRIO RESTINGA ALI'),
                array('id' => 1193, 'county_id' => '178', 'value' => 'BARRIO RODRIGUEZ PEÑA'),
                array('id' => 1194, 'county_id' => '178', 'value' => 'BARRIO SAAVEDRA'),
                array('id' => 1195, 'county_id' => '178', 'value' => 'BARRIO SARMIENTO'),
                array('id' => 1196, 'county_id' => '178', 'value' => 'BARRIO VILLA S.U.P.E.'),
                array('id' => 1197, 'county_id' => '178', 'value' => 'COMODORO RIVADAVIA'),
                array('id' => 1198, 'county_id' => '178', 'value' => 'DIADEMA ARGENTINA'),
                array('id' => 1199, 'county_id' => '178', 'value' => 'KM. 11 - CUARTELES'),
                array('id' => 1200, 'county_id' => '178', 'value' => 'KM. 3 - GENERAL MOSCONI'),
                array('id' => 1201, 'county_id' => '178', 'value' => 'KM. 5 - PRESIDENTE ORTIZ'),
                array('id' => 1202, 'county_id' => '178', 'value' => 'KM. 8 - DON BOSCO'),
                array('id' => 1203, 'county_id' => '178', 'value' => 'RADA TILLY'),
                array('id' => 1204, 'county_id' => '179', 'value' => 'CAMARONES'),
                array('id' => 1205, 'county_id' => '179', 'value' => 'GARAYALDE'),
                array('id' => 1206, 'county_id' => '180', 'value' => 'ALDEA ESCOLAR'),
                array('id' => 1207, 'county_id' => '180', 'value' => 'CORCOVADO'),
                array('id' => 1208, 'county_id' => '180', 'value' => 'ESQUEL'),
                array('id' => 1209, 'county_id' => '180', 'value' => 'LAGO ROSARIO'),
                array('id' => 1210, 'county_id' => '180', 'value' => 'LOS CIPRESES'),
                array('id' => 1211, 'county_id' => '180', 'value' => 'TREVELIN'),
                array('id' => 1212, 'county_id' => '180', 'value' => 'VILLA FUTALAUFQUEN'),
                array('id' => 1213, 'county_id' => '181', 'value' => '28 DE JULIO'),
                array('id' => 1214, 'county_id' => '181', 'value' => 'DIQUE FLORENTINO AMEGHINO'),
                array('id' => 1215, 'county_id' => '181', 'value' => 'DOLAVON'),
                array('id' => 1216, 'county_id' => '181', 'value' => 'GAIMAN'),
                array('id' => 1217, 'county_id' => '182', 'value' => 'BLANCUNTRE'),
                array('id' => 1218, 'county_id' => '182', 'value' => 'EL ESCORIAL'),
                array('id' => 1219, 'county_id' => '182', 'value' => 'GASTRE'),
                array('id' => 1220, 'county_id' => '182', 'value' => 'LAGUNITA SALADA'),
                array('id' => 1221, 'county_id' => '182', 'value' => 'YALA LAUBAT'),
                array('id' => 1222, 'county_id' => '183', 'value' => 'ALDEA EPULEF'),
                array('id' => 1223, 'county_id' => '183', 'value' => 'CARRENLEUFU'),
                array('id' => 1224, 'county_id' => '183', 'value' => 'COLAN CONHUE'),
                array('id' => 1225, 'county_id' => '183', 'value' => 'PASO DEL SAPO'),
                array('id' => 1226, 'county_id' => '183', 'value' => 'TECKA'),
                array('id' => 1227, 'county_id' => '184', 'value' => 'EL MIRASOL'),
                array('id' => 1228, 'county_id' => '184', 'value' => 'LAS PLUMAS'),
                array('id' => 1229, 'county_id' => '185', 'value' => 'CERRO CONDOR'),
                array('id' => 1230, 'county_id' => '185', 'value' => 'LOS ALTARES'),
                array('id' => 1231, 'county_id' => '185', 'value' => 'PASO DE INDIOS'),
                array('id' => 1232, 'county_id' => '186', 'value' => 'PLAYA MAGAGNA'),
                array('id' => 1233, 'county_id' => '186', 'value' => 'PLAYA UNION'),
                array('id' => 1234, 'county_id' => '186', 'value' => 'RAWSON'),
                array('id' => 1235, 'county_id' => '186', 'value' => 'TRELEW'),
                array('id' => 1236, 'county_id' => '187', 'value' => 'ALDEA APELEG'),
                array('id' => 1237, 'county_id' => '187', 'value' => 'ALDEA BELEIRO'),
                array('id' => 1238, 'county_id' => '187', 'value' => 'ALTO RIO SENGUER'),
                array('id' => 1239, 'county_id' => '187', 'value' => 'DOCTOR RICARDO ROJAS'),
                array('id' => 1240, 'county_id' => '187', 'value' => 'FACUNDO'),
                array('id' => 1241, 'county_id' => '187', 'value' => 'LAGO BLANCO'),
                array('id' => 1242, 'county_id' => '187', 'value' => 'RIO MAYO'),
                array('id' => 1243, 'county_id' => '188', 'value' => 'BUEN PASTO'),
                array('id' => 1244, 'county_id' => '188', 'value' => 'SARMIENTO'),
                array('id' => 1245, 'county_id' => '189', 'value' => 'FRONTERA DE RIO PICO'),
                array('id' => 1246, 'county_id' => '189', 'value' => 'GOBERNADOR COSTA'),
                array('id' => 1247, 'county_id' => '189', 'value' => 'JOSE DE SAN MARTIN'),
                array('id' => 1248, 'county_id' => '189', 'value' => 'RIO PICO'),
                array('id' => 1249, 'county_id' => '190', 'value' => 'GAN GAN'),
                array('id' => 1250, 'county_id' => '190', 'value' => 'TELSEN'),
                array('id' => 1251, 'county_id' => '191', 'value' => 'CONSTITUCION'),
                array('id' => 1252, 'county_id' => '191', 'value' => 'MONSERRAT'),
                array('id' => 1253, 'county_id' => '191', 'value' => 'PUERTO MADERO'),
                array('id' => 1254, 'county_id' => '191', 'value' => 'RETIRO'),
                array('id' => 1255, 'county_id' => '191', 'value' => 'SAN NICOLAS'),
                array('id' => 1256, 'county_id' => '191', 'value' => 'SAN TELMO'),
                array('id' => 1257, 'county_id' => '192', 'value' => 'FLORESTA'),
                array('id' => 1258, 'county_id' => '192', 'value' => 'MONTE CASTRO'),
                array('id' => 1259, 'county_id' => '192', 'value' => 'VELEZ SARSFIELD'),
                array('id' => 1260, 'county_id' => '192', 'value' => 'VERSALLES'),
                array('id' => 1261, 'county_id' => '192', 'value' => 'VILLA LURO'),
                array('id' => 1262, 'county_id' => '192', 'value' => 'VILLA REAL'),
                array('id' => 1263, 'county_id' => '193', 'value' => 'VILLA DEL PARQUE'),
                array('id' => 1264, 'county_id' => '193', 'value' => 'VILLA DEVOTO'),
                array('id' => 1265, 'county_id' => '193', 'value' => 'VILLA GENERAL MITRE'),
                array('id' => 1266, 'county_id' => '193', 'value' => 'VILLA SANTA RITA'),
                array('id' => 1267, 'county_id' => '194', 'value' => 'COGHLAN'),
                array('id' => 1268, 'county_id' => '194', 'value' => 'SAAVEDRA'),
                array('id' => 1269, 'county_id' => '194', 'value' => 'VILLA PUEYRREDON'),
                array('id' => 1270, 'county_id' => '194', 'value' => 'VILLA URQUIZA'),
                array('id' => 1271, 'county_id' => '195', 'value' => 'BELGRANO'),
                array('id' => 1272, 'county_id' => '195', 'value' => 'COLEGIALES'),
                array('id' => 1273, 'county_id' => '195', 'value' => 'NUÑEZ'),
                array('id' => 1274, 'county_id' => '196', 'value' => 'PALERMO'),
                array('id' => 1275, 'county_id' => '197', 'value' => 'AGRONOMIA'),
                array('id' => 1276, 'county_id' => '197', 'value' => 'CHACARITA'),
                array('id' => 1277, 'county_id' => '197', 'value' => 'PARQUE CHAS'),
                array('id' => 1278, 'county_id' => '197', 'value' => 'PATERNAL'),
                array('id' => 1279, 'county_id' => '197', 'value' => 'VILLA CRESPO'),
                array('id' => 1280, 'county_id' => '197', 'value' => 'VILLA ORTUZAR'),
                array('id' => 1281, 'county_id' => '198', 'value' => 'RECOLETA'),
                array('id' => 1282, 'county_id' => '199', 'value' => 'BALVANERA'),
                array('id' => 1283, 'county_id' => '199', 'value' => 'SAN CRISTOBAL'),
                array('id' => 1284, 'county_id' => '200', 'value' => 'BARRACAS'),
                array('id' => 1285, 'county_id' => '200', 'value' => 'BOCA'),
                array('id' => 1286, 'county_id' => '200', 'value' => 'NUEVA POMPEYA'),
                array('id' => 1287, 'county_id' => '200', 'value' => 'PARQUE PATRICIOS'),
                array('id' => 1288, 'county_id' => '201', 'value' => 'ALMAGRO'),
                array('id' => 1289, 'county_id' => '201', 'value' => 'BOEDO'),
                array('id' => 1290, 'county_id' => '202', 'value' => 'CABALLITO'),
                array('id' => 1291, 'county_id' => '203', 'value' => 'FLORES'),
                array('id' => 1292, 'county_id' => '203', 'value' => 'PARQUE CHACABUCO'),
                array('id' => 1293, 'county_id' => '204', 'value' => 'VILLA LUGANO'),
                array('id' => 1294, 'county_id' => '204', 'value' => 'VILLA RIACHUELO'),
                array('id' => 1295, 'county_id' => '204', 'value' => 'VILLA SOLDATI'),
                array('id' => 1296, 'county_id' => '205', 'value' => 'LINIERS'),
                array('id' => 1297, 'county_id' => '205', 'value' => 'MATADEROS'),
                array('id' => 1298, 'county_id' => '205', 'value' => 'PARQUE AVELLANEDA'),
                array('id' => 1299, 'county_id' => '206', 'value' => 'AMBOY'),
                array('id' => 1300, 'county_id' => '206', 'value' => 'ARROYO SAN ANTONIO'),
                array('id' => 1301, 'county_id' => '206', 'value' => 'CAÑADA DEL SAUCE'),
                array('id' => 1302, 'county_id' => '206', 'value' => 'CAPILLA VIEJA'),
                array('id' => 1303, 'county_id' => '206', 'value' => 'EL CORCOVADO - EL TORREON'),
                array('id' => 1304, 'county_id' => '206', 'value' => 'EL DURAZNO'),
                array('id' => 1305, 'county_id' => '206', 'value' => 'EMBALSE'),
                array('id' => 1306, 'county_id' => '206', 'value' => 'LA CRUZ'),
                array('id' => 1307, 'county_id' => '206', 'value' => 'LA CUMBRECITA'),
                array('id' => 1308, 'county_id' => '206', 'value' => 'LAS BAJADAS'),
                array('id' => 1309, 'county_id' => '206', 'value' => 'LAS CALERAS'),
                array('id' => 1310, 'county_id' => '206', 'value' => 'LOS CONDORES'),
                array('id' => 1311, 'county_id' => '206', 'value' => 'LOS MOLINOS'),
                array('id' => 1312, 'county_id' => '206', 'value' => 'LOS REARTES'),
                array('id' => 1313, 'county_id' => '206', 'value' => 'LUTTI'),
                array('id' => 1314, 'county_id' => '206', 'value' => 'PARQUE CALMAYO'),
                array('id' => 1315, 'county_id' => '206', 'value' => 'RIO DE LOS SAUCES'),
                array('id' => 1316, 'county_id' => '206', 'value' => 'SAN AGUSTIN'),
                array('id' => 1317, 'county_id' => '206', 'value' => 'SAN IGNACIO (LOTEO SAN JAVIER)'),
                array('id' => 1318, 'county_id' => '206', 'value' => 'SAN IGNACIO (LOTEO VELEZ CRESPO)'),
                array('id' => 1319, 'county_id' => '206', 'value' => 'SANTA MONICA'),
                array('id' => 1320, 'county_id' => '206', 'value' => 'SANTA ROSA DE CALAMUCHITA'),
                array('id' => 1321, 'county_id' => '206', 'value' => 'SEGUNDA USINA'),
                array('id' => 1322, 'county_id' => '206', 'value' => 'SOLAR DE LOS MOLINOS'),
                array('id' => 1323, 'county_id' => '206', 'value' => 'VILLA ALPINA'),
                array('id' => 1324, 'county_id' => '206', 'value' => 'VILLA AMANCAY'),
                array('id' => 1325, 'county_id' => '206', 'value' => 'VILLA BERNA'),
                array('id' => 1326, 'county_id' => '206', 'value' => 'VILLA CIUDAD PARQUE LOS REARTES'),
                array('id' => 1327, 'county_id' => '206', 'value' => 'VILLA CIUDAD PARQUE LOS REARTES (1a.SECC'),
                array('id' => 1328, 'county_id' => '206', 'value' => 'VILLA CIUDAD PARQUE LOS REARTES (3Â° SECCION)'),
                array('id' => 1329, 'county_id' => '206', 'value' => 'VILLA CIUDAD PARQUES LOS REARTES (1Â° SECCION)'),
                array('id' => 1330, 'county_id' => '206', 'value' => 'VILLA DEL DIQUE'),
                array('id' => 1331, 'county_id' => '206', 'value' => 'VILLA EL TALA'),
                array('id' => 1332, 'county_id' => '206', 'value' => 'VILLA GENERAL BELGRANO'),
                array('id' => 1333, 'county_id' => '206', 'value' => 'VILLA LA RIVERA'),
                array('id' => 1334, 'county_id' => '206', 'value' => 'VILLA QUILLINZO'),
                array('id' => 1335, 'county_id' => '206', 'value' => 'VILLA RUMIPAL'),
                array('id' => 1336, 'county_id' => '206', 'value' => 'VILLA SAN MIGUEL'),
                array('id' => 1337, 'county_id' => '206', 'value' => 'VILLA YACANTO'),
                array('id' => 1338, 'county_id' => '207', 'value' => 'CORDOBA'),
                array('id' => 1339, 'county_id' => '207', 'value' => 'JARDIN ARENALES'),
                array('id' => 1340, 'county_id' => '207', 'value' => 'LA FLORESTA'),
                array('id' => 1341, 'county_id' => '208', 'value' => '1 DE AGOSTO'),
                array('id' => 1342, 'county_id' => '208', 'value' => 'AGUA DE ORO'),
                array('id' => 1343, 'county_id' => '208', 'value' => 'ALMIRANTE BROWN'),
                array('id' => 1344, 'county_id' => '208', 'value' => 'ASCOCHINGA'),
                array('id' => 1345, 'county_id' => '208', 'value' => 'BARRIO NUEVO RIO CEBALLOS'),
                array('id' => 1346, 'county_id' => '208', 'value' => 'CANTERAS EL SAUCE'),
                array('id' => 1347, 'county_id' => '208', 'value' => 'CASA BAMBA'),
                array('id' => 1348, 'county_id' => '208', 'value' => 'CIUDAD DE LOS NIÑOS'),
                array('id' => 1349, 'county_id' => '208', 'value' => 'COLONIA CAROYA'),
                array('id' => 1350, 'county_id' => '208', 'value' => 'COLONIA TIROLESA'),
                array('id' => 1351, 'county_id' => '208', 'value' => 'COLONIA VICENTE AGUERO'),
                array('id' => 1352, 'county_id' => '208', 'value' => 'CORRAL QUEMADO'),
                array('id' => 1353, 'county_id' => '208', 'value' => 'COUNTRY CHACRAS DE LA VILLA'),
                array('id' => 1354, 'county_id' => '208', 'value' => 'COUNTRY CHACRAS DE LA VILLA - COUNTRY SA'),
                array('id' => 1355, 'county_id' => '208', 'value' => 'COUNTRY SAN ISIDRO'),
                array('id' => 1356, 'county_id' => '208', 'value' => 'DUMESNIL'),
                array('id' => 1357, 'county_id' => '208', 'value' => 'EL DIQUECITO'),
                array('id' => 1358, 'county_id' => '208', 'value' => 'EL MANZANO'),
                array('id' => 1359, 'county_id' => '208', 'value' => 'EL PUEBLITO'),
                array('id' => 1360, 'county_id' => '208', 'value' => 'ESTACION COLONIA TIROLESA'),
                array('id' => 1361, 'county_id' => '208', 'value' => 'GENERAL PAZ'),
                array('id' => 1362, 'county_id' => '208', 'value' => 'GUIÑAZU NORTE'),
                array('id' => 1363, 'county_id' => '208', 'value' => 'JESUS MARIA'),
                array('id' => 1364, 'county_id' => '208', 'value' => 'JUAREZ CELMAN'),
                array('id' => 1365, 'county_id' => '208', 'value' => 'LA CALERA'),
                array('id' => 1366, 'county_id' => '208', 'value' => 'LA GRANJA'),
                array('id' => 1367, 'county_id' => '208', 'value' => 'LA MORADA'),
                array('id' => 1368, 'county_id' => '208', 'value' => 'LA PUERTA'),
                array('id' => 1369, 'county_id' => '208', 'value' => 'LAS CORZUELAS'),
                array('id' => 1370, 'county_id' => '208', 'value' => 'LOS MOLLES'),
                array('id' => 1371, 'county_id' => '208', 'value' => 'MALVINAS ARGENTINAS'),
                array('id' => 1372, 'county_id' => '208', 'value' => 'MENDIOLAZA'),
                array('id' => 1373, 'county_id' => '208', 'value' => 'MI GRANJA'),
                array('id' => 1374, 'county_id' => '208', 'value' => 'PAJAS BLANCAS'),
                array('id' => 1375, 'county_id' => '208', 'value' => 'PARQUE NORTE'),
                array('id' => 1376, 'county_id' => '208', 'value' => 'RIO CEBALLOS'),
                array('id' => 1377, 'county_id' => '208', 'value' => 'SALDAN'),
                array('id' => 1378, 'county_id' => '208', 'value' => 'SALSIPUEDES'),
                array('id' => 1379, 'county_id' => '208', 'value' => 'SANTA ELENA'),
                array('id' => 1380, 'county_id' => '208', 'value' => 'TINOCO'),
                array('id' => 1381, 'county_id' => '208', 'value' => 'UNQUILLO'),
                array('id' => 1382, 'county_id' => '208', 'value' => 'VILLA ALLENDE'),
                array('id' => 1383, 'county_id' => '208', 'value' => 'VILLA CERRO AZUL'),
                array('id' => 1384, 'county_id' => '208', 'value' => 'VILLA CORAZON DE MARIA'),
                array('id' => 1385, 'county_id' => '208', 'value' => 'VILLA EL FACHINAL - PARQUE NORTE - GUIÑA'),
                array('id' => 1386, 'county_id' => '208', 'value' => 'VILLA LOS LLANOS'),
                array('id' => 1387, 'county_id' => '208', 'value' => 'VILLA PASTORA'),
                array('id' => 1388, 'county_id' => '209', 'value' => 'ALTO DE LOS QUEBRACHOS'),
                array('id' => 1389, 'county_id' => '209', 'value' => 'BAÑADO DE SOTO'),
                array('id' => 1390, 'county_id' => '209', 'value' => 'CANTERAS QUILPO'),
                array('id' => 1391, 'county_id' => '209', 'value' => 'CRUZ DE CAÑA'),
                array('id' => 1392, 'county_id' => '209', 'value' => 'CRUZ DEL EJE'),
                array('id' => 1393, 'county_id' => '209', 'value' => 'EL BRETE'),
                array('id' => 1394, 'county_id' => '209', 'value' => 'EL RINCON'),
                array('id' => 1395, 'county_id' => '209', 'value' => 'GUANACO MUERTO'),
                array('id' => 1396, 'county_id' => '209', 'value' => 'LA BANDA'),
                array('id' => 1397, 'county_id' => '209', 'value' => 'LA BATEA'),
                array('id' => 1398, 'county_id' => '209', 'value' => 'LA HIGUERA'),
                array('id' => 1399, 'county_id' => '209', 'value' => 'LAS CAÑADAS'),
                array('id' => 1400, 'county_id' => '209', 'value' => 'LAS PLAYAS'),
                array('id' => 1401, 'county_id' => '209', 'value' => 'LOS CHAÑARITOS'),
                array('id' => 1402, 'county_id' => '209', 'value' => 'MEDIA NARANJA'),
                array('id' => 1403, 'county_id' => '209', 'value' => 'PASO VIEJO'),
                array('id' => 1404, 'county_id' => '209', 'value' => 'SAN MARCOS SIERRA'),
                array('id' => 1405, 'county_id' => '209', 'value' => 'SERREZUELA'),
                array('id' => 1406, 'county_id' => '209', 'value' => 'TUCLAME'),
                array('id' => 1407, 'county_id' => '209', 'value' => 'VILLA DE SOTO'),
                array('id' => 1408, 'county_id' => '210', 'value' => 'DEL CAMPILLO'),
                array('id' => 1409, 'county_id' => '210', 'value' => 'ESTACION LECUEDER'),
                array('id' => 1410, 'county_id' => '210', 'value' => 'HIPOLITO BOUCHARD'),
                array('id' => 1411, 'county_id' => '210', 'value' => 'HUINCA RENANCO'),
                array('id' => 1412, 'county_id' => '210', 'value' => 'ITALO'),
                array('id' => 1413, 'county_id' => '210', 'value' => 'MATTALDI'),
                array('id' => 1414, 'county_id' => '210', 'value' => 'NICOLAS BRUZZONE'),
                array('id' => 1415, 'county_id' => '210', 'value' => 'ONAGOITY'),
                array('id' => 1416, 'county_id' => '210', 'value' => 'PINCEN'),
                array('id' => 1417, 'county_id' => '210', 'value' => 'RANQUELES'),
                array('id' => 1418, 'county_id' => '210', 'value' => 'SANTA MAGDALENA'),
                array('id' => 1419, 'county_id' => '210', 'value' => 'VILLA HUIDOBRO'),
                array('id' => 1420, 'county_id' => '210', 'value' => 'VILLA SARMIENTO'),
                array('id' => 1421, 'county_id' => '210', 'value' => 'VILLA VALERIA'),
                array('id' => 1422, 'county_id' => '211', 'value' => 'ARROYO ALGODON'),
                array('id' => 1423, 'county_id' => '211', 'value' => 'ARROYO CABRAL'),
                array('id' => 1424, 'county_id' => '211', 'value' => 'AUSONIA'),
                array('id' => 1425, 'county_id' => '211', 'value' => 'CHAZON'),
                array('id' => 1426, 'county_id' => '211', 'value' => 'ETRURIA'),
                array('id' => 1427, 'county_id' => '211', 'value' => 'LA LAGUNA'),
                array('id' => 1428, 'county_id' => '211', 'value' => 'LA PALESTINA'),
                array('id' => 1429, 'county_id' => '211', 'value' => 'LA PLAYOSA'),
                array('id' => 1430, 'county_id' => '211', 'value' => 'LAS MOJARRAS'),
                array('id' => 1431, 'county_id' => '211', 'value' => 'LUCA'),
                array('id' => 1432, 'county_id' => '211', 'value' => 'PASCO'),
                array('id' => 1433, 'county_id' => '211', 'value' => 'SANABRIA'),
                array('id' => 1434, 'county_id' => '211', 'value' => 'SILVIO PELLICO'),
                array('id' => 1435, 'county_id' => '211', 'value' => 'TICINO'),
                array('id' => 1436, 'county_id' => '211', 'value' => 'TIO PUJIO'),
                array('id' => 1437, 'county_id' => '211', 'value' => 'VILLA ALBERTINA'),
                array('id' => 1438, 'county_id' => '211', 'value' => 'VILLA MARIA'),
                array('id' => 1439, 'county_id' => '211', 'value' => 'VILLA NUEVA'),
                array('id' => 1440, 'county_id' => '211', 'value' => 'VILLA OESTE'),
                array('id' => 1441, 'county_id' => '212', 'value' => 'AVELLANEDA'),
                array('id' => 1442, 'county_id' => '212', 'value' => 'CAÑADA DE RIO PINTO'),
                array('id' => 1443, 'county_id' => '212', 'value' => 'CHUÑA'),
                array('id' => 1444, 'county_id' => '212', 'value' => 'COPACABANA'),
                array('id' => 1445, 'county_id' => '212', 'value' => 'DEAN FUNES'),
                array('id' => 1446, 'county_id' => '212', 'value' => 'ESQUINA DEL ALAMBRE'),
                array('id' => 1447, 'county_id' => '212', 'value' => 'LOS POZOS'),
                array('id' => 1448, 'county_id' => '212', 'value' => 'OLIVARES DE SAN NICOLAS'),
                array('id' => 1449, 'county_id' => '212', 'value' => 'QUILINO'),
                array('id' => 1450, 'county_id' => '212', 'value' => 'SAN PEDRO DE TOYOS'),
                array('id' => 1451, 'county_id' => '212', 'value' => 'VILLA GUTIERREZ'),
                array('id' => 1452, 'county_id' => '212', 'value' => 'VILLA QUILINO'),
                array('id' => 1453, 'county_id' => '213', 'value' => 'ALEJANDRO ROCA'),
                array('id' => 1454, 'county_id' => '213', 'value' => 'ASSUNTA'),
                array('id' => 1455, 'county_id' => '213', 'value' => 'BENGOLEA'),
                array('id' => 1456, 'county_id' => '213', 'value' => 'CARNERILLO'),
                array('id' => 1457, 'county_id' => '213', 'value' => 'CHARRAS'),
                array('id' => 1458, 'county_id' => '213', 'value' => 'EL RASTREADOR'),
                array('id' => 1459, 'county_id' => '213', 'value' => 'GENERAL CABRERA'),
                array('id' => 1460, 'county_id' => '213', 'value' => 'GENERAL DEHEZA'),
                array('id' => 1461, 'county_id' => '213', 'value' => 'HUANCHILLAS'),
                array('id' => 1462, 'county_id' => '213', 'value' => 'LA CARLOTA'),
                array('id' => 1463, 'county_id' => '213', 'value' => 'LOS CISNES'),
                array('id' => 1464, 'county_id' => '213', 'value' => 'OLAETA'),
                array('id' => 1465, 'county_id' => '213', 'value' => 'PACHECO DE MELO'),
                array('id' => 1466, 'county_id' => '213', 'value' => 'PASO DEL DURAZNO'),
                array('id' => 1467, 'county_id' => '213', 'value' => 'SANTA EUFEMIA'),
                array('id' => 1468, 'county_id' => '213', 'value' => 'UCACHA'),
                array('id' => 1469, 'county_id' => '213', 'value' => 'VILLA REDUCCION'),
                array('id' => 1470, 'county_id' => '214', 'value' => 'ALEJO LEDESMA'),
                array('id' => 1471, 'county_id' => '214', 'value' => 'ARIAS'),
                array('id' => 1472, 'county_id' => '214', 'value' => 'CAMILO ALDAO'),
                array('id' => 1473, 'county_id' => '214', 'value' => 'CAPITAN GENERAL BERNARDO O`HIGGINS'),
                array('id' => 1474, 'county_id' => '214', 'value' => 'CAVANAGH'),
                array('id' => 1475, 'county_id' => '214', 'value' => 'COLONIA BARGE'),
                array('id' => 1476, 'county_id' => '214', 'value' => 'COLONIA ITALIANA'),
                array('id' => 1477, 'county_id' => '214', 'value' => 'COLONIA VEINTICINCO'),
                array('id' => 1478, 'county_id' => '214', 'value' => 'CORRAL DE BUSTOS'),
                array('id' => 1479, 'county_id' => '214', 'value' => 'CRUZ ALTA'),
                array('id' => 1480, 'county_id' => '214', 'value' => 'GENERAL BALDISSERA'),
                array('id' => 1481, 'county_id' => '214', 'value' => 'GENERAL ROCA'),
                array('id' => 1482, 'county_id' => '214', 'value' => 'GUATIMOZIN'),
                array('id' => 1483, 'county_id' => '214', 'value' => 'INRIVILLE'),
                array('id' => 1484, 'county_id' => '214', 'value' => 'ISLA VERDE'),
                array('id' => 1485, 'county_id' => '214', 'value' => 'LEONES'),
                array('id' => 1486, 'county_id' => '214', 'value' => 'LOS SURGENTES'),
                array('id' => 1487, 'county_id' => '214', 'value' => 'MARCOS JUAREZ'),
                array('id' => 1488, 'county_id' => '214', 'value' => 'MONTE BUEY'),
                array('id' => 1489, 'county_id' => '214', 'value' => 'SAIRA'),
                array('id' => 1490, 'county_id' => '214', 'value' => 'SALADILLO'),
                array('id' => 1491, 'county_id' => '214', 'value' => 'VILLA ELISA'),
                array('id' => 1492, 'county_id' => '215', 'value' => 'CIENAGA DEL CORO'),
                array('id' => 1493, 'county_id' => '215', 'value' => 'EL CHACHO'),
                array('id' => 1494, 'county_id' => '215', 'value' => 'ESTANCIA DE GUADALUPE'),
                array('id' => 1495, 'county_id' => '215', 'value' => 'GUASAPAMPA'),
                array('id' => 1496, 'county_id' => '215', 'value' => 'LA PLAYA'),
                array('id' => 1497, 'county_id' => '215', 'value' => 'SAN CARLOS MINAS'),
                array('id' => 1498, 'county_id' => '215', 'value' => 'TALAINI'),
                array('id' => 1499, 'county_id' => '215', 'value' => 'TOSNO'),
                array('id' => 1500, 'county_id' => '216', 'value' => 'CHANCANI'),
                array('id' => 1501, 'county_id' => '216', 'value' => 'LAS PALMAS'),
                array('id' => 1502, 'county_id' => '216', 'value' => 'LOS TALARES'),
                array('id' => 1503, 'county_id' => '216', 'value' => 'SALSACATE'),
                array('id' => 1504, 'county_id' => '216', 'value' => 'SAN GERONIMO'),
                array('id' => 1505, 'county_id' => '216', 'value' => 'TALA CAÑADA'),
                array('id' => 1506, 'county_id' => '216', 'value' => 'TANINGA'),
                array('id' => 1507, 'county_id' => '216', 'value' => 'VILLA DE POCHO'),
                array('id' => 1508, 'county_id' => '217', 'value' => 'GENERAL LEVALLE'),
                array('id' => 1509, 'county_id' => '217', 'value' => 'LA CESIRA'),
                array('id' => 1510, 'county_id' => '217', 'value' => 'LABOULAYE'),
                array('id' => 1511, 'county_id' => '217', 'value' => 'LEGUIZAMON'),
                array('id' => 1512, 'county_id' => '217', 'value' => 'MELO'),
                array('id' => 1513, 'county_id' => '217', 'value' => 'RIO BAMBA'),
                array('id' => 1514, 'county_id' => '217', 'value' => 'ROSALES'),
                array('id' => 1515, 'county_id' => '217', 'value' => 'SAN JOAQUIN'),
                array('id' => 1516, 'county_id' => '217', 'value' => 'SERRANO'),
                array('id' => 1517, 'county_id' => '217', 'value' => 'VILLA ROSSI'),
                array('id' => 1518, 'county_id' => '218', 'value' => 'BARRIO SANTA ISABEL'),
                array('id' => 1519, 'county_id' => '218', 'value' => 'BIALET MASSE'),
                array('id' => 1520, 'county_id' => '218', 'value' => 'CABALANGO'),
                array('id' => 1521, 'county_id' => '218', 'value' => 'CAPILLA DEL MONTE'),
                array('id' => 1522, 'county_id' => '218', 'value' => 'CASA GRANDE'),
                array('id' => 1523, 'county_id' => '218', 'value' => 'CHARBONIER'),
                array('id' => 1524, 'county_id' => '218', 'value' => 'COSQUIN'),
                array('id' => 1525, 'county_id' => '218', 'value' => 'CUESTA BLANCA'),
                array('id' => 1526, 'county_id' => '218', 'value' => 'ESTANCIA VIEJA'),
                array('id' => 1527, 'county_id' => '218', 'value' => 'HUERTA GRANDE'),
                array('id' => 1528, 'county_id' => '218', 'value' => 'LA CUMBRE'),
                array('id' => 1529, 'county_id' => '218', 'value' => 'LA FALDA'),
                array('id' => 1530, 'county_id' => '218', 'value' => 'LAS JARILLAS'),
                array('id' => 1531, 'county_id' => '218', 'value' => 'LOS COCOS'),
                array('id' => 1532, 'county_id' => '218', 'value' => 'MALLIN'),
                array('id' => 1533, 'county_id' => '218', 'value' => 'MAYU SUMAJ'),
                array('id' => 1534, 'county_id' => '218', 'value' => 'QUEBRADA DE LUNA'),
                array('id' => 1535, 'county_id' => '218', 'value' => 'SAN ANTONIO DE ARREDONDO'),
                array('id' => 1536, 'county_id' => '218', 'value' => 'SAN ESTEBAN'),
                array('id' => 1537, 'county_id' => '218', 'value' => 'SAN ROQUE'),
                array('id' => 1538, 'county_id' => '218', 'value' => 'SAN ROQUE DEL LAGO'),
                array('id' => 1539, 'county_id' => '218', 'value' => 'SANTA MARIA DE PUNILLA'),
                array('id' => 1540, 'county_id' => '218', 'value' => 'TALA HUASI'),
                array('id' => 1541, 'county_id' => '218', 'value' => 'TANTI'),
                array('id' => 1542, 'county_id' => '218', 'value' => 'VALLE HERMOSO'),
                array('id' => 1543, 'county_id' => '218', 'value' => 'VILLA CARLOS PAZ'),
                array('id' => 1544, 'county_id' => '218', 'value' => 'VILLA FLOR SERRANA'),
                array('id' => 1545, 'county_id' => '218', 'value' => 'VILLA GIARDINO'),
                array('id' => 1546, 'county_id' => '218', 'value' => 'VILLA LAGO AZUL'),
                array('id' => 1547, 'county_id' => '218', 'value' => 'VILLA PARQUE SIQUIMAN'),
                array('id' => 1548, 'county_id' => '218', 'value' => 'VILLA RIO ICHO CRUZ'),
                array('id' => 1549, 'county_id' => '218', 'value' => 'VILLA SAN JOSE'),
                array('id' => 1550, 'county_id' => '218', 'value' => 'VILLA SANTA CRUZ DEL LAGO'),
                array('id' => 1551, 'county_id' => '219', 'value' => 'ACHIRAS'),
                array('id' => 1552, 'county_id' => '219', 'value' => 'ADELIA MARIA'),
                array('id' => 1553, 'county_id' => '219', 'value' => 'ALCIRA'),
                array('id' => 1554, 'county_id' => '219', 'value' => 'ALPA CORRAL'),
                array('id' => 1555, 'county_id' => '219', 'value' => 'BERROTARAN'),
                array('id' => 1556, 'county_id' => '219', 'value' => 'BULNES'),
                array('id' => 1557, 'county_id' => '219', 'value' => 'CHAJAN'),
                array('id' => 1558, 'county_id' => '219', 'value' => 'CHUCUL'),
                array('id' => 1559, 'county_id' => '219', 'value' => 'CORONEL BAIGORRIA'),
                array('id' => 1560, 'county_id' => '219', 'value' => 'CORONEL MOLDES'),
                array('id' => 1561, 'county_id' => '219', 'value' => 'ELENA'),
                array('id' => 1562, 'county_id' => '219', 'value' => 'LA CAROLINA'),
                array('id' => 1563, 'county_id' => '219', 'value' => 'LA CAUTIVA'),
                array('id' => 1564, 'county_id' => '219', 'value' => 'LA GILDA'),
                array('id' => 1565, 'county_id' => '219', 'value' => 'LAS ACEQUIAS'),
                array('id' => 1566, 'county_id' => '219', 'value' => 'LAS ALBAHACAS'),
                array('id' => 1567, 'county_id' => '219', 'value' => 'LAS HIGUERAS'),
                array('id' => 1568, 'county_id' => '219', 'value' => 'LAS PEÑAS'),
                array('id' => 1569, 'county_id' => '219', 'value' => 'LAS VERTIENTES'),
                array('id' => 1570, 'county_id' => '219', 'value' => 'MALENA'),
                array('id' => 1571, 'county_id' => '219', 'value' => 'MONTE DE LOS GAUCHOS'),
                array('id' => 1572, 'county_id' => '219', 'value' => 'PASO DEL DURAZNO'),
                array('id' => 1573, 'county_id' => '219', 'value' => 'RIO CUARTO'),
                array('id' => 1574, 'county_id' => '219', 'value' => 'SAMPACHO'),
                array('id' => 1575, 'county_id' => '219', 'value' => 'SAN BASILIO'),
                array('id' => 1576, 'county_id' => '219', 'value' => 'SANTA CATALINA'),
                array('id' => 1577, 'county_id' => '219', 'value' => 'SUCO'),
                array('id' => 1578, 'county_id' => '219', 'value' => 'TOSQUITAS'),
                array('id' => 1579, 'county_id' => '219', 'value' => 'VICUÑA MACKENNA'),
                array('id' => 1580, 'county_id' => '219', 'value' => 'VILLA EL CHACAY'),
                array('id' => 1581, 'county_id' => '219', 'value' => 'VILLA SANTA EUGENIA'),
                array('id' => 1582, 'county_id' => '219', 'value' => 'WASHINGTON'),
                array('id' => 1583, 'county_id' => '220', 'value' => 'ATAHONA'),
                array('id' => 1584, 'county_id' => '220', 'value' => 'CAÑADA DE MACHADO'),
                array('id' => 1585, 'county_id' => '220', 'value' => 'CAPILLA DE LOS REMEDIOS'),
                array('id' => 1586, 'county_id' => '220', 'value' => 'CHALACEA'),
                array('id' => 1587, 'county_id' => '220', 'value' => 'COLONIA LAS CUATRO ESQUINAS'),
                array('id' => 1588, 'county_id' => '220', 'value' => 'DIEGO DE ROJAS'),
                array('id' => 1589, 'county_id' => '220', 'value' => 'EL ALCALDE'),
                array('id' => 1590, 'county_id' => '220', 'value' => 'EL CRISPIN'),
                array('id' => 1591, 'county_id' => '220', 'value' => 'ESQUINA'),
                array('id' => 1592, 'county_id' => '220', 'value' => 'KILOMETRO 658'),
                array('id' => 1593, 'county_id' => '220', 'value' => 'LA PARA'),
                array('id' => 1594, 'county_id' => '220', 'value' => 'LA POSTA'),
                array('id' => 1595, 'county_id' => '220', 'value' => 'LA PUERTA'),
                array('id' => 1596, 'county_id' => '220', 'value' => 'LA QUINTA'),
                array('id' => 1597, 'county_id' => '220', 'value' => 'LAS GRAMILLAS'),
                array('id' => 1598, 'county_id' => '220', 'value' => 'LAS SALADAS'),
                array('id' => 1599, 'county_id' => '220', 'value' => 'MAQUINISTA GALLINI'),
                array('id' => 1600, 'county_id' => '220', 'value' => 'MONTE DEL ROSARIO'),
                array('id' => 1601, 'county_id' => '220', 'value' => 'MONTECRISTO'),
                array('id' => 1602, 'county_id' => '220', 'value' => 'OBISPO TREJO'),
                array('id' => 1603, 'county_id' => '220', 'value' => 'PIQUILLIN'),
                array('id' => 1604, 'county_id' => '220', 'value' => 'PLAZA DE MERCEDES'),
                array('id' => 1605, 'county_id' => '220', 'value' => 'PUEBLO COMECHINGONES'),
                array('id' => 1606, 'county_id' => '220', 'value' => 'RIO PRIMERO'),
                array('id' => 1607, 'county_id' => '220', 'value' => 'SAGRADA FAMILIA'),
                array('id' => 1608, 'county_id' => '220', 'value' => 'SANTA ROSA DE RIO PRIMERO'),
                array('id' => 1609, 'county_id' => '220', 'value' => 'VILLA FONTANA'),
                array('id' => 1610, 'county_id' => '221', 'value' => 'CERRO COLORADO'),
                array('id' => 1611, 'county_id' => '221', 'value' => 'CHAÑAR VIEJO'),
                array('id' => 1612, 'county_id' => '221', 'value' => 'EUFRASIO LOZA'),
                array('id' => 1613, 'county_id' => '221', 'value' => 'GUTEMBERG'),
                array('id' => 1614, 'county_id' => '221', 'value' => 'LA RINCONADA'),
                array('id' => 1615, 'county_id' => '221', 'value' => 'LOS HOYOS'),
                array('id' => 1616, 'county_id' => '221', 'value' => 'PUESTO DE CASTRO'),
                array('id' => 1617, 'county_id' => '221', 'value' => 'RAYO CORTADO'),
                array('id' => 1618, 'county_id' => '221', 'value' => 'SAN PEDRO DE GUTEMBERG'),
                array('id' => 1619, 'county_id' => '221', 'value' => 'SANTA ELENA'),
                array('id' => 1620, 'county_id' => '221', 'value' => 'SEBASTIAN ELCANO'),
                array('id' => 1621, 'county_id' => '221', 'value' => 'VILLA CANDELARIA NORTE'),
                array('id' => 1622, 'county_id' => '221', 'value' => 'VILLA DE MARIA'),
                array('id' => 1623, 'county_id' => '222', 'value' => 'CALCHIN'),
                array('id' => 1624, 'county_id' => '222', 'value' => 'CALCHIN OESTE'),
                array('id' => 1625, 'county_id' => '222', 'value' => 'CAPILLA DEL CARMEN'),
                array('id' => 1626, 'county_id' => '222', 'value' => 'CARRILOBO'),
                array('id' => 1627, 'county_id' => '222', 'value' => 'COLAZO'),
                array('id' => 1628, 'county_id' => '222', 'value' => 'COLONIA VIDELA'),
                array('id' => 1629, 'county_id' => '222', 'value' => 'COSTASACATE'),
                array('id' => 1630, 'county_id' => '222', 'value' => 'IMPIRA'),
                array('id' => 1631, 'county_id' => '222', 'value' => 'LAGUNA LARGA'),
                array('id' => 1632, 'county_id' => '222', 'value' => 'LAS JUNTURAS'),
                array('id' => 1633, 'county_id' => '222', 'value' => 'LOS CHAÑARITOS'),
                array('id' => 1634, 'county_id' => '222', 'value' => 'LUQUE'),
                array('id' => 1635, 'county_id' => '222', 'value' => 'MANFREDI'),
                array('id' => 1636, 'county_id' => '222', 'value' => 'MATORRALES'),
                array('id' => 1637, 'county_id' => '222', 'value' => 'ONCATIVO'),
                array('id' => 1638, 'county_id' => '222', 'value' => 'PILAR'),
                array('id' => 1639, 'county_id' => '222', 'value' => 'POZO DEL MOLLE'),
                array('id' => 1640, 'county_id' => '222', 'value' => 'RINCON'),
                array('id' => 1641, 'county_id' => '222', 'value' => 'RIO SEGUNDO'),
                array('id' => 1642, 'county_id' => '222', 'value' => 'SANTIAGO TEMPLE'),
                array('id' => 1643, 'county_id' => '222', 'value' => 'VILLA DEL ROSARIO'),
                array('id' => 1644, 'county_id' => '223', 'value' => 'AMBUL'),
                array('id' => 1645, 'county_id' => '223', 'value' => 'ARROYO LOS PATOS'),
                array('id' => 1646, 'county_id' => '223', 'value' => 'EL HUAYCO'),
                array('id' => 1647, 'county_id' => '223', 'value' => 'LA CORTADERA'),
                array('id' => 1648, 'county_id' => '223', 'value' => 'LAS CALLES'),
                array('id' => 1649, 'county_id' => '223', 'value' => 'LAS OSCURAS'),
                array('id' => 1650, 'county_id' => '223', 'value' => 'LAS RABONAS'),
                array('id' => 1651, 'county_id' => '223', 'value' => 'LOS CALLEJONES'),
                array('id' => 1652, 'county_id' => '223', 'value' => 'MINA CLAVERO'),
                array('id' => 1653, 'county_id' => '223', 'value' => 'MUSSI'),
                array('id' => 1654, 'county_id' => '223', 'value' => 'NONO'),
                array('id' => 1655, 'county_id' => '223', 'value' => 'PANAHOLMA'),
                array('id' => 1656, 'county_id' => '223', 'value' => 'SAN HUBERTO'),
                array('id' => 1657, 'county_id' => '223', 'value' => 'SAN LORENZO'),
                array('id' => 1658, 'county_id' => '223', 'value' => 'SAN MARTIN'),
                array('id' => 1659, 'county_id' => '223', 'value' => 'SAN PEDRO'),
                array('id' => 1660, 'county_id' => '223', 'value' => 'SAN VICENTE'),
                array('id' => 1661, 'county_id' => '223', 'value' => 'SAUCE ARRIBA'),
                array('id' => 1662, 'county_id' => '223', 'value' => 'TASNA'),
                array('id' => 1663, 'county_id' => '223', 'value' => 'VILLA CURA BROCHERO'),
                array('id' => 1664, 'county_id' => '223', 'value' => 'VILLA SARMIENTO'),
                array('id' => 1665, 'county_id' => '224', 'value' => 'ALTO RESBALOSO - EL BARRIAL'),
                array('id' => 1666, 'county_id' => '224', 'value' => 'CONLARA'),
                array('id' => 1667, 'county_id' => '224', 'value' => 'CRUZ CAÑA'),
                array('id' => 1668, 'county_id' => '224', 'value' => 'DOS ARROYOS'),
                array('id' => 1669, 'county_id' => '224', 'value' => 'EL PANTANILLO'),
                array('id' => 1670, 'county_id' => '224', 'value' => 'EL PUEBLITO'),
                array('id' => 1671, 'county_id' => '224', 'value' => 'EL VALLE'),
                array('id' => 1672, 'county_id' => '224', 'value' => 'LA PAZ'),
                array('id' => 1673, 'county_id' => '224', 'value' => 'LA POBLACION'),
                array('id' => 1674, 'county_id' => '224', 'value' => 'LA RAMADA'),
                array('id' => 1675, 'county_id' => '224', 'value' => 'LA TRAVESIA'),
                array('id' => 1676, 'county_id' => '224', 'value' => 'LAS CHACRAS'),
                array('id' => 1677, 'county_id' => '224', 'value' => 'LAS TAPIAS'),
                array('id' => 1678, 'county_id' => '224', 'value' => 'LOMA BOLA'),
                array('id' => 1679, 'county_id' => '224', 'value' => 'LOS CERRILLOS'),
                array('id' => 1680, 'county_id' => '224', 'value' => 'LOS HORNILLOS'),
                array('id' => 1681, 'county_id' => '224', 'value' => 'LOS MOLLES'),
                array('id' => 1682, 'county_id' => '224', 'value' => 'LUYABA'),
                array('id' => 1683, 'county_id' => '224', 'value' => 'QUEBRACHO LADEADO'),
                array('id' => 1684, 'county_id' => '224', 'value' => 'QUEBRADA DE LOS POZOS'),
                array('id' => 1685, 'county_id' => '224', 'value' => 'SAN JAVIER Y YACANTO'),
                array('id' => 1686, 'county_id' => '224', 'value' => 'SAN JOSE'),
                array('id' => 1687, 'county_id' => '224', 'value' => 'VILLA DE LAS ROSAS'),
                array('id' => 1688, 'county_id' => '224', 'value' => 'VILLA DOLORES'),
                array('id' => 1689, 'county_id' => '224', 'value' => 'VILLA LA VIÑA'),
                array('id' => 1690, 'county_id' => '225', 'value' => 'ALICIA'),
                array('id' => 1691, 'county_id' => '225', 'value' => 'ALTOS DE CHIPION'),
                array('id' => 1692, 'county_id' => '225', 'value' => 'ARROYITO'),
                array('id' => 1693, 'county_id' => '225', 'value' => 'BALNEARIA'),
                array('id' => 1694, 'county_id' => '225', 'value' => 'BRINCKMANN'),
                array('id' => 1695, 'county_id' => '225', 'value' => 'COLONIA 10 DE JULIO'),
                array('id' => 1696, 'county_id' => '225', 'value' => 'COLONIA ANITA'),
                array('id' => 1697, 'county_id' => '225', 'value' => 'COLONIA ITURRASPE'),
                array('id' => 1698, 'county_id' => '225', 'value' => 'COLONIA LAS PICHANAS'),
                array('id' => 1699, 'county_id' => '225', 'value' => 'COLONIA MARINA'),
                array('id' => 1700, 'county_id' => '225', 'value' => 'COLONIA PROSPERIDAD'),
                array('id' => 1701, 'county_id' => '225', 'value' => 'COLONIA SAN BARTOLOME'),
                array('id' => 1702, 'county_id' => '225', 'value' => 'COLONIA SAN PEDRO'),
                array('id' => 1703, 'county_id' => '225', 'value' => 'COLONIA SANTA MARIA'),
                array('id' => 1704, 'county_id' => '225', 'value' => 'COLONIA VALTELINA'),
                array('id' => 1705, 'county_id' => '225', 'value' => 'COLONIA VIGNAUD'),
                array('id' => 1706, 'county_id' => '225', 'value' => 'DEVOTO'),
                array('id' => 1707, 'county_id' => '225', 'value' => 'EL ARAÑADO'),
                array('id' => 1708, 'county_id' => '225', 'value' => 'EL FORTIN'),
                array('id' => 1709, 'county_id' => '225', 'value' => 'EL FUERTECITO'),
                array('id' => 1710, 'county_id' => '225', 'value' => 'EL TIO'),
                array('id' => 1711, 'county_id' => '225', 'value' => 'ESTACION LUXARDO'),
                array('id' => 1712, 'county_id' => '225', 'value' => 'FREYRE'),
                array('id' => 1713, 'county_id' => '225', 'value' => 'LA FRANCIA'),
                array('id' => 1714, 'county_id' => '225', 'value' => 'LA PAQUITA'),
                array('id' => 1715, 'county_id' => '225', 'value' => 'LA TORDILLA'),
                array('id' => 1716, 'county_id' => '225', 'value' => 'LAS VARAS'),
                array('id' => 1717, 'county_id' => '225', 'value' => 'LAS VARILLAS'),
                array('id' => 1718, 'county_id' => '225', 'value' => 'MARULL'),
                array('id' => 1719, 'county_id' => '225', 'value' => 'MIRAMAR'),
                array('id' => 1720, 'county_id' => '225', 'value' => 'MORTEROS'),
                array('id' => 1721, 'county_id' => '225', 'value' => 'PLAZA LUXARDO'),
                array('id' => 1722, 'county_id' => '225', 'value' => 'PLAZA SAN FRANCISCO'),
                array('id' => 1723, 'county_id' => '225', 'value' => 'PORTEÑA'),
                array('id' => 1724, 'county_id' => '225', 'value' => 'QUEBRACHO HERRADO'),
                array('id' => 1725, 'county_id' => '225', 'value' => 'SACANTA'),
                array('id' => 1726, 'county_id' => '225', 'value' => 'SAN FRANCISCO'),
                array('id' => 1727, 'county_id' => '225', 'value' => 'SATURNINO MARIA LASPIUR'),
                array('id' => 1728, 'county_id' => '225', 'value' => 'SEEBER'),
                array('id' => 1729, 'county_id' => '225', 'value' => 'TORO PUJIO'),
                array('id' => 1730, 'county_id' => '225', 'value' => 'TRANSITO'),
                array('id' => 1731, 'county_id' => '225', 'value' => 'VILLA CONCEPCION DEL TIO'),
                array('id' => 1732, 'county_id' => '225', 'value' => 'VILLA DEL TRANSITO'),
                array('id' => 1733, 'county_id' => '225', 'value' => 'VILLA SAN ESTEBAN'),
                array('id' => 1734, 'county_id' => '226', 'value' => 'ALTA GRACIA'),
                array('id' => 1735, 'county_id' => '226', 'value' => 'ANISACATE'),
                array('id' => 1736, 'county_id' => '226', 'value' => 'BARRIO GILBERT'),
                array('id' => 1737, 'county_id' => '226', 'value' => 'BARRIO GILBERT (1Â° DE MAYO)'),
                array('id' => 1738, 'county_id' => '226', 'value' => 'BARRIO LAS QUINTAS'),
                array('id' => 1739, 'county_id' => '226', 'value' => 'BARRIO VILLA DEL PARQUE'),
                array('id' => 1740, 'county_id' => '226', 'value' => 'BOUWER'),
                array('id' => 1741, 'county_id' => '226', 'value' => 'CAMPOS DEL VIRREY'),
                array('id' => 1742, 'county_id' => '226', 'value' => 'CASEROS CENTRO'),
                array('id' => 1743, 'county_id' => '226', 'value' => 'CAUSANA'),
                array('id' => 1744, 'county_id' => '226', 'value' => 'COSTA AZUL'),
                array('id' => 1745, 'county_id' => '226', 'value' => 'DESPEÑADEROS'),
                array('id' => 1746, 'county_id' => '226', 'value' => 'DIQUE CHICO'),
                array('id' => 1747, 'county_id' => '226', 'value' => 'EL POTRERILLO'),
                array('id' => 1748, 'county_id' => '226', 'value' => 'FALDA DEL CAÑETE'),
                array('id' => 1749, 'county_id' => '226', 'value' => 'FALDA DEL CARMEN'),
                array('id' => 1750, 'county_id' => '226', 'value' => 'JOSE DE LA QUINTANA'),
                array('id' => 1751, 'county_id' => '226', 'value' => 'LA BOCA DEL RIO'),
                array('id' => 1752, 'county_id' => '226', 'value' => 'LA CARBONADA'),
                array('id' => 1753, 'county_id' => '226', 'value' => 'LA DONOSA'),
                array('id' => 1754, 'county_id' => '226', 'value' => 'LA PAISANITA'),
                array('id' => 1755, 'county_id' => '226', 'value' => 'LA PERLA'),
                array('id' => 1756, 'county_id' => '226', 'value' => 'LA RANCHERITA'),
                array('id' => 1757, 'county_id' => '226', 'value' => 'LA SERRANITA'),
                array('id' => 1758, 'county_id' => '226', 'value' => 'LOS CEDROS'),
                array('id' => 1759, 'county_id' => '226', 'value' => 'LOS CEDROS - LAS QUINTAS'),
                array('id' => 1760, 'county_id' => '226', 'value' => 'LOZADA'),
                array('id' => 1761, 'county_id' => '226', 'value' => 'MALAGUEÑO'),
                array('id' => 1762, 'county_id' => '226', 'value' => 'MI VALLE'),
                array('id' => 1763, 'county_id' => '226', 'value' => 'MILENICA'),
                array('id' => 1764, 'county_id' => '226', 'value' => 'MONTE RALO'),
                array('id' => 1765, 'county_id' => '226', 'value' => 'POTRERO DE GARAY'),
                array('id' => 1766, 'county_id' => '226', 'value' => 'RAFAEL GARCIA'),
                array('id' => 1767, 'county_id' => '226', 'value' => 'SAN CLEMENTE'),
                array('id' => 1768, 'county_id' => '226', 'value' => 'SAN NICOLAS'),
                array('id' => 1769, 'county_id' => '226', 'value' => 'SOCAVONES'),
                array('id' => 1770, 'county_id' => '226', 'value' => 'TEJAS TRES'),
                array('id' => 1771, 'county_id' => '226', 'value' => 'TIERRA ALTA'),
                array('id' => 1772, 'county_id' => '226', 'value' => 'TOLEDO'),
                array('id' => 1773, 'county_id' => '226', 'value' => 'VALLE ALEGRE'),
                array('id' => 1774, 'county_id' => '226', 'value' => 'VALLE DE ANISACATE'),
                array('id' => 1775, 'county_id' => '226', 'value' => 'VILLA CIUDAD DE AMERICA'),
                array('id' => 1776, 'county_id' => '226', 'value' => 'VILLA CIUDAD DE AMERICA (LOTEO DIEGO DE'),
                array('id' => 1777, 'county_id' => '226', 'value' => 'VILLA DEL PRADO'),
                array('id' => 1778, 'county_id' => '226', 'value' => 'VILLA LA BOLSA'),
                array('id' => 1779, 'county_id' => '226', 'value' => 'VILLA LOS AROMOS'),
                array('id' => 1780, 'county_id' => '226', 'value' => 'VILLA PARQUE SANTA ANA'),
                array('id' => 1781, 'county_id' => '226', 'value' => 'VILLA SAN ISIDRO - JOSE DE LA QUINTANA'),
                array('id' => 1782, 'county_id' => '226', 'value' => 'VILLA SIERRAS DE ORO'),
                array('id' => 1783, 'county_id' => '226', 'value' => 'YOCSINA'),
                array('id' => 1784, 'county_id' => '227', 'value' => 'CAMINIAGA'),
                array('id' => 1785, 'county_id' => '227', 'value' => 'CHUÑA HUASI'),
                array('id' => 1786, 'county_id' => '227', 'value' => 'POZO NUEVO'),
                array('id' => 1787, 'county_id' => '227', 'value' => 'SAN FRANCISCO DEL CHAÑAR'),
                array('id' => 1788, 'county_id' => '228', 'value' => 'ALMAFUERTE'),
                array('id' => 1789, 'county_id' => '228', 'value' => 'COLONIA ALMADA'),
                array('id' => 1790, 'county_id' => '228', 'value' => 'CORRALITO'),
                array('id' => 1791, 'county_id' => '228', 'value' => 'DALMACIO VELEZ'),
                array('id' => 1792, 'county_id' => '228', 'value' => 'GENERAL FOTHERINGHAM'),
                array('id' => 1793, 'county_id' => '228', 'value' => 'HERNANDO'),
                array('id' => 1794, 'county_id' => '228', 'value' => 'JAMES CRAIK'),
                array('id' => 1795, 'county_id' => '228', 'value' => 'LAS ISLETILLAS'),
                array('id' => 1796, 'county_id' => '228', 'value' => 'LAS PERDICES'),
                array('id' => 1797, 'county_id' => '228', 'value' => 'LOS ZORROS'),
                array('id' => 1798, 'county_id' => '228', 'value' => 'OLIVA'),
                array('id' => 1799, 'county_id' => '228', 'value' => 'PAMPAYASTA NORTE'),
                array('id' => 1800, 'county_id' => '228', 'value' => 'PAMPAYASTA SUR'),
                array('id' => 1801, 'county_id' => '228', 'value' => 'PUNTA DEL AGUA'),
                array('id' => 1802, 'county_id' => '228', 'value' => 'RIO TERCERO'),
                array('id' => 1803, 'county_id' => '228', 'value' => 'TANCACHA'),
                array('id' => 1804, 'county_id' => '228', 'value' => 'VILLA ASCASUBI'),
                array('id' => 1805, 'county_id' => '229', 'value' => 'CAÑADA DE LUQUE'),
                array('id' => 1806, 'county_id' => '229', 'value' => 'CANDELARIA SUR'),
                array('id' => 1807, 'county_id' => '229', 'value' => 'CAPILLA DE SITON'),
                array('id' => 1808, 'county_id' => '229', 'value' => 'LA PAMPA'),
                array('id' => 1809, 'county_id' => '229', 'value' => 'LAS PEÑAS'),
                array('id' => 1810, 'county_id' => '229', 'value' => 'LOS MISTOLES'),
                array('id' => 1811, 'county_id' => '229', 'value' => 'SANTA CATALINA'),
                array('id' => 1812, 'county_id' => '229', 'value' => 'SARMIENTO'),
                array('id' => 1813, 'county_id' => '229', 'value' => 'SIMBOLAR'),
                array('id' => 1814, 'county_id' => '229', 'value' => 'SINSACATE'),
                array('id' => 1815, 'county_id' => '229', 'value' => 'VILLA DEL TOTORAL'),
                array('id' => 1816, 'county_id' => '230', 'value' => 'CHURQUI CAÑADA'),
                array('id' => 1817, 'county_id' => '230', 'value' => 'EL RODEO'),
                array('id' => 1818, 'county_id' => '230', 'value' => 'EL TUSCAL'),
                array('id' => 1819, 'county_id' => '230', 'value' => 'LAS ARRIAS'),
                array('id' => 1820, 'county_id' => '230', 'value' => 'LUCIO V. MANSILLA'),
                array('id' => 1821, 'county_id' => '230', 'value' => 'ROSARIO DEL SALADILLO'),
                array('id' => 1822, 'county_id' => '230', 'value' => 'SAN JOSE DE LA DORMIDA'),
                array('id' => 1823, 'county_id' => '230', 'value' => 'SAN JOSE DE LAS SALINAS'),
                array('id' => 1824, 'county_id' => '230', 'value' => 'SAN PEDRO NORTE'),
                array('id' => 1825, 'county_id' => '230', 'value' => 'VILLA TULUMBA'),
                array('id' => 1826, 'county_id' => '231', 'value' => 'ALDEA SANTA MARIA'),
                array('id' => 1827, 'county_id' => '231', 'value' => 'ALTO ALEGRE'),
                array('id' => 1828, 'county_id' => '231', 'value' => 'ANA ZUMARAN'),
                array('id' => 1829, 'county_id' => '231', 'value' => 'BALLESTEROS'),
                array('id' => 1830, 'county_id' => '231', 'value' => 'BALLESTEROS SUR'),
                array('id' => 1831, 'county_id' => '231', 'value' => 'BELL VILLE'),
                array('id' => 1832, 'county_id' => '231', 'value' => 'BENJAMIN GOULD'),
                array('id' => 1833, 'county_id' => '231', 'value' => 'CANALS'),
                array('id' => 1834, 'county_id' => '231', 'value' => 'CHILIBROSTE'),
                array('id' => 1835, 'county_id' => '231', 'value' => 'CINTRA'),
                array('id' => 1836, 'county_id' => '231', 'value' => 'COLONIA BISMARCK'),
                array('id' => 1837, 'county_id' => '231', 'value' => 'COLONIA BREMEN'),
                array('id' => 1838, 'county_id' => '231', 'value' => 'IDIAZABAL'),
                array('id' => 1839, 'county_id' => '231', 'value' => 'JUSTINIANO POSSE'),
                array('id' => 1840, 'county_id' => '231', 'value' => 'LABORDE'),
                array('id' => 1841, 'county_id' => '231', 'value' => 'MONTE LEÑA'),
                array('id' => 1842, 'county_id' => '231', 'value' => 'MONTE MAIZ'),
                array('id' => 1843, 'county_id' => '231', 'value' => 'MORRISON'),
                array('id' => 1844, 'county_id' => '231', 'value' => 'NOETINGER'),
                array('id' => 1845, 'county_id' => '231', 'value' => 'ORDOÑEZ'),
                array('id' => 1846, 'county_id' => '231', 'value' => 'PASCANAS'),
                array('id' => 1847, 'county_id' => '231', 'value' => 'PUEBLO ITALIANO'),
                array('id' => 1848, 'county_id' => '231', 'value' => 'RAMON J. CARCANO'),
                array('id' => 1849, 'county_id' => '231', 'value' => 'SAN ANTONIO DE LITIN'),
                array('id' => 1850, 'county_id' => '231', 'value' => 'SAN MARCOS'),
                array('id' => 1851, 'county_id' => '231', 'value' => 'SAN SEVERO'),
                array('id' => 1852, 'county_id' => '231', 'value' => 'VIAMONTE'),
                array('id' => 1853, 'county_id' => '231', 'value' => 'VILLA LOS PATOS'),
                array('id' => 1854, 'county_id' => '231', 'value' => 'WENCESLAO ESCALANTE'),
                array('id' => 1855, 'county_id' => '232', 'value' => 'BELLA VISTA'),
                array('id' => 1856, 'county_id' => '233', 'value' => 'BERON DE ASTRADA'),
                array('id' => 1857, 'county_id' => '233', 'value' => 'YAHAPE'),
                array('id' => 1858, 'county_id' => '234', 'value' => 'CORRIENTES'),
                array('id' => 1859, 'county_id' => '234', 'value' => 'LAGUNA BRAVA'),
                array('id' => 1860, 'county_id' => '234', 'value' => 'RIACHUELO'),
                array('id' => 1861, 'county_id' => '234', 'value' => 'SAN CAYETANO'),
                array('id' => 1862, 'county_id' => '235', 'value' => 'CONCEPCION'),
                array('id' => 1863, 'county_id' => '235', 'value' => 'SANTA ROSA'),
                array('id' => 1864, 'county_id' => '235', 'value' => 'TABAY'),
                array('id' => 1865, 'county_id' => '235', 'value' => 'TATACUA'),
                array('id' => 1866, 'county_id' => '236', 'value' => 'CAZADORES CORRENTINOS'),
                array('id' => 1867, 'county_id' => '236', 'value' => 'CURUZU CUATIA'),
                array('id' => 1868, 'county_id' => '236', 'value' => 'PERUGORRIA'),
                array('id' => 1869, 'county_id' => '237', 'value' => 'EL SOMBRERO'),
                array('id' => 1870, 'county_id' => '237', 'value' => 'EMPEDRADO'),
                array('id' => 1871, 'county_id' => '238', 'value' => 'ESQUINA'),
                array('id' => 1872, 'county_id' => '238', 'value' => 'PUEBLO LIBERTADOR'),
                array('id' => 1873, 'county_id' => '239', 'value' => 'ALVEAR'),
                array('id' => 1874, 'county_id' => '239', 'value' => 'ESTACION TORRENT'),
                array('id' => 1875, 'county_id' => '240', 'value' => 'ITA IBATE'),
                array('id' => 1876, 'county_id' => '240', 'value' => 'LOMAS DE VALLEJOS'),
                array('id' => 1877, 'county_id' => '240', 'value' => 'NUESTRA SEÑORA DEL ROSARIO DE CAA CATI'),
                array('id' => 1878, 'county_id' => '240', 'value' => 'PALMAR GRANDE'),
                array('id' => 1879, 'county_id' => '241', 'value' => 'COLONIA CAROLINA'),
                array('id' => 1880, 'county_id' => '241', 'value' => 'GOYA'),
                array('id' => 1881, 'county_id' => '242', 'value' => 'ITATI'),
                array('id' => 1882, 'county_id' => '242', 'value' => 'RAMADA PASO'),
                array('id' => 1883, 'county_id' => '243', 'value' => 'COLONIA LIEBIG´S'),
                array('id' => 1884, 'county_id' => '243', 'value' => 'ITUZAINGO'),
                array('id' => 1885, 'county_id' => '243', 'value' => 'SAN ANTONIO'),
                array('id' => 1886, 'county_id' => '243', 'value' => 'SAN CARLOS'),
                array('id' => 1887, 'county_id' => '243', 'value' => 'VILLA OLIVARI'),
                array('id' => 1888, 'county_id' => '244', 'value' => 'CRUZ DE LOS MILAGROS'),
                array('id' => 1889, 'county_id' => '244', 'value' => 'GOBERNADOR JUAN E. MARTINEZ'),
                array('id' => 1890, 'county_id' => '244', 'value' => 'LAVALLE'),
                array('id' => 1891, 'county_id' => '244', 'value' => 'SANTA LUCIA'),
                array('id' => 1892, 'county_id' => '244', 'value' => 'VILLA CORDOBA'),
                array('id' => 1893, 'county_id' => '244', 'value' => 'YATAYTI CALLE'),
                array('id' => 1894, 'county_id' => '245', 'value' => 'MBURUCUYA'),
                array('id' => 1895, 'county_id' => '246', 'value' => 'FELIPE YOFRE'),
                array('id' => 1896, 'county_id' => '246', 'value' => 'MARIANO I. LOZA'),
                array('id' => 1897, 'county_id' => '246', 'value' => 'MERCEDES'),
                array('id' => 1898, 'county_id' => '247', 'value' => 'COLONIA LIBERTAD'),
                array('id' => 1899, 'county_id' => '247', 'value' => 'ESTACION LIBERTAD'),
                array('id' => 1900, 'county_id' => '247', 'value' => 'JUAN PUJOL'),
                array('id' => 1901, 'county_id' => '247', 'value' => 'MOCORETA'),
                array('id' => 1902, 'county_id' => '247', 'value' => 'MONTE CASEROS'),
                array('id' => 1903, 'county_id' => '247', 'value' => 'PARADA ACUÑA'),
                array('id' => 1904, 'county_id' => '247', 'value' => 'PARADA LABOUGLE'),
                array('id' => 1905, 'county_id' => '248', 'value' => 'BONPLAND'),
                array('id' => 1906, 'county_id' => '248', 'value' => 'PARADA PUCHETA'),
                array('id' => 1907, 'county_id' => '248', 'value' => 'PASO DE LOS LIBRES'),
                array('id' => 1908, 'county_id' => '248', 'value' => 'TAPEBICUA'),
                array('id' => 1909, 'county_id' => '249', 'value' => 'SALADAS'),
                array('id' => 1910, 'county_id' => '249', 'value' => 'SAN LORENZO'),
                array('id' => 1911, 'county_id' => '250', 'value' => 'INGENIO PRIMER CORRENTINO'),
                array('id' => 1912, 'county_id' => '250', 'value' => 'PASO DE LA PATRIA'),
                array('id' => 1913, 'county_id' => '250', 'value' => 'SAN COSME'),
                array('id' => 1914, 'county_id' => '250', 'value' => 'SANTA ANA'),
                array('id' => 1915, 'county_id' => '251', 'value' => 'SAN LUIS DEL PALMAR'),
                array('id' => 1916, 'county_id' => '252', 'value' => 'COLONIA CARLOS PELLEGRINI'),
                array('id' => 1917, 'county_id' => '252', 'value' => 'GUAVIRAVI'),
                array('id' => 1918, 'county_id' => '252', 'value' => 'LA CRUZ'),
                array('id' => 1919, 'county_id' => '252', 'value' => 'YAPEYU'),
                array('id' => 1920, 'county_id' => '253', 'value' => 'LORETO'),
                array('id' => 1921, 'county_id' => '253', 'value' => 'SAN MIGUEL'),
                array('id' => 1922, 'county_id' => '254', 'value' => '9 DE JULIO'),
                array('id' => 1923, 'county_id' => '254', 'value' => 'CHAVARRIA'),
                array('id' => 1924, 'county_id' => '254', 'value' => 'COLONIA PANDO'),
                array('id' => 1925, 'county_id' => '254', 'value' => 'PEDRO R. FERNANDEZ'),
                array('id' => 1926, 'county_id' => '254', 'value' => 'SAN ROQUE'),
                array('id' => 1927, 'county_id' => '255', 'value' => 'GARRUCHOS'),
                array('id' => 1928, 'county_id' => '255', 'value' => 'GOBERNADOR IGR.VALENTIN VIRASORO'),
                array('id' => 1929, 'county_id' => '255', 'value' => 'JOSE R. GOMEZ'),
                array('id' => 1930, 'county_id' => '255', 'value' => 'SANTO TOME'),
                array('id' => 1931, 'county_id' => '256', 'value' => 'SAUCE'),
                array('id' => 1932, 'county_id' => '257', 'value' => 'ARROYO BARU'),
                array('id' => 1933, 'county_id' => '257', 'value' => 'COLON'),
                array('id' => 1934, 'county_id' => '257', 'value' => 'COLONIA HUGUES'),
                array('id' => 1935, 'county_id' => '257', 'value' => 'EL BRILLANTE'),
                array('id' => 1936, 'county_id' => '257', 'value' => 'EL COLORADO'),
                array('id' => 1937, 'county_id' => '257', 'value' => 'HAMBIS'),
                array('id' => 1938, 'county_id' => '257', 'value' => 'HOCKER'),
                array('id' => 1939, 'county_id' => '257', 'value' => 'LA CLARITA'),
                array('id' => 1940, 'county_id' => '257', 'value' => 'PUEBLO CAZES'),
                array('id' => 1941, 'county_id' => '257', 'value' => 'PUEBLO LIEBIG´S'),
                array('id' => 1942, 'county_id' => '257', 'value' => 'SAN JOSE'),
                array('id' => 1943, 'county_id' => '257', 'value' => 'UBAJAY'),
                array('id' => 1944, 'county_id' => '257', 'value' => 'VILLA ELISA'),
                array('id' => 1945, 'county_id' => '258', 'value' => 'BENITO LEGEREN'),
                array('id' => 1946, 'county_id' => '258', 'value' => 'CALABACILLA'),
                array('id' => 1947, 'county_id' => '258', 'value' => 'CLODOMIRO LEDESMA'),
                array('id' => 1948, 'county_id' => '258', 'value' => 'COLONIA AYUI'),
                array('id' => 1949, 'county_id' => '258', 'value' => 'COLONIA GENERAL ROCA'),
                array('id' => 1950, 'county_id' => '258', 'value' => 'CONCORDIA'),
                array('id' => 1951, 'county_id' => '258', 'value' => 'ESTACION YERUA'),
                array('id' => 1952, 'county_id' => '258', 'value' => 'ESTACION YUQUERI'),
                array('id' => 1953, 'county_id' => '258', 'value' => 'ESTANCIA GRANDE'),
                array('id' => 1954, 'county_id' => '258', 'value' => 'LA CRIOLLA'),
                array('id' => 1955, 'county_id' => '258', 'value' => 'LAS TEJAS'),
                array('id' => 1956, 'county_id' => '258', 'value' => 'LOS CHARRUAS'),
                array('id' => 1957, 'county_id' => '258', 'value' => 'NUEVA ESCOCIA'),
                array('id' => 1958, 'county_id' => '258', 'value' => 'PEDERNAL'),
                array('id' => 1959, 'county_id' => '258', 'value' => 'PUERTO YERUA'),
                array('id' => 1960, 'county_id' => '258', 'value' => 'VILLA ADELA'),
                array('id' => 1961, 'county_id' => '258', 'value' => 'VILLA ZORRAQUIN'),
                array('id' => 1962, 'county_id' => '259', 'value' => 'ALDEA BRASILERA'),
                array('id' => 1963, 'county_id' => '259', 'value' => 'ALDEA GRAPSCHENTAL'),
                array('id' => 1964, 'county_id' => '259', 'value' => 'ALDEA PROTESTANTE'),
                array('id' => 1965, 'county_id' => '259', 'value' => 'ALDEA SALTO'),
                array('id' => 1966, 'county_id' => '259', 'value' => 'ALDEA SAN FRANCISCO'),
                array('id' => 1967, 'county_id' => '259', 'value' => 'ALDEA SPATZENKUTTER'),
                array('id' => 1968, 'county_id' => '259', 'value' => 'ALDEA VALLE MARIA'),
                array('id' => 1969, 'county_id' => '259', 'value' => 'COLONIA ENSAYO'),
                array('id' => 1970, 'county_id' => '259', 'value' => 'DIAMANTE'),
                array('id' => 1971, 'county_id' => '259', 'value' => 'ESTACION CAMPS'),
                array('id' => 1972, 'county_id' => '259', 'value' => 'ESTACION PUIGGARI'),
                array('id' => 1973, 'county_id' => '259', 'value' => 'GENERAL ALVEAR'),
                array('id' => 1974, 'county_id' => '259', 'value' => 'GENERAL RACEDO'),
                array('id' => 1975, 'county_id' => '259', 'value' => 'GENERAL RAMIREZ'),
                array('id' => 1976, 'county_id' => '259', 'value' => 'LA JAULA'),
                array('id' => 1977, 'county_id' => '259', 'value' => 'LA JUANITA'),
                array('id' => 1978, 'county_id' => '259', 'value' => 'PARAJE LA VIRGEN'),
                array('id' => 1979, 'county_id' => '259', 'value' => 'PUERTO LAS CUEVAS'),
                array('id' => 1980, 'county_id' => '259', 'value' => 'STROBEL'),
                array('id' => 1981, 'county_id' => '259', 'value' => 'VILLA LIBERTADOR SAN MARTIN'),
                array('id' => 1982, 'county_id' => '260', 'value' => 'CHAJARI'),
                array('id' => 1983, 'county_id' => '260', 'value' => 'COLONIA ALEMANA'),
                array('id' => 1984, 'county_id' => '260', 'value' => 'COLONIA PEÑA'),
                array('id' => 1985, 'county_id' => '260', 'value' => 'FEDERACION'),
                array('id' => 1986, 'county_id' => '260', 'value' => 'LOS CONQUISTADORES'),
                array('id' => 1987, 'county_id' => '260', 'value' => 'SAN JAIME DE LA FRONTERA'),
                array('id' => 1988, 'county_id' => '260', 'value' => 'SAN PEDRO'),
                array('id' => 1989, 'county_id' => '260', 'value' => 'SAN RAMON'),
                array('id' => 1990, 'county_id' => '260', 'value' => 'SANTA ANA'),
                array('id' => 1991, 'county_id' => '260', 'value' => 'VILLA DEL ROSARIO'),
                array('id' => 1992, 'county_id' => '261', 'value' => 'CONSCRIPTO BERNARDI'),
                array('id' => 1993, 'county_id' => '261', 'value' => 'EL CIMARRON'),
                array('id' => 1994, 'county_id' => '261', 'value' => 'FEDERAL'),
                array('id' => 1995, 'county_id' => '261', 'value' => 'NUEVA VIZCAYA'),
                array('id' => 1996, 'county_id' => '261', 'value' => 'SAUCE DE LUNA'),
                array('id' => 1997, 'county_id' => '262', 'value' => 'SAN JOSE DE FELICIANO'),
                array('id' => 1998, 'county_id' => '262', 'value' => 'SAN VICTOR'),
                array('id' => 1999, 'county_id' => '263', 'value' => 'ALDEA ASUNCION'),
                array('id' => 2000, 'county_id' => '263', 'value' => 'ESTACION LAZO')
                )
            );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('cities_table_1', function (Blueprint $table) {
            //
        });
    }
}
