<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('counties', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('province_id')->index();
            $table->string('value');
        });

         DB::table('counties')->insert(
            array(
                array('id' => 1, 'province_id' => '1', 'value' => '25 de Mayo'),
                array('id' => 2, 'province_id' => '1', 'value' => '9 de Julio'),
                array('id' => 3, 'province_id' => '1', 'value' => 'Adolfo Alsina'),
                array('id' => 4, 'province_id' => '1', 'value' => 'Adolfo Gonzales Chaves'),
                array('id' => 5, 'province_id' => '1', 'value' => 'Alberti'),
                array('id' => 6, 'province_id' => '1', 'value' => 'Almirante Brown'),
                array('id' => 7, 'province_id' => '1', 'value' => 'Arrecifes'),
                array('id' => 8, 'province_id' => '1', 'value' => 'Avellaneda'),
                array('id' => 9, 'province_id' => '1', 'value' => 'Ayacucho'),
                array('id' => 10, 'province_id' => '1', 'value' => 'Azul'),
                array('id' => 11, 'province_id' => '1', 'value' => 'Bahía Blanca'),
                array('id' => 12, 'province_id' => '1', 'value' => 'Balcarce'),
                array('id' => 13, 'province_id' => '1', 'value' => 'Baradero'),
                array('id' => 14, 'province_id' => '1', 'value' => 'Benito Juárez'),
                array('id' => 15, 'province_id' => '1', 'value' => 'Berazategui'),
                array('id' => 16, 'province_id' => '1', 'value' => 'Berisso'),
                array('id' => 17, 'province_id' => '1', 'value' => 'Bolívar'),
                array('id' => 18, 'province_id' => '1', 'value' => 'Bragado'),
                array('id' => 19, 'province_id' => '1', 'value' => 'Brandsen'),
                array('id' => 20, 'province_id' => '1', 'value' => 'Campana'),
                array('id' => 21, 'province_id' => '1', 'value' => 'Cañuelas'),
                array('id' => 22, 'province_id' => '1', 'value' => 'Capitán Sarmiento'),
                array('id' => 23, 'province_id' => '1', 'value' => 'Carlos Casares'),
                array('id' => 24, 'province_id' => '1', 'value' => 'Carlos Tejedor'),
                array('id' => 25, 'province_id' => '1', 'value' => 'Carmen de Areco'),
                array('id' => 26, 'province_id' => '1', 'value' => 'Castelli'),
                array('id' => 27, 'province_id' => '1', 'value' => 'Chacabuco'),
                array('id' => 28, 'province_id' => '1', 'value' => 'Chascomús'),
                array('id' => 29, 'province_id' => '1', 'value' => 'Chivilcoy'),
                array('id' => 30, 'province_id' => '1', 'value' => 'Ciudad Libertador San Martín'),
                array('id' => 31, 'province_id' => '1', 'value' => 'Colón'),
                array('id' => 32, 'province_id' => '1', 'value' => 'Coronel de Marina Leonardo Rosales'),
                array('id' => 33, 'province_id' => '1', 'value' => 'Coronel Dorrego'),
                array('id' => 34, 'province_id' => '1', 'value' => 'Coronel Pringles'),
                array('id' => 35, 'province_id' => '1', 'value' => 'Coronel Suárez'),
                array('id' => 36, 'province_id' => '1', 'value' => 'Daireaux'),
                array('id' => 37, 'province_id' => '1', 'value' => 'Dolores'),
                array('id' => 38, 'province_id' => '1', 'value' => 'Ensenada'),
                array('id' => 39, 'province_id' => '1', 'value' => 'Escobar'),
                array('id' => 40, 'province_id' => '1', 'value' => 'Esteban Echeverría'),
                array('id' => 41, 'province_id' => '1', 'value' => 'Exaltación de la Cruz'),
                array('id' => 42, 'province_id' => '1', 'value' => 'Florencio Varela'),
                array('id' => 43, 'province_id' => '1', 'value' => 'Florentino Ameghino'),
                array('id' => 44, 'province_id' => '1', 'value' => 'General Alvarado'),
                array('id' => 45, 'province_id' => '1', 'value' => 'General Alvear'),
                array('id' => 46, 'province_id' => '1', 'value' => 'General Arenales'),
                array('id' => 47, 'province_id' => '1', 'value' => 'General Belgrano'),
                array('id' => 48, 'province_id' => '1', 'value' => 'General Guido'),
                array('id' => 49, 'province_id' => '1', 'value' => 'General Juan Madariaga'),
                array('id' => 50, 'province_id' => '1', 'value' => 'General La Madrid'),
                array('id' => 51, 'province_id' => '1', 'value' => 'General Las Heras'),
                array('id' => 52, 'province_id' => '1', 'value' => 'General Lavalle'),
                array('id' => 53, 'province_id' => '1', 'value' => 'General Paz'),
                array('id' => 54, 'province_id' => '1', 'value' => 'General Pinto'),
                array('id' => 55, 'province_id' => '1', 'value' => 'General Pueyrredón'),
                array('id' => 56, 'province_id' => '1', 'value' => 'General Rodríguez'),
                array('id' => 57, 'province_id' => '1', 'value' => 'General Viamonte'),
                array('id' => 58, 'province_id' => '1', 'value' => 'General Villegas'),
                array('id' => 59, 'province_id' => '1', 'value' => 'Guaminí'),
                array('id' => 60, 'province_id' => '1', 'value' => 'Hipólito Yrigoyen'),
                array('id' => 61, 'province_id' => '1', 'value' => 'Hurlingham'),
                array('id' => 62, 'province_id' => '1', 'value' => 'Ituzaingó'),
                array('id' => 63, 'province_id' => '1', 'value' => 'José C. Paz'),
                array('id' => 64, 'province_id' => '1', 'value' => 'José M. Ezeiza'),
                array('id' => 65, 'province_id' => '1', 'value' => 'Junín'),
                array('id' => 66, 'province_id' => '1', 'value' => 'La Costa'),
                array('id' => 67, 'province_id' => '1', 'value' => 'La Matanza'),
                array('id' => 68, 'province_id' => '1', 'value' => 'La Plata'),
                array('id' => 69, 'province_id' => '1', 'value' => 'Lanús'),
                array('id' => 70, 'province_id' => '1', 'value' => 'Laprida'),
                array('id' => 71, 'province_id' => '1', 'value' => 'Las Flores'),
                array('id' => 72, 'province_id' => '1', 'value' => 'Leandro N. Alem'),
                array('id' => 73, 'province_id' => '1', 'value' => 'Lincoln'),
                array('id' => 74, 'province_id' => '1', 'value' => 'Lobería'),
                array('id' => 75, 'province_id' => '1', 'value' => 'Lobos'),
                array('id' => 76, 'province_id' => '1', 'value' => 'Lomas de Zamora'),
                array('id' => 77, 'province_id' => '1', 'value' => 'Luján'),
                array('id' => 78, 'province_id' => '1', 'value' => 'Magdalena'),
                array('id' => 79, 'province_id' => '1', 'value' => 'Maipú'),
                array('id' => 80, 'province_id' => '1', 'value' => 'Malvinas Argentinas'),
                array('id' => 81, 'province_id' => '1', 'value' => 'Mar Chiquita'),
                array('id' => 82, 'province_id' => '1', 'value' => 'Marcos Paz'),
                array('id' => 83, 'province_id' => '1', 'value' => 'Mercedes'),
                array('id' => 84, 'province_id' => '1', 'value' => 'Merlo'),
                array('id' => 85, 'province_id' => '1', 'value' => 'Monte'),
                array('id' => 86, 'province_id' => '1', 'value' => 'Monte Hermoso'),
                array('id' => 87, 'province_id' => '1', 'value' => 'Moreno'),
                array('id' => 88, 'province_id' => '1', 'value' => 'Morón'),
                array('id' => 89, 'province_id' => '1', 'value' => 'Navarro'),
                array('id' => 90, 'province_id' => '1', 'value' => 'Necochea'),
                array('id' => 91, 'province_id' => '1', 'value' => 'Olavarría'),
                array('id' => 92, 'province_id' => '1', 'value' => 'Patagones'),
                array('id' => 93, 'province_id' => '1', 'value' => 'Pehuajó'),
                array('id' => 94, 'province_id' => '1', 'value' => 'Pellegrini'),
                array('id' => 95, 'province_id' => '1', 'value' => 'Pergamino'),
                array('id' => 96, 'province_id' => '1', 'value' => 'Pila'),
                array('id' => 97, 'province_id' => '1', 'value' => 'Pilar'),
                array('id' => 98, 'province_id' => '1', 'value' => 'Pinamar'),
                array('id' => 99, 'province_id' => '1', 'value' => 'Presidente Perón'),
                array('id' => 100, 'province_id' => '1', 'value' => 'Puán'),
                array('id' => 101, 'province_id' => '1', 'value' => 'Punta Indio'),
                array('id' => 102, 'province_id' => '1', 'value' => 'Quilmes'),
                array('id' => 103, 'province_id' => '1', 'value' => 'Ramallo'),
                array('id' => 104, 'province_id' => '1', 'value' => 'Rauch'),
                array('id' => 105, 'province_id' => '1', 'value' => 'Rivadavia'),
                array('id' => 106, 'province_id' => '1', 'value' => 'Rojas'),
                array('id' => 107, 'province_id' => '1', 'value' => 'Roque Pérez'),
                array('id' => 108, 'province_id' => '1', 'value' => 'Saavedra'),
                array('id' => 109, 'province_id' => '1', 'value' => 'Saladillo'),
                array('id' => 110, 'province_id' => '1', 'value' => 'Salliqueló'),
                array('id' => 111, 'province_id' => '1', 'value' => 'Salto'),
                array('id' => 112, 'province_id' => '1', 'value' => 'San Andrés de Giles'),
                array('id' => 113, 'province_id' => '1', 'value' => 'San Antonio de Areco'),
                array('id' => 114, 'province_id' => '1', 'value' => 'San Cayetano'),
                array('id' => 115, 'province_id' => '1', 'value' => 'San Fernando'),
                array('id' => 116, 'province_id' => '1', 'value' => 'San Isidro'),
                array('id' => 117, 'province_id' => '1', 'value' => 'San Miguel'),
                array('id' => 118, 'province_id' => '1', 'value' => 'San Nicolás'),
                array('id' => 119, 'province_id' => '1', 'value' => 'San Pedro'),
                array('id' => 120, 'province_id' => '1', 'value' => 'San Vicente'),
                array('id' => 121, 'province_id' => '1', 'value' => 'Suipacha'),
                array('id' => 122, 'province_id' => '1', 'value' => 'Tandil'),
                array('id' => 123, 'province_id' => '1', 'value' => 'Tapalqué'),
                array('id' => 124, 'province_id' => '1', 'value' => 'Tigre'),
                array('id' => 125, 'province_id' => '1', 'value' => 'Tordillo'),
                array('id' => 126, 'province_id' => '1', 'value' => 'Tornquist'),
                array('id' => 127, 'province_id' => '1', 'value' => 'Trenque Lauquen'),
                array('id' => 128, 'province_id' => '1', 'value' => 'Tres Arroyos'),
                array('id' => 129, 'province_id' => '1', 'value' => 'Tres de Febrero'),
                array('id' => 130, 'province_id' => '1', 'value' => 'Tres Lomas'),
                array('id' => 131, 'province_id' => '1', 'value' => 'Vicente López'),
                array('id' => 132, 'province_id' => '1', 'value' => 'Villa Gesell'),
                array('id' => 133, 'province_id' => '1', 'value' => 'Villarino'),
                array('id' => 134, 'province_id' => '1', 'value' => 'Zárate'),
                array('id' => 135, 'province_id' => '2', 'value' => 'Ambato'),
                array('id' => 136, 'province_id' => '2', 'value' => 'Ancasti'),
                array('id' => 137, 'province_id' => '2', 'value' => 'Andalgalá'),
                array('id' => 138, 'province_id' => '2', 'value' => 'Antofagasta de la Sierra'),
                array('id' => 139, 'province_id' => '2', 'value' => 'Belén'),
                array('id' => 140, 'province_id' => '2', 'value' => 'Capayán'),
                array('id' => 141, 'province_id' => '2', 'value' => 'Capital'),
                array('id' => 142, 'province_id' => '2', 'value' => 'El Alto'),
                array('id' => 143, 'province_id' => '2', 'value' => 'Fray Mamerto Esquiú'),
                array('id' => 144, 'province_id' => '2', 'value' => 'La Paz'),
                array('id' => 145, 'province_id' => '2', 'value' => 'Paclín'),
                array('id' => 146, 'province_id' => '2', 'value' => 'Pomán'),
                array('id' => 147, 'province_id' => '2', 'value' => 'Santa María'),
                array('id' => 148, 'province_id' => '2', 'value' => 'Santa Rosa'),
                array('id' => 149, 'province_id' => '2', 'value' => 'Tinogasta'),
                array('id' => 150, 'province_id' => '2', 'value' => 'Valle Viejo'),
                array('id' => 151, 'province_id' => '3', 'value' => '12 de Octubre'),
                array('id' => 152, 'province_id' => '3', 'value' => '1Â° de Mayo'),
                array('id' => 153, 'province_id' => '3', 'value' => '2 de Abril'),
                array('id' => 154, 'province_id' => '3', 'value' => '25 de Mayo'),
                array('id' => 155, 'province_id' => '3', 'value' => '9 de Julio'),
                array('id' => 156, 'province_id' => '3', 'value' => 'Almirante Brown'),
                array('id' => 157, 'province_id' => '3', 'value' => 'Bermejo'),
                array('id' => 158, 'province_id' => '3', 'value' => 'Chacabuco'),
                array('id' => 159, 'province_id' => '3', 'value' => 'Comandante Fernández'),
                array('id' => 160, 'province_id' => '3', 'value' => 'Fray Justo Santa María de Oro'),
                array('id' => 161, 'province_id' => '3', 'value' => 'General Belgrano'),
                array('id' => 162, 'province_id' => '3', 'value' => 'General Donovan'),
                array('id' => 163, 'province_id' => '3', 'value' => 'General GÃ¼emes'),
                array('id' => 164, 'province_id' => '3', 'value' => 'Independencia'),
                array('id' => 165, 'province_id' => '3', 'value' => 'Libertad'),
                array('id' => 166, 'province_id' => '3', 'value' => 'Libertador General San Martín'),
                array('id' => 167, 'province_id' => '3', 'value' => 'Maipú'),
                array('id' => 168, 'province_id' => '3', 'value' => 'Mayor Luis J. Fontana'),
                array('id' => 169, 'province_id' => '3', 'value' => 'O´Higgins'),
                array('id' => 170, 'province_id' => '3', 'value' => 'Presidencia de la Plaza'),
                array('id' => 171, 'province_id' => '3', 'value' => 'Quitilipi'),
                array('id' => 172, 'province_id' => '3', 'value' => 'San Fernando'),
                array('id' => 173, 'province_id' => '3', 'value' => 'San Lorenzo'),
                array('id' => 174, 'province_id' => '3', 'value' => 'Sargento Cabral'),
                array('id' => 175, 'province_id' => '3', 'value' => 'Tapenagá'),
                array('id' => 176, 'province_id' => '4', 'value' => 'Biedma'),
                array('id' => 177, 'province_id' => '4', 'value' => 'Cushamen'),
                array('id' => 178, 'province_id' => '4', 'value' => 'Escalante'),
                array('id' => 179, 'province_id' => '4', 'value' => 'Florentino Ameghino'),
                array('id' => 180, 'province_id' => '4', 'value' => 'Futaleufú'),
                array('id' => 181, 'province_id' => '4', 'value' => 'Gaiman'),
                array('id' => 182, 'province_id' => '4', 'value' => 'Gastre'),
                array('id' => 183, 'province_id' => '4', 'value' => 'Languiñeo'),
                array('id' => 184, 'province_id' => '4', 'value' => 'Mártires'),
                array('id' => 185, 'province_id' => '4', 'value' => 'Paso de Indios'),
                array('id' => 186, 'province_id' => '4', 'value' => 'Rawson'),
                array('id' => 187, 'province_id' => '4', 'value' => 'Río Senguer'),
                array('id' => 188, 'province_id' => '4', 'value' => 'Sarmiento'),
                array('id' => 189, 'province_id' => '4', 'value' => 'Tehuelches'),
                array('id' => 190, 'province_id' => '4', 'value' => 'Telsen'),
                array('id' => 191, 'province_id' => '5', 'value' => 'Comuna 1'),
                array('id' => 192, 'province_id' => '5', 'value' => 'Comuna 10'),
                array('id' => 193, 'province_id' => '5', 'value' => 'Comuna 11'),
                array('id' => 194, 'province_id' => '5', 'value' => 'Comuna 12'),
                array('id' => 195, 'province_id' => '5', 'value' => 'Comuna 13'),
                array('id' => 196, 'province_id' => '5', 'value' => 'Comuna 14'),
                array('id' => 197, 'province_id' => '5', 'value' => 'Comuna 15'),
                array('id' => 198, 'province_id' => '5', 'value' => 'Comuna 2'),
                array('id' => 199, 'province_id' => '5', 'value' => 'Comuna 3'),
                array('id' => 200, 'province_id' => '5', 'value' => 'Comuna 4'),
                array('id' => 201, 'province_id' => '5', 'value' => 'Comuna 5'),
                array('id' => 202, 'province_id' => '5', 'value' => 'Comuna 6'),
                array('id' => 203, 'province_id' => '5', 'value' => 'Comuna 7'),
                array('id' => 204, 'province_id' => '5', 'value' => 'Comuna 8'),
                array('id' => 205, 'province_id' => '5', 'value' => 'Comuna 9'),
                array('id' => 206, 'province_id' => '6', 'value' => 'Calamuchita'),
                array('id' => 207, 'province_id' => '6', 'value' => 'Capital'),
                array('id' => 208, 'province_id' => '6', 'value' => 'Colón'),
                array('id' => 209, 'province_id' => '6', 'value' => 'Cruz del Eje'),
                array('id' => 210, 'province_id' => '6', 'value' => 'General Roca'),
                array('id' => 211, 'province_id' => '6', 'value' => 'General San Martín'),
                array('id' => 212, 'province_id' => '6', 'value' => 'Ischilín'),
                array('id' => 213, 'province_id' => '6', 'value' => 'Juárez Celman'),
                array('id' => 214, 'province_id' => '6', 'value' => 'Marcos Juárez'),
                array('id' => 215, 'province_id' => '6', 'value' => 'Minas'),
                array('id' => 216, 'province_id' => '6', 'value' => 'Pocho'),
                array('id' => 217, 'province_id' => '6', 'value' => 'Presidente Roque Sáenz Peña'),
                array('id' => 218, 'province_id' => '6', 'value' => 'Punilla'),
                array('id' => 219, 'province_id' => '6', 'value' => 'Río Cuarto'),
                array('id' => 220, 'province_id' => '6', 'value' => 'Río Primero'),
                array('id' => 221, 'province_id' => '6', 'value' => 'Río Seco'),
                array('id' => 222, 'province_id' => '6', 'value' => 'Río Segundo'),
                array('id' => 223, 'province_id' => '6', 'value' => 'San Alberto'),
                array('id' => 224, 'province_id' => '6', 'value' => 'San Javier'),
                array('id' => 225, 'province_id' => '6', 'value' => 'San Justo'),
                array('id' => 226, 'province_id' => '6', 'value' => 'Santa María'),
                array('id' => 227, 'province_id' => '6', 'value' => 'Sobremonte'),
                array('id' => 228, 'province_id' => '6', 'value' => 'Tercero Arriba'),
                array('id' => 229, 'province_id' => '6', 'value' => 'Totoral'),
                array('id' => 230, 'province_id' => '6', 'value' => 'Tulumba'),
                array('id' => 231, 'province_id' => '6', 'value' => 'Unión'),
                array('id' => 232, 'province_id' => '7', 'value' => 'Bella Vista'),
                array('id' => 233, 'province_id' => '7', 'value' => 'Berón de Astrada'),
                array('id' => 234, 'province_id' => '7', 'value' => 'Capital'),
                array('id' => 235, 'province_id' => '7', 'value' => 'Concepción'),
                array('id' => 236, 'province_id' => '7', 'value' => 'Curuzu Cuatia'),
                array('id' => 237, 'province_id' => '7', 'value' => 'Empedrado'),
                array('id' => 238, 'province_id' => '7', 'value' => 'Esquina'),
                array('id' => 239, 'province_id' => '7', 'value' => 'General Alvear'),
                array('id' => 240, 'province_id' => '7', 'value' => 'General Paz'),
                array('id' => 241, 'province_id' => '7', 'value' => 'Goya'),
                array('id' => 242, 'province_id' => '7', 'value' => 'Itatí'),
                array('id' => 243, 'province_id' => '7', 'value' => 'Ituzaingó'),
                array('id' => 244, 'province_id' => '7', 'value' => 'Lavalle'),
                array('id' => 245, 'province_id' => '7', 'value' => 'Mburucuyá'),
                array('id' => 246, 'province_id' => '7', 'value' => 'Mercedes'),
                array('id' => 247, 'province_id' => '7', 'value' => 'Monte Caseros'),
                array('id' => 248, 'province_id' => '7', 'value' => 'Paso de los Libres'),
                array('id' => 249, 'province_id' => '7', 'value' => 'Saladas'),
                array('id' => 250, 'province_id' => '7', 'value' => 'San Cosme'),
                array('id' => 251, 'province_id' => '7', 'value' => 'San Luis del Palmar'),
                array('id' => 252, 'province_id' => '7', 'value' => 'San Martín'),
                array('id' => 253, 'province_id' => '7', 'value' => 'San Miguel'),
                array('id' => 254, 'province_id' => '7', 'value' => 'San Roque'),
                array('id' => 255, 'province_id' => '7', 'value' => 'Santo Tomé'),
                array('id' => 256, 'province_id' => '7', 'value' => 'Sauce'),
                array('id' => 257, 'province_id' => '8', 'value' => 'Colón'),
                array('id' => 258, 'province_id' => '8', 'value' => 'Concordia'),
                array('id' => 259, 'province_id' => '8', 'value' => 'Diamante'),
                array('id' => 260, 'province_id' => '8', 'value' => 'Federación'),
                array('id' => 261, 'province_id' => '8', 'value' => 'Federal'),
                array('id' => 262, 'province_id' => '8', 'value' => 'Feliciano'),
                array('id' => 263, 'province_id' => '8', 'value' => 'Gualeguay'),
                array('id' => 264, 'province_id' => '8', 'value' => 'Gualeguaychú'),
                array('id' => 265, 'province_id' => '8', 'value' => 'Islas del Ibicuy'),
                array('id' => 266, 'province_id' => '8', 'value' => 'La Paz'),
                array('id' => 267, 'province_id' => '8', 'value' => 'Nogoyá'),
                array('id' => 268, 'province_id' => '8', 'value' => 'Paraná'),
                array('id' => 269, 'province_id' => '8', 'value' => 'San Salvador'),
                array('id' => 270, 'province_id' => '8', 'value' => 'Tala'),
                array('id' => 271, 'province_id' => '8', 'value' => 'Uruguay'),
                array('id' => 272, 'province_id' => '8', 'value' => 'Victoria'),
                array('id' => 273, 'province_id' => '8', 'value' => 'Villaguay'),
                array('id' => 274, 'province_id' => '9', 'value' => 'Bermejo'),
                array('id' => 275, 'province_id' => '9', 'value' => 'Formosa'),
                array('id' => 276, 'province_id' => '9', 'value' => 'Laishí'),
                array('id' => 277, 'province_id' => '9', 'value' => 'Matacos'),
                array('id' => 278, 'province_id' => '9', 'value' => 'Patiño'),
                array('id' => 279, 'province_id' => '9', 'value' => 'Pilagás'),
                array('id' => 280, 'province_id' => '9', 'value' => 'Pilcomayo'),
                array('id' => 281, 'province_id' => '9', 'value' => 'Pirané'),
                array('id' => 282, 'province_id' => '9', 'value' => 'Ramón Lista'),
                array('id' => 283, 'province_id' => '10', 'value' => 'Cochinoca'),
                array('id' => 284, 'province_id' => '10', 'value' => 'Dr. Manuel Belgrano'),
                array('id' => 285, 'province_id' => '10', 'value' => 'El Carmen'),
                array('id' => 286, 'province_id' => '10', 'value' => 'Humahuaca'),
                array('id' => 287, 'province_id' => '10', 'value' => 'Ledesma'),
                array('id' => 288, 'province_id' => '10', 'value' => 'Palpalá'),
                array('id' => 289, 'province_id' => '10', 'value' => 'Rinconada'),
                array('id' => 290, 'province_id' => '10', 'value' => 'San Antonio'),
                array('id' => 291, 'province_id' => '10', 'value' => 'San Pedro'),
                array('id' => 292, 'province_id' => '10', 'value' => 'Santa Bárbara'),
                array('id' => 293, 'province_id' => '10', 'value' => 'Santa Catalina'),
                array('id' => 294, 'province_id' => '10', 'value' => 'Susques'),
                array('id' => 295, 'province_id' => '10', 'value' => 'Tilcara'),
                array('id' => 296, 'province_id' => '10', 'value' => 'Tumbaya'),
                array('id' => 297, 'province_id' => '10', 'value' => 'Valle Grande'),
                array('id' => 298, 'province_id' => '10', 'value' => 'Yaví'),
                array('id' => 299, 'province_id' => '11', 'value' => 'Atreucó'),
                array('id' => 300, 'province_id' => '11', 'value' => 'Caleu Caleu'),
                array('id' => 301, 'province_id' => '11', 'value' => 'Capital'),
                array('id' => 302, 'province_id' => '11', 'value' => 'Catriló'),
                array('id' => 303, 'province_id' => '11', 'value' => 'Chalileo'),
                array('id' => 304, 'province_id' => '11', 'value' => 'Chapaleufú'),
                array('id' => 305, 'province_id' => '11', 'value' => 'Chical Co'),
                array('id' => 306, 'province_id' => '11', 'value' => 'Conhelo'),
                array('id' => 307, 'province_id' => '11', 'value' => 'Curacó'),
                array('id' => 308, 'province_id' => '11', 'value' => 'Guatraché'),
                array('id' => 309, 'province_id' => '11', 'value' => 'Hucal'),
                array('id' => 310, 'province_id' => '11', 'value' => 'Lihuel Calel'),
                array('id' => 311, 'province_id' => '11', 'value' => 'Limay Mahuida'),
                array('id' => 312, 'province_id' => '11', 'value' => 'Loventué'),
                array('id' => 313, 'province_id' => '11', 'value' => 'Maracó'),
                array('id' => 314, 'province_id' => '11', 'value' => 'Puelén'),
                array('id' => 315, 'province_id' => '11', 'value' => 'Quemú Quemú'),
                array('id' => 316, 'province_id' => '11', 'value' => 'Rancul'),
                array('id' => 317, 'province_id' => '11', 'value' => 'Realicó'),
                array('id' => 318, 'province_id' => '11', 'value' => 'Toay'),
                array('id' => 319, 'province_id' => '11', 'value' => 'Trenel'),
                array('id' => 320, 'province_id' => '11', 'value' => 'Utracán'),
                array('id' => 321, 'province_id' => '12', 'value' => 'Arauco'),
                array('id' => 322, 'province_id' => '12', 'value' => 'Capital'),
                array('id' => 323, 'province_id' => '12', 'value' => 'Castro Barros'),
                array('id' => 324, 'province_id' => '12', 'value' => 'Chamical'),
                array('id' => 325, 'province_id' => '12', 'value' => 'Chilecito'),
                array('id' => 326, 'province_id' => '12', 'value' => 'Coronel Felipe Varela'),
                array('id' => 327, 'province_id' => '12', 'value' => 'Famatina'),
                array('id' => 328, 'province_id' => '12', 'value' => 'General Ãngel V. Peñaloza'),
                array('id' => 329, 'province_id' => '12', 'value' => 'General Belgrano'),
                array('id' => 330, 'province_id' => '12', 'value' => 'General Juan F. Quiroga'),
                array('id' => 331, 'province_id' => '12', 'value' => 'General Lamadrid'),
                array('id' => 332, 'province_id' => '12', 'value' => 'General Ocampo'),
                array('id' => 333, 'province_id' => '12', 'value' => 'General San Martín'),
                array('id' => 334, 'province_id' => '12', 'value' => 'Independencia'),
                array('id' => 335, 'province_id' => '12', 'value' => 'Rosario Vera Peñaloza'),
                array('id' => 336, 'province_id' => '12', 'value' => 'San Blas de Los Sauces'),
                array('id' => 337, 'province_id' => '12', 'value' => 'Sanagasta'),
                array('id' => 338, 'province_id' => '12', 'value' => 'Vinchina'),
                array('id' => 339, 'province_id' => '13', 'value' => 'Capital'),
                array('id' => 340, 'province_id' => '13', 'value' => 'General Alvear'),
                array('id' => 341, 'province_id' => '13', 'value' => 'Godoy Cruz'),
                array('id' => 342, 'province_id' => '13', 'value' => 'Guaymallén'),
                array('id' => 343, 'province_id' => '13', 'value' => 'Junín'),
                array('id' => 344, 'province_id' => '13', 'value' => 'La Paz'),
                array('id' => 345, 'province_id' => '13', 'value' => 'Las Heras'),
                array('id' => 346, 'province_id' => '13', 'value' => 'Lavalle'),
                array('id' => 347, 'province_id' => '13', 'value' => 'Luján de Cuyo'),
                array('id' => 348, 'province_id' => '13', 'value' => 'Maipú'),
                array('id' => 349, 'province_id' => '13', 'value' => 'MalargÃ¼e'),
                array('id' => 350, 'province_id' => '13', 'value' => 'Rivadavia'),
                array('id' => 351, 'province_id' => '13', 'value' => 'San Carlos'),
                array('id' => 352, 'province_id' => '13', 'value' => 'San Martín'),
                array('id' => 353, 'province_id' => '13', 'value' => 'San Rafael'),
                array('id' => 354, 'province_id' => '13', 'value' => 'Santa Rosa'),
                array('id' => 355, 'province_id' => '13', 'value' => 'Tunuyán'),
                array('id' => 356, 'province_id' => '13', 'value' => 'Tupungato'),
                array('id' => 357, 'province_id' => '14', 'value' => '25 de Mayo'),
                array('id' => 358, 'province_id' => '14', 'value' => 'Apóstoles'),
                array('id' => 359, 'province_id' => '14', 'value' => 'Cainguás'),
                array('id' => 360, 'province_id' => '14', 'value' => 'Candelaria'),
                array('id' => 361, 'province_id' => '14', 'value' => 'Capital'),
                array('id' => 362, 'province_id' => '14', 'value' => 'Concepción'),
                array('id' => 363, 'province_id' => '14', 'value' => 'Eldorado'),
                array('id' => 364, 'province_id' => '14', 'value' => 'General Manuel Belgrano'),
                array('id' => 365, 'province_id' => '14', 'value' => 'Guaraní'),
                array('id' => 366, 'province_id' => '14', 'value' => 'Iguazú'),
                array('id' => 367, 'province_id' => '14', 'value' => 'Leandro N. Alem'),
                array('id' => 368, 'province_id' => '14', 'value' => 'Libertador General San Martín'),
                array('id' => 369, 'province_id' => '14', 'value' => 'Montecarlo'),
                array('id' => 370, 'province_id' => '14', 'value' => 'Oberá'),
                array('id' => 371, 'province_id' => '14', 'value' => 'San Ignacio'),
                array('id' => 372, 'province_id' => '14', 'value' => 'San Javier'),
                array('id' => 373, 'province_id' => '14', 'value' => 'San Pedro'),
                array('id' => 374, 'province_id' => '15', 'value' => 'Ã‘orquín'),
                array('id' => 375, 'province_id' => '15', 'value' => 'Aluminé'),
                array('id' => 376, 'province_id' => '15', 'value' => 'Añelo'),
                array('id' => 377, 'province_id' => '15', 'value' => 'Catán Lil'),
                array('id' => 378, 'province_id' => '15', 'value' => 'Chos Malal'),
                array('id' => 379, 'province_id' => '15', 'value' => 'Collón Curá'),
                array('id' => 380, 'province_id' => '15', 'value' => 'Confluencia'),
                array('id' => 381, 'province_id' => '15', 'value' => 'Huiliches'),
                array('id' => 382, 'province_id' => '15', 'value' => 'Lácar'),
                array('id' => 383, 'province_id' => '15', 'value' => 'Loncopué'),
                array('id' => 384, 'province_id' => '15', 'value' => 'Los Lagos'),
                array('id' => 385, 'province_id' => '15', 'value' => 'Minas'),
                array('id' => 386, 'province_id' => '15', 'value' => 'Pehuenches'),
                array('id' => 387, 'province_id' => '15', 'value' => 'Picún Leufú'),
                array('id' => 388, 'province_id' => '15', 'value' => 'Picunches'),
                array('id' => 389, 'province_id' => '15', 'value' => 'Zapala'),
                array('id' => 390, 'province_id' => '16', 'value' => '25 de Mayo'),
                array('id' => 391, 'province_id' => '16', 'value' => '9 de Julio'),
                array('id' => 392, 'province_id' => '16', 'value' => 'Ã‘orquinco'),
                array('id' => 393, 'province_id' => '16', 'value' => 'Adolfo Alsina'),
                array('id' => 394, 'province_id' => '16', 'value' => 'Avellaneda'),
                array('id' => 395, 'province_id' => '16', 'value' => 'Bariloche'),
                array('id' => 396, 'province_id' => '16', 'value' => 'Conesa'),
                array('id' => 397, 'province_id' => '16', 'value' => 'El Cuy'),
                array('id' => 398, 'province_id' => '16', 'value' => 'General Roca'),
                array('id' => 399, 'province_id' => '16', 'value' => 'Pichi Mahuida'),
                array('id' => 400, 'province_id' => '16', 'value' => 'Pilcaniyeu'),
                array('id' => 401, 'province_id' => '16', 'value' => 'San Antonio'),
                array('id' => 402, 'province_id' => '16', 'value' => 'Valcheta'),
                array('id' => 403, 'province_id' => '17', 'value' => 'Anta'),
                array('id' => 404, 'province_id' => '17', 'value' => 'Cachi'),
                array('id' => 405, 'province_id' => '17', 'value' => 'Cafayate'),
                array('id' => 406, 'province_id' => '17', 'value' => 'Capital'),
                array('id' => 407, 'province_id' => '17', 'value' => 'Cerrillos'),
                array('id' => 408, 'province_id' => '17', 'value' => 'Chicoana'),
                array('id' => 409, 'province_id' => '17', 'value' => 'General GÃ¼emes'),
                array('id' => 410, 'province_id' => '17', 'value' => 'General José de San Martín'),
                array('id' => 411, 'province_id' => '17', 'value' => 'Guachipas'),
                array('id' => 412, 'province_id' => '17', 'value' => 'Iruya'),
                array('id' => 413, 'province_id' => '17', 'value' => 'La Caldera'),
                array('id' => 414, 'province_id' => '17', 'value' => 'La Candelaria'),
                array('id' => 415, 'province_id' => '17', 'value' => 'La Poma'),
                array('id' => 416, 'province_id' => '17', 'value' => 'La Viña'),
                array('id' => 417, 'province_id' => '17', 'value' => 'Los Andes'),
                array('id' => 418, 'province_id' => '17', 'value' => 'Metán'),
                array('id' => 419, 'province_id' => '17', 'value' => 'Molinos'),
                array('id' => 420, 'province_id' => '17', 'value' => 'Orán'),
                array('id' => 421, 'province_id' => '17', 'value' => 'Rivadavia'),
                array('id' => 422, 'province_id' => '17', 'value' => 'Rosario de la Frontera'),
                array('id' => 423, 'province_id' => '17', 'value' => 'Rosario de Lerma'),
                array('id' => 424, 'province_id' => '17', 'value' => 'San Carlos'),
                array('id' => 425, 'province_id' => '17', 'value' => 'Santa Victoria'),
                array('id' => 426, 'province_id' => '18', 'value' => '25 de Mayo'),
                array('id' => 427, 'province_id' => '18', 'value' => '9 de Julio'),
                array('id' => 428, 'province_id' => '18', 'value' => 'Albardón'),
                array('id' => 429, 'province_id' => '18', 'value' => 'Angaco'),
                array('id' => 430, 'province_id' => '18', 'value' => 'Calingasta'),
                array('id' => 431, 'province_id' => '18', 'value' => 'Capital'),
                array('id' => 432, 'province_id' => '18', 'value' => 'Caucete'),
                array('id' => 433, 'province_id' => '18', 'value' => 'Chimbas'),
                array('id' => 434, 'province_id' => '18', 'value' => 'Iglesia'),
                array('id' => 435, 'province_id' => '18', 'value' => 'Jáchal'),
                array('id' => 436, 'province_id' => '18', 'value' => 'Pocito'),
                array('id' => 437, 'province_id' => '18', 'value' => 'Rawson'),
                array('id' => 438, 'province_id' => '18', 'value' => 'Rivadavia'),
                array('id' => 439, 'province_id' => '18', 'value' => 'San Martín'),
                array('id' => 440, 'province_id' => '18', 'value' => 'Santa Lucía'),
                array('id' => 441, 'province_id' => '18', 'value' => 'Sarmiento'),
                array('id' => 442, 'province_id' => '18', 'value' => 'Ullum'),
                array('id' => 443, 'province_id' => '18', 'value' => 'Valle Fértil'),
                array('id' => 444, 'province_id' => '18', 'value' => 'Zonda'),
                array('id' => 445, 'province_id' => '19', 'value' => 'Ayacucho'),
                array('id' => 446, 'province_id' => '19', 'value' => 'Belgrano'),
                array('id' => 447, 'province_id' => '19', 'value' => 'Chacabuco'),
                array('id' => 448, 'province_id' => '19', 'value' => 'Coronel Pringles'),
                array('id' => 449, 'province_id' => '19', 'value' => 'General Pedernera'),
                array('id' => 450, 'province_id' => '19', 'value' => 'Gobernador Dupuy'),
                array('id' => 451, 'province_id' => '19', 'value' => 'Juan Martín de Pueyrredón'),
                array('id' => 452, 'province_id' => '19', 'value' => 'Junín'),
                array('id' => 453, 'province_id' => '19', 'value' => 'Libertador General San Martín'),
                array('id' => 454, 'province_id' => '20', 'value' => 'Corpen Aike'),
                array('id' => 455, 'province_id' => '20', 'value' => 'Deseado'),
                array('id' => 456, 'province_id' => '20', 'value' => 'GÃ¼er Aike'),
                array('id' => 457, 'province_id' => '20', 'value' => 'Lago Argentino'),
                array('id' => 458, 'province_id' => '20', 'value' => 'Lago Buenos Aires'),
                array('id' => 459, 'province_id' => '20', 'value' => 'Magallanes'),
                array('id' => 460, 'province_id' => '20', 'value' => 'Río Chico'),
                array('id' => 461, 'province_id' => '21', 'value' => '9 de Julio'),
                array('id' => 462, 'province_id' => '21', 'value' => 'Belgrano'),
                array('id' => 463, 'province_id' => '21', 'value' => 'Caseros'),
                array('id' => 464, 'province_id' => '21', 'value' => 'Castellanos'),
                array('id' => 465, 'province_id' => '21', 'value' => 'Garay'),
                array('id' => 466, 'province_id' => '21', 'value' => 'General López'),
                array('id' => 467, 'province_id' => '21', 'value' => 'General Obligado'),
                array('id' => 468, 'province_id' => '21', 'value' => 'Iriondo'),
                array('id' => 469, 'province_id' => '21', 'value' => 'La Capital'),
                array('id' => 470, 'province_id' => '21', 'value' => 'Las Colonias'),
                array('id' => 471, 'province_id' => '21', 'value' => 'Rosario'),
                array('id' => 472, 'province_id' => '21', 'value' => 'San Cristóbal'),
                array('id' => 473, 'province_id' => '21', 'value' => 'San Javier'),
                array('id' => 474, 'province_id' => '21', 'value' => 'San Jerónimo'),
                array('id' => 475, 'province_id' => '21', 'value' => 'San Justo'),
                array('id' => 476, 'province_id' => '21', 'value' => 'San Lorenzo'),
                array('id' => 477, 'province_id' => '21', 'value' => 'San Martín'),
                array('id' => 478, 'province_id' => '21', 'value' => 'Vera'),
                array('id' => 479, 'province_id' => '21', 'value' => 'Villa Constitución'),
                array('id' => 480, 'province_id' => '22', 'value' => 'Aguirre'),
                array('id' => 481, 'province_id' => '22', 'value' => 'Alberdi'),
                array('id' => 482, 'province_id' => '22', 'value' => 'Atamisqui'),
                array('id' => 483, 'province_id' => '22', 'value' => 'Avellaneda'),
                array('id' => 484, 'province_id' => '22', 'value' => 'Banda'),
                array('id' => 485, 'province_id' => '22', 'value' => 'Belgrano'),
                array('id' => 486, 'province_id' => '22', 'value' => 'Capital'),
                array('id' => 487, 'province_id' => '22', 'value' => 'Choya'),
                array('id' => 488, 'province_id' => '22', 'value' => 'Copo'),
                array('id' => 489, 'province_id' => '22', 'value' => 'Figueroa'),
                array('id' => 490, 'province_id' => '22', 'value' => 'General Taboada'),
                array('id' => 491, 'province_id' => '22', 'value' => 'Guasayán'),
                array('id' => 492, 'province_id' => '22', 'value' => 'Jiménez'),
                array('id' => 493, 'province_id' => '22', 'value' => 'Juan F. Ibarra'),
                array('id' => 494, 'province_id' => '22', 'value' => 'Loreto'),
                array('id' => 495, 'province_id' => '22', 'value' => 'Mitre'),
                array('id' => 496, 'province_id' => '22', 'value' => 'Moreno'),
                array('id' => 497, 'province_id' => '22', 'value' => 'Ojo de Agua'),
                array('id' => 498, 'province_id' => '22', 'value' => 'Pellegrini'),
                array('id' => 499, 'province_id' => '22', 'value' => 'Quebrachos'),
                array('id' => 500, 'province_id' => '22', 'value' => 'Río Hondo'),
                array('id' => 501, 'province_id' => '22', 'value' => 'Rivadavia'),
                array('id' => 502, 'province_id' => '22', 'value' => 'Robles'),
                array('id' => 503, 'province_id' => '22', 'value' => 'Salavina'),
                array('id' => 504, 'province_id' => '22', 'value' => 'San Martín'),
                array('id' => 505, 'province_id' => '22', 'value' => 'Sarmiento'),
                array('id' => 506, 'province_id' => '22', 'value' => 'Silípica'),
                array('id' => 507, 'province_id' => '23', 'value' => 'Río Grande'),
                array('id' => 508, 'province_id' => '23', 'value' => 'Ushuaia'),
                array('id' => 509, 'province_id' => '24', 'value' => 'Burruyacú'),
                array('id' => 510, 'province_id' => '24', 'value' => 'Capital'),
                array('id' => 511, 'province_id' => '24', 'value' => 'Chicligasta'),
                array('id' => 512, 'province_id' => '24', 'value' => 'Cruz Alta'),
                array('id' => 513, 'province_id' => '24', 'value' => 'Famaillá'),
                array('id' => 514, 'province_id' => '24', 'value' => 'Graneros'),
                array('id' => 515, 'province_id' => '24', 'value' => 'Juan Bautista Alberdi'),
                array('id' => 516, 'province_id' => '24', 'value' => 'La Cocha'),
                array('id' => 517, 'province_id' => '24', 'value' => 'Leales'),
                array('id' => 518, 'province_id' => '24', 'value' => 'Lules'),
                array('id' => 519, 'province_id' => '24', 'value' => 'Monteros'),
                array('id' => 520, 'province_id' => '24', 'value' => 'Río Chico'),
                array('id' => 521, 'province_id' => '24', 'value' => 'Simoca'),
                array('id' => 522, 'province_id' => '24', 'value' => 'Tafí del Valle'),
                array('id' => 523, 'province_id' => '24', 'value' => 'Tafí Viejo'),
                array('id' => 524, 'province_id' => '24', 'value' => 'Trancas'),
                array('id' => 525, 'province_id' => '24', 'value' => 'Yerba Buena')
            )
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('counties');
    }
}
