<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cities', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('county_id')->index();
            $table->string('value');
        });

        DB::table('cities')->insert(
            array(
                array('id' => 1, 'county_id' => '1', 'value' => '25 DE MAYO'),
                array('id' => 2, 'county_id' => '1', 'value' => 'AGUSTIN MOSCONI'),
                array('id' => 3, 'county_id' => '1', 'value' => 'DEL VALLE'),
                array('id' => 4, 'county_id' => '1', 'value' => 'ERNESTINA'),
                array('id' => 5, 'county_id' => '1', 'value' => 'GOBERNADOR UGARTE'),
                array('id' => 6, 'county_id' => '1', 'value' => 'LUCAS MONTEVERDE'),
                array('id' => 7, 'county_id' => '1', 'value' => 'NORBERTO DE LA RIESTRA'),
                array('id' => 8, 'county_id' => '1', 'value' => 'PEDERNALES'),
                array('id' => 9, 'county_id' => '1', 'value' => 'SAN ENRIQUE'),
                array('id' => 10, 'county_id' => '1', 'value' => 'VALDES'),
                array('id' => 11, 'county_id' => '2', 'value' => '12 DE OCTUBRE'),
                array('id' => 12, 'county_id' => '2', 'value' => '9 DE JULIO'),
                array('id' => 13, 'county_id' => '2', 'value' => 'ALFREDO DEMARCHI'),
                array('id' => 14, 'county_id' => '2', 'value' => 'CARLOS MARIA NAON'),
                array('id' => 15, 'county_id' => '2', 'value' => 'DUDIGNAC'),
                array('id' => 16, 'county_id' => '2', 'value' => 'LA AURORA'),
                array('id' => 17, 'county_id' => '2', 'value' => 'MANUEL B. GONNET'),
                array('id' => 18, 'county_id' => '2', 'value' => 'MARCELINO UGARTE'),
                array('id' => 19, 'county_id' => '2', 'value' => 'MOREA'),
                array('id' => 20, 'county_id' => '2', 'value' => 'NORUMBEGA'),
                array('id' => 21, 'county_id' => '2', 'value' => 'PATRICIOS'),
                array('id' => 22, 'county_id' => '2', 'value' => 'VILLA GENERAL FOURNIER'),
                array('id' => 23, 'county_id' => '3', 'value' => 'CARHUE'),
                array('id' => 24, 'county_id' => '3', 'value' => 'COLONIA SAN MIGUEL ARCANGEL'),
                array('id' => 25, 'county_id' => '3', 'value' => 'DELFIN HUERGO'),
                array('id' => 26, 'county_id' => '3', 'value' => 'ESPARTILLAR'),
                array('id' => 27, 'county_id' => '3', 'value' => 'ESTEBAN AGUSTIN GASCON'),
                array('id' => 28, 'county_id' => '3', 'value' => 'LA PALA'),
                array('id' => 29, 'county_id' => '3', 'value' => 'MAZA'),
                array('id' => 30, 'county_id' => '3', 'value' => 'RIVERA'),
                array('id' => 31, 'county_id' => '3', 'value' => 'VILLA MARGARITA'),
                array('id' => 32, 'county_id' => '3', 'value' => 'YUTUYACO'),
                array('id' => 33, 'county_id' => '4', 'value' => 'ADOLFO GONZALES CHAVES'),
                array('id' => 34, 'county_id' => '4', 'value' => 'DE LA GARMA'),
                array('id' => 35, 'county_id' => '4', 'value' => 'JUAN E. BARRA'),
                array('id' => 36, 'county_id' => '4', 'value' => 'VASQUEZ'),
                array('id' => 37, 'county_id' => '5', 'value' => 'ALBERTI'),
                array('id' => 38, 'county_id' => '5', 'value' => 'CORONEL SEGUI'),
                array('id' => 39, 'county_id' => '5', 'value' => 'MECHITA'),
                array('id' => 40, 'county_id' => '5', 'value' => 'PLA'),
                array('id' => 41, 'county_id' => '5', 'value' => 'VILLA GRISOLIA'),
                array('id' => 42, 'county_id' => '5', 'value' => 'VILLA MARIA'),
                array('id' => 43, 'county_id' => '5', 'value' => 'VILLA ORTIZ'),
                array('id' => 44, 'county_id' => '6', 'value' => 'ADROGUE'),
                array('id' => 45, 'county_id' => '6', 'value' => 'BURZACO'),
                array('id' => 46, 'county_id' => '6', 'value' => 'CLAYPOLE'),
                array('id' => 47, 'county_id' => '6', 'value' => 'DON ORIONE'),
                array('id' => 48, 'county_id' => '6', 'value' => 'GLEW'),
                array('id' => 49, 'county_id' => '6', 'value' => 'JOSE MARMOL'),
                array('id' => 50, 'county_id' => '6', 'value' => 'LONGCHAMPS'),
                array('id' => 51, 'county_id' => '6', 'value' => 'MALVINAS ARGENTINAS'),
                array('id' => 52, 'county_id' => '6', 'value' => 'MINISTRO RIVADAVIA'),
                array('id' => 53, 'county_id' => '6', 'value' => 'RAFAEL CALZADA'),
                array('id' => 54, 'county_id' => '6', 'value' => 'SAN FRANCISCO SOLANO'),
                array('id' => 55, 'county_id' => '6', 'value' => 'SAN JOSE'),
                array('id' => 56, 'county_id' => '7', 'value' => 'ARRECIFES'),
                array('id' => 57, 'county_id' => '7', 'value' => 'TODD'),
                array('id' => 58, 'county_id' => '7', 'value' => 'VIÂ¥A'),
                array('id' => 59, 'county_id' => '8', 'value' => 'AREA CINTURON ECOLOGICO'),
                array('id' => 60, 'county_id' => '8', 'value' => 'AVELLANEDA'),
                array('id' => 61, 'county_id' => '8', 'value' => 'CRUCESITA'),
                array('id' => 62, 'county_id' => '8', 'value' => 'DOCK SUD'),
                array('id' => 63, 'county_id' => '8', 'value' => 'GERLI'),
                array('id' => 64, 'county_id' => '8', 'value' => 'PIÑEYRO'),
                array('id' => 65, 'county_id' => '8', 'value' => 'SARANDI'),
                array('id' => 66, 'county_id' => '8', 'value' => 'VILLA DOMINICO'),
                array('id' => 67, 'county_id' => '8', 'value' => 'WILDE'),
                array('id' => 68, 'county_id' => '9', 'value' => 'AYACUCHO'),
                array('id' => 69, 'county_id' => '9', 'value' => 'LA CONSTANCIA'),
                array('id' => 70, 'county_id' => '9', 'value' => 'SOLANET'),
                array('id' => 71, 'county_id' => '9', 'value' => 'UDAQUIOLA'),
                array('id' => 72, 'county_id' => '10', 'value' => '16 DE JULIO'),
                array('id' => 73, 'county_id' => '10', 'value' => 'ARIEL'),
                array('id' => 74, 'county_id' => '10', 'value' => 'AZUL'),
                array('id' => 75, 'county_id' => '10', 'value' => 'CACHARI'),
                array('id' => 76, 'county_id' => '10', 'value' => 'CHILLAR'),
                array('id' => 77, 'county_id' => '11', 'value' => 'BAHIA BLANCA'),
                array('id' => 78, 'county_id' => '11', 'value' => 'CABILDO'),
                array('id' => 79, 'county_id' => '11', 'value' => 'GENERAL DANIEL CERRI'),
                array('id' => 80, 'county_id' => '11', 'value' => 'GRÜNBEIN'),
                array('id' => 81, 'county_id' => '11', 'value' => 'INGENIERO WHITE'),
                array('id' => 82, 'county_id' => '11', 'value' => 'VILLA BORDEAU'),
                array('id' => 83, 'county_id' => '11', 'value' => 'VILLA ESPORA'),
                array('id' => 84, 'county_id' => '12', 'value' => 'BALCARCE'),
                array('id' => 85, 'county_id' => '12', 'value' => 'LOS PINOS'),
                array('id' => 86, 'county_id' => '12', 'value' => 'NAPALEOFU'),
                array('id' => 87, 'county_id' => '12', 'value' => 'RAMOS OTERO'),
                array('id' => 88, 'county_id' => '12', 'value' => 'SAN AGUSTIN'),
                array('id' => 89, 'county_id' => '12', 'value' => 'VILLA LAGUNA LA BRAVA'),
                array('id' => 90, 'county_id' => '13', 'value' => 'BARADERO'),
                array('id' => 91, 'county_id' => '13', 'value' => 'IRINEO PORTELA'),
                array('id' => 92, 'county_id' => '13', 'value' => 'SANTA COLOMA'),
                array('id' => 93, 'county_id' => '13', 'value' => 'VILLA ALSINA'),
                array('id' => 94, 'county_id' => '14', 'value' => 'BARKER'),
                array('id' => 95, 'county_id' => '14', 'value' => 'BENITO JUAREZ'),
                array('id' => 96, 'county_id' => '14', 'value' => 'LOPEZ'),
                array('id' => 97, 'county_id' => '14', 'value' => 'TEDIN URIBURU'),
                array('id' => 98, 'county_id' => '14', 'value' => 'VILLA CACIQUE'),
                array('id' => 99, 'county_id' => '15', 'value' => 'BERAZATEGUI'),
                array('id' => 100, 'county_id' => '15', 'value' => 'BERAZATEGUI OESTE'),
                array('id' => 101, 'county_id' => '15', 'value' => 'CARLOS TOMAS SOURIGUES'),
                array('id' => 102, 'county_id' => '15', 'value' => 'EL PATO'),
                array('id' => 103, 'county_id' => '15', 'value' => 'GUILLERMO ENRIQUE HUDSON'),
                array('id' => 104, 'county_id' => '15', 'value' => 'JUAN MARIA GUTIERREZ'),
                array('id' => 105, 'county_id' => '15', 'value' => 'PEREYRA'),
                array('id' => 106, 'county_id' => '15', 'value' => 'PLATANOS'),
                array('id' => 107, 'county_id' => '15', 'value' => 'RANELAGH'),
                array('id' => 108, 'county_id' => '15', 'value' => 'VILLA ESPAÑA'),
                array('id' => 109, 'county_id' => '16', 'value' => 'BARRIO BANCO PROVINCIA'),
                array('id' => 110, 'county_id' => '16', 'value' => 'BARRIO EL CARMEN (ESTE)'),
                array('id' => 111, 'county_id' => '16', 'value' => 'BARRIO UNIVERSITARIO'),
                array('id' => 112, 'county_id' => '16', 'value' => 'BERISSO'),
                array('id' => 113, 'county_id' => '16', 'value' => 'LOS TALAS'),
                array('id' => 114, 'county_id' => '16', 'value' => 'VILLA ARGÜELLO'),
                array('id' => 115, 'county_id' => '16', 'value' => 'VILLA DOLORES'),
                array('id' => 116, 'county_id' => '16', 'value' => 'VILLA INDEPENDENCIA'),
                array('id' => 117, 'county_id' => '16', 'value' => 'VILLA NUEVA'),
                array('id' => 118, 'county_id' => '16', 'value' => 'VILLA PORTEÑA'),
                array('id' => 119, 'county_id' => '16', 'value' => 'VILLA PROGRESO'),
                array('id' => 120, 'county_id' => '16', 'value' => 'VILLA SAN CARLOS'),
                array('id' => 121, 'county_id' => '16', 'value' => 'VILLA ZULA'),
                array('id' => 122, 'county_id' => '17', 'value' => 'HALE'),
                array('id' => 123, 'county_id' => '17', 'value' => 'JUAN F. IBARRA'),
                array('id' => 124, 'county_id' => '17', 'value' => 'PAULA'),
                array('id' => 125, 'county_id' => '17', 'value' => 'PIROVANO'),
                array('id' => 126, 'county_id' => '17', 'value' => 'SAN CARLOS DE BOLIVAR'),
                array('id' => 127, 'county_id' => '17', 'value' => 'URDAMPILLETA'),
                array('id' => 128, 'county_id' => '17', 'value' => 'VILLA LYNCH PUEYRREDON'),
                array('id' => 129, 'county_id' => '18', 'value' => 'ASAMBLEA'),
                array('id' => 130, 'county_id' => '18', 'value' => 'BRAGADO'),
                array('id' => 131, 'county_id' => '18', 'value' => 'COMODORO PY'),
                array('id' => 132, 'county_id' => '18', 'value' => 'GENERAL O´BRIEN'),
                array('id' => 133, 'county_id' => '18', 'value' => 'IRALA'),
                array('id' => 134, 'county_id' => '18', 'value' => 'LA LIMPIA'),
                array('id' => 135, 'county_id' => '18', 'value' => 'MAXIMO FERNANDEZ'),
                array('id' => 136, 'county_id' => '18', 'value' => 'MECHITA'),
                array('id' => 137, 'county_id' => '18', 'value' => 'OLASCOAGA'),
                array('id' => 138, 'county_id' => '18', 'value' => 'WARNES'),
                array('id' => 139, 'county_id' => '19', 'value' => 'ALTAMIRANO'),
                array('id' => 140, 'county_id' => '19', 'value' => 'BARRIO EL MIRADOR'),
                array('id' => 141, 'county_id' => '19', 'value' => 'BARRIO LAS GOLONDRINAS'),
                array('id' => 142, 'county_id' => '19', 'value' => 'BARRIO LOS BOSQUECITOS'),
                array('id' => 143, 'county_id' => '19', 'value' => 'BARRIO PARQUE LAS ACACIAS'),
                array('id' => 144, 'county_id' => '19', 'value' => 'CAMPOS DE ROCA'),
                array('id' => 145, 'county_id' => '19', 'value' => 'CLUB DE CAMPO LAS MALVINAS'),
                array('id' => 146, 'county_id' => '19', 'value' => 'CORONEL BRANDSEN'),
                array('id' => 147, 'county_id' => '19', 'value' => 'GOMEZ'),
                array('id' => 148, 'county_id' => '19', 'value' => 'JEPPENER'),
                array('id' => 149, 'county_id' => '19', 'value' => 'OLIDEN'),
                array('id' => 150, 'county_id' => '19', 'value' => 'POSADA DE LOS LAGOS'),
                array('id' => 151, 'county_id' => '19', 'value' => 'SAMBOROMBON'),
                array('id' => 152, 'county_id' => '20', 'value' => 'ALTO LOS CARDALES'),
                array('id' => 153, 'county_id' => '20', 'value' => 'BARRIO LOS PIONEROS'),
                array('id' => 154, 'county_id' => '20', 'value' => 'CAMPANA'),
                array('id' => 155, 'county_id' => '20', 'value' => 'CHACRAS DEL RIO LUJAN'),
                array('id' => 156, 'county_id' => '20', 'value' => 'LOMAS DEL RIO LUJAN'),
                array('id' => 157, 'county_id' => '21', 'value' => 'ALEJANDRO PETION'),
                array('id' => 158, 'county_id' => '21', 'value' => 'BARRIO BELGRANO'),
                array('id' => 159, 'county_id' => '21', 'value' => 'BARRIO EL TALADRO'),
                array('id' => 160, 'county_id' => '21', 'value' => 'CAÂ¥UELAS'),
                array('id' => 161, 'county_id' => '21', 'value' => 'GOBERNADOR UDAONDO'),
                array('id' => 162, 'county_id' => '21', 'value' => 'MAXIMO PAZ'),
                array('id' => 163, 'county_id' => '21', 'value' => 'SANTA ROSA'),
                array('id' => 164, 'county_id' => '21', 'value' => 'URIBELARREA'),
                array('id' => 165, 'county_id' => '21', 'value' => 'VICENTE CASARES'),
                array('id' => 166, 'county_id' => '22', 'value' => 'CAPITAN SARMIENTO'),
                array('id' => 167, 'county_id' => '22', 'value' => 'LA LUISA'),
                array('id' => 168, 'county_id' => '23', 'value' => 'BELLOCQ'),
                array('id' => 169, 'county_id' => '23', 'value' => 'CADRET'),
                array('id' => 170, 'county_id' => '23', 'value' => 'CARLOS CASARES'),
                array('id' => 171, 'county_id' => '23', 'value' => 'COLONIA MAURICIO'),
                array('id' => 172, 'county_id' => '23', 'value' => 'HORTENSIA'),
                array('id' => 173, 'county_id' => '23', 'value' => 'LA SOFIA'),
                array('id' => 174, 'county_id' => '23', 'value' => 'MAURICIO HIRSCH'),
                array('id' => 175, 'county_id' => '23', 'value' => 'MOCTEZUMA'),
                array('id' => 176, 'county_id' => '23', 'value' => 'ORDOQUI'),
                array('id' => 177, 'county_id' => '23', 'value' => 'SANTO TOMAS'),
                array('id' => 178, 'county_id' => '23', 'value' => 'SMITH'),
                array('id' => 179, 'county_id' => '24', 'value' => 'CARLOS TEJEDOR'),
                array('id' => 180, 'county_id' => '24', 'value' => 'COLONIA SERE'),
                array('id' => 181, 'county_id' => '24', 'value' => 'CURARU'),
                array('id' => 182, 'county_id' => '24', 'value' => 'TIMOTE'),
                array('id' => 183, 'county_id' => '24', 'value' => 'TRES ALGARROBOS'),
                array('id' => 184, 'county_id' => '25', 'value' => 'CARMEN DE ARECO'),
                array('id' => 185, 'county_id' => '25', 'value' => 'PUEBLO GOUIN'),
                array('id' => 186, 'county_id' => '25', 'value' => 'TRES SARGENTOS'),
                array('id' => 187, 'county_id' => '26', 'value' => 'CASTELLI'),
                array('id' => 188, 'county_id' => '26', 'value' => 'CENTRO GUERRERO'),
                array('id' => 189, 'county_id' => '26', 'value' => 'CERRO DE LA GLORIA (CANAL 15)'),
                array('id' => 190, 'county_id' => '27', 'value' => 'CASTILLA'),
                array('id' => 191, 'county_id' => '27', 'value' => 'CHACABUCO'),
                array('id' => 192, 'county_id' => '27', 'value' => 'LOS ANGELES'),
                array('id' => 193, 'county_id' => '27', 'value' => 'O´HIGGINS'),
                array('id' => 194, 'county_id' => '27', 'value' => 'RAWSON'),
                array('id' => 195, 'county_id' => '28', 'value' => 'BARRIO LOMAS ALTAS'),
                array('id' => 196, 'county_id' => '28', 'value' => 'BARRIO SAN CAYETANO'),
                array('id' => 197, 'county_id' => '28', 'value' => 'CHASCOMUS'),
                array('id' => 198, 'county_id' => '28', 'value' => 'LAGUNA VITEL'),
                array('id' => 199, 'county_id' => '28', 'value' => 'MANUEL J. COBO'),
                array('id' => 200, 'county_id' => '28', 'value' => 'VILLA PARQUE GIRADO'),
                array('id' => 201, 'county_id' => '29', 'value' => 'BENITEZ'),
                array('id' => 202, 'county_id' => '29', 'value' => 'CHIVILCOY'),
                array('id' => 203, 'county_id' => '29', 'value' => 'EMILIO AYARZA'),
                array('id' => 204, 'county_id' => '29', 'value' => 'GOROSTIAGA'),
                array('id' => 205, 'county_id' => '29', 'value' => 'LA RICA'),
                array('id' => 206, 'county_id' => '29', 'value' => 'MOQUEHUA'),
                array('id' => 207, 'county_id' => '29', 'value' => 'RAMON BIAUS'),
                array('id' => 208, 'county_id' => '29', 'value' => 'SAN SEBASTIAN'),
                array('id' => 209, 'county_id' => '30', 'value' => 'BARRIO PARQUE GENERAL SAN MARTIN'),
                array('id' => 210, 'county_id' => '30', 'value' => 'BILLINGHURST'),
                array('id' => 211, 'county_id' => '30', 'value' => 'CIUDAD DEL LIBERTADOR GENERAL SAN MARTIN'),
                array('id' => 212, 'county_id' => '30', 'value' => 'CIUDAD JARDIN EL LIBERTADOR'),
                array('id' => 213, 'county_id' => '30', 'value' => 'VILLA AYACUCHO'),
                array('id' => 214, 'county_id' => '30', 'value' => 'VILLA BALLESTER'),
                array('id' => 215, 'county_id' => '30', 'value' => 'VILLA BERNARDO MONTEAGUDO'),
                array('id' => 216, 'county_id' => '30', 'value' => 'VILLA CHACABUCO'),
                array('id' => 217, 'county_id' => '30', 'value' => 'VILLA CORONEL JOSE M. ZAPIOLA'),
                array('id' => 218, 'county_id' => '30', 'value' => 'VILLA GENERAL ANTONIO J. DE SUCRE'),
                array('id' => 219, 'county_id' => '30', 'value' => 'VILLA GENERAL EUGENIO NECOCHEA'),
                array('id' => 220, 'county_id' => '30', 'value' => 'VILLA GENERAL JOSE TOMAS GUIDO'),
                array('id' => 221, 'county_id' => '30', 'value' => 'VILLA GENERAL JUAN G. LAS HERAS'),
                array('id' => 222, 'county_id' => '30', 'value' => 'VILLA GODOY CRUZ'),
                array('id' => 223, 'county_id' => '30', 'value' => 'VILLA GRANADEROS DE SAN MARTIN'),
                array('id' => 224, 'county_id' => '30', 'value' => 'VILLA GREGORIA MATORRAS'),
                array('id' => 225, 'county_id' => '30', 'value' => 'VILLA JOSE LEON SUAREZ'),
                array('id' => 226, 'county_id' => '30', 'value' => 'VILLA JUAN MARTIN DE PUEYRREDON'),
                array('id' => 227, 'county_id' => '30', 'value' => 'VILLA LIBERTAD'),
                array('id' => 228, 'county_id' => '30', 'value' => 'VILLA LYNCH'),
                array('id' => 229, 'county_id' => '30', 'value' => 'VILLA MAIPU'),
                array('id' => 230, 'county_id' => '30', 'value' => 'VILLA MARIA IRENE DE LOS REMEDIOS DE ESCALADA'),
                array('id' => 231, 'county_id' => '30', 'value' => 'VILLA MARQUES ALEJANDRO MARIA DE AGUADO'),
                array('id' => 232, 'county_id' => '30', 'value' => 'VILLA PARQUE PRESIDENTE FIGUEROA ALCORTA'),
                array('id' => 233, 'county_id' => '30', 'value' => 'VILLA PARQUE SAN LORENZO'),
                array('id' => 234, 'county_id' => '30', 'value' => 'VILLA SAN ANDRES'),
                array('id' => 235, 'county_id' => '30', 'value' => 'VILLA YAPEYU'),
                array('id' => 236, 'county_id' => '31', 'value' => 'COLON'),
                array('id' => 237, 'county_id' => '31', 'value' => 'EL ARBOLITO'),
                array('id' => 238, 'county_id' => '31', 'value' => 'PEARSON'),
                array('id' => 239, 'county_id' => '31', 'value' => 'SARASA'),
                array('id' => 240, 'county_id' => '32', 'value' => 'BAJO HONDO'),
                array('id' => 241, 'county_id' => '32', 'value' => 'BALNEARIO PEHUEN CO'),
                array('id' => 242, 'county_id' => '32', 'value' => 'PAGO CHICO'),
                array('id' => 243, 'county_id' => '32', 'value' => 'PUNTA ALTA'),
                array('id' => 244, 'county_id' => '32', 'value' => 'VILLA DEL MAR'),
                array('id' => 245, 'county_id' => '32', 'value' => 'VILLA GENERAL ARIAS'),
                array('id' => 246, 'county_id' => '33', 'value' => 'APARICIO'),
                array('id' => 247, 'county_id' => '33', 'value' => 'BALNEARIO MARISOL'),
                array('id' => 248, 'county_id' => '33', 'value' => 'CORONEL DORREGO'),
                array('id' => 249, 'county_id' => '33', 'value' => 'EL PERDIDO'),
                array('id' => 250, 'county_id' => '33', 'value' => 'FARO'),
                array('id' => 251, 'county_id' => '33', 'value' => 'IRENE'),
                array('id' => 252, 'county_id' => '33', 'value' => 'LA RUTA'),
                array('id' => 253, 'county_id' => '33', 'value' => 'ORIENTE'),
                array('id' => 254, 'county_id' => '33', 'value' => 'SAN ROMAN'),
                array('id' => 255, 'county_id' => '34', 'value' => 'CORONEL PRINGLES'),
                array('id' => 256, 'county_id' => '34', 'value' => 'EL DIVISORIO'),
                array('id' => 257, 'county_id' => '34', 'value' => 'EL PENSAMIENTO'),
                array('id' => 258, 'county_id' => '34', 'value' => 'INDIO RICO'),
                array('id' => 259, 'county_id' => '34', 'value' => 'LARTIGAU'),
                array('id' => 260, 'county_id' => '35', 'value' => 'CASCADAS'),
                array('id' => 261, 'county_id' => '35', 'value' => 'CORONEL SUAREZ'),
                array('id' => 262, 'county_id' => '35', 'value' => 'CURA MALAL'),
                array('id' => 263, 'county_id' => '35', 'value' => 'D´ORBIGNY'),
                array('id' => 264, 'county_id' => '35', 'value' => 'HUANGUELEN'),
                array('id' => 265, 'county_id' => '35', 'value' => 'PASMAN'),
                array('id' => 266, 'county_id' => '35', 'value' => 'SAN JOSE'),
                array('id' => 267, 'county_id' => '35', 'value' => 'SANTA MARIA'),
                array('id' => 268, 'county_id' => '35', 'value' => 'SANTA TRINIDAD'),
                array('id' => 269, 'county_id' => '35', 'value' => 'VILLA LA ARCADIA'),
                array('id' => 270, 'county_id' => '36', 'value' => 'ANDANT'),
                array('id' => 271, 'county_id' => '36', 'value' => 'ARBOLEDAS'),
                array('id' => 272, 'county_id' => '36', 'value' => 'DAIREAUX'),
                array('id' => 273, 'county_id' => '36', 'value' => 'LA LARGA'),
                array('id' => 274, 'county_id' => '36', 'value' => 'SALAZAR'),
                array('id' => 275, 'county_id' => '37', 'value' => 'DOLORES'),
                array('id' => 276, 'county_id' => '37', 'value' => 'SEVIGNE'),
                array('id' => 277, 'county_id' => '38', 'value' => 'DIQUE NÂº 1'),
                array('id' => 278, 'county_id' => '38', 'value' => 'ENSENADA'),
                array('id' => 279, 'county_id' => '38', 'value' => 'ISLA SANTIAGO (OESTE)'),
                array('id' => 280, 'county_id' => '38', 'value' => 'PUNTA LARA'),
                array('id' => 281, 'county_id' => '38', 'value' => 'VILLA CATELA'),
                array('id' => 282, 'county_id' => '39', 'value' => 'BELEN DE ESCOBAR'),
                array('id' => 283, 'county_id' => '39', 'value' => 'EL CAZADOR'),
                array('id' => 284, 'county_id' => '39', 'value' => 'GARIN'),
                array('id' => 285, 'county_id' => '39', 'value' => 'INGENIERO MASCHWITZ'),
                array('id' => 286, 'county_id' => '39', 'value' => 'LOMA VERDE'),
                array('id' => 287, 'county_id' => '39', 'value' => 'MAQUINISTA F. SAVIO ESTE'),
                array('id' => 288, 'county_id' => '39', 'value' => 'MATHEU'),
                array('id' => 289, 'county_id' => '40', 'value' => '9 DE ABRIL'),
                array('id' => 290, 'county_id' => '40', 'value' => 'CANNING'),
                array('id' => 291, 'county_id' => '40', 'value' => 'EL JAGÜEL'),
                array('id' => 292, 'county_id' => '40', 'value' => 'LUIS GUILLON'),
                array('id' => 293, 'county_id' => '40', 'value' => 'MONTE GRANDE'),
                array('id' => 294, 'county_id' => '41', 'value' => 'ARROYO DE LA CRUZ'),
                array('id' => 295, 'county_id' => '41', 'value' => 'CAPILLA DEL SEÂ¥OR'),
                array('id' => 296, 'county_id' => '41', 'value' => 'DIEGO GAYNOR'),
                array('id' => 297, 'county_id' => '41', 'value' => 'EL REMANSO'),
                array('id' => 298, 'county_id' => '41', 'value' => 'LOS CARDALES'),
                array('id' => 299, 'county_id' => '41', 'value' => 'PARADA ORLANDO'),
                array('id' => 300, 'county_id' => '41', 'value' => 'PARADA ROBLES'),
                array('id' => 301, 'county_id' => '41', 'value' => 'PAVON'),
                array('id' => 302, 'county_id' => '42', 'value' => 'BOSQUES'),
                array('id' => 303, 'county_id' => '42', 'value' => 'EL TROPEZON'),
                array('id' => 304, 'county_id' => '42', 'value' => 'ESTANISLAO SEVERO ZEBALLOS'),
                array('id' => 305, 'county_id' => '42', 'value' => 'FLORENCIO VARELA'),
                array('id' => 306, 'county_id' => '42', 'value' => 'GOBERNADOR JULIO A. COSTA'),
                array('id' => 307, 'county_id' => '42', 'value' => 'INGENIERO JUAN ALLAN'),
                array('id' => 308, 'county_id' => '42', 'value' => 'LA CAPILLA'),
                array('id' => 309, 'county_id' => '42', 'value' => 'VILLA BROWN'),
                array('id' => 310, 'county_id' => '42', 'value' => 'VILLA SAN LUIS'),
                array('id' => 311, 'county_id' => '42', 'value' => 'VILLA SANTA ROSA'),
                array('id' => 312, 'county_id' => '42', 'value' => 'VILLA VATTEONE'),
                array('id' => 313, 'county_id' => '43', 'value' => 'BLAQUIER'),
                array('id' => 314, 'county_id' => '43', 'value' => 'FLORENTINO AMEGHINO'),
                array('id' => 315, 'county_id' => '43', 'value' => 'PORVENIR'),
                array('id' => 316, 'county_id' => '44', 'value' => 'CENTINELA DEL MAR'),
                array('id' => 317, 'county_id' => '44', 'value' => 'COMANDANTE NICANOR OTAMENDI'),
                array('id' => 318, 'county_id' => '44', 'value' => 'MAR DEL SUR'),
                array('id' => 319, 'county_id' => '44', 'value' => 'MECHONGUE'),
                array('id' => 320, 'county_id' => '44', 'value' => 'MIRAMAR'),
                array('id' => 321, 'county_id' => '45', 'value' => 'GENERAL ALVEAR'),
                array('id' => 322, 'county_id' => '46', 'value' => 'ARRIBEÂ¥OS'),
                array('id' => 323, 'county_id' => '46', 'value' => 'ASCENSION'),
                array('id' => 324, 'county_id' => '46', 'value' => 'ESTACION ARENALES'),
                array('id' => 325, 'county_id' => '46', 'value' => 'FERRE'),
                array('id' => 326, 'county_id' => '46', 'value' => 'GENERAL ARENALES'),
                array('id' => 327, 'county_id' => '46', 'value' => 'LA ANGELITA'),
                array('id' => 328, 'county_id' => '46', 'value' => 'LA TRINIDAD'),
                array('id' => 329, 'county_id' => '47', 'value' => 'GENERAL BELGRANO'),
                array('id' => 330, 'county_id' => '47', 'value' => 'GORCHS'),
                array('id' => 331, 'county_id' => '48', 'value' => 'GENERAL GUIDO'),
                array('id' => 332, 'county_id' => '48', 'value' => 'LABARDEN'),
                array('id' => 333, 'county_id' => '49', 'value' => 'BARRIO KENNEDY'),
                array('id' => 334, 'county_id' => '49', 'value' => 'GENERAL JUAN MADARIAGA'),
                array('id' => 335, 'county_id' => '50', 'value' => 'GENERAL LA MADRID'),
                array('id' => 336, 'county_id' => '50', 'value' => 'LA COLINA'),
                array('id' => 337, 'county_id' => '50', 'value' => 'LAS MARTINETAS'),
                array('id' => 338, 'county_id' => '50', 'value' => 'LIBANO'),
                array('id' => 339, 'county_id' => '50', 'value' => 'PONTAUT'),
                array('id' => 340, 'county_id' => '51', 'value' => 'GENERAL HORNOS'),
                array('id' => 341, 'county_id' => '51', 'value' => 'GENERAL LAS HERAS'),
                array('id' => 342, 'county_id' => '51', 'value' => 'LA CHOZA'),
                array('id' => 343, 'county_id' => '51', 'value' => 'PLOMER'),
                array('id' => 344, 'county_id' => '51', 'value' => 'VILLARS'),
                array('id' => 345, 'county_id' => '52', 'value' => 'GENERAL LAVALLE'),
                array('id' => 346, 'county_id' => '52', 'value' => 'PAVON'),
                array('id' => 347, 'county_id' => '53', 'value' => 'BARRIO RIO SALADO'),
                array('id' => 348, 'county_id' => '53', 'value' => 'LOMA VERDE'),
                array('id' => 349, 'county_id' => '53', 'value' => 'RANCHOS'),
                array('id' => 350, 'county_id' => '53', 'value' => 'VILLANUEVA'),
                array('id' => 351, 'county_id' => '54', 'value' => 'COLONIA SAN RICARDO'),
                array('id' => 352, 'county_id' => '54', 'value' => 'GENERAL PINTO'),
                array('id' => 353, 'county_id' => '54', 'value' => 'GERMANIA'),
                array('id' => 354, 'county_id' => '54', 'value' => 'GUNTHER'),
                array('id' => 355, 'county_id' => '54', 'value' => 'VILLA FRANCIA'),
                array('id' => 356, 'county_id' => '54', 'value' => 'VILLA ROTH'),
                array('id' => 357, 'county_id' => '55', 'value' => 'BARRIO COLINAS VERDES'),
                array('id' => 358, 'county_id' => '55', 'value' => 'BARRIO EL BOQUERON'),
                array('id' => 359, 'county_id' => '55', 'value' => 'BARRIO EL CASAL'),
                array('id' => 360, 'county_id' => '55', 'value' => 'BARRIO EL COYUNCO'),
                array('id' => 361, 'county_id' => '55', 'value' => 'BARRIO LA GLORIA'),
                array('id' => 362, 'county_id' => '55', 'value' => 'BARRIO SANTA PAULA'),
                array('id' => 363, 'county_id' => '55', 'value' => 'BATAN'),
                array('id' => 364, 'county_id' => '55', 'value' => 'CAMET'),
                array('id' => 365, 'county_id' => '55', 'value' => 'CHAPADMALAL'),
                array('id' => 366, 'county_id' => '55', 'value' => 'EL MARQUESADO'),
                array('id' => 367, 'county_id' => '55', 'value' => 'ESTACION CAMET'),
                array('id' => 368, 'county_id' => '55', 'value' => 'ESTACION CHAPADMALAL'),
                array('id' => 369, 'county_id' => '55', 'value' => 'MAR DEL PLATA'),
                array('id' => 370, 'county_id' => '55', 'value' => 'PUNTA MOGOTES'),
                array('id' => 371, 'county_id' => '55', 'value' => 'SIERRA DE LOS PADRES'),
                array('id' => 372, 'county_id' => '56', 'value' => 'BARRIO MORABO'),
                array('id' => 373, 'county_id' => '56', 'value' => 'BARRIO RUTA 24 KILOMETRO 10'),
                array('id' => 374, 'county_id' => '56', 'value' => 'BARRIO RUTA 24 KM. 10'),
                array('id' => 375, 'county_id' => '56', 'value' => 'C.C. BOSQUE REAL'),
                array('id' => 376, 'county_id' => '56', 'value' => 'GENERAL RODRGUEZ'),
                array('id' => 377, 'county_id' => '56', 'value' => 'GENERAL RODRIGUEZ'),
                array('id' => 378, 'county_id' => '57', 'value' => 'BAIGORRITA'),
                array('id' => 379, 'county_id' => '57', 'value' => 'LA DELFINA'),
                array('id' => 380, 'county_id' => '57', 'value' => 'LOS TOLDOS'),
                array('id' => 381, 'county_id' => '57', 'value' => 'SAN EMILIO'),
                array('id' => 382, 'county_id' => '57', 'value' => 'ZAVALIA'),
                array('id' => 383, 'county_id' => '58', 'value' => 'BANDERALO'),
                array('id' => 384, 'county_id' => '58', 'value' => 'CAÂ¥ADA SECA'),
                array('id' => 385, 'county_id' => '58', 'value' => 'CORONEL CHARLONE'),
                array('id' => 386, 'county_id' => '58', 'value' => 'EMILIO V. BUNGE'),
                array('id' => 387, 'county_id' => '58', 'value' => 'GENERAL VILLEGAS'),
                array('id' => 388, 'county_id' => '58', 'value' => 'MASSEY'),
                array('id' => 389, 'county_id' => '58', 'value' => 'PICHINCHA'),
                array('id' => 390, 'county_id' => '58', 'value' => 'PIEDRITAS'),
                array('id' => 391, 'county_id' => '58', 'value' => 'SANTA ELEODORA'),
                array('id' => 392, 'county_id' => '58', 'value' => 'SANTA REGINA'),
                array('id' => 393, 'county_id' => '58', 'value' => 'VILLA SABOYA'),
                array('id' => 394, 'county_id' => '58', 'value' => 'VILLA SAUZE'),
                array('id' => 395, 'county_id' => '59', 'value' => 'ARROYO VENADO'),
                array('id' => 396, 'county_id' => '59', 'value' => 'CASBAS'),
                array('id' => 397, 'county_id' => '59', 'value' => 'GARRE'),
                array('id' => 398, 'county_id' => '59', 'value' => 'GUAMINI'),
                array('id' => 399, 'county_id' => '59', 'value' => 'LAGUNA ALSINA'),
                array('id' => 400, 'county_id' => '60', 'value' => 'HENDERSON'),
                array('id' => 401, 'county_id' => '60', 'value' => 'HERRERA VEGAS'),
                array('id' => 402, 'county_id' => '61', 'value' => 'HURLINGHAM'),
                array('id' => 403, 'county_id' => '61', 'value' => 'VILLA SANTOS TESEI'),
                array('id' => 404, 'county_id' => '61', 'value' => 'WILLIAM C. MORRIS'),
                array('id' => 405, 'county_id' => '62', 'value' => 'ITUZAINGO CENTRO'),
                array('id' => 406, 'county_id' => '62', 'value' => 'ITUZAINGO SUR'),
                array('id' => 407, 'county_id' => '62', 'value' => 'VILLA GOBERNADOR UDAONDO'),
                array('id' => 408, 'county_id' => '63', 'value' => 'DEL VISO'),
                array('id' => 409, 'county_id' => '63', 'value' => 'JOSE C. PAZ'),
                array('id' => 410, 'county_id' => '63', 'value' => 'TORTUGUITAS'),
                array('id' => 411, 'county_id' => '64', 'value' => 'AEROPUERTO INTERNACIONAL EZEIZA'),
                array('id' => 412, 'county_id' => '64', 'value' => 'CANNING'),
                array('id' => 413, 'county_id' => '64', 'value' => 'CARLOS SPEGAZZINI'),
                array('id' => 414, 'county_id' => '64', 'value' => 'JOSE MARIA EZEIZA'),
                array('id' => 415, 'county_id' => '64', 'value' => 'LA UNION'),
                array('id' => 416, 'county_id' => '64', 'value' => 'TRISTAN SUAREZ'),
                array('id' => 417, 'county_id' => '65', 'value' => 'AGUSTIN ROCA'),
                array('id' => 418, 'county_id' => '65', 'value' => 'AGUSTINA'),
                array('id' => 419, 'county_id' => '65', 'value' => 'BALNEARIO LAGUNA DE GOMEZ'),
                array('id' => 420, 'county_id' => '65', 'value' => 'FORTIN TIBURCIO'),
                array('id' => 421, 'county_id' => '65', 'value' => 'JUNIN'),
                array('id' => 422, 'county_id' => '65', 'value' => 'LA AGRARIA'),
                array('id' => 423, 'county_id' => '65', 'value' => 'LAPLACETTE'),
                array('id' => 424, 'county_id' => '65', 'value' => 'MORSE'),
                array('id' => 425, 'county_id' => '65', 'value' => 'SAFORCADA'),
                array('id' => 426, 'county_id' => '66', 'value' => 'AGUAS VERDES'),
                array('id' => 427, 'county_id' => '66', 'value' => 'LAS TONINAS'),
                array('id' => 428, 'county_id' => '66', 'value' => 'LUCILA DEL MAR'),
                array('id' => 429, 'county_id' => '66', 'value' => 'MAR DE AJO'),
                array('id' => 430, 'county_id' => '66', 'value' => 'MAR DE AJO NORTE'),
                array('id' => 431, 'county_id' => '66', 'value' => 'MAR DEL TUYU'),
                array('id' => 432, 'county_id' => '66', 'value' => 'SAN BERNARDO'),
                array('id' => 433, 'county_id' => '66', 'value' => 'SAN CLEMENTE DEL TUYU'),
                array('id' => 434, 'county_id' => '66', 'value' => 'SANTA TERESITA'),
                array('id' => 435, 'county_id' => '67', 'value' => '20 DE JUNIO'),
                array('id' => 436, 'county_id' => '67', 'value' => 'ALDO BONZI'),
                array('id' => 437, 'county_id' => '67', 'value' => 'CIUDAD EVITA'),
                array('id' => 438, 'county_id' => '67', 'value' => 'GONZALEZ CATAN'),
                array('id' => 439, 'county_id' => '67', 'value' => 'GREGORIO DE LAFERRERE'),
                array('id' => 440, 'county_id' => '67', 'value' => 'ISIDRO CASANOVA'),
                array('id' => 441, 'county_id' => '67', 'value' => 'LA TABLADA'),
                array('id' => 442, 'county_id' => '67', 'value' => 'LOMAS DEL MIRADOR'),
                array('id' => 443, 'county_id' => '67', 'value' => 'RAFAEL CASTILLO'),
                array('id' => 444, 'county_id' => '67', 'value' => 'RAMOS MEJIA'),
                array('id' => 445, 'county_id' => '67', 'value' => 'SAN JUSTO'),
                array('id' => 446, 'county_id' => '67', 'value' => 'TAPIALES'),
                array('id' => 447, 'county_id' => '67', 'value' => 'VILLA EDUARDO MADERO'),
                array('id' => 448, 'county_id' => '67', 'value' => 'VILLA LUZURIAGA'),
                array('id' => 449, 'county_id' => '67', 'value' => 'VIRREY DEL PINO'),
                array('id' => 450, 'county_id' => '68', 'value' => 'ABASTO'),
                array('id' => 451, 'county_id' => '68', 'value' => 'ANGEL ETCHEVERRY'),
                array('id' => 452, 'county_id' => '68', 'value' => 'ARANA'),
                array('id' => 453, 'county_id' => '68', 'value' => 'ARTURO SEGUI'),
                array('id' => 454, 'county_id' => '68', 'value' => 'BARRIO EL CARMEN (OESTE)'),
                array('id' => 455, 'county_id' => '68', 'value' => 'BARRIO GAMBIER'),
                array('id' => 456, 'county_id' => '68', 'value' => 'BARRIO LAS MALVINAS'),
                array('id' => 457, 'county_id' => '68', 'value' => 'BARRIO LAS QUINTAS'),
                array('id' => 458, 'county_id' => '68', 'value' => 'BARRIO RUTA SOL'),
                array('id' => 459, 'county_id' => '68', 'value' => 'CITY BELL'),
                array('id' => 460, 'county_id' => '68', 'value' => 'COUNTRY CLUB EL RODEO'),
                array('id' => 461, 'county_id' => '68', 'value' => 'EL RETIRO'),
                array('id' => 462, 'county_id' => '68', 'value' => 'IGNACIO CORREAS'),
                array('id' => 463, 'county_id' => '68', 'value' => 'JOAQUIN GORINA'),
                array('id' => 464, 'county_id' => '68', 'value' => 'JOSE HERNANDEZ'),
                array('id' => 465, 'county_id' => '68', 'value' => 'JOSE MELCHOR ROMERO'),
                array('id' => 466, 'county_id' => '68', 'value' => 'LA CUMBRE'),
                array('id' => 467, 'county_id' => '68', 'value' => 'LA PLATA'),
                array('id' => 468, 'county_id' => '68', 'value' => 'LISANDRO OLMOS'),
                array('id' => 469, 'county_id' => '68', 'value' => 'LOMAS DE COPELLO'),
                array('id' => 470, 'county_id' => '68', 'value' => 'LOS HORNOS'),
                array('id' => 471, 'county_id' => '68', 'value' => 'MANUEL B. GONNET'),
                array('id' => 472, 'county_id' => '68', 'value' => 'RINGUELET'),
                array('id' => 473, 'county_id' => '68', 'value' => 'RUFINO DE ELIZALDE'),
                array('id' => 474, 'county_id' => '68', 'value' => 'TOLOSA'),
                array('id' => 475, 'county_id' => '68', 'value' => 'TRANSRADIO'),
                array('id' => 476, 'county_id' => '68', 'value' => 'VILLA ELISA'),
                array('id' => 477, 'county_id' => '68', 'value' => 'VILLA ELVIRA'),
                array('id' => 478, 'county_id' => '68', 'value' => 'VILLA GARIBALDI'),
                array('id' => 479, 'county_id' => '68', 'value' => 'VILLA MONTORO'),
                array('id' => 480, 'county_id' => '68', 'value' => 'VILLA PARQUE SICARDI'),
                array('id' => 481, 'county_id' => '69', 'value' => 'GERLI'),
                array('id' => 482, 'county_id' => '69', 'value' => 'LANUS ESTE'),
                array('id' => 483, 'county_id' => '69', 'value' => 'LANUS OESTE'),
                array('id' => 484, 'county_id' => '69', 'value' => 'MONTE CHINGOLO'),
                array('id' => 485, 'county_id' => '69', 'value' => 'REMEDIOS ESCALADA DE SAN MARTIN'),
                array('id' => 486, 'county_id' => '69', 'value' => 'VALENTIN ALSINA'),
                array('id' => 487, 'county_id' => '70', 'value' => 'LAPRIDA'),
                array('id' => 488, 'county_id' => '70', 'value' => 'PUEBLO NUEVO'),
                array('id' => 489, 'county_id' => '70', 'value' => 'PUEBLO SAN JORGE'),
                array('id' => 490, 'county_id' => '71', 'value' => 'CORONEL BOERR'),
                array('id' => 491, 'county_id' => '71', 'value' => 'EL TRIGO'),
                array('id' => 492, 'county_id' => '71', 'value' => 'LAS FLORES'),
                array('id' => 493, 'county_id' => '71', 'value' => 'PARDO'),
                array('id' => 494, 'county_id' => '72', 'value' => 'ALBERDI VIEJO'),
                array('id' => 495, 'county_id' => '72', 'value' => 'EL DORADO'),
                array('id' => 496, 'county_id' => '72', 'value' => 'FORTIN ACHA'),
                array('id' => 497, 'county_id' => '72', 'value' => 'JUAN BAUTISTA ALBERDI'),
                array('id' => 498, 'county_id' => '72', 'value' => 'LEANDRO N. ALEM'),
                array('id' => 499, 'county_id' => '72', 'value' => 'VEDIA'),
                array('id' => 500, 'county_id' => '73', 'value' => 'ARENAZA'),
                array('id' => 501, 'county_id' => '73', 'value' => 'BAYAUCA'),
                array('id' => 502, 'county_id' => '73', 'value' => 'BERMUDEZ'),
                array('id' => 503, 'county_id' => '73', 'value' => 'CARLOS SALAS'),
                array('id' => 504, 'county_id' => '73', 'value' => 'CORONEL MARTINEZ DE HOZ'),
                array('id' => 505, 'county_id' => '73', 'value' => 'EL TRIUNFO'),
                array('id' => 506, 'county_id' => '73', 'value' => 'LAS TOSCAS'),
                array('id' => 507, 'county_id' => '73', 'value' => 'LINCOLN'),
                array('id' => 508, 'county_id' => '73', 'value' => 'PASTEUR'),
                array('id' => 509, 'county_id' => '73', 'value' => 'ROBERTS'),
                array('id' => 510, 'county_id' => '73', 'value' => 'TRIUNVIRATO'),
                array('id' => 511, 'county_id' => '74', 'value' => 'ARENAS VERDES'),
                array('id' => 512, 'county_id' => '74', 'value' => 'LICENCIADO MATIENZO'),
                array('id' => 513, 'county_id' => '74', 'value' => 'LOBERIA'),
                array('id' => 514, 'county_id' => '74', 'value' => 'PIERES'),
                array('id' => 515, 'county_id' => '74', 'value' => 'SAN MANUEL'),
                array('id' => 516, 'county_id' => '74', 'value' => 'TAMANGUEYU'),
                array('id' => 517, 'county_id' => '75', 'value' => 'ANTONIO CARBONI'),
                array('id' => 518, 'county_id' => '75', 'value' => 'ELVIRA'),
                array('id' => 519, 'county_id' => '75', 'value' => 'LAGUNA DE LOBOS'),
                array('id' => 520, 'county_id' => '75', 'value' => 'LOBOS'),
                array('id' => 521, 'county_id' => '75', 'value' => 'SALVADOR MARIA'),
                array('id' => 522, 'county_id' => '76', 'value' => 'BANFIELD'),
                array('id' => 523, 'county_id' => '76', 'value' => 'LLAVALLOL'),
                array('id' => 524, 'county_id' => '76', 'value' => 'LOMAS DE ZAMORA'),
                array('id' => 525, 'county_id' => '76', 'value' => 'TEMPERLEY'),
                array('id' => 526, 'county_id' => '76', 'value' => 'TURDERA'),
                array('id' => 527, 'county_id' => '76', 'value' => 'VILLA CENTENARIO'),
                array('id' => 528, 'county_id' => '76', 'value' => 'VILLA FIORITO'),
                array('id' => 529, 'county_id' => '77', 'value' => 'BARRIO LAS CASUARINAS'),
                array('id' => 530, 'county_id' => '77', 'value' => 'CARLOS KEEN'),
                array('id' => 531, 'county_id' => '77', 'value' => 'CLUB DE CAMPO LOS PUENTES'),
                array('id' => 532, 'county_id' => '77', 'value' => 'CORTINES'),
                array('id' => 533, 'county_id' => '77', 'value' => 'COUNTRY CLUB LAS PRADERAS'),
                array('id' => 534, 'county_id' => '77', 'value' => 'LEZICA Y TORREZURI'),
                array('id' => 535, 'county_id' => '77', 'value' => 'LUJAN'),
                array('id' => 536, 'county_id' => '77', 'value' => 'OLIVERA'),
                array('id' => 537, 'county_id' => '77', 'value' => 'OPEN DOOR'),
                array('id' => 538, 'county_id' => '77', 'value' => 'TORRES'),
                array('id' => 539, 'county_id' => '77', 'value' => 'VILLA FLANDRIA NORTE (PUEBLO NUEVO)'),
                array('id' => 540, 'county_id' => '77', 'value' => 'VILLA FLANDRIA SUR (EST. JAUREGUI)'),
                array('id' => 541, 'county_id' => '78', 'value' => 'ATALAYA'),
                array('id' => 542, 'county_id' => '78', 'value' => 'GENERAL MANSILLA'),
                array('id' => 543, 'county_id' => '78', 'value' => 'LOS NARANJOS'),
                array('id' => 544, 'county_id' => '78', 'value' => 'MAGDALENA'),
                array('id' => 545, 'county_id' => '78', 'value' => 'ROBERTO J. PAYRO'),
                array('id' => 546, 'county_id' => '78', 'value' => 'VIEYTES'),
                array('id' => 547, 'county_id' => '79', 'value' => 'LAS ARMAS'),
                array('id' => 548, 'county_id' => '79', 'value' => 'MAIPU'),
                array('id' => 549, 'county_id' => '79', 'value' => 'SANTO DOMINGO'),
                array('id' => 550, 'county_id' => '80', 'value' => 'AREA DE PROMOCION EL TRIANGULO'),
                array('id' => 551, 'county_id' => '80', 'value' => 'GRAND BOURG'),
                array('id' => 552, 'county_id' => '80', 'value' => 'INGENIERO ADOLFO SOURDEAUX'),
                array('id' => 553, 'county_id' => '80', 'value' => 'INGENIERO PABLO NOGUES'),
                array('id' => 554, 'county_id' => '80', 'value' => 'LOS POLVORINES'),
                array('id' => 555, 'county_id' => '80', 'value' => 'TORTUGUITAS'),
                array('id' => 556, 'county_id' => '80', 'value' => 'VILLA DE MAYO'),
                array('id' => 557, 'county_id' => '81', 'value' => 'ATLANTIDA'),
                array('id' => 558, 'county_id' => '81', 'value' => 'CAMET NORTE'),
                array('id' => 559, 'county_id' => '81', 'value' => 'CORONEL VIDAL'),
                array('id' => 560, 'county_id' => '81', 'value' => 'FRENTE MAR'),
                array('id' => 561, 'county_id' => '81', 'value' => 'GENERAL PIRAN'),
                array('id' => 562, 'county_id' => '81', 'value' => 'LA ARMONIA'),
                array('id' => 563, 'county_id' => '81', 'value' => 'LA BALIZA'),
                array('id' => 564, 'county_id' => '81', 'value' => 'LA CALETA'),
                array('id' => 565, 'county_id' => '81', 'value' => 'MAR CHIQUITA'),
                array('id' => 566, 'county_id' => '81', 'value' => 'MAR DE COBO'),
                array('id' => 567, 'county_id' => '81', 'value' => 'PLAYA DORADA'),
                array('id' => 568, 'county_id' => '81', 'value' => 'SANTA CLARA DEL MAR'),
                array('id' => 569, 'county_id' => '81', 'value' => 'SANTA ELENA'),
                array('id' => 570, 'county_id' => '81', 'value' => 'VIVORATA'),
                array('id' => 571, 'county_id' => '82', 'value' => 'BARRIO SANTA ROSA'),
                array('id' => 572, 'county_id' => '82', 'value' => 'BARRIOS LISANDRO DE LA TORRE Y SANTA MARTA'),
                array('id' => 573, 'county_id' => '82', 'value' => 'MARCOS PAZ'),
                array('id' => 574, 'county_id' => '83', 'value' => 'GOLDNEY'),
                array('id' => 575, 'county_id' => '83', 'value' => 'GOWLAND'),
                array('id' => 576, 'county_id' => '83', 'value' => 'MERCEDES'),
                array('id' => 577, 'county_id' => '83', 'value' => 'TOMAS JOFRE'),
                array('id' => 578, 'county_id' => '84', 'value' => 'LIBERTAD'),
                array('id' => 579, 'county_id' => '84', 'value' => 'MARIANO ACOSTA'),
                array('id' => 580, 'county_id' => '84', 'value' => 'MERLO'),
                array('id' => 581, 'county_id' => '84', 'value' => 'PONTEVEDRA'),
                array('id' => 582, 'county_id' => '84', 'value' => 'SAN ANTONIO DE PADUA'),
                array('id' => 583, 'county_id' => '85', 'value' => 'ABBOTT'),
                array('id' => 584, 'county_id' => '85', 'value' => 'SAN MIGUEL DEL MONTE'),
                array('id' => 585, 'county_id' => '85', 'value' => 'ZENON VIDELA DORNA'),
                array('id' => 586, 'county_id' => '86', 'value' => 'BALNEARIO SAUCE GRANDE'),
                array('id' => 587, 'county_id' => '86', 'value' => 'MONTE HERMOSO'),
                array('id' => 588, 'county_id' => '87', 'value' => 'CUARTEL V'),
                array('id' => 589, 'county_id' => '87', 'value' => 'FRANCISCO ALVAREZ'),
                array('id' => 590, 'county_id' => '87', 'value' => 'LA REJA'),
                array('id' => 591, 'county_id' => '87', 'value' => 'MORENO'),
                array('id' => 592, 'county_id' => '87', 'value' => 'PASO DEL REY'),
                array('id' => 593, 'county_id' => '87', 'value' => 'TRUJUI'),
                array('id' => 594, 'county_id' => '88', 'value' => 'CASTELAR'),
                array('id' => 595, 'county_id' => '88', 'value' => 'EL PALOMAR'),
                array('id' => 596, 'county_id' => '88', 'value' => 'HAEDO'),
                array('id' => 597, 'county_id' => '88', 'value' => 'MORON'),
                array('id' => 598, 'county_id' => '88', 'value' => 'VILLA SARMIENTO'),
                array('id' => 599, 'county_id' => '89', 'value' => 'JOSE JUAN ALMEYRA'),
                array('id' => 600, 'county_id' => '89', 'value' => 'LAS MARIANAS'),
                array('id' => 601, 'county_id' => '89', 'value' => 'NAVARRO'),
                array('id' => 602, 'county_id' => '89', 'value' => 'VILLA MOLL'),
                array('id' => 603, 'county_id' => '90', 'value' => 'CLARAZ'),
                array('id' => 604, 'county_id' => '90', 'value' => 'COSTA BONITA'),
                array('id' => 605, 'county_id' => '90', 'value' => 'ENERGIA'),
                array('id' => 606, 'county_id' => '90', 'value' => 'JUAN N. FERNANDEZ'),
                array('id' => 607, 'county_id' => '90', 'value' => 'NECOCHEA'),
                array('id' => 608, 'county_id' => '90', 'value' => 'NICANOR OLIVERA'),
                array('id' => 609, 'county_id' => '90', 'value' => 'QUEQUEN'),
                array('id' => 610, 'county_id' => '90', 'value' => 'RAMON SANTAMARINA'),
                array('id' => 611, 'county_id' => '91', 'value' => 'BLANCAGRANDE'),
                array('id' => 612, 'county_id' => '91', 'value' => 'COLONIA HINOJO'),
                array('id' => 613, 'county_id' => '91', 'value' => 'COLONIA NIEVAS'),
                array('id' => 614, 'county_id' => '91', 'value' => 'COLONIA SAN MIGUEL'),
                array('id' => 615, 'county_id' => '91', 'value' => 'ESPIGAS'),
                array('id' => 616, 'county_id' => '91', 'value' => 'HINOJO'),
                array('id' => 617, 'county_id' => '91', 'value' => 'OLAVARRIA'),
                array('id' => 618, 'county_id' => '91', 'value' => 'RECALDE'),
                array('id' => 619, 'county_id' => '91', 'value' => 'SANTA LUISA'),
                array('id' => 620, 'county_id' => '91', 'value' => 'SIERRA CHICA'),
                array('id' => 621, 'county_id' => '91', 'value' => 'SIERRAS BAYAS'),
                array('id' => 622, 'county_id' => '91', 'value' => 'VILLA ALFREDO FORTABAT'),
                array('id' => 623, 'county_id' => '91', 'value' => 'VILLA ARRIETA'),
                array('id' => 624, 'county_id' => '91', 'value' => 'VILLA LA SERRANIA'),
                array('id' => 625, 'county_id' => '92', 'value' => 'BAHIA SAN BLAS'),
                array('id' => 626, 'county_id' => '92', 'value' => 'CARDENAL CAGLIERO'),
                array('id' => 627, 'county_id' => '92', 'value' => 'CARMEN DE PATAGONES'),
                array('id' => 628, 'county_id' => '92', 'value' => 'JOSE B. CASAS'),
                array('id' => 629, 'county_id' => '92', 'value' => 'JUAN A. PRADERE'),
                array('id' => 630, 'county_id' => '92', 'value' => 'STROEDER'),
                array('id' => 631, 'county_id' => '92', 'value' => 'VILLALONGA'),
                array('id' => 632, 'county_id' => '93', 'value' => 'CAPITAN CASTRO'),
                array('id' => 633, 'county_id' => '93', 'value' => 'CHICLANA'),
                array('id' => 634, 'county_id' => '93', 'value' => 'FRANCISCO MADERO'),
                array('id' => 635, 'county_id' => '93', 'value' => 'INOCENCIO SOSA'),
                array('id' => 636, 'county_id' => '93', 'value' => 'JUAN JOSE PASO'),
                array('id' => 637, 'county_id' => '93', 'value' => 'MAGDALA'),
                array('id' => 638, 'county_id' => '93', 'value' => 'MONES CAZON'),
                array('id' => 639, 'county_id' => '93', 'value' => 'NUEVA PLATA'),
                array('id' => 640, 'county_id' => '93', 'value' => 'PEHUAJO'),
                array('id' => 641, 'county_id' => '93', 'value' => 'SAN BERNARDO'),
                array('id' => 642, 'county_id' => '94', 'value' => 'BOCAYUVA'),
                array('id' => 643, 'county_id' => '94', 'value' => 'DE BARY'),
                array('id' => 644, 'county_id' => '94', 'value' => 'PELLEGRINI'),
                array('id' => 645, 'county_id' => '95', 'value' => 'ACEVEDO'),
                array('id' => 646, 'county_id' => '95', 'value' => 'FONTEZUELA'),
                array('id' => 647, 'county_id' => '95', 'value' => 'GUERRICO'),
                array('id' => 648, 'county_id' => '95', 'value' => 'JUAN A. DE LA PEÂ¥A'),
                array('id' => 649, 'county_id' => '95', 'value' => 'JUAN ANCHORENA'),
                array('id' => 650, 'county_id' => '95', 'value' => 'LA VIOLETA'),
                array('id' => 651, 'county_id' => '95', 'value' => 'MANUEL OCAMPO'),
                array('id' => 652, 'county_id' => '95', 'value' => 'MARIANO BENITEZ'),
                array('id' => 653, 'county_id' => '95', 'value' => 'MARIANO H. ALFONZO'),
                array('id' => 654, 'county_id' => '95', 'value' => 'PERGAMINO'),
                array('id' => 655, 'county_id' => '95', 'value' => 'PINZON'),
                array('id' => 656, 'county_id' => '95', 'value' => 'RANCAGUA'),
                array('id' => 657, 'county_id' => '95', 'value' => 'VILLA ANGELICA'),
                array('id' => 658, 'county_id' => '95', 'value' => 'VILLA SAN JOSE'),
                array('id' => 659, 'county_id' => '96', 'value' => 'CASALINS'),
                array('id' => 660, 'county_id' => '96', 'value' => 'PILA'),
                array('id' => 661, 'county_id' => '97', 'value' => 'DEL VISO'),
                array('id' => 662, 'county_id' => '97', 'value' => 'FATIMA'),
                array('id' => 663, 'county_id' => '97', 'value' => 'LA LONJA'),
                array('id' => 664, 'county_id' => '97', 'value' => 'LOS CACHORROS'),
                array('id' => 665, 'county_id' => '97', 'value' => 'MANZANARES'),
                array('id' => 666, 'county_id' => '97', 'value' => 'MANZONE'),
                array('id' => 667, 'county_id' => '97', 'value' => 'MAQUINISTA F. SAVIO (OESTE)'),
                array('id' => 668, 'county_id' => '97', 'value' => 'PILAR'),
                array('id' => 669, 'county_id' => '97', 'value' => 'PRESIDENTE DERQUI'),
                array('id' => 670, 'county_id' => '97', 'value' => 'ROBERTO DE VICENZO'),
                array('id' => 671, 'county_id' => '97', 'value' => 'SANTA TERESA'),
                array('id' => 672, 'county_id' => '97', 'value' => 'TORTUGUITAS'),
                array('id' => 673, 'county_id' => '97', 'value' => 'VILLA ASTOLFI'),
                array('id' => 674, 'county_id' => '97', 'value' => 'VILLA ROSA'),
                array('id' => 675, 'county_id' => '97', 'value' => 'ZELAYA'),
                array('id' => 676, 'county_id' => '98', 'value' => 'CARILO'),
                array('id' => 677, 'county_id' => '98', 'value' => 'OSTENDE'),
                array('id' => 678, 'county_id' => '98', 'value' => 'PINAMAR'),
                array('id' => 679, 'county_id' => '98', 'value' => 'VALERIA DEL MAR'),
                array('id' => 680, 'county_id' => '99', 'value' => 'BARRIO AMERICA UNIDA'),
                array('id' => 681, 'county_id' => '99', 'value' => 'GUERNICA'),
                array('id' => 682, 'county_id' => '100', 'value' => '17 DE AGOSTO'),
                array('id' => 683, 'county_id' => '100', 'value' => 'AZOPARDO'),
                array('id' => 684, 'county_id' => '100', 'value' => 'BORDENAVE'),
                array('id' => 685, 'county_id' => '100', 'value' => 'DARREGUEIRA'),
                array('id' => 686, 'county_id' => '100', 'value' => 'ESTELA'),
                array('id' => 687, 'county_id' => '100', 'value' => 'FELIPE SOLA'),
                array('id' => 688, 'county_id' => '100', 'value' => 'LOPEZ LECUBE'),
                array('id' => 689, 'county_id' => '100', 'value' => 'PUAN'),
                array('id' => 690, 'county_id' => '100', 'value' => 'SAN GERMAN'),
                array('id' => 691, 'county_id' => '100', 'value' => 'VILLA CASTELAR'),
                array('id' => 692, 'county_id' => '100', 'value' => 'VILLA IRIS'),
                array('id' => 693, 'county_id' => '101', 'value' => 'ALVAREZ JONTE'),
                array('id' => 694, 'county_id' => '101', 'value' => 'PIPINAS'),
                array('id' => 695, 'county_id' => '101', 'value' => 'PUNTA INDIO'),
                array('id' => 696, 'county_id' => '101', 'value' => 'VERONICA'),
                array('id' => 697, 'county_id' => '102', 'value' => 'BERNAL'),
                array('id' => 698, 'county_id' => '102', 'value' => 'BERNAL OESTE'),
                array('id' => 699, 'county_id' => '102', 'value' => 'DON BOSCO'),
                array('id' => 700, 'county_id' => '102', 'value' => 'EZPELETA'),
                array('id' => 701, 'county_id' => '102', 'value' => 'EZPELETA OESTE'),
                array('id' => 702, 'county_id' => '102', 'value' => 'QUILMES'),
                array('id' => 703, 'county_id' => '102', 'value' => 'QUILMES OESTE'),
                array('id' => 704, 'county_id' => '102', 'value' => 'SAN FRANCISCO SOLANO'),
                array('id' => 705, 'county_id' => '102', 'value' => 'VILLA LA FLORIDA'),
                array('id' => 706, 'county_id' => '103', 'value' => 'EL PARAISO'),
                array('id' => 707, 'county_id' => '103', 'value' => 'LAS BAHAMAS'),
                array('id' => 708, 'county_id' => '103', 'value' => 'PEREZ MILLAN'),
                array('id' => 709, 'county_id' => '103', 'value' => 'RAMALLO'),
                array('id' => 710, 'county_id' => '103', 'value' => 'VILLA GENERAL SAVIO'),
                array('id' => 711, 'county_id' => '103', 'value' => 'VILLA RAMALLO'),
                array('id' => 712, 'county_id' => '104', 'value' => 'RAUCH'),
                array('id' => 713, 'county_id' => '105', 'value' => 'AMERICA'),
                array('id' => 714, 'county_id' => '105', 'value' => 'FORTIN OLAVARRIA'),
                array('id' => 715, 'county_id' => '105', 'value' => 'GONZALEZ MORENO'),
                array('id' => 716, 'county_id' => '105', 'value' => 'MIRA PAMPA'),
                array('id' => 717, 'county_id' => '105', 'value' => 'ROOSEVELT'),
                array('id' => 718, 'county_id' => '105', 'value' => 'SAN MAURICIO'),
                array('id' => 719, 'county_id' => '105', 'value' => 'SANSINENA'),
                array('id' => 720, 'county_id' => '105', 'value' => 'SUNDBLAD'),
                array('id' => 721, 'county_id' => '106', 'value' => 'BARRIO LAS MARGARITAS'),
                array('id' => 722, 'county_id' => '106', 'value' => 'ESTACION SOL DE MAYO'),
                array('id' => 723, 'county_id' => '106', 'value' => 'LA BEBA'),
                array('id' => 724, 'county_id' => '106', 'value' => 'LAS CARABELAS'),
                array('id' => 725, 'county_id' => '106', 'value' => 'LOS INDIOS'),
                array('id' => 726, 'county_id' => '106', 'value' => 'RAFAEL OBLIGADO'),
                array('id' => 727, 'county_id' => '106', 'value' => 'ROBERTO CANO'),
                array('id' => 728, 'county_id' => '106', 'value' => 'ROJAS'),
                array('id' => 729, 'county_id' => '106', 'value' => 'VILLA MANUEL POMAR'),
                array('id' => 730, 'county_id' => '106', 'value' => 'VILLA PARQUE CECIR'),
                array('id' => 731, 'county_id' => '107', 'value' => 'CARLOS BEGUERIE'),
                array('id' => 732, 'county_id' => '107', 'value' => 'ROQUE PEREZ'),
                array('id' => 733, 'county_id' => '108', 'value' => 'ARROYO CORTO'),
                array('id' => 734, 'county_id' => '108', 'value' => 'COLONIA SAN MARTIN'),
                array('id' => 735, 'county_id' => '108', 'value' => 'DUFAUR'),
                array('id' => 736, 'county_id' => '108', 'value' => 'ESPARTILLAR (E)'),
                array('id' => 737, 'county_id' => '108', 'value' => 'GOYENA'),
                array('id' => 738, 'county_id' => '108', 'value' => 'LAS ENCADENADAS'),
                array('id' => 739, 'county_id' => '108', 'value' => 'PIGUE'),
                array('id' => 740, 'county_id' => '108', 'value' => 'SAAVEDRA'),
                array('id' => 741, 'county_id' => '109', 'value' => 'ALVAREZ DE TOLEDO'),
                array('id' => 742, 'county_id' => '109', 'value' => 'CAZON'),
                array('id' => 743, 'county_id' => '109', 'value' => 'DEL CARRIL'),
                array('id' => 744, 'county_id' => '109', 'value' => 'POLVAREDAS'),
                array('id' => 745, 'county_id' => '109', 'value' => 'SALADILLO'),
                array('id' => 746, 'county_id' => '110', 'value' => 'QUENUMA'),
                array('id' => 747, 'county_id' => '110', 'value' => 'SALLIQUELO'),
                array('id' => 748, 'county_id' => '111', 'value' => 'ARROYO DULCE'),
                array('id' => 749, 'county_id' => '111', 'value' => 'BERDIER'),
                array('id' => 750, 'county_id' => '111', 'value' => 'GAHAN'),
                array('id' => 751, 'county_id' => '111', 'value' => 'INES INDART'),
                array('id' => 752, 'county_id' => '111', 'value' => 'LA INVENCIBLE'),
                array('id' => 753, 'county_id' => '111', 'value' => 'SALTO'),
                array('id' => 754, 'county_id' => '112', 'value' => 'AZCUENAGA'),
                array('id' => 755, 'county_id' => '112', 'value' => 'CULULLU'),
                array('id' => 756, 'county_id' => '112', 'value' => 'FRANKLIN'),
                array('id' => 757, 'county_id' => '112', 'value' => 'SAN ANDRES DE GILES'),
                array('id' => 758, 'county_id' => '112', 'value' => 'SOLIS'),
                array('id' => 759, 'county_id' => '112', 'value' => 'VILLA ESPIL'),
                array('id' => 760, 'county_id' => '112', 'value' => 'VILLA RUIZ'),
                array('id' => 761, 'county_id' => '113', 'value' => 'DUGGAN'),
                array('id' => 762, 'county_id' => '113', 'value' => 'SAN ANTONIO DE ARECO'),
                array('id' => 763, 'county_id' => '113', 'value' => 'VILLA LIA'),
                array('id' => 764, 'county_id' => '114', 'value' => 'BALNEARIO SAN CAYETANO'),
                array('id' => 765, 'county_id' => '114', 'value' => 'OCHANDIO'),
                array('id' => 766, 'county_id' => '114', 'value' => 'SAN CAYETANO'),
                array('id' => 767, 'county_id' => '115', 'value' => 'SAN FERNANDO'),
                array('id' => 768, 'county_id' => '115', 'value' => 'VICTORIA'),
                array('id' => 769, 'county_id' => '115', 'value' => 'VIRREYES'),
                array('id' => 770, 'county_id' => '116', 'value' => 'ACASSUSO'),
                array('id' => 771, 'county_id' => '116', 'value' => 'BECCAR'),
                array('id' => 772, 'county_id' => '116', 'value' => 'BOULOGNE SUR MER'),
                array('id' => 773, 'county_id' => '116', 'value' => 'MARTINEZ'),
                array('id' => 774, 'county_id' => '116', 'value' => 'SAN ISIDRO'),
                array('id' => 775, 'county_id' => '116', 'value' => 'VILLA ADELINA'),
                array('id' => 776, 'county_id' => '117', 'value' => 'BELLA VISTA'),
                array('id' => 777, 'county_id' => '117', 'value' => 'CAMPO DE MAYO'),
                array('id' => 778, 'county_id' => '117', 'value' => 'MUÑIZ'),
                array('id' => 779, 'county_id' => '117', 'value' => 'SAN MIGUEL'),
                array('id' => 780, 'county_id' => '118', 'value' => 'CAMPOS SALLES'),
                array('id' => 781, 'county_id' => '118', 'value' => 'CONESA'),
                array('id' => 782, 'county_id' => '118', 'value' => 'EREZCANO'),
                array('id' => 783, 'county_id' => '118', 'value' => 'GENERAL ROJO'),
                array('id' => 784, 'county_id' => '118', 'value' => 'LA EMILIA'),
                array('id' => 785, 'county_id' => '118', 'value' => 'SAN NICOLAS DE LOS ARROYOS'),
                array('id' => 786, 'county_id' => '118', 'value' => 'VILLA CAMPI'),
                array('id' => 787, 'county_id' => '118', 'value' => 'VILLA CANTO'),
                array('id' => 788, 'county_id' => '118', 'value' => 'VILLA ESPERANZA'),
                array('id' => 789, 'county_id' => '118', 'value' => 'VILLA RICCIO'),
                array('id' => 790, 'county_id' => '119', 'value' => 'GOBERNADOR CASTRO'),
                array('id' => 791, 'county_id' => '119', 'value' => 'INGENIERO MONETA'),
                array('id' => 792, 'county_id' => '119', 'value' => 'OBLIGADO'),
                array('id' => 793, 'county_id' => '119', 'value' => 'PUEBLO DOYLE'),
                array('id' => 794, 'county_id' => '119', 'value' => 'RIO TALA'),
                array('id' => 795, 'county_id' => '119', 'value' => 'SAN PEDRO'),
                array('id' => 796, 'county_id' => '119', 'value' => 'SANTA LUCIA'),
                array('id' => 797, 'county_id' => '120', 'value' => 'ALEJANDRO KORN'),
                array('id' => 798, 'county_id' => '120', 'value' => 'DOMSELAAR'),
                array('id' => 799, 'county_id' => '120', 'value' => 'SAN VICENTE'),
                array('id' => 800, 'county_id' => '121', 'value' => 'GENERAL RIVAS'),
                array('id' => 801, 'county_id' => '121', 'value' => 'SUIPACHA'),
                array('id' => 802, 'county_id' => '122', 'value' => 'DE LA CANAL'),
                array('id' => 803, 'county_id' => '122', 'value' => 'GARDEY'),
                array('id' => 804, 'county_id' => '122', 'value' => 'MARIA IGNACIA'),
                array('id' => 805, 'county_id' => '122', 'value' => 'TANDIL'),
                array('id' => 806, 'county_id' => '123', 'value' => 'CROTTO'),
                array('id' => 807, 'county_id' => '123', 'value' => 'TAPALQUE'),
                array('id' => 808, 'county_id' => '123', 'value' => 'VELLOSO'),
                array('id' => 809, 'county_id' => '124', 'value' => 'BENAVIDEZ'),
                array('id' => 810, 'county_id' => '124', 'value' => 'DIQUE LUJAN'),
                array('id' => 811, 'county_id' => '124', 'value' => 'DON TORCUATO ESTE'),
                array('id' => 812, 'county_id' => '124', 'value' => 'DON TORCUATO OESTE'),
                array('id' => 813, 'county_id' => '124', 'value' => 'EL TALAR'),
                array('id' => 814, 'county_id' => '124', 'value' => 'GENERAL PACHECO'),
                array('id' => 815, 'county_id' => '124', 'value' => 'LOS TRONCOS DEL TALAR'),
                array('id' => 816, 'county_id' => '124', 'value' => 'RICARDO ROJAS'),
                array('id' => 817, 'county_id' => '124', 'value' => 'RINCON DE MILBERG'),
                array('id' => 818, 'county_id' => '124', 'value' => 'TIGRE'),
                array('id' => 819, 'county_id' => '125', 'value' => 'GENERAL CONESA'),
                array('id' => 820, 'county_id' => '126', 'value' => 'CHASICO'),
                array('id' => 821, 'county_id' => '126', 'value' => 'SALDUNGARAY'),
                array('id' => 822, 'county_id' => '126', 'value' => 'SIERRA DE LA VENTANA'),
                array('id' => 823, 'county_id' => '126', 'value' => 'TORNQUIST'),
                array('id' => 824, 'county_id' => '126', 'value' => 'TRES PICOS'),
                array('id' => 825, 'county_id' => '126', 'value' => 'VILLA SERRANA LA GRUTA'),
                array('id' => 826, 'county_id' => '126', 'value' => 'VILLA VENTANA'),
                array('id' => 827, 'county_id' => '127', 'value' => '30 DE AGOSTO'),
                array('id' => 828, 'county_id' => '127', 'value' => 'BERUTTI'),
                array('id' => 829, 'county_id' => '127', 'value' => 'GIRODIAS'),
                array('id' => 830, 'county_id' => '127', 'value' => 'LA CARRETA'),
                array('id' => 831, 'county_id' => '127', 'value' => 'TRENQUE LAUQUEN'),
                array('id' => 832, 'county_id' => '127', 'value' => 'TRONGE'),
                array('id' => 833, 'county_id' => '128', 'value' => 'BALNEARIO ORENSE'),
                array('id' => 834, 'county_id' => '128', 'value' => 'CLAROMECO'),
                array('id' => 835, 'county_id' => '128', 'value' => 'COPETONAS'),
                array('id' => 836, 'county_id' => '128', 'value' => 'DUNAMAR'),
                array('id' => 837, 'county_id' => '128', 'value' => 'LIN CALEL'),
                array('id' => 838, 'county_id' => '128', 'value' => 'MICAELA CASCALLARES'),
                array('id' => 839, 'county_id' => '128', 'value' => 'ORENSE'),
                array('id' => 840, 'county_id' => '128', 'value' => 'RETA'),
                array('id' => 841, 'county_id' => '128', 'value' => 'SAN FRANCISCO DE BELLOCQ'),
                array('id' => 842, 'county_id' => '128', 'value' => 'SAN MAYOL'),
                array('id' => 843, 'county_id' => '128', 'value' => 'TRES ARROYOS'),
                array('id' => 844, 'county_id' => '128', 'value' => 'VILLA RODRIGUEZ'),
                array('id' => 845, 'county_id' => '129', 'value' => '11 DE SEPTIEMBRE'),
                array('id' => 846, 'county_id' => '129', 'value' => 'CASEROS'),
                array('id' => 847, 'county_id' => '129', 'value' => 'CHURRUCA'),
                array('id' => 848, 'county_id' => '129', 'value' => 'CIUDAD JARDIN LOMAS DEL PALOMAR'),
                array('id' => 849, 'county_id' => '129', 'value' => 'CIUDADELA'),
                array('id' => 850, 'county_id' => '129', 'value' => 'EL LIBERTADOR'),
                array('id' => 851, 'county_id' => '129', 'value' => 'JOSE INGENIEROS'),
                array('id' => 852, 'county_id' => '129', 'value' => 'LOMA HERMOSA'),
                array('id' => 853, 'county_id' => '129', 'value' => 'MARTIN CORONADO'),
                array('id' => 854, 'county_id' => '129', 'value' => 'PABLO PODESTA'),
                array('id' => 855, 'county_id' => '129', 'value' => 'REMEDIOS DE ESCALADA'),
                array('id' => 856, 'county_id' => '129', 'value' => 'SAENZ PEÑA'),
                array('id' => 857, 'county_id' => '129', 'value' => 'SANTOS LUGARES'),
                array('id' => 858, 'county_id' => '129', 'value' => 'VILLA BOSCH (EST. JUAN MARIA BOSCH)'),
                array('id' => 859, 'county_id' => '129', 'value' => 'VILLA RAFFO'),
                array('id' => 860, 'county_id' => '130', 'value' => 'INGENIERO THOMPSON'),
                array('id' => 861, 'county_id' => '130', 'value' => 'TRES LOMAS'),
                array('id' => 862, 'county_id' => '131', 'value' => 'CARAPACHAY'),
                array('id' => 863, 'county_id' => '131', 'value' => 'FLORIDA'),
                array('id' => 864, 'county_id' => '131', 'value' => 'FLORIDA OESTE'),
                array('id' => 865, 'county_id' => '131', 'value' => 'LA LUCILA'),
                array('id' => 866, 'county_id' => '131', 'value' => 'MUNRO'),
                array('id' => 867, 'county_id' => '131', 'value' => 'OLIVOS'),
                array('id' => 868, 'county_id' => '131', 'value' => 'VICENTE LOPEZ'),
                array('id' => 869, 'county_id' => '131', 'value' => 'VILLA ADELINA'),
                array('id' => 870, 'county_id' => '131', 'value' => 'VILLA MARTELLI'),
                array('id' => 871, 'county_id' => '132', 'value' => 'MAR AZUL'),
                array('id' => 872, 'county_id' => '132', 'value' => 'MAR DE LAS PAMPAS'),
                array('id' => 873, 'county_id' => '132', 'value' => 'VILLA GESELL'),
                array('id' => 874, 'county_id' => '133', 'value' => 'ARGERICH'),
                array('id' => 875, 'county_id' => '133', 'value' => 'COLONIA SAN ADOLFO'),
                array('id' => 876, 'county_id' => '133', 'value' => 'COUNTRY LOS MEDANOS'),
                array('id' => 877, 'county_id' => '133', 'value' => 'HILARIO ASCASUBI'),
                array('id' => 878, 'county_id' => '133', 'value' => 'JUAN COUSTE'),
                array('id' => 879, 'county_id' => '133', 'value' => 'MAYOR BURATOVICH'),
                array('id' => 880, 'county_id' => '133', 'value' => 'MEDANOS'),
                array('id' => 881, 'county_id' => '133', 'value' => 'PEDRO LURO'),
                array('id' => 882, 'county_id' => '133', 'value' => 'TENIENTE ORIGONE'),
                array('id' => 883, 'county_id' => '134', 'value' => 'BARRIO SAAVEDRA'),
                array('id' => 884, 'county_id' => '134', 'value' => 'COUNTRY CLUB EL CASCO'),
                array('id' => 885, 'county_id' => '134', 'value' => 'ESCALADA'),
                array('id' => 886, 'county_id' => '134', 'value' => 'LIMA'),
                array('id' => 887, 'county_id' => '134', 'value' => 'ZARATE'),
                array('id' => 888, 'county_id' => '135', 'value' => 'CHUCHUCARUANA'),
                array('id' => 889, 'county_id' => '135', 'value' => 'COLPES'),
                array('id' => 890, 'county_id' => '135', 'value' => 'EL BOLSON'),
                array('id' => 891, 'county_id' => '135', 'value' => 'EL RODEO'),
                array('id' => 892, 'county_id' => '135', 'value' => 'HUAYCAMA'),
                array('id' => 893, 'county_id' => '135', 'value' => 'LA PUERTA'),
                array('id' => 894, 'county_id' => '135', 'value' => 'LAS CHACRITAS'),
                array('id' => 895, 'county_id' => '135', 'value' => 'LAS JUNTAS'),
                array('id' => 896, 'county_id' => '135', 'value' => 'LOS CASTILLOS'),
                array('id' => 897, 'county_id' => '135', 'value' => 'LOS TALAS'),
                array('id' => 898, 'county_id' => '135', 'value' => 'LOS VARELA'),
                array('id' => 899, 'county_id' => '135', 'value' => 'SINGUIL'),
                array('id' => 900, 'county_id' => '136', 'value' => 'ANCASTI'),
                array('id' => 901, 'county_id' => '136', 'value' => 'ANQUINCILA'),
                array('id' => 902, 'county_id' => '136', 'value' => 'LA CANDELARIA'),
                array('id' => 903, 'county_id' => '136', 'value' => 'LA MAJADA'),
                array('id' => 904, 'county_id' => '137', 'value' => 'ACONQUIJA'),
                array('id' => 905, 'county_id' => '137', 'value' => 'ALTO DE LAS JUNTAS'),
                array('id' => 906, 'county_id' => '137', 'value' => 'AMANAO'),
                array('id' => 907, 'county_id' => '137', 'value' => 'ANDALGALA'),
                array('id' => 908, 'county_id' => '137', 'value' => 'BUENA VISTA'),
                array('id' => 909, 'county_id' => '137', 'value' => 'CHAQUIAGO'),
                array('id' => 910, 'county_id' => '137', 'value' => 'CHOYA'),
                array('id' => 911, 'county_id' => '137', 'value' => 'EL ALAMITO'),
                array('id' => 912, 'county_id' => '137', 'value' => 'EL LINDERO'),
                array('id' => 913, 'county_id' => '137', 'value' => 'EL POTRERO'),
                array('id' => 914, 'county_id' => '137', 'value' => 'LA AGUADA'),
                array('id' => 915, 'county_id' => '137', 'value' => 'LA MESADA'),
                array('id' => 916, 'county_id' => '138', 'value' => 'ANTOFAGASTA DE LA SIERRA'),
                array('id' => 917, 'county_id' => '138', 'value' => 'ANTOFALLA'),
                array('id' => 918, 'county_id' => '138', 'value' => 'EL PEÑON'),
                array('id' => 919, 'county_id' => '138', 'value' => 'LOS NACIMIENTOS'),
                array('id' => 920, 'county_id' => '139', 'value' => 'BARRANCA LARGA'),
                array('id' => 921, 'county_id' => '139', 'value' => 'BELEN'),
                array('id' => 922, 'county_id' => '139', 'value' => 'CONDOR HUASI'),
                array('id' => 923, 'county_id' => '139', 'value' => 'CORRAL QUEMADO'),
                array('id' => 924, 'county_id' => '139', 'value' => 'EL DURAZNO'),
                array('id' => 925, 'county_id' => '139', 'value' => 'FARALLON NEGRO'),
                array('id' => 926, 'county_id' => '139', 'value' => 'HUALFIN'),
                array('id' => 927, 'county_id' => '139', 'value' => 'JACIPUNCO'),
                array('id' => 928, 'county_id' => '139', 'value' => 'LA PUNTILLA'),
                array('id' => 929, 'county_id' => '139', 'value' => 'LAS JUNTAS'),
                array('id' => 930, 'county_id' => '139', 'value' => 'LONDRES'),
                array('id' => 931, 'county_id' => '139', 'value' => 'LOS NACIMIENTOS'),
                array('id' => 932, 'county_id' => '139', 'value' => 'PUERTA DE CORRAL QUEMADO'),
                array('id' => 933, 'county_id' => '139', 'value' => 'PUERTA DE SAN JOSE'),
                array('id' => 934, 'county_id' => '139', 'value' => 'VILLA VIL'),
                array('id' => 935, 'county_id' => '140', 'value' => 'ADOLFO E. CARRANZA'),
                array('id' => 936, 'county_id' => '140', 'value' => 'BALDE DE LA PUNTA'),
                array('id' => 937, 'county_id' => '140', 'value' => 'CAPAYAN'),
                array('id' => 938, 'county_id' => '140', 'value' => 'CHUMBICHA'),
                array('id' => 939, 'county_id' => '140', 'value' => 'COLONIA DEL VALLE'),
                array('id' => 940, 'county_id' => '140', 'value' => 'COLONIA NUEVA CONETA'),
                array('id' => 941, 'county_id' => '140', 'value' => 'CONCEPCION'),
                array('id' => 942, 'county_id' => '140', 'value' => 'CONETA'),
                array('id' => 943, 'county_id' => '140', 'value' => 'EL BAÑADO'),
                array('id' => 944, 'county_id' => '140', 'value' => 'HUILLAPIMA'),
                array('id' => 945, 'county_id' => '140', 'value' => 'LOS ANGELES'),
                array('id' => 946, 'county_id' => '140', 'value' => 'LOS ANGELES NORTE'),
                array('id' => 947, 'county_id' => '140', 'value' => 'LOS ANGELES SUR'),
                array('id' => 948, 'county_id' => '140', 'value' => 'MIRAFLORES'),
                array('id' => 949, 'county_id' => '140', 'value' => 'SAN MARTIN'),
                array('id' => 950, 'county_id' => '140', 'value' => 'SAN PABLO'),
                array('id' => 951, 'county_id' => '140', 'value' => 'SAN PEDRO'),
                array('id' => 952, 'county_id' => '141', 'value' => 'EL PANTANILLO'),
                array('id' => 953, 'county_id' => '141', 'value' => 'SAN FERNANDO DEL VALLE DE CATAMARCA'),
                array('id' => 954, 'county_id' => '142', 'value' => 'EL ALTO'),
                array('id' => 955, 'county_id' => '142', 'value' => 'GUAYAMBA'),
                array('id' => 956, 'county_id' => '142', 'value' => 'INFANZON'),
                array('id' => 957, 'county_id' => '142', 'value' => 'LOS CORRALES'),
                array('id' => 958, 'county_id' => '142', 'value' => 'TAPSO'),
                array('id' => 959, 'county_id' => '142', 'value' => 'VILISMAN'),
                array('id' => 960, 'county_id' => '143', 'value' => 'COLLAGASTA'),
                array('id' => 961, 'county_id' => '143', 'value' => 'EL HUECO'),
                array('id' => 962, 'county_id' => '143', 'value' => 'LA CARRERA'),
                array('id' => 963, 'county_id' => '143', 'value' => 'LA FALDA DE SAN ANTONIO'),
                array('id' => 964, 'county_id' => '143', 'value' => 'LA TERCENA'),
                array('id' => 965, 'county_id' => '143', 'value' => 'POMANCILLO ESTE'),
                array('id' => 966, 'county_id' => '143', 'value' => 'POMANCILLO OESTE'),
                array('id' => 967, 'county_id' => '143', 'value' => 'SAN ANTONIO'),
                array('id' => 968, 'county_id' => '143', 'value' => 'SAN JOSE'),
                array('id' => 969, 'county_id' => '143', 'value' => 'VILLA LAS PIRQUITAS'),
                array('id' => 970, 'county_id' => '144', 'value' => 'CASA DE PIEDRA'),
                array('id' => 971, 'county_id' => '144', 'value' => 'EL AYBAL'),
                array('id' => 972, 'county_id' => '144', 'value' => 'EL BAÑADO'),
                array('id' => 973, 'county_id' => '144', 'value' => 'EL DIVISADERO'),
                array('id' => 974, 'county_id' => '144', 'value' => 'EL QUIMILO'),
                array('id' => 975, 'county_id' => '144', 'value' => 'ESQUIU'),
                array('id' => 976, 'county_id' => '144', 'value' => 'ICAÑO'),
                array('id' => 977, 'county_id' => '144', 'value' => 'LA DORADA'),
                array('id' => 978, 'county_id' => '144', 'value' => 'LA GUARDIA'),
                array('id' => 979, 'county_id' => '144', 'value' => 'LAS ESQUINAS'),
                array('id' => 980, 'county_id' => '144', 'value' => 'LAS PALMITAS'),
                array('id' => 981, 'county_id' => '144', 'value' => 'QUIROS'),
                array('id' => 982, 'county_id' => '144', 'value' => 'RAMBLONES'),
                array('id' => 983, 'county_id' => '144', 'value' => 'RECREO'),
                array('id' => 984, 'county_id' => '144', 'value' => 'SAN ANTONIO'),
                array('id' => 985, 'county_id' => '145', 'value' => 'AMADORES'),
                array('id' => 986, 'county_id' => '145', 'value' => 'EL ROSARIO'),
                array('id' => 987, 'county_id' => '145', 'value' => 'LA BAJADA'),
                array('id' => 988, 'county_id' => '145', 'value' => 'LA HIGUERA'),
                array('id' => 989, 'county_id' => '145', 'value' => 'LA MERCED'),
                array('id' => 990, 'county_id' => '145', 'value' => 'LA VIÑA'),
                array('id' => 991, 'county_id' => '145', 'value' => 'LAS LAJAS'),
                array('id' => 992, 'county_id' => '145', 'value' => 'MONTE POTRERO'),
                array('id' => 993, 'county_id' => '145', 'value' => 'PALO LABRADO'),
                array('id' => 994, 'county_id' => '145', 'value' => 'SAN ANTONIO'),
                array('id' => 995, 'county_id' => '145', 'value' => 'VILLA DE BALCOZNA'),
                array('id' => 996, 'county_id' => '146', 'value' => 'APOYACO'),
                array('id' => 997, 'county_id' => '146', 'value' => 'COLANA'),
                array('id' => 998, 'county_id' => '146', 'value' => 'COLPES'),
                array('id' => 999, 'county_id' => '146', 'value' => 'EL PAJONAL'),
                array('id' => 1000, 'county_id' => '146', 'value' => 'JOYANGO')
                )
            );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cities');
    }
}
