<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddRecordsToCitiesTable3 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('cities')->insert(
            array(
                array('id' => 3001, 'county_id' => '398', 'value' => 'BARRIO EL MARUCHITO'),
                array('id' => 3002, 'county_id' => '398', 'value' => 'BARRIO EL PETROLEO'),
                array('id' => 3003, 'county_id' => '398', 'value' => 'BARRIO EL TREINTA'),
                array('id' => 3004, 'county_id' => '398', 'value' => 'BARRIO EMERGENTE'),
                array('id' => 3005, 'county_id' => '398', 'value' => 'BARRIO FRONTERA'),
                array('id' => 3006, 'county_id' => '398', 'value' => 'BARRIO GORETTI'),
                array('id' => 3007, 'county_id' => '398', 'value' => 'BARRIO GUERRICO'),
                array('id' => 3008, 'county_id' => '398', 'value' => 'BARRIO ISLA 10'),
                array('id' => 3009, 'county_id' => '398', 'value' => 'BARRIO LA BARDA'),
                array('id' => 3010, 'county_id' => '398', 'value' => 'BARRIO LA COSTA'),
                array('id' => 3011, 'county_id' => '398', 'value' => 'BARRIO LA DEFENSA'),
                array('id' => 3012, 'county_id' => '398', 'value' => 'BARRIO LA HERRADURA'),
                array('id' => 3013, 'county_id' => '398', 'value' => 'BARRIO LA LOR'),
                array('id' => 3014, 'county_id' => '398', 'value' => 'BARRIO LA RIBERA - BARRIO APYCAR'),
                array('id' => 3015, 'county_id' => '398', 'value' => 'BARRIO LAS ANGUSTIAS'),
                array('id' => 3016, 'county_id' => '398', 'value' => 'BARRIO LUISILLO'),
                array('id' => 3017, 'county_id' => '398', 'value' => 'BARRIO MAR DEL PLATA'),
                array('id' => 3018, 'county_id' => '398', 'value' => 'BARRIO MARIA ELVIRA'),
                array('id' => 3019, 'county_id' => '398', 'value' => 'BARRIO MOÑO AZUL'),
                array('id' => 3020, 'county_id' => '398', 'value' => 'BARRIO MOSCONI'),
                array('id' => 3021, 'county_id' => '398', 'value' => 'BARRIO NORTE'),
                array('id' => 3022, 'county_id' => '398', 'value' => 'BARRIO PINAR'),
                array('id' => 3023, 'county_id' => '398', 'value' => 'BARRIO PINO AZUL'),
                array('id' => 3024, 'county_id' => '398', 'value' => 'BARRIO PORVENIR'),
                array('id' => 3025, 'county_id' => '398', 'value' => 'BARRIO PRESIDENTE PERON'),
                array('id' => 3026, 'county_id' => '398', 'value' => 'BARRIO PUENTE 83'),
                array('id' => 3027, 'county_id' => '398', 'value' => 'BARRIO PUENTE DE MADERA'),
                array('id' => 3028, 'county_id' => '398', 'value' => 'BARRIO SANTA RITA'),
                array('id' => 3029, 'county_id' => '398', 'value' => 'BARRIO TRES LUCES'),
                array('id' => 3030, 'county_id' => '398', 'value' => 'BARRIO UNION'),
                array('id' => 3031, 'county_id' => '398', 'value' => 'CATRIEL'),
                array('id' => 3032, 'county_id' => '398', 'value' => 'CERVANTES'),
                array('id' => 3033, 'county_id' => '398', 'value' => 'CHICHINALES'),
                array('id' => 3034, 'county_id' => '398', 'value' => 'CINCO SALTOS'),
                array('id' => 3035, 'county_id' => '398', 'value' => 'CIPOLLETTI'),
                array('id' => 3036, 'county_id' => '398', 'value' => 'COLONIA FATIMA'),
                array('id' => 3037, 'county_id' => '398', 'value' => 'CONTRALMIRANTE CORDERO'),
                array('id' => 3038, 'county_id' => '398', 'value' => 'FERRI'),
                array('id' => 3039, 'county_id' => '398', 'value' => 'GENERAL ENRIQUE GODOY'),
                array('id' => 3040, 'county_id' => '398', 'value' => 'GENERAL FERNANDEZ ORO'),
                array('id' => 3041, 'county_id' => '398', 'value' => 'GENERAL ROCA'),
                array('id' => 3042, 'county_id' => '398', 'value' => 'INGENIERO LUIS A. HUERGO'),
                array('id' => 3043, 'county_id' => '398', 'value' => 'INGENIERO OTTO KRAUSE'),
                array('id' => 3044, 'county_id' => '398', 'value' => 'MAINQUE'),
                array('id' => 3045, 'county_id' => '398', 'value' => 'PASO CORDOVA'),
                array('id' => 3046, 'county_id' => '398', 'value' => 'PENINSULA RUCA CO'),
                array('id' => 3047, 'county_id' => '398', 'value' => 'SANTA LUCIA'),
                array('id' => 3048, 'county_id' => '398', 'value' => 'SARGENTO VIDAL'),
                array('id' => 3049, 'county_id' => '398', 'value' => 'TRES LUCES'),
                array('id' => 3050, 'county_id' => '398', 'value' => 'VILLA ALBERDI'),
                array('id' => 3051, 'county_id' => '398', 'value' => 'VILLA DEL PARQUE'),
                array('id' => 3052, 'county_id' => '398', 'value' => 'VILLA MANZANO'),
                array('id' => 3053, 'county_id' => '398', 'value' => 'VILLA REGINA'),
                array('id' => 3054, 'county_id' => '398', 'value' => 'VILLA SAN ISIDRO'),
                array('id' => 3055, 'county_id' => '399', 'value' => 'BARRIO ESPERANZA'),
                array('id' => 3056, 'county_id' => '399', 'value' => 'COLONIA JULIA Y ECHARREN'),
                array('id' => 3057, 'county_id' => '399', 'value' => 'JUVENTUD UNIDA'),
                array('id' => 3058, 'county_id' => '399', 'value' => 'PICHI MAHUIDA'),
                array('id' => 3059, 'county_id' => '399', 'value' => 'RIO COLORADO'),
                array('id' => 3060, 'county_id' => '399', 'value' => 'SALTO ANDERSEN'),
                array('id' => 3061, 'county_id' => '400', 'value' => 'ÑIRIHUAU'),
                array('id' => 3062, 'county_id' => '400', 'value' => 'CAÑADON CHILENO'),
                array('id' => 3063, 'county_id' => '400', 'value' => 'COMALLO'),
                array('id' => 3064, 'county_id' => '400', 'value' => 'DINA HUAPI'),
                array('id' => 3065, 'county_id' => '400', 'value' => 'LAGUNA BLANCA'),
                array('id' => 3066, 'county_id' => '400', 'value' => 'PILCANIYEU'),
                array('id' => 3067, 'county_id' => '400', 'value' => 'PILQUINIYEU DEL LIMAY'),
                array('id' => 3068, 'county_id' => '400', 'value' => 'VILLA LLANQUIN'),
                array('id' => 3069, 'county_id' => '401', 'value' => 'ESTACION EMPALME'),
                array('id' => 3070, 'county_id' => '401', 'value' => 'LAS GRUTAS'),
                array('id' => 3071, 'county_id' => '401', 'value' => 'PLAYAS DORADAS'),
                array('id' => 3072, 'county_id' => '401', 'value' => 'PUERTO SAN ANTONIO ESTE'),
                array('id' => 3073, 'county_id' => '401', 'value' => 'PUNTA COLORADA'),
                array('id' => 3074, 'county_id' => '401', 'value' => 'SACO VIEJO'),
                array('id' => 3075, 'county_id' => '401', 'value' => 'SAN ANTONIO OESTE'),
                array('id' => 3076, 'county_id' => '401', 'value' => 'SIERRA GRANDE'),
                array('id' => 3077, 'county_id' => '402', 'value' => 'AGUADA CECILIO'),
                array('id' => 3078, 'county_id' => '402', 'value' => 'ARROYO LOS BERROS'),
                array('id' => 3079, 'county_id' => '402', 'value' => 'ARROYO VENTANA'),
                array('id' => 3080, 'county_id' => '402', 'value' => 'NAHUEL NIYEU'),
                array('id' => 3081, 'county_id' => '402', 'value' => 'SIERRA PAILEMAN'),
                array('id' => 3082, 'county_id' => '402', 'value' => 'VALCHETA'),
                array('id' => 3083, 'county_id' => '403', 'value' => 'APOLINARIO SARAVIA'),
                array('id' => 3084, 'county_id' => '403', 'value' => 'CEIBALITO'),
                array('id' => 3085, 'county_id' => '403', 'value' => 'CENTRO 25 DE JUNIO'),
                array('id' => 3086, 'county_id' => '403', 'value' => 'CORONEL MOLLINEDO'),
                array('id' => 3087, 'county_id' => '403', 'value' => 'CORONEL OLLEROS'),
                array('id' => 3088, 'county_id' => '403', 'value' => 'EL QUEBRACHAL'),
                array('id' => 3089, 'county_id' => '403', 'value' => 'GAONA'),
                array('id' => 3090, 'county_id' => '403', 'value' => 'GENERAL PIZARRO'),
                array('id' => 3091, 'county_id' => '403', 'value' => 'JOAQUIN V. GONZALEZ'),
                array('id' => 3092, 'county_id' => '403', 'value' => 'LAS LAJITAS'),
                array('id' => 3093, 'county_id' => '403', 'value' => 'LUIS BURELA'),
                array('id' => 3094, 'county_id' => '403', 'value' => 'MACAPILLO'),
                array('id' => 3095, 'county_id' => '403', 'value' => 'NUESTRA SEÑORA DE TALAVERA'),
                array('id' => 3096, 'county_id' => '403', 'value' => 'PIQUETE CABADO'),
                array('id' => 3097, 'county_id' => '403', 'value' => 'RIO DEL VALLE'),
                array('id' => 3098, 'county_id' => '403', 'value' => 'TOLLOCHE'),
                array('id' => 3099, 'county_id' => '404', 'value' => 'CACHI'),
                array('id' => 3100, 'county_id' => '404', 'value' => 'PAYOGASTA'),
                array('id' => 3101, 'county_id' => '405', 'value' => 'CAFAYATE'),
                array('id' => 3102, 'county_id' => '405', 'value' => 'TOLOMBOM'),
                array('id' => 3103, 'county_id' => '406', 'value' => 'ATOCHA'),
                array('id' => 3104, 'county_id' => '406', 'value' => 'BARRIO SAN RAFAEL'),
                array('id' => 3105, 'county_id' => '406', 'value' => 'CC EL TIPAL'),
                array('id' => 3106, 'county_id' => '406', 'value' => 'CC LA ALMUDENA'),
                array('id' => 3107, 'county_id' => '406', 'value' => 'LA CIENAGA'),
                array('id' => 3108, 'county_id' => '406', 'value' => 'LAS COSTAS'),
                array('id' => 3109, 'county_id' => '406', 'value' => 'SALTA'),
                array('id' => 3110, 'county_id' => '406', 'value' => 'VILLA SAN LORENZO'),
                array('id' => 3111, 'county_id' => '407', 'value' => 'BARRIO EL CONGRESO'),
                array('id' => 3112, 'county_id' => '407', 'value' => 'BARRIO LAS TUNAS'),
                array('id' => 3113, 'county_id' => '407', 'value' => 'BARRIO LOS OLMOS'),
                array('id' => 3114, 'county_id' => '407', 'value' => 'BARRIO LOS PINARES'),
                array('id' => 3115, 'county_id' => '407', 'value' => 'CERRILLOS'),
                array('id' => 3116, 'county_id' => '407', 'value' => 'LA MERCED'),
                array('id' => 3117, 'county_id' => '407', 'value' => 'SAN AGUSTIN'),
                array('id' => 3118, 'county_id' => '407', 'value' => 'VILLA LOS ALAMOS'),
                array('id' => 3119, 'county_id' => '408', 'value' => 'BARRIO LA ROTONDA'),
                array('id' => 3120, 'county_id' => '408', 'value' => 'BARRIO SANTA TERESITA'),
                array('id' => 3121, 'county_id' => '408', 'value' => 'CHICOANA'),
                array('id' => 3122, 'county_id' => '408', 'value' => 'EL CARRIL'),
                array('id' => 3123, 'county_id' => '408', 'value' => 'LA MAROMA'),
                array('id' => 3124, 'county_id' => '409', 'value' => 'CAMPO SANTO'),
                array('id' => 3125, 'county_id' => '409', 'value' => 'COBOS'),
                array('id' => 3126, 'county_id' => '409', 'value' => 'EL BORDO'),
                array('id' => 3127, 'county_id' => '409', 'value' => 'GENERAL GUEMES'),
                array('id' => 3128, 'county_id' => '410', 'value' => 'AGUARAY'),
                array('id' => 3129, 'county_id' => '410', 'value' => 'BARRIO EL JARDIN DE SAN MARTIN'),
                array('id' => 3130, 'county_id' => '410', 'value' => 'BARRIO EL MILAGRO'),
                array('id' => 3131, 'county_id' => '410', 'value' => 'CAMPAMENTO VESPUCIO'),
                array('id' => 3132, 'county_id' => '410', 'value' => 'CAMPICHUELO'),
                array('id' => 3133, 'county_id' => '410', 'value' => 'CAMPO DURAN'),
                array('id' => 3134, 'county_id' => '410', 'value' => 'CAPIAZUTI'),
                array('id' => 3135, 'county_id' => '410', 'value' => 'CARBONCITO'),
                array('id' => 3136, 'county_id' => '410', 'value' => 'CORONEL CORNEJO'),
                array('id' => 3137, 'county_id' => '410', 'value' => 'DRAGONES'),
                array('id' => 3138, 'county_id' => '410', 'value' => 'EMBARCACION'),
                array('id' => 3139, 'county_id' => '410', 'value' => 'GENERAL BALLIVIAN'),
                array('id' => 3140, 'county_id' => '410', 'value' => 'GENERAL MOSCONI'),
                array('id' => 3141, 'county_id' => '410', 'value' => 'HICKMAN'),
                array('id' => 3142, 'county_id' => '410', 'value' => 'MISION CHAQUEÑA'),
                array('id' => 3143, 'county_id' => '410', 'value' => 'MISION EL CRUCE'),
                array('id' => 3144, 'county_id' => '410', 'value' => 'MISION KILOMETRO 6'),
                array('id' => 3145, 'county_id' => '410', 'value' => 'MISION TIERRAS FISCALES'),
                array('id' => 3146, 'county_id' => '410', 'value' => 'PACARA'),
                array('id' => 3147, 'county_id' => '410', 'value' => 'PADRE LOZANO'),
                array('id' => 3148, 'county_id' => '410', 'value' => 'PIQUIRENDA'),
                array('id' => 3149, 'county_id' => '410', 'value' => 'PROFESOR SALVADOR MAZZA'),
                array('id' => 3150, 'county_id' => '410', 'value' => 'RECAREDO'),
                array('id' => 3151, 'county_id' => '410', 'value' => 'TARTAGAL'),
                array('id' => 3152, 'county_id' => '410', 'value' => 'TOBANTIRENDA'),
                array('id' => 3153, 'county_id' => '410', 'value' => 'TRANQUITAS'),
                array('id' => 3154, 'county_id' => '410', 'value' => 'YACUY'),
                array('id' => 3155, 'county_id' => '411', 'value' => 'GUACHIPAS'),
                array('id' => 3156, 'county_id' => '412', 'value' => 'IRUYA'),
                array('id' => 3157, 'county_id' => '412', 'value' => 'ISLA DE CAÑAS'),
                array('id' => 3158, 'county_id' => '412', 'value' => 'PUEBLO VIEJO'),
                array('id' => 3159, 'county_id' => '413', 'value' => 'LA CALDERA'),
                array('id' => 3160, 'county_id' => '413', 'value' => 'VAQUEROS'),
                array('id' => 3161, 'county_id' => '414', 'value' => 'EL JARDIN'),
                array('id' => 3162, 'county_id' => '414', 'value' => 'EL TALA'),
                array('id' => 3163, 'county_id' => '414', 'value' => 'LA CANDELARIA'),
                array('id' => 3164, 'county_id' => '415', 'value' => 'COBRES'),
                array('id' => 3165, 'county_id' => '415', 'value' => 'LA POMA'),
                array('id' => 3166, 'county_id' => '416', 'value' => 'AMPASCACHI'),
                array('id' => 3167, 'county_id' => '416', 'value' => 'CABRA CORRAL'),
                array('id' => 3168, 'county_id' => '416', 'value' => 'CORONEL MOLDES'),
                array('id' => 3169, 'county_id' => '416', 'value' => 'LA VIÑA'),
                array('id' => 3170, 'county_id' => '416', 'value' => 'TALAPAMPA'),
                array('id' => 3171, 'county_id' => '417', 'value' => 'OLACAPATO'),
                array('id' => 3172, 'county_id' => '417', 'value' => 'SAN ANTONIO DE LOS COBRES'),
                array('id' => 3173, 'county_id' => '417', 'value' => 'SANTA ROSA DE LOS PASTOS GRANDES'),
                array('id' => 3174, 'county_id' => '417', 'value' => 'TOLAR GRANDE'),
                array('id' => 3175, 'county_id' => '418', 'value' => 'EL GALPON'),
                array('id' => 3176, 'county_id' => '418', 'value' => 'EL TUNAL'),
                array('id' => 3177, 'county_id' => '418', 'value' => 'LUMBRERAS'),
                array('id' => 3178, 'county_id' => '418', 'value' => 'METAN VIEJO'),
                array('id' => 3179, 'county_id' => '418', 'value' => 'RIO PIEDRAS'),
                array('id' => 3180, 'county_id' => '418', 'value' => 'SAN JOSE DE METAN'),
                array('id' => 3181, 'county_id' => '418', 'value' => 'SAN JOSE DE ORQUERA'),
                array('id' => 3182, 'county_id' => '419', 'value' => 'LA PUERTA'),
                array('id' => 3183, 'county_id' => '419', 'value' => 'MOLINOS'),
                array('id' => 3184, 'county_id' => '419', 'value' => 'SECLANTAS'),
                array('id' => 3185, 'county_id' => '420', 'value' => 'AGUAS BLANCAS'),
                array('id' => 3186, 'county_id' => '420', 'value' => 'COLONIA SANTA ROSA'),
                array('id' => 3187, 'county_id' => '420', 'value' => 'EL TABACAL'),
                array('id' => 3188, 'county_id' => '420', 'value' => 'HIPOLITO YRIGOYEN'),
                array('id' => 3189, 'county_id' => '420', 'value' => 'LA MISION'),
                array('id' => 3190, 'county_id' => '420', 'value' => 'PICHANAL'),
                array('id' => 3191, 'county_id' => '420', 'value' => 'SAN RAMON DE LA NUEVA ORAN'),
                array('id' => 3192, 'county_id' => '420', 'value' => 'URUNDEL'),
                array('id' => 3193, 'county_id' => '421', 'value' => 'ALTO DE LA SIERRA'),
                array('id' => 3194, 'county_id' => '421', 'value' => 'CAPITAN JUAN PAGE'),
                array('id' => 3195, 'county_id' => '421', 'value' => 'CORONEL JUAN SOLA'),
                array('id' => 3196, 'county_id' => '421', 'value' => 'HITO 1'),
                array('id' => 3197, 'county_id' => '421', 'value' => 'LA UNION'),
                array('id' => 3198, 'county_id' => '421', 'value' => 'LOS BLANCOS'),
                array('id' => 3199, 'county_id' => '421', 'value' => 'PLUMA DE PATO'),
                array('id' => 3200, 'county_id' => '421', 'value' => 'RIVADAVIA'),
                array('id' => 3201, 'county_id' => '421', 'value' => 'SANTA MARIA'),
                array('id' => 3202, 'county_id' => '421', 'value' => 'SANTA ROSA'),
                array('id' => 3203, 'county_id' => '421', 'value' => 'SANTA VICTORIA ESTE'),
                array('id' => 3204, 'county_id' => '422', 'value' => 'ANTILLA'),
                array('id' => 3205, 'county_id' => '422', 'value' => 'COPO QUILE'),
                array('id' => 3206, 'county_id' => '422', 'value' => 'EL NARANJO'),
                array('id' => 3207, 'county_id' => '422', 'value' => 'EL POTRERO'),
                array('id' => 3208, 'county_id' => '422', 'value' => 'ROSARIO DE LA FRONTERA'),
                array('id' => 3209, 'county_id' => '422', 'value' => 'SAN FELIPE'),
                array('id' => 3210, 'county_id' => '423', 'value' => 'CAMPO QUIJANO'),
                array('id' => 3211, 'county_id' => '423', 'value' => 'LA MERCED DEL ENCON'),
                array('id' => 3212, 'county_id' => '423', 'value' => 'LA SILLETA'),
                array('id' => 3213, 'county_id' => '423', 'value' => 'ROSARIO DE LERMA'),
                array('id' => 3214, 'county_id' => '424', 'value' => 'ANGASTACO'),
                array('id' => 3215, 'county_id' => '424', 'value' => 'ANIMANA'),
                array('id' => 3216, 'county_id' => '424', 'value' => 'EL BARRIAL'),
                array('id' => 3217, 'county_id' => '424', 'value' => 'SAN CARLOS'),
                array('id' => 3218, 'county_id' => '425', 'value' => 'ACOYTE'),
                array('id' => 3219, 'county_id' => '425', 'value' => 'CAMPO LA CRUZ'),
                array('id' => 3220, 'county_id' => '425', 'value' => 'LOS TOLDOS'),
                array('id' => 3221, 'county_id' => '425', 'value' => 'NAZARENO'),
                array('id' => 3222, 'county_id' => '425', 'value' => 'POSCAYA'),
                array('id' => 3223, 'county_id' => '425', 'value' => 'SAN MARCOS'),
                array('id' => 3224, 'county_id' => '425', 'value' => 'SANTA VICTORIA'),
                array('id' => 3225, 'county_id' => '426', 'value' => 'EL ENCON'),
                array('id' => 3226, 'county_id' => '426', 'value' => 'LA CHIMBERA'),
                array('id' => 3227, 'county_id' => '426', 'value' => 'TUPELI'),
                array('id' => 3228, 'county_id' => '426', 'value' => 'VILLA BORJAS'),
                array('id' => 3229, 'county_id' => '426', 'value' => 'VILLA EL TANGO'),
                array('id' => 3230, 'county_id' => '426', 'value' => 'VILLA SANTA ROSA'),
                array('id' => 3231, 'county_id' => '427', 'value' => '9 DE JULIO'),
                array('id' => 3232, 'county_id' => '427', 'value' => 'COLONIA FIORITO'),
                array('id' => 3233, 'county_id' => '427', 'value' => 'LAS CHACRITAS'),
                array('id' => 3234, 'county_id' => '428', 'value' => 'CAMPO AFUERA'),
                array('id' => 3235, 'county_id' => '428', 'value' => 'EL RINCON'),
                array('id' => 3236, 'county_id' => '428', 'value' => 'LA CAÑADA'),
                array('id' => 3237, 'county_id' => '428', 'value' => 'VILLA AMPACAMA'),
                array('id' => 3238, 'county_id' => '428', 'value' => 'VILLA GENERAL SAN MARTIN'),
                array('id' => 3239, 'county_id' => '429', 'value' => 'LAS TAPIAS'),
                array('id' => 3240, 'county_id' => '429', 'value' => 'VILLA EL SALVADOR'),
                array('id' => 3241, 'county_id' => '429', 'value' => 'VILLA SEFAIR (TALACASTO)'),
                array('id' => 3242, 'county_id' => '430', 'value' => 'BARREAL'),
                array('id' => 3243, 'county_id' => '430', 'value' => 'CALINGASTA'),
                array('id' => 3244, 'county_id' => '430', 'value' => 'TAMBERIAS'),
                array('id' => 3245, 'county_id' => '430', 'value' => 'VILLA PITUIL'),
                array('id' => 3246, 'county_id' => '431', 'value' => 'SAN JUAN'),
                array('id' => 3247, 'county_id' => '432', 'value' => 'BARRIO JUSTO P. CASTRO IV'),
                array('id' => 3248, 'county_id' => '432', 'value' => 'BERMEJO'),
                array('id' => 3249, 'county_id' => '432', 'value' => 'CAUCETE'),
                array('id' => 3250, 'county_id' => '432', 'value' => 'EL RINCON'),
                array('id' => 3251, 'county_id' => '432', 'value' => 'LAS TALAS'),
                array('id' => 3252, 'county_id' => '432', 'value' => 'LOS MEDANOS'),
                array('id' => 3253, 'county_id' => '432', 'value' => 'MARAYES'),
                array('id' => 3254, 'county_id' => '432', 'value' => 'PIE DE PALO'),
                array('id' => 3255, 'county_id' => '432', 'value' => 'VALLECITO'),
                array('id' => 3256, 'county_id' => '432', 'value' => 'VILLA INDEPENDENCIA'),
                array('id' => 3257, 'county_id' => '433', 'value' => 'CHIMBAS'),
                array('id' => 3258, 'county_id' => '433', 'value' => 'EL MOGOTE'),
                array('id' => 3259, 'county_id' => '433', 'value' => 'VILLA PAULA ALBARRACIN'),
                array('id' => 3260, 'county_id' => '434', 'value' => 'ANGUALASTO'),
                array('id' => 3261, 'county_id' => '434', 'value' => 'BELLA VISTA'),
                array('id' => 3262, 'county_id' => '434', 'value' => 'IGLESIA'),
                array('id' => 3263, 'county_id' => '434', 'value' => 'LAS FLORES'),
                array('id' => 3264, 'county_id' => '434', 'value' => 'PISMANTA'),
                array('id' => 3265, 'county_id' => '434', 'value' => 'RODEO'),
                array('id' => 3266, 'county_id' => '434', 'value' => 'TUDCUM'),
                array('id' => 3267, 'county_id' => '435', 'value' => 'EL FISCAL'),
                array('id' => 3268, 'county_id' => '435', 'value' => 'EL MEDANO'),
                array('id' => 3269, 'county_id' => '435', 'value' => 'GRAN CHINA'),
                array('id' => 3270, 'county_id' => '435', 'value' => 'HUACO'),
                array('id' => 3271, 'county_id' => '435', 'value' => 'LA FALDA'),
                array('id' => 3272, 'county_id' => '435', 'value' => 'MOGNA'),
                array('id' => 3273, 'county_id' => '435', 'value' => 'NIQUIVIL'),
                array('id' => 3274, 'county_id' => '435', 'value' => 'PAMPA VIEJA'),
                array('id' => 3275, 'county_id' => '435', 'value' => 'SAN ISIDRO'),
                array('id' => 3276, 'county_id' => '435', 'value' => 'SAN JOSE DE JACHAL'),
                array('id' => 3277, 'county_id' => '435', 'value' => 'TAMBERIAS'),
                array('id' => 3278, 'county_id' => '435', 'value' => 'VILLA MALVINAS ARGENTINAS'),
                array('id' => 3279, 'county_id' => '435', 'value' => 'VILLA MERCEDES'),
                array('id' => 3280, 'county_id' => '436', 'value' => 'BARRIO MUNICIPAL'),
                array('id' => 3281, 'county_id' => '436', 'value' => 'BARRIO RUTA 40'),
                array('id' => 3282, 'county_id' => '436', 'value' => 'CARPINTERIA'),
                array('id' => 3283, 'county_id' => '436', 'value' => 'LA RINCONADA'),
                array('id' => 3284, 'county_id' => '436', 'value' => 'LAS PIEDRITAS'),
                array('id' => 3285, 'county_id' => '436', 'value' => 'QUINTO CUARTEL'),
                array('id' => 3286, 'county_id' => '436', 'value' => 'VILLA ABERASTAIN'),
                array('id' => 3287, 'county_id' => '436', 'value' => 'VILLA BARBOZA'),
                array('id' => 3288, 'county_id' => '436', 'value' => 'VILLA CENTENARIO'),
                array('id' => 3289, 'county_id' => '436', 'value' => 'VILLA NACUSI'),
                array('id' => 3290, 'county_id' => '437', 'value' => 'EL MEDANITO'),
                array('id' => 3291, 'county_id' => '437', 'value' => 'RAWSON'),
                array('id' => 3292, 'county_id' => '437', 'value' => 'VILLA BOLAÑOS'),
                array('id' => 3293, 'county_id' => '437', 'value' => 'VILLA KRAUSE'),
                array('id' => 3294, 'county_id' => '438', 'value' => 'RIVADAVIA'),
                array('id' => 3295, 'county_id' => '439', 'value' => 'BARRIO SADOP'),
                array('id' => 3296, 'county_id' => '439', 'value' => 'DOS ACEQUIAS'),
                array('id' => 3297, 'county_id' => '439', 'value' => 'SAN ISIDRO'),
                array('id' => 3298, 'county_id' => '439', 'value' => 'VILLA DOMINGUITO'),
                array('id' => 3299, 'county_id' => '439', 'value' => 'VILLA DON BOSCO'),
                array('id' => 3300, 'county_id' => '439', 'value' => 'VILLA EL SALVADOR'),
                array('id' => 3301, 'county_id' => '439', 'value' => 'VILLA SAN MARTIN'),
                array('id' => 3302, 'county_id' => '440', 'value' => 'ALTO DE SIERRA'),
                array('id' => 3303, 'county_id' => '440', 'value' => 'COLONIA GUTIERREZ'),
                array('id' => 3304, 'county_id' => '440', 'value' => 'SANTA LUCIA'),
                array('id' => 3305, 'county_id' => '441', 'value' => 'CAÑADA HONDA'),
                array('id' => 3306, 'county_id' => '441', 'value' => 'CIENAGUITA'),
                array('id' => 3307, 'county_id' => '441', 'value' => 'COLONIA FISCAL'),
                array('id' => 3308, 'county_id' => '441', 'value' => 'DIVISADERO'),
                array('id' => 3309, 'county_id' => '441', 'value' => 'GUANACACHE'),
                array('id' => 3310, 'county_id' => '441', 'value' => 'LAS LAGUNAS'),
                array('id' => 3311, 'county_id' => '441', 'value' => 'LOS BERROS'),
                array('id' => 3312, 'county_id' => '441', 'value' => 'PEDERNAL'),
                array('id' => 3313, 'county_id' => '441', 'value' => 'PUNTA DEL MEDANO'),
                array('id' => 3314, 'county_id' => '441', 'value' => 'VILLA MEDIA AGUA'),
                array('id' => 3315, 'county_id' => '442', 'value' => 'VILLA IBAÑEZ'),
                array('id' => 3316, 'county_id' => '443', 'value' => 'ASTICA'),
                array('id' => 3317, 'county_id' => '443', 'value' => 'BALDE DEL ROSARIO'),
                array('id' => 3318, 'county_id' => '443', 'value' => 'CHUCUMA'),
                array('id' => 3319, 'county_id' => '443', 'value' => 'LOS BALDECITOS'),
                array('id' => 3320, 'county_id' => '443', 'value' => 'USNO'),
                array('id' => 3321, 'county_id' => '443', 'value' => 'VILLA SAN AGUSTIN'),
                array('id' => 3322, 'county_id' => '444', 'value' => 'VILLA BASILIO NIEVAS'),
                array('id' => 3323, 'county_id' => '444', 'value' => 'VILLA TACU'),
                array('id' => 3324, 'county_id' => '445', 'value' => 'CANDELARIA'),
                array('id' => 3325, 'county_id' => '445', 'value' => 'LEANDRO N. ALEM'),
                array('id' => 3326, 'county_id' => '445', 'value' => 'LUJAN'),
                array('id' => 3327, 'county_id' => '445', 'value' => 'QUINES'),
                array('id' => 3328, 'county_id' => '445', 'value' => 'SAN FRANCISCO DEL MONTE DE ORO'),
                array('id' => 3329, 'county_id' => '446', 'value' => 'LA CALERA'),
                array('id' => 3330, 'county_id' => '446', 'value' => 'NOGOLI'),
                array('id' => 3331, 'county_id' => '446', 'value' => 'VILLA DE LA QUEBRADA'),
                array('id' => 3332, 'county_id' => '446', 'value' => 'VILLA GENERAL ROCA'),
                array('id' => 3333, 'county_id' => '447', 'value' => 'CONCARAN'),
                array('id' => 3334, 'county_id' => '447', 'value' => 'CORTADERAS'),
                array('id' => 3335, 'county_id' => '447', 'value' => 'NASCHEL'),
                array('id' => 3336, 'county_id' => '447', 'value' => 'PAPAGAYOS'),
                array('id' => 3337, 'county_id' => '447', 'value' => 'RENCA'),
                array('id' => 3338, 'county_id' => '447', 'value' => 'SAN PABLO'),
                array('id' => 3339, 'county_id' => '447', 'value' => 'TILISARAO'),
                array('id' => 3340, 'county_id' => '447', 'value' => 'VILLA DEL CARMEN'),
                array('id' => 3341, 'county_id' => '447', 'value' => 'VILLA LARCA'),
                array('id' => 3342, 'county_id' => '448', 'value' => 'CAROLINA'),
                array('id' => 3343, 'county_id' => '448', 'value' => 'EL TRAPICHE'),
                array('id' => 3344, 'county_id' => '448', 'value' => 'ESTANCIA GRANDE'),
                array('id' => 3345, 'county_id' => '448', 'value' => 'FRAGA'),
                array('id' => 3346, 'county_id' => '448', 'value' => 'LA BAJADA'),
                array('id' => 3347, 'county_id' => '448', 'value' => 'LA FLORIDA'),
                array('id' => 3348, 'county_id' => '448', 'value' => 'LA TOMA'),
                array('id' => 3349, 'county_id' => '448', 'value' => 'RIO GRANDE'),
                array('id' => 3350, 'county_id' => '448', 'value' => 'RIOCITO'),
                array('id' => 3351, 'county_id' => '448', 'value' => 'SALADILLO'),
                array('id' => 3352, 'county_id' => '449', 'value' => '5TA BRIGADA'),
                array('id' => 3353, 'county_id' => '449', 'value' => 'COUNTRY CLUB LOS CALDENES'),
                array('id' => 3354, 'county_id' => '449', 'value' => 'JUAN JORBA'),
                array('id' => 3355, 'county_id' => '449', 'value' => 'JUAN LLERENA'),
                array('id' => 3356, 'county_id' => '449', 'value' => 'JUSTO DARACT'),
                array('id' => 3357, 'county_id' => '449', 'value' => 'LA PUNILLA'),
                array('id' => 3358, 'county_id' => '449', 'value' => 'LA RIBERA'),
                array('id' => 3359, 'county_id' => '449', 'value' => 'LAVAISSE'),
                array('id' => 3360, 'county_id' => '449', 'value' => 'NACION RANQUEL'),
                array('id' => 3361, 'county_id' => '449', 'value' => 'SAN JOSE DEL MORRO'),
                array('id' => 3362, 'county_id' => '449', 'value' => 'VILLA MERCEDES'),
                array('id' => 3363, 'county_id' => '449', 'value' => 'VILLA REYNOLDS'),
                array('id' => 3364, 'county_id' => '449', 'value' => 'VILLA SALLES'),
                array('id' => 3365, 'county_id' => '450', 'value' => 'ANCHORENA'),
                array('id' => 3366, 'county_id' => '450', 'value' => 'ARIZONA'),
                array('id' => 3367, 'county_id' => '450', 'value' => 'BAGUAL'),
                array('id' => 3368, 'county_id' => '450', 'value' => 'BATAVIA'),
                array('id' => 3369, 'county_id' => '450', 'value' => 'BUENA ESPERANZA'),
                array('id' => 3370, 'county_id' => '450', 'value' => 'FORTIN EL PATRIA'),
                array('id' => 3371, 'county_id' => '450', 'value' => 'FORTUNA'),
                array('id' => 3372, 'county_id' => '450', 'value' => 'LA MAROMA'),
                array('id' => 3373, 'county_id' => '450', 'value' => 'LOS OVEROS'),
                array('id' => 3374, 'county_id' => '450', 'value' => 'MARTIN DE LOYOLA'),
                array('id' => 3375, 'county_id' => '450', 'value' => 'NAHUEL MAPA'),
                array('id' => 3376, 'county_id' => '450', 'value' => 'NAVIA'),
                array('id' => 3377, 'county_id' => '450', 'value' => 'NUEVA GALIA'),
                array('id' => 3378, 'county_id' => '450', 'value' => 'UNION'),
                array('id' => 3379, 'county_id' => '451', 'value' => 'ALTO PELADO'),
                array('id' => 3380, 'county_id' => '451', 'value' => 'ALTO PENCOSO'),
                array('id' => 3381, 'county_id' => '451', 'value' => 'BALDE'),
                array('id' => 3382, 'county_id' => '451', 'value' => 'BEAZLEY'),
                array('id' => 3383, 'county_id' => '451', 'value' => 'CAZADOR'),
                array('id' => 3384, 'county_id' => '451', 'value' => 'CERRO COLORADO'),
                array('id' => 3385, 'county_id' => '451', 'value' => 'CHOSMES'),
                array('id' => 3386, 'county_id' => '451', 'value' => 'CIUDAD DE LA PUNTA'),
                array('id' => 3387, 'county_id' => '451', 'value' => 'CRUZ DE PIEDRA'),
                array('id' => 3388, 'county_id' => '451', 'value' => 'DESAGUADERO'),
                array('id' => 3389, 'county_id' => '451', 'value' => 'EL CHORRILLO'),
                array('id' => 3390, 'county_id' => '451', 'value' => 'EL VOLCAN'),
                array('id' => 3391, 'county_id' => '451', 'value' => 'JARILLA'),
                array('id' => 3392, 'county_id' => '451', 'value' => 'LAS CHACRAS'),
                array('id' => 3393, 'county_id' => '451', 'value' => 'MOSMOTA'),
                array('id' => 3394, 'county_id' => '451', 'value' => 'POTRERO DE LOS FUNES'),
                array('id' => 3395, 'county_id' => '451', 'value' => 'SALINAS DEL BEBEDERO'),
                array('id' => 3396, 'county_id' => '451', 'value' => 'SAN JERONIMO'),
                array('id' => 3397, 'county_id' => '451', 'value' => 'SAN LUIS'),
                array('id' => 3398, 'county_id' => '451', 'value' => 'SAN ROQUE'),
                array('id' => 3399, 'county_id' => '451', 'value' => 'ZANJITAS'),
                array('id' => 3400, 'county_id' => '452', 'value' => 'CARPINTERIA'),
                array('id' => 3401, 'county_id' => '452', 'value' => 'CERRO DE ORO'),
                array('id' => 3402, 'county_id' => '452', 'value' => 'LAFINUR'),
                array('id' => 3403, 'county_id' => '452', 'value' => 'LOS CAJONES'),
                array('id' => 3404, 'county_id' => '452', 'value' => 'LOS MOLLES'),
                array('id' => 3405, 'county_id' => '452', 'value' => 'MERLO'),
                array('id' => 3406, 'county_id' => '452', 'value' => 'SANTA ROSA DEL CONLARA'),
                array('id' => 3407, 'county_id' => '452', 'value' => 'TALITA'),
                array('id' => 3408, 'county_id' => '453', 'value' => 'LA VERTIENTE'),
                array('id' => 3409, 'county_id' => '453', 'value' => 'LAS AGUADAS'),
                array('id' => 3410, 'county_id' => '453', 'value' => 'LAS CHACRAS'),
                array('id' => 3411, 'county_id' => '453', 'value' => 'LAS LAGUNAS'),
                array('id' => 3412, 'county_id' => '453', 'value' => 'PASO GRANDE'),
                array('id' => 3413, 'county_id' => '453', 'value' => 'POTRERILLO'),
                array('id' => 3414, 'county_id' => '453', 'value' => 'SAN MARTIN'),
                array('id' => 3415, 'county_id' => '453', 'value' => 'VILLA DE PRAGA'),
                array('id' => 3416, 'county_id' => '454', 'value' => 'COMANDANTE LUIS PIEDRABUENA'),
                array('id' => 3417, 'county_id' => '454', 'value' => 'PUERTO SANTA CRUZ'),
                array('id' => 3418, 'county_id' => '455', 'value' => 'CAÑADON SECO'),
                array('id' => 3419, 'county_id' => '455', 'value' => 'CALETA OLIVIA'),
                array('id' => 3420, 'county_id' => '455', 'value' => 'FITZ ROY'),
                array('id' => 3421, 'county_id' => '455', 'value' => 'JARAMILLO'),
                array('id' => 3422, 'county_id' => '455', 'value' => 'KOLUEL KAIKE'),
                array('id' => 3423, 'county_id' => '455', 'value' => 'LAS HERAS'),
                array('id' => 3424, 'county_id' => '455', 'value' => 'PICO TRUNCADO'),
                array('id' => 3425, 'county_id' => '455', 'value' => 'PUERTO DESEADO'),
                array('id' => 3426, 'county_id' => '455', 'value' => 'TELLIER'),
                array('id' => 3427, 'county_id' => '456', 'value' => '28 DE NOVIEMBRE'),
                array('id' => 3428, 'county_id' => '456', 'value' => 'EL TURBIO'),
                array('id' => 3429, 'county_id' => '456', 'value' => 'JULIA DUFOUR'),
                array('id' => 3430, 'county_id' => '456', 'value' => 'MINA 3'),
                array('id' => 3431, 'county_id' => '456', 'value' => 'RIO GALLEGOS'),
                array('id' => 3432, 'county_id' => '456', 'value' => 'ROSPENTEK'),
                array('id' => 3433, 'county_id' => '456', 'value' => 'YACIMIENTOS RIO TURBIO'),
                array('id' => 3434, 'county_id' => '457', 'value' => 'EL CALAFATE'),
                array('id' => 3435, 'county_id' => '457', 'value' => 'EL CHALTEN'),
                array('id' => 3436, 'county_id' => '457', 'value' => 'TRES LAGOS'),
                array('id' => 3437, 'county_id' => '458', 'value' => 'LOS ANTIGUOS'),
                array('id' => 3438, 'county_id' => '458', 'value' => 'PERITO MORENO'),
                array('id' => 3439, 'county_id' => '459', 'value' => 'PUERTO SAN JULIAN'),
                array('id' => 3440, 'county_id' => '460', 'value' => 'BAJO CARACOLES'),
                array('id' => 3441, 'county_id' => '460', 'value' => 'GOBERNADOR GREGORES'),
                array('id' => 3442, 'county_id' => '460', 'value' => 'HIPOLITO YRIGOYEN'),
                array('id' => 3443, 'county_id' => '461', 'value' => 'ESTEBAN RAMS'),
                array('id' => 3444, 'county_id' => '461', 'value' => 'GATO COLORADO'),
                array('id' => 3445, 'county_id' => '461', 'value' => 'GREGORIA PEREZ DE DENIS'),
                array('id' => 3446, 'county_id' => '461', 'value' => 'LOGROÑO'),
                array('id' => 3447, 'county_id' => '461', 'value' => 'MONTEFIORE'),
                array('id' => 3448, 'county_id' => '461', 'value' => 'POZO BORRADO'),
                array('id' => 3449, 'county_id' => '461', 'value' => 'SAN BERNARDO'),
                array('id' => 3450, 'county_id' => '461', 'value' => 'SANTA MARGARITA'),
                array('id' => 3451, 'county_id' => '461', 'value' => 'TOSTADO'),
                array('id' => 3452, 'county_id' => '461', 'value' => 'VILLA MINETTI'),
                array('id' => 3453, 'county_id' => '462', 'value' => 'ARMSTRONG'),
                array('id' => 3454, 'county_id' => '462', 'value' => 'BOUQUET'),
                array('id' => 3455, 'county_id' => '462', 'value' => 'LAS PAREJAS'),
                array('id' => 3456, 'county_id' => '462', 'value' => 'LAS ROSAS'),
                array('id' => 3457, 'county_id' => '462', 'value' => 'MONTES DE OCA'),
                array('id' => 3458, 'county_id' => '462', 'value' => 'TORTUGAS'),
                array('id' => 3459, 'county_id' => '463', 'value' => 'AREQUITO'),
                array('id' => 3460, 'county_id' => '463', 'value' => 'ARTEAGA'),
                array('id' => 3461, 'county_id' => '463', 'value' => 'BERAVEBU'),
                array('id' => 3462, 'county_id' => '463', 'value' => 'BIGAND'),
                array('id' => 3463, 'county_id' => '463', 'value' => 'CASILDA'),
                array('id' => 3464, 'county_id' => '463', 'value' => 'CHAÑAR LADEADO'),
                array('id' => 3465, 'county_id' => '463', 'value' => 'CHABAS'),
                array('id' => 3466, 'county_id' => '463', 'value' => 'GODEKEN'),
                array('id' => 3467, 'county_id' => '463', 'value' => 'LOS MOLINOS'),
                array('id' => 3468, 'county_id' => '463', 'value' => 'LOS NOGALES'),
                array('id' => 3469, 'county_id' => '463', 'value' => 'LOS QUIRQUINCHOS'),
                array('id' => 3470, 'county_id' => '463', 'value' => 'SAN JOSE DE LA ESQUINA'),
                array('id' => 3471, 'county_id' => '463', 'value' => 'SANFORD'),
                array('id' => 3472, 'county_id' => '463', 'value' => 'VILLADA'),
                array('id' => 3473, 'county_id' => '464', 'value' => 'ALDAO'),
                array('id' => 3474, 'county_id' => '464', 'value' => 'ANGELICA'),
                array('id' => 3475, 'county_id' => '464', 'value' => 'ATALIVA'),
                array('id' => 3476, 'county_id' => '464', 'value' => 'AURELIA'),
                array('id' => 3477, 'county_id' => '464', 'value' => 'BARRIOS ACAPULCO Y VERACRUZ'),
                array('id' => 3478, 'county_id' => '464', 'value' => 'BAUER Y SIGEL'),
                array('id' => 3479, 'county_id' => '464', 'value' => 'BELLA ITALIA'),
                array('id' => 3480, 'county_id' => '464', 'value' => 'CASTELLANOS'),
                array('id' => 3481, 'county_id' => '464', 'value' => 'COLONIA BICHA'),
                array('id' => 3482, 'county_id' => '464', 'value' => 'COLONIA CELLO'),
                array('id' => 3483, 'county_id' => '464', 'value' => 'COLONIA MARGARITA'),
                array('id' => 3484, 'county_id' => '464', 'value' => 'COLONIA RAQUEL'),
                array('id' => 3485, 'county_id' => '464', 'value' => 'CORONEL FRAGA'),
                array('id' => 3486, 'county_id' => '464', 'value' => 'EGUSQUIZA'),
                array('id' => 3487, 'county_id' => '464', 'value' => 'ESMERALDA'),
                array('id' => 3488, 'county_id' => '464', 'value' => 'ESTACION CLUCELLAS'),
                array('id' => 3489, 'county_id' => '464', 'value' => 'ESTACION PRESIDENTE ROCA'),
                array('id' => 3490, 'county_id' => '464', 'value' => 'ESTACION SAGUIER'),
                array('id' => 3491, 'county_id' => '464', 'value' => 'EUSEBIA Y CAROLINA'),
                array('id' => 3492, 'county_id' => '464', 'value' => 'EUSTOLIA'),
                array('id' => 3493, 'county_id' => '464', 'value' => 'FRONTERA'),
                array('id' => 3494, 'county_id' => '464', 'value' => 'GARIBALDI'),
                array('id' => 3495, 'county_id' => '464', 'value' => 'HUMBERTO PRIMO'),
                array('id' => 3496, 'county_id' => '464', 'value' => 'JOSEFINA'),
                array('id' => 3497, 'county_id' => '464', 'value' => 'LEHMANN'),
                array('id' => 3498, 'county_id' => '464', 'value' => 'MARIA JUANA'),
                array('id' => 3499, 'county_id' => '464', 'value' => 'NUEVA LEHMANN'),
                array('id' => 3500, 'county_id' => '464', 'value' => 'PLAZA CLUCELLAS'),
                array('id' => 3501, 'county_id' => '464', 'value' => 'PLAZA SAGUIER'),
                array('id' => 3502, 'county_id' => '464', 'value' => 'PRESIDENTE ROCA'),
                array('id' => 3503, 'county_id' => '464', 'value' => 'PUEBLO MARINI'),
                array('id' => 3504, 'county_id' => '464', 'value' => 'RAFAELA'),
                array('id' => 3505, 'county_id' => '464', 'value' => 'RAMONA'),
                array('id' => 3506, 'county_id' => '464', 'value' => 'SAN ANTONIO'),
                array('id' => 3507, 'county_id' => '464', 'value' => 'SAN VICENTE'),
                array('id' => 3508, 'county_id' => '464', 'value' => 'SANTA CLARA DE SAGUIER'),
                array('id' => 3509, 'county_id' => '464', 'value' => 'SUNCHALES'),
                array('id' => 3510, 'county_id' => '464', 'value' => 'SUSANA'),
                array('id' => 3511, 'county_id' => '464', 'value' => 'TACURAL'),
                array('id' => 3512, 'county_id' => '464', 'value' => 'VILA'),
                array('id' => 3513, 'county_id' => '464', 'value' => 'VILLA JOSEFINA'),
                array('id' => 3514, 'county_id' => '464', 'value' => 'VILLA SAN JOSE'),
                array('id' => 3515, 'county_id' => '464', 'value' => 'VIRGINIA'),
                array('id' => 3516, 'county_id' => '464', 'value' => 'ZENON PEREYRA'),
                array('id' => 3517, 'county_id' => '465', 'value' => 'CAYASTA'),
                array('id' => 3518, 'county_id' => '465', 'value' => 'HELVECIA'),
                array('id' => 3519, 'county_id' => '465', 'value' => 'LOS ZAPALLOS'),
                array('id' => 3520, 'county_id' => '465', 'value' => 'SALADERO MARIANO CABAL'),
                array('id' => 3521, 'county_id' => '465', 'value' => 'SANTA ROSA DE CALCHINES'),
                array('id' => 3522, 'county_id' => '466', 'value' => 'AARON CASTELLANOS'),
                array('id' => 3523, 'county_id' => '466', 'value' => 'AMENABAR'),
                array('id' => 3524, 'county_id' => '466', 'value' => 'CAÑADA DEL UCLE'),
                array('id' => 3525, 'county_id' => '466', 'value' => 'CAFFERATA'),
                array('id' => 3526, 'county_id' => '466', 'value' => 'CARMEN'),
                array('id' => 3527, 'county_id' => '466', 'value' => 'CARRERAS'),
                array('id' => 3528, 'county_id' => '466', 'value' => 'CHAPUY'),
                array('id' => 3529, 'county_id' => '466', 'value' => 'CHOVET'),
                array('id' => 3530, 'county_id' => '466', 'value' => 'CHRISTOPHERSEN'),
                array('id' => 3531, 'county_id' => '466', 'value' => 'DIEGO DE ALVEAR'),
                array('id' => 3532, 'county_id' => '466', 'value' => 'ELORTONDO'),
                array('id' => 3533, 'county_id' => '466', 'value' => 'FIRMAT'),
                array('id' => 3534, 'county_id' => '466', 'value' => 'HUGHES'),
                array('id' => 3535, 'county_id' => '466', 'value' => 'LA CHISPA'),
                array('id' => 3536, 'county_id' => '466', 'value' => 'LABORDEBOY'),
                array('id' => 3537, 'county_id' => '466', 'value' => 'LAZZARINO'),
                array('id' => 3538, 'county_id' => '466', 'value' => 'MAGGIOLO'),
                array('id' => 3539, 'county_id' => '466', 'value' => 'MARIA TERESA'),
                array('id' => 3540, 'county_id' => '466', 'value' => 'MELINCUE'),
                array('id' => 3541, 'county_id' => '466', 'value' => 'MIGUEL TORRES'),
                array('id' => 3542, 'county_id' => '466', 'value' => 'MURPHY'),
                array('id' => 3543, 'county_id' => '466', 'value' => 'RUFINO'),
                array('id' => 3544, 'county_id' => '466', 'value' => 'SAN EDUARDO'),
                array('id' => 3545, 'county_id' => '466', 'value' => 'SAN FRANCISCO DE SANTA FE'),
                array('id' => 3546, 'county_id' => '466', 'value' => 'SAN GREGORIO'),
                array('id' => 3547, 'county_id' => '466', 'value' => 'SANCTI SPIRITU'),
                array('id' => 3548, 'county_id' => '466', 'value' => 'SANTA ISABEL'),
                array('id' => 3549, 'county_id' => '466', 'value' => 'TEODELINA'),
                array('id' => 3550, 'county_id' => '466', 'value' => 'VENADO TUERTO'),
                array('id' => 3551, 'county_id' => '466', 'value' => 'VILLA CAÑAS'),
                array('id' => 3552, 'county_id' => '466', 'value' => 'WHEELWRIGHT'),
                array('id' => 3553, 'county_id' => '467', 'value' => 'ARROYO CEIBAL'),
                array('id' => 3554, 'county_id' => '467', 'value' => 'AVELLANEDA'),
                array('id' => 3555, 'county_id' => '467', 'value' => 'BERNA'),
                array('id' => 3556, 'county_id' => '467', 'value' => 'EL ARAZA'),
                array('id' => 3557, 'county_id' => '467', 'value' => 'EL RABON'),
                array('id' => 3558, 'county_id' => '467', 'value' => 'FLORENCIA'),
                array('id' => 3559, 'county_id' => '467', 'value' => 'GUADALUPE NORTE'),
                array('id' => 3560, 'county_id' => '467', 'value' => 'INGENIERO CHANOURDIE'),
                array('id' => 3561, 'county_id' => '467', 'value' => 'LA ISLETA'),
                array('id' => 3562, 'county_id' => '467', 'value' => 'LA SARITA'),
                array('id' => 3563, 'county_id' => '467', 'value' => 'LANTERI'),
                array('id' => 3564, 'county_id' => '467', 'value' => 'LAS GARZAS'),
                array('id' => 3565, 'county_id' => '467', 'value' => 'LAS TOSCAS'),
                array('id' => 3566, 'county_id' => '467', 'value' => 'LOS LAURELES'),
                array('id' => 3567, 'county_id' => '467', 'value' => 'MALABRIGO'),
                array('id' => 3568, 'county_id' => '467', 'value' => 'PARAJE SAN MANUEL'),
                array('id' => 3569, 'county_id' => '467', 'value' => 'PUERTO RECONQUISTA'),
                array('id' => 3570, 'county_id' => '467', 'value' => 'RECONQUISTA'),
                array('id' => 3571, 'county_id' => '467', 'value' => 'SAN ANTONIO DE OBLIGADO'),
                array('id' => 3572, 'county_id' => '467', 'value' => 'TACUARENDI'),
                array('id' => 3573, 'county_id' => '467', 'value' => 'VILLA ANA'),
                array('id' => 3574, 'county_id' => '467', 'value' => 'VILLA GUILLERMINA'),
                array('id' => 3575, 'county_id' => '467', 'value' => 'VILLA OCAMPO'),
                array('id' => 3576, 'county_id' => '468', 'value' => 'BARRIO CICARELLI'),
                array('id' => 3577, 'county_id' => '468', 'value' => 'BUSTINZA'),
                array('id' => 3578, 'county_id' => '468', 'value' => 'CAÑADA DE GOMEZ'),
                array('id' => 3579, 'county_id' => '468', 'value' => 'CARRIZALES'),
                array('id' => 3580, 'county_id' => '468', 'value' => 'CLASSON'),
                array('id' => 3581, 'county_id' => '468', 'value' => 'COLONIA MEDICI'),
                array('id' => 3582, 'county_id' => '468', 'value' => 'CORREA'),
                array('id' => 3583, 'county_id' => '468', 'value' => 'LARGUIA'),
                array('id' => 3584, 'county_id' => '468', 'value' => 'LUCIO V. LOPEZ'),
                array('id' => 3585, 'county_id' => '468', 'value' => 'OLIVEROS'),
                array('id' => 3586, 'county_id' => '468', 'value' => 'PUEBLO ANDINO'),
                array('id' => 3587, 'county_id' => '468', 'value' => 'SALTO GRANDE'),
                array('id' => 3588, 'county_id' => '468', 'value' => 'SERODINO'),
                array('id' => 3589, 'county_id' => '468', 'value' => 'TOTORAS'),
                array('id' => 3590, 'county_id' => '468', 'value' => 'VILLA ELOISA'),
                array('id' => 3591, 'county_id' => '468', 'value' => 'VILLA LA RIVERA - OLIVEROS'),
                array('id' => 3592, 'county_id' => '468', 'value' => 'VILLA LA RIVERA - PUEBLO ANDINO'),
                array('id' => 3593, 'county_id' => '469', 'value' => 'ANGEL GALLARDO'),
                array('id' => 3594, 'county_id' => '469', 'value' => 'ARROYO AGUIAR'),
                array('id' => 3595, 'county_id' => '469', 'value' => 'ARROYO LEYES'),
                array('id' => 3596, 'county_id' => '469', 'value' => 'CABAL'),
                array('id' => 3597, 'county_id' => '469', 'value' => 'CAMPO ANDINO'),
                array('id' => 3598, 'county_id' => '469', 'value' => 'CANDIOTI'),
                array('id' => 3599, 'county_id' => '469', 'value' => 'EMILIA'),
                array('id' => 3600, 'county_id' => '469', 'value' => 'LAGUNA PAIVA'),
                array('id' => 3601, 'county_id' => '469', 'value' => 'LLAMBI CAMPBELL'),
                array('id' => 3602, 'county_id' => '469', 'value' => 'MONTE VERA'),
                array('id' => 3603, 'county_id' => '469', 'value' => 'NELSON'),
                array('id' => 3604, 'county_id' => '469', 'value' => 'PARAJE CHACO CHICO'),
                array('id' => 3605, 'county_id' => '469', 'value' => 'PARAJE LA COSTA'),
                array('id' => 3606, 'county_id' => '469', 'value' => 'RECREO'),
                array('id' => 3607, 'county_id' => '469', 'value' => 'RINCON NORTE'),
                array('id' => 3608, 'county_id' => '469', 'value' => 'RINCON POTRERO'),
                array('id' => 3609, 'county_id' => '469', 'value' => 'SAN JOSE DEL RINCON'),
                array('id' => 3610, 'county_id' => '469', 'value' => 'SANTA FE'),
                array('id' => 3611, 'county_id' => '469', 'value' => 'SANTO TOME'),
                array('id' => 3612, 'county_id' => '469', 'value' => 'SAUCE VIEJO'),
                array('id' => 3613, 'county_id' => '469', 'value' => 'VILLA ADELINA'),
                array('id' => 3614, 'county_id' => '469', 'value' => 'VILLA LAURA'),
                array('id' => 3615, 'county_id' => '470', 'value' => 'CAVOUR'),
                array('id' => 3616, 'county_id' => '470', 'value' => 'CULULU'),
                array('id' => 3617, 'county_id' => '470', 'value' => 'ELISA'),
                array('id' => 3618, 'county_id' => '470', 'value' => 'EMPALME SAN CARLOS'),
                array('id' => 3619, 'county_id' => '470', 'value' => 'ESPERANZA'),
                array('id' => 3620, 'county_id' => '470', 'value' => 'FELICIA'),
                array('id' => 3621, 'county_id' => '470', 'value' => 'FRANCK'),
                array('id' => 3622, 'county_id' => '470', 'value' => 'GRUTLY'),
                array('id' => 3623, 'county_id' => '470', 'value' => 'HIPATIA'),
                array('id' => 3624, 'county_id' => '470', 'value' => 'HUMBOLDT'),
                array('id' => 3625, 'county_id' => '470', 'value' => 'JACINTO L. ARAUZ'),
                array('id' => 3626, 'county_id' => '470', 'value' => 'LA PELADA'),
                array('id' => 3627, 'county_id' => '470', 'value' => 'LAS TUNAS'),
                array('id' => 3628, 'county_id' => '470', 'value' => 'MARIA LUISA'),
                array('id' => 3629, 'county_id' => '470', 'value' => 'MATILDE'),
                array('id' => 3630, 'county_id' => '470', 'value' => 'NUEVO TORINO'),
                array('id' => 3631, 'county_id' => '470', 'value' => 'PILAR'),
                array('id' => 3632, 'county_id' => '470', 'value' => 'PLAZA MATILDE'),
                array('id' => 3633, 'county_id' => '470', 'value' => 'PROGRESO'),
                array('id' => 3634, 'county_id' => '470', 'value' => 'PROVIDENCIA'),
                array('id' => 3635, 'county_id' => '470', 'value' => 'SA PEREYRA'),
                array('id' => 3636, 'county_id' => '470', 'value' => 'SAN AGUSTIN'),
                array('id' => 3637, 'county_id' => '470', 'value' => 'SAN CARLOS CENTRO'),
                array('id' => 3638, 'county_id' => '470', 'value' => 'SAN CARLOS NORTE'),
                array('id' => 3639, 'county_id' => '470', 'value' => 'SAN CARLOS SUD'),
                array('id' => 3640, 'county_id' => '470', 'value' => 'SAN JERONIMO DEL SAUCE'),
                array('id' => 3641, 'county_id' => '470', 'value' => 'SAN JERONIMO NORTE'),
                array('id' => 3642, 'county_id' => '470', 'value' => 'SAN MARIANO'),
                array('id' => 3643, 'county_id' => '470', 'value' => 'SANTA CLARA DE BUENA VISTA'),
                array('id' => 3644, 'county_id' => '470', 'value' => 'SANTO DOMINGO'),
                array('id' => 3645, 'county_id' => '470', 'value' => 'SARMIENTO'),
                array('id' => 3646, 'county_id' => '471', 'value' => 'ACEBAL'),
                array('id' => 3647, 'county_id' => '471', 'value' => 'ALBARELLOS'),
                array('id' => 3648, 'county_id' => '471', 'value' => 'ALVAREZ'),
                array('id' => 3649, 'county_id' => '471', 'value' => 'ALVEAR'),
                array('id' => 3650, 'county_id' => '471', 'value' => 'ARBILLA'),
                array('id' => 3651, 'county_id' => '471', 'value' => 'ARMINDA'),
                array('id' => 3652, 'county_id' => '471', 'value' => 'ARROYO SECO'),
                array('id' => 3653, 'county_id' => '471', 'value' => 'CARMEN DEL SAUCE'),
                array('id' => 3654, 'county_id' => '471', 'value' => 'CORONEL BOGADO'),
                array('id' => 3655, 'county_id' => '471', 'value' => 'CORONEL RODOLFO S. DOMINGUEZ'),
                array('id' => 3656, 'county_id' => '471', 'value' => 'CUATRO ESQUINAS'),
                array('id' => 3657, 'county_id' => '471', 'value' => 'EL CARAMELO'),
                array('id' => 3658, 'county_id' => '471', 'value' => 'FIGHIERA'),
                array('id' => 3659, 'county_id' => '471', 'value' => 'FUNES'),
                array('id' => 3660, 'county_id' => '471', 'value' => 'GENERAL LAGOS'),
                array('id' => 3661, 'county_id' => '471', 'value' => 'GRANADERO BAIGORRIA'),
                array('id' => 3662, 'county_id' => '471', 'value' => 'IBARLUCEA'),
                array('id' => 3663, 'county_id' => '471', 'value' => 'KILOMETRO 101'),
                array('id' => 3664, 'county_id' => '471', 'value' => 'LOS MUCHACHOS - LA ALBORADA'),
                array('id' => 3665, 'county_id' => '471', 'value' => 'MONTE FLORES'),
                array('id' => 3666, 'county_id' => '471', 'value' => 'PEREZ'),
                array('id' => 3667, 'county_id' => '471', 'value' => 'PIÑERO'),
                array('id' => 3668, 'county_id' => '471', 'value' => 'PUEBLO ESTHER'),
                array('id' => 3669, 'county_id' => '471', 'value' => 'PUEBLO MUÑOZ'),
                array('id' => 3670, 'county_id' => '471', 'value' => 'PUEBLO URANGA'),
                array('id' => 3671, 'county_id' => '471', 'value' => 'PUERTO ARROYO SECO'),
                array('id' => 3672, 'county_id' => '471', 'value' => 'ROSARIO'),
                array('id' => 3673, 'county_id' => '471', 'value' => 'SOLDINI'),
                array('id' => 3674, 'county_id' => '471', 'value' => 'VILLA AMELIA'),
                array('id' => 3675, 'county_id' => '471', 'value' => 'VILLA DEL PLATA'),
                array('id' => 3676, 'county_id' => '471', 'value' => 'VILLA GOBERNADOR GALVEZ'),
                array('id' => 3677, 'county_id' => '471', 'value' => 'ZAVALLA'),
                array('id' => 3678, 'county_id' => '472', 'value' => 'ÑANDUCITA'),
                array('id' => 3679, 'county_id' => '472', 'value' => 'AGUARA GRANDE'),
                array('id' => 3680, 'county_id' => '472', 'value' => 'AMBROSETTI'),
                array('id' => 3681, 'county_id' => '472', 'value' => 'ARRUFO'),
                array('id' => 3682, 'county_id' => '472', 'value' => 'BALNEARIO LA VERDE'),
                array('id' => 3683, 'county_id' => '472', 'value' => 'CAPIVARA'),
                array('id' => 3684, 'county_id' => '472', 'value' => 'CERES'),
                array('id' => 3685, 'county_id' => '472', 'value' => 'COLONIA ANA'),
                array('id' => 3686, 'county_id' => '472', 'value' => 'COLONIA BOSSI'),
                array('id' => 3687, 'county_id' => '472', 'value' => 'COLONIA ROSA'),
                array('id' => 3688, 'county_id' => '472', 'value' => 'CONSTANZA'),
                array('id' => 3689, 'county_id' => '472', 'value' => 'CURUPAYTI'),
                array('id' => 3690, 'county_id' => '472', 'value' => 'HERSILIA'),
                array('id' => 3691, 'county_id' => '472', 'value' => 'HUANQUEROS'),
                array('id' => 3692, 'county_id' => '472', 'value' => 'LA CABRAL'),
                array('id' => 3693, 'county_id' => '472', 'value' => 'LA LUCILA'),
                array('id' => 3694, 'county_id' => '472', 'value' => 'LA RUBIA'),
                array('id' => 3695, 'county_id' => '472', 'value' => 'LAS AVISPAS'),
                array('id' => 3696, 'county_id' => '472', 'value' => 'LAS PALMERAS'),
                array('id' => 3697, 'county_id' => '472', 'value' => 'MOISES VILLE'),
                array('id' => 3698, 'county_id' => '472', 'value' => 'MONIGOTES'),
                array('id' => 3699, 'county_id' => '472', 'value' => 'PALACIOS'),
                array('id' => 3700, 'county_id' => '472', 'value' => 'SAN CRISTOBAL'),
                array('id' => 3701, 'county_id' => '472', 'value' => 'SAN GUILLERMO'),
                array('id' => 3702, 'county_id' => '472', 'value' => 'SANTURCE'),
                array('id' => 3703, 'county_id' => '472', 'value' => 'SOLEDAD'),
                array('id' => 3704, 'county_id' => '472', 'value' => 'SUARDI'),
                array('id' => 3705, 'county_id' => '472', 'value' => 'VILLA SARALEGUI'),
                array('id' => 3706, 'county_id' => '472', 'value' => 'VILLA TRINIDAD'),
                array('id' => 3707, 'county_id' => '473', 'value' => 'ALEJANDRA'),
                array('id' => 3708, 'county_id' => '473', 'value' => 'CACIQUE ARIACAIQUIN'),
                array('id' => 3709, 'county_id' => '473', 'value' => 'COLONIA DURAN'),
                array('id' => 3710, 'county_id' => '473', 'value' => 'LA BRAVA'),
                array('id' => 3711, 'county_id' => '473', 'value' => 'ROMANG'),
                array('id' => 3712, 'county_id' => '473', 'value' => 'SAN JAVIER'),
                array('id' => 3713, 'county_id' => '474', 'value' => 'AROCENA'),
                array('id' => 3714, 'county_id' => '474', 'value' => 'BALNEARIO MONJE'),
                array('id' => 3715, 'county_id' => '474', 'value' => 'BARRANCAS'),
                array('id' => 3716, 'county_id' => '474', 'value' => 'BARRIO CAIMA'),
                array('id' => 3717, 'county_id' => '474', 'value' => 'BARRIO EL PACAA - BARRIO COMIPINI'),
                array('id' => 3718, 'county_id' => '474', 'value' => 'BERNARDO DE IRIGOYEN'),
                array('id' => 3719, 'county_id' => '474', 'value' => 'CASALEGNO'),
                array('id' => 3720, 'county_id' => '474', 'value' => 'CENTENO'),
                array('id' => 3721, 'county_id' => '474', 'value' => 'CORONDA'),
                array('id' => 3722, 'county_id' => '474', 'value' => 'DESVIO ARIJON'),
                array('id' => 3723, 'county_id' => '474', 'value' => 'DIAZ'),
                array('id' => 3724, 'county_id' => '474', 'value' => 'GABOTO'),
                array('id' => 3725, 'county_id' => '474', 'value' => 'GALVEZ'),
                array('id' => 3726, 'county_id' => '474', 'value' => 'GESSLER'),
                array('id' => 3727, 'county_id' => '474', 'value' => 'IRIGOYEN'),
                array('id' => 3728, 'county_id' => '474', 'value' => 'LARRECHEA'),
                array('id' => 3729, 'county_id' => '474', 'value' => 'LOMA ALTA'),
                array('id' => 3730, 'county_id' => '474', 'value' => 'LOPEZ'),
                array('id' => 3731, 'county_id' => '474', 'value' => 'MACIEL'),
                array('id' => 3732, 'county_id' => '474', 'value' => 'MONJE'),
                array('id' => 3733, 'county_id' => '474', 'value' => 'PUERTO ARAGON'),
                array('id' => 3734, 'county_id' => '474', 'value' => 'SAN EUGENIO'),
                array('id' => 3735, 'county_id' => '474', 'value' => 'SAN FABIAN'),
                array('id' => 3736, 'county_id' => '474', 'value' => 'SAN GENARO'),
                array('id' => 3737, 'county_id' => '474', 'value' => 'SAN GENARO NORTE'),
                array('id' => 3738, 'county_id' => '475', 'value' => 'ANGELONI'),
                array('id' => 3739, 'county_id' => '475', 'value' => 'CAYASTACITO'),
                array('id' => 3740, 'county_id' => '475', 'value' => 'COLONIA DOLORES'),
                array('id' => 3741, 'county_id' => '475', 'value' => 'ESTHER'),
                array('id' => 3742, 'county_id' => '475', 'value' => 'GOBERNADOR CRESPO'),
                array('id' => 3743, 'county_id' => '475', 'value' => 'LA CRIOLLA'),
                array('id' => 3744, 'county_id' => '475', 'value' => 'LA PENCA Y CARAGUATA'),
                array('id' => 3745, 'county_id' => '475', 'value' => 'MARCELINO ESCALADA'),
                array('id' => 3746, 'county_id' => '475', 'value' => 'NARE'),
                array('id' => 3747, 'county_id' => '475', 'value' => 'PEDRO GOMEZ CELLO'),
                array('id' => 3748, 'county_id' => '475', 'value' => 'RAMAYON'),
                array('id' => 3749, 'county_id' => '475', 'value' => 'SAN BERNARDO'),
                array('id' => 3750, 'county_id' => '475', 'value' => 'SAN JUSTO'),
                array('id' => 3751, 'county_id' => '475', 'value' => 'SAN MARTIN NORTE'),
                array('id' => 3752, 'county_id' => '475', 'value' => 'SILVA'),
                array('id' => 3753, 'county_id' => '475', 'value' => 'VERA Y PINTADO'),
                array('id' => 3754, 'county_id' => '475', 'value' => 'VIDELA'),
                array('id' => 3755, 'county_id' => '476', 'value' => 'ALDAO'),
                array('id' => 3756, 'county_id' => '476', 'value' => 'CAPITAN BERMUDEZ'),
                array('id' => 3757, 'county_id' => '476', 'value' => 'CARCARAÑA'),
                array('id' => 3758, 'county_id' => '476', 'value' => 'CORONEL ARNOLD'),
                array('id' => 3759, 'county_id' => '476', 'value' => 'FRAY LUIS BELTRAN'),
                array('id' => 3760, 'county_id' => '476', 'value' => 'FUENTES'),
                array('id' => 3761, 'county_id' => '476', 'value' => 'LUIS PALACIOS'),
                array('id' => 3762, 'county_id' => '476', 'value' => 'PUERTO GENERAL SAN MARTIN'),
                array('id' => 3763, 'county_id' => '476', 'value' => 'PUJATO'),
                array('id' => 3764, 'county_id' => '476', 'value' => 'RICARDONE'),
                array('id' => 3765, 'county_id' => '476', 'value' => 'ROLDAN'),
                array('id' => 3766, 'county_id' => '476', 'value' => 'SAN JERONIMO SUD'),
                array('id' => 3767, 'county_id' => '476', 'value' => 'SAN LORENZO'),
                array('id' => 3768, 'county_id' => '476', 'value' => 'TIMBUES'),
                array('id' => 3769, 'county_id' => '476', 'value' => 'VILLA ELVIRA'),
                array('id' => 3770, 'county_id' => '476', 'value' => 'VILLA MUGUETA'),
                array('id' => 3771, 'county_id' => '477', 'value' => 'CAÑADA ROSQUIN'),
                array('id' => 3772, 'county_id' => '477', 'value' => 'CARLOS PELLEGRINI'),
                array('id' => 3773, 'county_id' => '477', 'value' => 'CASAS'),
                array('id' => 3774, 'county_id' => '477', 'value' => 'CASTELAR'),
                array('id' => 3775, 'county_id' => '477', 'value' => 'COLONIA BELGRANO'),
                array('id' => 3776, 'county_id' => '477', 'value' => 'CRISPI'),
                array('id' => 3777, 'county_id' => '477', 'value' => 'EL TREBOL'),
                array('id' => 3778, 'county_id' => '477', 'value' => 'LANDETA'),
                array('id' => 3779, 'county_id' => '477', 'value' => 'LAS BANDURRIAS'),
                array('id' => 3780, 'county_id' => '477', 'value' => 'LAS PETACAS'),
                array('id' => 3781, 'county_id' => '477', 'value' => 'LOS CARDOS'),
                array('id' => 3782, 'county_id' => '477', 'value' => 'MARIA SUSANA'),
                array('id' => 3783, 'county_id' => '477', 'value' => 'PIAMONTE'),
                array('id' => 3784, 'county_id' => '477', 'value' => 'SAN JORGE'),
                array('id' => 3785, 'county_id' => '477', 'value' => 'SAN MARTIN DE LAS ESCOBAS'),
                array('id' => 3786, 'county_id' => '477', 'value' => 'SASTRE'),
                array('id' => 3787, 'county_id' => '477', 'value' => 'TRAILL'),
                array('id' => 3788, 'county_id' => '477', 'value' => 'WILDERMUTH'),
                array('id' => 3789, 'county_id' => '478', 'value' => 'CAÑADA OMBU'),
                array('id' => 3790, 'county_id' => '478', 'value' => 'CALCHAQUI'),
                array('id' => 3791, 'county_id' => '478', 'value' => 'COLMENA'),
                array('id' => 3792, 'county_id' => '478', 'value' => 'FORTIN OLMOS'),
                array('id' => 3793, 'county_id' => '478', 'value' => 'GARABATO'),
                array('id' => 3794, 'county_id' => '478', 'value' => 'GOLONDRINA'),
                array('id' => 3795, 'county_id' => '478', 'value' => 'INTIYACO'),
                array('id' => 3796, 'county_id' => '478', 'value' => 'KILOMETRO 115'),
                array('id' => 3797, 'county_id' => '478', 'value' => 'LA GALLARETA'),
                array('id' => 3798, 'county_id' => '478', 'value' => 'LOS AMORES'),
                array('id' => 3799, 'county_id' => '478', 'value' => 'MARGARITA'),
                array('id' => 3800, 'county_id' => '478', 'value' => 'PARAJE 29'),
                array('id' => 3801, 'county_id' => '478', 'value' => 'POZO DE LOS INDIOS'),
                array('id' => 3802, 'county_id' => '478', 'value' => 'PUEBLO SANTA LUCIA'),
                array('id' => 3803, 'county_id' => '478', 'value' => 'TARTAGAL'),
                array('id' => 3804, 'county_id' => '478', 'value' => 'TOBA'),
                array('id' => 3805, 'county_id' => '478', 'value' => 'VERA'),
                array('id' => 3806, 'county_id' => '479', 'value' => 'ALCORTA'),
                array('id' => 3807, 'county_id' => '479', 'value' => 'BARRIO ARROYO DEL MEDIO'),
                array('id' => 3808, 'county_id' => '479', 'value' => 'BARRIO MITRE'),
                array('id' => 3809, 'county_id' => '479', 'value' => 'BOMBAL'),
                array('id' => 3810, 'county_id' => '479', 'value' => 'CAÑADA RICA'),
                array('id' => 3811, 'county_id' => '479', 'value' => 'CEPEDA'),
                array('id' => 3812, 'county_id' => '479', 'value' => 'EMPALME VILLA CONSTITUCION'),
                array('id' => 3813, 'county_id' => '479', 'value' => 'FIRMAT'),
                array('id' => 3814, 'county_id' => '479', 'value' => 'GENERAL GELLY'),
                array('id' => 3815, 'county_id' => '479', 'value' => 'GODOY'),
                array('id' => 3816, 'county_id' => '479', 'value' => 'JUAN B. MOLINA'),
                array('id' => 3817, 'county_id' => '479', 'value' => 'JUNCAL'),
                array('id' => 3818, 'county_id' => '479', 'value' => 'LA VANGUARDIA'),
                array('id' => 3819, 'county_id' => '479', 'value' => 'MAXIMO PAZ'),
                array('id' => 3820, 'county_id' => '479', 'value' => 'PAVON'),
                array('id' => 3821, 'county_id' => '479', 'value' => 'PAVON ARRIBA'),
                array('id' => 3822, 'county_id' => '479', 'value' => 'PEYRANO'),
                array('id' => 3823, 'county_id' => '479', 'value' => 'RUEDA'),
                array('id' => 3824, 'county_id' => '479', 'value' => 'SANTA TERESA'),
                array('id' => 3825, 'county_id' => '479', 'value' => 'SARGENTO CABRAL'),
                array('id' => 3826, 'county_id' => '479', 'value' => 'STEPHENSON'),
                array('id' => 3827, 'county_id' => '479', 'value' => 'THEOBALD'),
                array('id' => 3828, 'county_id' => '479', 'value' => 'VILLA CONSTITUCION'),
                array('id' => 3829, 'county_id' => '480', 'value' => 'ARGENTINA'),
                array('id' => 3830, 'county_id' => '480', 'value' => 'CASARES'),
                array('id' => 3831, 'county_id' => '480', 'value' => 'MALBRAN'),
                array('id' => 3832, 'county_id' => '480', 'value' => 'VILLA GENERAL MITRE'),
                array('id' => 3833, 'county_id' => '481', 'value' => 'CAMPO GALLO'),
                array('id' => 3834, 'county_id' => '481', 'value' => 'CORONEL MANUEL L. RICO'),
                array('id' => 3835, 'county_id' => '481', 'value' => 'DONADEU'),
                array('id' => 3836, 'county_id' => '481', 'value' => 'SACHAYOJ'),
                array('id' => 3837, 'county_id' => '481', 'value' => 'SANTOS LUGARES'),
                array('id' => 3838, 'county_id' => '482', 'value' => 'ESTACION ATAMISQUI'),
                array('id' => 3839, 'county_id' => '482', 'value' => 'MEDELLIN'),
                array('id' => 3840, 'county_id' => '482', 'value' => 'VILLA ATAMISQUI'),
                array('id' => 3841, 'county_id' => '483', 'value' => 'COLONIA DORA'),
                array('id' => 3842, 'county_id' => '483', 'value' => 'HERRERA'),
                array('id' => 3843, 'county_id' => '483', 'value' => 'ICAÑO'),
                array('id' => 3844, 'county_id' => '483', 'value' => 'LUGONES'),
                array('id' => 3845, 'county_id' => '483', 'value' => 'REAL SAYANA'),
                array('id' => 3846, 'county_id' => '483', 'value' => 'VILLA MAILIN'),
                array('id' => 3847, 'county_id' => '484', 'value' => 'ABRA GRANDE'),
                array('id' => 3848, 'county_id' => '484', 'value' => 'ANTAJE'),
                array('id' => 3849, 'county_id' => '484', 'value' => 'ARDILES'),
                array('id' => 3850, 'county_id' => '484', 'value' => 'CAÑADA ESCOBAR'),
                array('id' => 3851, 'county_id' => '484', 'value' => 'CHAUPI POZO'),
                array('id' => 3852, 'county_id' => '484', 'value' => 'CLODOMIRA'),
                array('id' => 3853, 'county_id' => '484', 'value' => 'HUYAMAMPA'),
                array('id' => 3854, 'county_id' => '484', 'value' => 'LA AURORA'),
                array('id' => 3855, 'county_id' => '484', 'value' => 'LA BANDA'),
                array('id' => 3856, 'county_id' => '484', 'value' => 'LA DARSENA'),
                array('id' => 3857, 'county_id' => '484', 'value' => 'LOS QUIROGA'),
                array('id' => 3858, 'county_id' => '484', 'value' => 'LOS SORIA'),
                array('id' => 3859, 'county_id' => '484', 'value' => 'SIMBOLAR'),
                array('id' => 3860, 'county_id' => '484', 'value' => 'TRAMO 16'),
                array('id' => 3861, 'county_id' => '484', 'value' => 'TRAMO 20'),
                array('id' => 3862, 'county_id' => '485', 'value' => 'BANDERA'),
                array('id' => 3863, 'county_id' => '485', 'value' => 'CUATRO BOCAS'),
                array('id' => 3864, 'county_id' => '485', 'value' => 'FORTIN INCA'),
                array('id' => 3865, 'county_id' => '485', 'value' => 'GUARDIA ESCOLTA'),
                array('id' => 3866, 'county_id' => '486', 'value' => 'EL DEAN'),
                array('id' => 3867, 'county_id' => '486', 'value' => 'EL MOJON'),
                array('id' => 3868, 'county_id' => '486', 'value' => 'EL ZANJON'),
                array('id' => 3869, 'county_id' => '486', 'value' => 'LOS CARDOZOS'),
                array('id' => 3870, 'county_id' => '486', 'value' => 'MACO'),
                array('id' => 3871, 'county_id' => '486', 'value' => 'MAQUITO'),
                array('id' => 3872, 'county_id' => '486', 'value' => 'MORALES'),
                array('id' => 3873, 'county_id' => '486', 'value' => 'PUESTO DE SAN ANTONIO'),
                array('id' => 3874, 'county_id' => '486', 'value' => 'SAN PEDRO'),
                array('id' => 3875, 'county_id' => '486', 'value' => 'SANTA MARIA'),
                array('id' => 3876, 'county_id' => '486', 'value' => 'SANTIAGO DEL ESTERO'),
                array('id' => 3877, 'county_id' => '486', 'value' => 'VUELTA DE LA BARRANCA'),
                array('id' => 3878, 'county_id' => '486', 'value' => 'YANDA'),
                array('id' => 3879, 'county_id' => '487', 'value' => 'ANCAJAN'),
                array('id' => 3880, 'county_id' => '487', 'value' => 'CHOYA'),
                array('id' => 3881, 'county_id' => '487', 'value' => 'ESTACION LA PUNTA'),
                array('id' => 3882, 'county_id' => '487', 'value' => 'FRIAS'),
                array('id' => 3883, 'county_id' => '487', 'value' => 'LAPRIDA'),
                array('id' => 3884, 'county_id' => '487', 'value' => 'SAN PEDRO'),
                array('id' => 3885, 'county_id' => '487', 'value' => 'TAPSO'),
                array('id' => 3886, 'county_id' => '487', 'value' => 'VILLA LA PUNTA'),
                array('id' => 3887, 'county_id' => '488', 'value' => 'EL CABURE'),
                array('id' => 3888, 'county_id' => '488', 'value' => 'LA FIRMEZA'),
                array('id' => 3889, 'county_id' => '488', 'value' => 'LOS PIRPINTOS'),
                array('id' => 3890, 'county_id' => '488', 'value' => 'LOS TIGRES'),
                array('id' => 3891, 'county_id' => '488', 'value' => 'MONTE QUEMADO'),
                array('id' => 3892, 'county_id' => '488', 'value' => 'NUEVA ESPERANZA'),
                array('id' => 3893, 'county_id' => '488', 'value' => 'PAMPA DE LOS GUANACOS'),
                array('id' => 3894, 'county_id' => '488', 'value' => 'SAN JOSE DEL BOQUERON'),
                array('id' => 3895, 'county_id' => '488', 'value' => 'URUTAU'),
                array('id' => 3896, 'county_id' => '489', 'value' => 'BANDERA BAJADA'),
                array('id' => 3897, 'county_id' => '489', 'value' => 'CASPI CORRAL'),
                array('id' => 3898, 'county_id' => '489', 'value' => 'COLONIA SAN JUAN'),
                array('id' => 3899, 'county_id' => '489', 'value' => 'EL CRUCERO'),
                array('id' => 3900, 'county_id' => '489', 'value' => 'KILOMETRO 30'),
                array('id' => 3901, 'county_id' => '489', 'value' => 'LA CAÑADA'),
                array('id' => 3902, 'county_id' => '489', 'value' => 'LA INVERNADA'),
                array('id' => 3903, 'county_id' => '489', 'value' => 'MINERVA'),
                array('id' => 3904, 'county_id' => '489', 'value' => 'VACA HUAÑUNA'),
                array('id' => 3905, 'county_id' => '489', 'value' => 'VILLA FIGUEROA'),
                array('id' => 3906, 'county_id' => '490', 'value' => 'AÑATUYA'),
                array('id' => 3907, 'county_id' => '490', 'value' => 'AVERIAS'),
                array('id' => 3908, 'county_id' => '490', 'value' => 'ESTACION TACAÑITAS'),
                array('id' => 3909, 'county_id' => '490', 'value' => 'LA NENA'),
                array('id' => 3910, 'county_id' => '490', 'value' => 'LOS JURIES'),
                array('id' => 3911, 'county_id' => '490', 'value' => 'TOMAS YOUNG'),
                array('id' => 3912, 'county_id' => '491', 'value' => 'LAVALLE'),
                array('id' => 3913, 'county_id' => '491', 'value' => 'SAN PEDRO'),
                array('id' => 3914, 'county_id' => '492', 'value' => 'EL ARENAL'),
                array('id' => 3915, 'county_id' => '492', 'value' => 'EL BOBADAL'),
                array('id' => 3916, 'county_id' => '492', 'value' => 'EL CHARCO'),
                array('id' => 3917, 'county_id' => '492', 'value' => 'EL RINCON'),
                array('id' => 3918, 'county_id' => '492', 'value' => 'GRAMILLA'),
                array('id' => 3919, 'county_id' => '492', 'value' => 'ISCA YACU'),
                array('id' => 3920, 'county_id' => '492', 'value' => 'ISCA YACU SEMAUL'),
                array('id' => 3921, 'county_id' => '492', 'value' => 'POZO HONDO'),
                array('id' => 3922, 'county_id' => '492', 'value' => 'SAN PEDRO'),
                array('id' => 3923, 'county_id' => '493', 'value' => 'EL COLORADO'),
                array('id' => 3924, 'county_id' => '493', 'value' => 'EL CUADRADO'),
                array('id' => 3925, 'county_id' => '493', 'value' => 'MATARA'),
                array('id' => 3926, 'county_id' => '493', 'value' => 'SUNCHO CORRAL'),
                array('id' => 3927, 'county_id' => '493', 'value' => 'VILELAS'),
                array('id' => 3928, 'county_id' => '493', 'value' => 'YUCHAN'),
                array('id' => 3929, 'county_id' => '494', 'value' => 'VILLA SAN MARTIN'),
                array('id' => 3930, 'county_id' => '495', 'value' => 'VILLA UNION'),
                array('id' => 3931, 'county_id' => '496', 'value' => 'AEROLITO'),
                array('id' => 3932, 'county_id' => '496', 'value' => 'ALHUAMPA'),
                array('id' => 3933, 'county_id' => '496', 'value' => 'HASSE'),
                array('id' => 3934, 'county_id' => '496', 'value' => 'HERNAN MEJIA MIRAVAL'),
                array('id' => 3935, 'county_id' => '496', 'value' => 'LAS TINAJAS'),
                array('id' => 3936, 'county_id' => '496', 'value' => 'LIBERTAD'),
                array('id' => 3937, 'county_id' => '496', 'value' => 'LILO VIEJO'),
                array('id' => 3938, 'county_id' => '496', 'value' => 'PATAY'),
                array('id' => 3939, 'county_id' => '496', 'value' => 'PUEBLO PABLO TORELO'),
                array('id' => 3940, 'county_id' => '496', 'value' => 'QUIMILI'),
                array('id' => 3941, 'county_id' => '496', 'value' => 'ROVERSI'),
                array('id' => 3942, 'county_id' => '496', 'value' => 'TINTINA'),
                array('id' => 3943, 'county_id' => '496', 'value' => 'WEISBURD'),
                array('id' => 3944, 'county_id' => '497', 'value' => 'EL 49'),
                array('id' => 3945, 'county_id' => '497', 'value' => 'SOL DE JULIO'),
                array('id' => 3946, 'county_id' => '497', 'value' => 'VILLA OJO DE AGUA'),
                array('id' => 3947, 'county_id' => '498', 'value' => 'EL MOJON'),
                array('id' => 3948, 'county_id' => '498', 'value' => 'LAS DELICIAS'),
                array('id' => 3949, 'county_id' => '498', 'value' => 'NUEVA ESPERANZA'),
                array('id' => 3950, 'county_id' => '498', 'value' => 'POZO BETBEDER'),
                array('id' => 3951, 'county_id' => '498', 'value' => 'RAPELLI'),
                array('id' => 3952, 'county_id' => '498', 'value' => 'SANTO DOMINGO'),
                array('id' => 3953, 'county_id' => '499', 'value' => 'RAMIREZ DE VELAZCO'),
                array('id' => 3954, 'county_id' => '499', 'value' => 'SUMAMPA'),
                array('id' => 3955, 'county_id' => '499', 'value' => 'SUMAMPA VIEJO'),
                array('id' => 3956, 'county_id' => '500', 'value' => 'CHAÑAR POZO DE ABAJO'),
                array('id' => 3957, 'county_id' => '500', 'value' => 'CHAUCHILLAS'),
                array('id' => 3958, 'county_id' => '500', 'value' => 'COLONIA TINCO'),
                array('id' => 3959, 'county_id' => '500', 'value' => 'EL CHARCO'),
                array('id' => 3960, 'county_id' => '500', 'value' => 'GRAMILLA'),
                array('id' => 3961, 'county_id' => '500', 'value' => 'LA NUEVA DONOSA'),
                array('id' => 3962, 'county_id' => '500', 'value' => 'LOS MIRANDA'),
                array('id' => 3963, 'county_id' => '500', 'value' => 'LOS NUÑEZ'),
                array('id' => 3964, 'county_id' => '500', 'value' => 'MANSUPA'),
                array('id' => 3965, 'county_id' => '500', 'value' => 'POZUELOS'),
                array('id' => 3966, 'county_id' => '500', 'value' => 'RODEO DE VALDEZ'),
                array('id' => 3967, 'county_id' => '500', 'value' => 'SAUZAL'),
                array('id' => 3968, 'county_id' => '500', 'value' => 'TERMAS DE RIO HONDO'),
                array('id' => 3969, 'county_id' => '500', 'value' => 'VILLA GIMENEZ'),
                array('id' => 3970, 'county_id' => '500', 'value' => 'VILLA RIO HONDO'),
                array('id' => 3971, 'county_id' => '500', 'value' => 'VILLA TURISTICA DEL EMBALSE'),
                array('id' => 3972, 'county_id' => '500', 'value' => 'VINARA'),
                array('id' => 3973, 'county_id' => '501', 'value' => 'COLONIA ALPINA'),
                array('id' => 3974, 'county_id' => '501', 'value' => 'PALO NEGRO'),
                array('id' => 3975, 'county_id' => '501', 'value' => 'SELVA'),
                array('id' => 3976, 'county_id' => '502', 'value' => 'BELTRAN'),
                array('id' => 3977, 'county_id' => '502', 'value' => 'COLONIA EL SIMBOLAR'),
                array('id' => 3978, 'county_id' => '502', 'value' => 'FERNANDEZ'),
                array('id' => 3979, 'county_id' => '502', 'value' => 'INGENIERO FORRES'),
                array('id' => 3980, 'county_id' => '502', 'value' => 'VILMER'),
                array('id' => 3981, 'county_id' => '503', 'value' => 'CHILCA JULIANA'),
                array('id' => 3982, 'county_id' => '503', 'value' => 'LOS TELARES'),
                array('id' => 3983, 'county_id' => '503', 'value' => 'VILLA SALAVINA'),
                array('id' => 3984, 'county_id' => '504', 'value' => 'BREA POZO'),
                array('id' => 3985, 'county_id' => '504', 'value' => 'ESTACION ROBLES'),
                array('id' => 3986, 'county_id' => '504', 'value' => 'ESTACION TABOADA'),
                array('id' => 3987, 'county_id' => '504', 'value' => 'VILLA NUEVA'),
                array('id' => 3988, 'county_id' => '505', 'value' => 'GARZA'),
                array('id' => 3989, 'county_id' => '506', 'value' => 'ARRAGA'),
                array('id' => 3990, 'county_id' => '506', 'value' => 'NUEVA FRANCIA'),
                array('id' => 3991, 'county_id' => '506', 'value' => 'SIMBOL'),
                array('id' => 3992, 'county_id' => '506', 'value' => 'SUMAMAO'),
                array('id' => 3993, 'county_id' => '506', 'value' => 'VILLA SILIPICA'),
                array('id' => 3994, 'county_id' => '507', 'value' => 'RIO GRANDE'),
                array('id' => 3995, 'county_id' => '507', 'value' => 'TOLHUIN'),
                array('id' => 3996, 'county_id' => '508', 'value' => 'LAGUNA ESCONDIDA'),
                array('id' => 3997, 'county_id' => '508', 'value' => 'USHUAIA'),
                array('id' => 3998, 'county_id' => '509', 'value' => '7 DE ABRIL'),
                array('id' => 3999, 'county_id' => '509', 'value' => 'BARRIO SAN JORGE'),
                array('id' => 4000, 'county_id' => '509', 'value' => 'EL CHAÑAR')
                )
            );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('cities_table_3', function (Blueprint $table) {
            //
        });
    }
}
