<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddRecordsToCitiesTable5 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('cities')->insert(
            array(
                array('id' => 4110, 'county_id' => '526', 'value' => 'MONTEVIDEO'),
                array('id' => 4111, 'county_id' => '527', 'value' => 'ARTIGAS'),
                array('id' => 4112, 'county_id' => '527', 'value' => 'BELLA UNION'),
                array('id' => 4113, 'county_id' => '527', 'value' => 'TOMAS GOMENSORO'),
                array('id' => 4114, 'county_id' => '527', 'value' => 'BALTASAR BRUM'),
                array('id' => 4115, 'county_id' => '527', 'value' => 'BERNABE RIVERA'),
                array('id' => 4116, 'county_id' => '527', 'value' => 'FRANQUIA'),
                array('id' => 4117, 'county_id' => '527', 'value' => 'SEQUEIRA'),
                array('id' => 4118, 'county_id' => '527', 'value' => 'CORONADO'),
                array('id' => 4119, 'county_id' => '527', 'value' => 'CUAREIM'),
                array('id' => 4120, 'county_id' => '527', 'value' => 'CUARO'),
                array('id' => 4121, 'county_id' => '527', 'value' => 'JAVIER DE VIANA'),
                array('id' => 4122, 'county_id' => '527', 'value' => 'LA BOLSA'),
                array('id' => 4123, 'county_id' => '527', 'value' => 'LAS PIEDRAS'),
                array('id' => 4124, 'county_id' => '527', 'value' => 'PINTADITO'),
                array('id' => 4125, 'county_id' => '527', 'value' => 'PORT. DE HIERRO Y CAMPODONICO'),
                array('id' => 4126, 'county_id' => '527', 'value' => 'MONES QUINTELA'),
                array('id' => 4127, 'county_id' => '527', 'value' => 'CAINSA'),
                array('id' => 4128, 'county_id' => '527', 'value' => 'PASO CAMPAMENTO'),
                array('id' => 4129, 'county_id' => '527', 'value' => 'DIEGO LAMAS'),
                array('id' => 4130, 'county_id' => '527', 'value' => 'PASO FARIAS'),
                array('id' => 4131, 'county_id' => '527', 'value' => 'RINCON DE PACHECO'),
                array('id' => 4132, 'county_id' => '527', 'value' => 'TOPADOR'),
                array('id' => 4133, 'county_id' => '527', 'value' => 'CERRO EJIDO'),
                array('id' => 4134, 'county_id' => '527', 'value' => 'COLONIA PALMA'),
                array('id' => 4135, 'county_id' => '527', 'value' => 'CERRO SIGNORELLI (EL MIRADOR)'),
                array('id' => 4136, 'county_id' => '527', 'value' => 'CERRO SAN EUGENIO'),
                array('id' => 4137, 'county_id' => '527', 'value' => 'CALNU'),
                array('id' => 4138, 'county_id' => '528', 'value' => 'LAS PIEDRAS'),
                array('id' => 4139, 'county_id' => '528', 'value' => 'CANELONES'),
                array('id' => 4140, 'county_id' => '528', 'value' => 'LA PAZ'),
                array('id' => 4141, 'county_id' => '528', 'value' => 'PANDO'),
                array('id' => 4142, 'county_id' => '528', 'value' => 'SANTA LUCIA'),
                array('id' => 4143, 'county_id' => '528', 'value' => 'PIEDRAS DE AFILAR'),
                array('id' => 4144, 'county_id' => '528', 'value' => 'CUMBRES DE CARRASCO'),
                array('id' => 4145, 'county_id' => '528', 'value' => 'HARAS DEL LAGO'),
                array('id' => 4146, 'county_id' => '528', 'value' => 'QUINTA LOS HORNEROS'),
                array('id' => 4147, 'county_id' => '528', 'value' => 'LAS HIGUERITAS'),
                array('id' => 4148, 'county_id' => '528', 'value' => 'SOFIA SANTOS'),
                array('id' => 4149, 'county_id' => '528', 'value' => 'PROGRESO'),
                array('id' => 4150, 'county_id' => '528', 'value' => 'SAN RAMON'),
                array('id' => 4151, 'county_id' => '528', 'value' => 'BARROS BLANCOS'),
                array('id' => 4152, 'county_id' => '528', 'value' => 'COLONIA NICOLICH'),
                array('id' => 4153, 'county_id' => '528', 'value' => 'JOAQUIN SUAREZ'),
                array('id' => 4154, 'county_id' => '528', 'value' => 'PASO CARRASCO'),
                array('id' => 4155, 'county_id' => '528', 'value' => 'SANTA ROSA'),
                array('id' => 4156, 'county_id' => '528', 'value' => 'SAUCE'),
                array('id' => 4157, 'county_id' => '528', 'value' => 'TALA'),
                array('id' => 4158, 'county_id' => '528', 'value' => 'VILLA CRESPO Y SAN ANDRES'),
                array('id' => 4159, 'county_id' => '528', 'value' => 'FRACC. CNO. ANDALUZ Y R.84'),
                array('id' => 4160, 'county_id' => '528', 'value' => 'ATLANTIDA'),
                array('id' => 4161, 'county_id' => '528', 'value' => 'ESTACION ATLANTIDA'),
                array('id' => 4162, 'county_id' => '528', 'value' => 'CERRILLOS'),
                array('id' => 4163, 'county_id' => '528', 'value' => 'EMPALME OLMOS'),
                array('id' => 4164, 'county_id' => '528', 'value' => 'MIGUES'),
                array('id' => 4165, 'county_id' => '528', 'value' => 'PARQUE DEL PLATA'),
                array('id' => 4166, 'county_id' => '528', 'value' => 'SAN BAUTISTA'),
                array('id' => 4167, 'county_id' => '528', 'value' => 'SAN JACINTO'),
                array('id' => 4168, 'county_id' => '528', 'value' => 'DR. FRANCISCO SOCA'),
                array('id' => 4169, 'county_id' => '528', 'value' => 'TOLEDO'),
                array('id' => 4170, 'county_id' => '528', 'value' => 'MONTES'),
                array('id' => 4171, 'county_id' => '528', 'value' => 'SAN JOSE DE CARRASCO'),
                array('id' => 4172, 'county_id' => '528', 'value' => 'FRACC. SOBRE RUTA 74'),
                array('id' => 4173, 'county_id' => '528', 'value' => 'AGUAS CORRIENTES'),
                array('id' => 4174, 'county_id' => '528', 'value' => 'BARRA DE CARRASCO'),
                array('id' => 4175, 'county_id' => '528', 'value' => 'JUANICO'),
                array('id' => 4176, 'county_id' => '528', 'value' => 'LA FLORESTA'),
                array('id' => 4177, 'county_id' => '528', 'value' => 'ESTACION LA FLORESTA'),
                array('id' => 4178, 'county_id' => '528', 'value' => 'LAS TOSCAS'),
                array('id' => 4179, 'county_id' => '528', 'value' => 'PARQUE CARRASCO'),
                array('id' => 4180, 'county_id' => '528', 'value' => 'SALINAS'),
                array('id' => 4181, 'county_id' => '528', 'value' => 'SAN ANTONIO'),
                array('id' => 4182, 'county_id' => '528', 'value' => 'AEROPUERTO INTERNACIONAL DE CARRAS'),
                array('id' => 4183, 'county_id' => '528', 'value' => 'SOLYMAR'),
                array('id' => 4184, 'county_id' => '528', 'value' => 'VILLA AEROPARQUE'),
                array('id' => 4185, 'county_id' => '528', 'value' => 'CASTELLANOS'),
                array('id' => 4186, 'county_id' => '528', 'value' => 'BARRIO COPOLA'),
                array('id' => 4187, 'county_id' => '528', 'value' => 'COSTA AZUL'),
                array('id' => 4188, 'county_id' => '528', 'value' => 'COSTA Y GUILLAMON'),
                array('id' => 4189, 'county_id' => '528', 'value' => 'EL PINAR'),
                array('id' => 4190, 'county_id' => '528', 'value' => 'ESTACION MIGUES'),
                array('id' => 4191, 'county_id' => '528', 'value' => 'PINAMAR - PINEPARK'),
                array('id' => 4192, 'county_id' => '528', 'value' => 'LAGOMAR'),
                array('id' => 4193, 'county_id' => '528', 'value' => 'OLMOS'),
                array('id' => 4194, 'county_id' => '528', 'value' => 'PARADA CABRERA'),
                array('id' => 4195, 'county_id' => '528', 'value' => 'SAN LUIS'),
                array('id' => 4196, 'county_id' => '528', 'value' => 'SHANGRILA'),
                array('id' => 4197, 'county_id' => '528', 'value' => 'TOTORAL DEL SAUCE'),
                array('id' => 4198, 'county_id' => '528', 'value' => 'VILLA FELICIDAD'),
                array('id' => 4199, 'county_id' => '528', 'value' => 'VILLA PAZ S.A.'),
                array('id' => 4200, 'county_id' => '528', 'value' => 'VILLA SAN JOSE'),
                array('id' => 4201, 'county_id' => '528', 'value' => 'ESTACION TAPIA'),
                array('id' => 4202, 'county_id' => '528', 'value' => 'VILLA SAN FELIPE'),
                array('id' => 4203, 'county_id' => '528', 'value' => 'VILLA HADITA'),
                array('id' => 4204, 'county_id' => '528', 'value' => 'PASO DE PACHE'),
                array('id' => 4205, 'county_id' => '528', 'value' => 'CITY GOLF'),
                array('id' => 4206, 'county_id' => '528', 'value' => 'VIEJO MOLINO SAN BERNARDO'),
                array('id' => 4207, 'county_id' => '528', 'value' => 'ESTANQUE DE PANDO'),
                array('id' => 4208, 'county_id' => '528', 'value' => 'JARDINES DE PANDO'),
                array('id' => 4209, 'county_id' => '528', 'value' => 'PASO ESPINOSA'),
                array('id' => 4210, 'county_id' => '528', 'value' => 'ARAMINDA'),
                array('id' => 4211, 'county_id' => '528', 'value' => 'ARGENTINO'),
                array('id' => 4212, 'county_id' => '528', 'value' => 'BELLO HORIZONTE'),
                array('id' => 4213, 'county_id' => '528', 'value' => 'BIARRITZ'),
                array('id' => 4214, 'county_id' => '528', 'value' => 'BOLIVAR'),
                array('id' => 4215, 'county_id' => '528', 'value' => 'CAMPO MILITAR'),
                array('id' => 4216, 'county_id' => '528', 'value' => 'CAPILLA DE CELLA'),
                array('id' => 4217, 'county_id' => '528', 'value' => 'CRUZ DE LOS CAMINOS'),
                array('id' => 4218, 'county_id' => '528', 'value' => 'CUCHILLA ALTA'),
                array('id' => 4219, 'county_id' => '528', 'value' => 'EL BOSQUE'),
                array('id' => 4220, 'county_id' => '528', 'value' => 'ESTACION PEDRERA'),
                array('id' => 4221, 'county_id' => '528', 'value' => 'FORTIN DE SANTA ROSA'),
                array('id' => 4222, 'county_id' => '528', 'value' => 'FRACC. PROGRESO'),
                array('id' => 4223, 'county_id' => '528', 'value' => 'INSTITUTO ADVENTISTA'),
                array('id' => 4224, 'county_id' => '528', 'value' => 'JAUREGUIBERRY'),
                array('id' => 4225, 'county_id' => '528', 'value' => 'LA LUCHA'),
                array('id' => 4226, 'county_id' => '528', 'value' => 'LA MONTAÑESA'),
                array('id' => 4227, 'county_id' => '528', 'value' => 'LOMAS DE SOLYMAR'),
                array('id' => 4228, 'county_id' => '528', 'value' => 'LOS TITANES'),
                array('id' => 4229, 'county_id' => '528', 'value' => 'MARINDIA'),
                array('id' => 4230, 'county_id' => '528', 'value' => 'NEPTUNIA'),
                array('id' => 4231, 'county_id' => '528', 'value' => 'PASO DE LA CADENA'),
                array('id' => 4232, 'county_id' => '528', 'value' => 'PASO PALOMEQUE'),
                array('id' => 4233, 'county_id' => '528', 'value' => 'PIEDRA DEL TORO'),
                array('id' => 4234, 'county_id' => '528', 'value' => 'ESTACION PIEDRAS DE AFILAR'),
                array('id' => 4235, 'county_id' => '528', 'value' => 'EL GALEON'),
                array('id' => 4236, 'county_id' => '528', 'value' => 'SANTA ANA'),
                array('id' => 4237, 'county_id' => '528', 'value' => 'SANTA LUCIA DEL ESTE'),
                array('id' => 4238, 'county_id' => '528', 'value' => 'SEIS HERMANOS'),
                array('id' => 4239, 'county_id' => '528', 'value' => 'VILLA AREJO'),
                array('id' => 4240, 'county_id' => '528', 'value' => 'VILLA ARGENTINA'),
                array('id' => 4241, 'county_id' => '528', 'value' => 'VILLA PORVENIR'),
                array('id' => 4242, 'county_id' => '528', 'value' => 'LA TUNA'),
                array('id' => 4243, 'county_id' => '528', 'value' => 'GUAZU - VIRA'),
                array('id' => 4244, 'county_id' => '528', 'value' => 'COLINAS DE SOLYMAR'),
                array('id' => 4245, 'county_id' => '528', 'value' => 'BARRIO REMANSO'),
                array('id' => 4246, 'county_id' => '528', 'value' => 'VILLA EL TATO'),
                array('id' => 4247, 'county_id' => '528', 'value' => 'VILLA SAN CONO'),
                array('id' => 4248, 'county_id' => '528', 'value' => 'VILLA JUANA'),
                array('id' => 4249, 'county_id' => '528', 'value' => 'COLINAS DE CARRASCO'),
                array('id' => 4250, 'county_id' => '528', 'value' => 'LOMAS DE CARRASCO'),
                array('id' => 4251, 'county_id' => '528', 'value' => 'CARMEL'),
                array('id' => 4252, 'county_id' => '528', 'value' => 'LA ASUNCION'),
                array('id' => 4253, 'county_id' => '528', 'value' => 'QUINTAS DEL BOSQUE'),
                array('id' => 4254, 'county_id' => '528', 'value' => 'ALTOS DE LA TAHONA'),
                array('id' => 4255, 'county_id' => '529', 'value' => 'MELO'),
                array('id' => 4256, 'county_id' => '529', 'value' => 'FRAILE MUERTO'),
                array('id' => 4257, 'county_id' => '529', 'value' => 'RIO BRANCO'),
                array('id' => 4258, 'county_id' => '529', 'value' => 'TUPAMBAE'),
                array('id' => 4259, 'county_id' => '529', 'value' => 'ISIDORO NOBLIA'),
                array('id' => 4260, 'county_id' => '529', 'value' => 'ACEGUA'),
                array('id' => 4261, 'county_id' => '529', 'value' => 'BAÑADO DE MEDINA'),
                array('id' => 4262, 'county_id' => '529', 'value' => 'CENTURION'),
                array('id' => 4263, 'county_id' => '529', 'value' => 'CERRO DE LAS CUENTAS'),
                array('id' => 4264, 'county_id' => '529', 'value' => 'HIPODROMO'),
                array('id' => 4265, 'county_id' => '529', 'value' => 'PLACIDO ROSAS'),
                array('id' => 4266, 'county_id' => '529', 'value' => 'TOLEDO'),
                array('id' => 4267, 'county_id' => '529', 'value' => 'TRES ISLAS'),
                array('id' => 4268, 'county_id' => '529', 'value' => 'POBLADO URUGUAY'),
                array('id' => 4269, 'county_id' => '529', 'value' => 'ARBOLITO'),
                array('id' => 4270, 'county_id' => '529', 'value' => 'AREVALO'),
                array('id' => 4271, 'county_id' => '529', 'value' => 'CASERIO LAS CAÑAS'),
                array('id' => 4272, 'county_id' => '529', 'value' => 'ESPERANZA'),
                array('id' => 4273, 'county_id' => '529', 'value' => 'GETULIO VARGAS'),
                array('id' => 4274, 'county_id' => '529', 'value' => 'LA PEDRERA'),
                array('id' => 4275, 'county_id' => '529', 'value' => 'LAGO MERIN'),
                array('id' => 4276, 'county_id' => '529', 'value' => 'MANGRULLO'),
                array('id' => 4277, 'county_id' => '529', 'value' => 'NANDO'),
                array('id' => 4278, 'county_id' => '529', 'value' => 'QUEBRACHO'),
                array('id' => 4279, 'county_id' => '529', 'value' => 'RAMON TRIGO'),
                array('id' => 4280, 'county_id' => '529', 'value' => 'SOTO GORO'),
                array('id' => 4281, 'county_id' => '529', 'value' => 'BARRIO LOPEZ BENITEZ'),
                array('id' => 4282, 'county_id' => '529', 'value' => 'BARRIO LA VINCHUCA'),
                array('id' => 4283, 'county_id' => '529', 'value' => 'ARACHANIA'),
                array('id' => 4284, 'county_id' => '529', 'value' => 'ÑANGAPIRE'),
                array('id' => 4285, 'county_id' => '530', 'value' => 'COLONIA DEL SACRAMENTO'),
                array('id' => 4286, 'county_id' => '530', 'value' => 'CARMELO'),
                array('id' => 4287, 'county_id' => '530', 'value' => 'JUAN LACAZE'),
                array('id' => 4288, 'county_id' => '530', 'value' => 'NUEVA HELVECIA'),
                array('id' => 4289, 'county_id' => '530', 'value' => 'ROSARIO'),
                array('id' => 4290, 'county_id' => '530', 'value' => 'NUEVA PALMIRA'),
                array('id' => 4291, 'county_id' => '530', 'value' => 'PASO ANTOLIN'),
                array('id' => 4292, 'county_id' => '530', 'value' => 'OMBUES DE LAVALLE'),
                array('id' => 4293, 'county_id' => '530', 'value' => 'TARARIRAS'),
                array('id' => 4294, 'county_id' => '530', 'value' => 'COLONIA VALDENSE'),
                array('id' => 4295, 'county_id' => '530', 'value' => 'FLORENCIO SANCHEZ'),
                array('id' => 4296, 'county_id' => '530', 'value' => 'CONCHILLAS'),
                array('id' => 4297, 'county_id' => '530', 'value' => 'CASERIO EL CERRO'),
                array('id' => 4298, 'county_id' => '530', 'value' => 'LA PAZ'),
                array('id' => 4299, 'county_id' => '530', 'value' => 'RIACHUELO'),
                array('id' => 4300, 'county_id' => '530', 'value' => 'JUAN CARLOS CASEROS'),
                array('id' => 4301, 'county_id' => '530', 'value' => 'AGRACIADA'),
                array('id' => 4302, 'county_id' => '530', 'value' => 'BOCA DEL ROSARIO'),
                array('id' => 4303, 'county_id' => '530', 'value' => 'CUFRE'),
                array('id' => 4304, 'county_id' => '530', 'value' => 'EL SEMILLERO'),
                array('id' => 4305, 'county_id' => '530', 'value' => 'ESTACION ESTANZUELA'),
                array('id' => 4306, 'county_id' => '530', 'value' => 'CERROS DE SAN JUAN'),
                array('id' => 4307, 'county_id' => '530', 'value' => 'MIGUELETE'),
                array('id' => 4308, 'county_id' => '530', 'value' => 'CAMPANA'),
                array('id' => 4309, 'county_id' => '530', 'value' => 'ARTILLEROS'),
                array('id' => 4310, 'county_id' => '530', 'value' => 'BARKER'),
                array('id' => 4311, 'county_id' => '530', 'value' => 'EL ENSUEÑO'),
                array('id' => 4312, 'county_id' => '530', 'value' => 'BLANCA ARENA'),
                array('id' => 4313, 'county_id' => '530', 'value' => 'BRISAS DEL PLATA'),
                array('id' => 4314, 'county_id' => '530', 'value' => 'COLONIA COSMOPOLITA'),
                array('id' => 4315, 'county_id' => '530', 'value' => 'PARAJE MINUANO'),
                array('id' => 4316, 'county_id' => '530', 'value' => 'LOS PINOS'),
                array('id' => 4317, 'county_id' => '530', 'value' => 'CHICO TORINO'),
                array('id' => 4318, 'county_id' => '530', 'value' => 'LA HORQUETA'),
                array('id' => 4319, 'county_id' => '530', 'value' => 'PLAYA AZUL'),
                array('id' => 4320, 'county_id' => '530', 'value' => 'PLAYA BRITOPOLIS'),
                array('id' => 4321, 'county_id' => '530', 'value' => 'PLAYA PARANT'),
                array('id' => 4322, 'county_id' => '530', 'value' => 'PLAYA FOMENTO'),
                array('id' => 4323, 'county_id' => '530', 'value' => 'PUERTO INGLES'),
                array('id' => 4324, 'county_id' => '530', 'value' => 'RADIAL HERNANDEZ'),
                array('id' => 4325, 'county_id' => '530', 'value' => 'SAN PEDRO'),
                array('id' => 4326, 'county_id' => '530', 'value' => 'SANTA ANA'),
                array('id' => 4327, 'county_id' => '530', 'value' => 'SANTA REGINA'),
                array('id' => 4328, 'county_id' => '530', 'value' => 'ZAGARZAZU'),
                array('id' => 4329, 'county_id' => '530', 'value' => 'ARRIVILLAGA'),
                array('id' => 4330, 'county_id' => '530', 'value' => 'EL FARO'),
                array('id' => 4331, 'county_id' => '530', 'value' => 'LAGUNA DE LOS PATOS'),
                array('id' => 4332, 'county_id' => '530', 'value' => 'JUAN JACKSON'),
                array('id' => 4333, 'county_id' => '530', 'value' => 'PUEBLO GIL'),
                array('id' => 4334, 'county_id' => '530', 'value' => 'CERRO CARMELO'),
                array('id' => 4335, 'county_id' => '530', 'value' => 'EL QUINTON'),
                array('id' => 4336, 'county_id' => '531', 'value' => 'DURAZNO'),
                array('id' => 4337, 'county_id' => '531', 'value' => 'SARANDI DEL YI'),
                array('id' => 4338, 'county_id' => '531', 'value' => 'CARMEN'),
                array('id' => 4339, 'county_id' => '531', 'value' => 'BLANQUILLO'),
                array('id' => 4340, 'county_id' => '531', 'value' => 'LA PALOMA'),
                array('id' => 4341, 'county_id' => '531', 'value' => 'CARLOS REYLES'),
                array('id' => 4342, 'county_id' => '531', 'value' => 'CENTENARIO'),
                array('id' => 4343, 'county_id' => '531', 'value' => 'SANTA BERNARDINA'),
                array('id' => 4344, 'county_id' => '531', 'value' => 'CERRO CHATO'),
                array('id' => 4345, 'county_id' => '531', 'value' => 'BAYGORRIA'),
                array('id' => 4346, 'county_id' => '531', 'value' => 'AGUAS BUENAS'),
                array('id' => 4347, 'county_id' => '531', 'value' => 'PUEBLO DE ALVAREZ'),
                array('id' => 4348, 'county_id' => '531', 'value' => 'FELICIANO'),
                array('id' => 4349, 'county_id' => '531', 'value' => 'OMBUES DE ORIBE'),
                array('id' => 4350, 'county_id' => '531', 'value' => 'ROSSELL Y RIUS'),
                array('id' => 4351, 'county_id' => '531', 'value' => 'SAN JORGE'),
                array('id' => 4352, 'county_id' => '531', 'value' => 'LAS PALMAS'),
                array('id' => 4353, 'county_id' => '532', 'value' => 'TRINIDAD'),
                array('id' => 4354, 'county_id' => '532', 'value' => 'ISMAEL CORTINAS'),
                array('id' => 4355, 'county_id' => '532', 'value' => 'ANDRESITO'),
                array('id' => 4356, 'county_id' => '532', 'value' => 'JUAN JOSE CASTRO'),
                array('id' => 4357, 'county_id' => '532', 'value' => 'LA CASILLA'),
                array('id' => 4358, 'county_id' => '532', 'value' => 'CERRO COLORADO'),
                array('id' => 4359, 'county_id' => '533', 'value' => 'FLORIDA'),
                array('id' => 4360, 'county_id' => '533', 'value' => 'SARANDI GRANDE'),
                array('id' => 4361, 'county_id' => '533', 'value' => 'CASUPA'),
                array('id' => 4362, 'county_id' => '533', 'value' => 'CARDAL'),
                array('id' => 4363, 'county_id' => '533', 'value' => 'FRAY MARCOS'),
                array('id' => 4364, 'county_id' => '533', 'value' => '25 DE AGOSTO'),
                array('id' => 4365, 'county_id' => '533', 'value' => '25 DE MAYO'),
                array('id' => 4366, 'county_id' => '533', 'value' => 'ALEJANDRO GALLINAL'),
                array('id' => 4367, 'county_id' => '533', 'value' => 'CAPILLA DEL SAUCE'),
                array('id' => 4368, 'county_id' => '533', 'value' => 'LA CRUZ'),
                array('id' => 4369, 'county_id' => '533', 'value' => 'NICO PEREZ'),
                array('id' => 4370, 'county_id' => '533', 'value' => 'CERRO CHATO'),
                array('id' => 4371, 'county_id' => '533', 'value' => 'CHAMIZO'),
                array('id' => 4372, 'county_id' => '533', 'value' => 'GOÑI'),
                array('id' => 4373, 'county_id' => '533', 'value' => 'MENDOZA'),
                array('id' => 4374, 'county_id' => '533', 'value' => 'MENDOZA CHICO'),
                array('id' => 4375, 'county_id' => '533', 'value' => 'REBOLEDO'),
                array('id' => 4376, 'county_id' => '533', 'value' => 'VALENTINES'),
                array('id' => 4377, 'county_id' => '533', 'value' => 'BERRONDO'),
                array('id' => 4378, 'county_id' => '533', 'value' => 'PUEBLO FERRER'),
                array('id' => 4379, 'county_id' => '533', 'value' => 'INDEPENDENCIA'),
                array('id' => 4380, 'county_id' => '533', 'value' => 'MONTECORAL'),
                array('id' => 4381, 'county_id' => '533', 'value' => 'PINTADO'),
                array('id' => 4382, 'county_id' => '533', 'value' => 'POLANCO DEL YI'),
                array('id' => 4383, 'county_id' => '533', 'value' => 'PUNTAS DE MACIEL'),
                array('id' => 4384, 'county_id' => '533', 'value' => 'ILLESCAS'),
                array('id' => 4385, 'county_id' => '533', 'value' => 'CASERIO LA FUNDACION'),
                array('id' => 4386, 'county_id' => '533', 'value' => 'LA MACANA'),
                array('id' => 4387, 'county_id' => '533', 'value' => 'ESTACION CAPILLA DEL SAUCE'),
                array('id' => 4388, 'county_id' => '533', 'value' => 'SAN GABRIEL'),
                array('id' => 4389, 'county_id' => '534', 'value' => 'MINAS'),
                array('id' => 4390, 'county_id' => '534', 'value' => 'JOSE BATLLE Y ORDOÑEZ'),
                array('id' => 4391, 'county_id' => '534', 'value' => 'JOSE PEDRO VARELA'),
                array('id' => 4392, 'county_id' => '534', 'value' => 'MARISCALA'),
                array('id' => 4393, 'county_id' => '534', 'value' => 'SOLIS DE MATAOJO'),
                array('id' => 4394, 'county_id' => '534', 'value' => 'PIRARAJA'),
                array('id' => 4395, 'county_id' => '534', 'value' => 'ZAPICAN'),
                array('id' => 4396, 'county_id' => '534', 'value' => 'COLON'),
                array('id' => 4397, 'county_id' => '534', 'value' => 'ARAMENDIA'),
                array('id' => 4398, 'county_id' => '534', 'value' => 'BLANES VIALE'),
                array('id' => 4399, 'county_id' => '534', 'value' => '19 DE JUNIO'),
                array('id' => 4400, 'county_id' => '534', 'value' => 'ESTACION SOLIS'),
                array('id' => 4401, 'county_id' => '534', 'value' => 'GAETAN'),
                array('id' => 4402, 'county_id' => '534', 'value' => 'POLANCO NORTE'),
                array('id' => 4403, 'county_id' => '534', 'value' => 'VILLA DEL ROSARIO'),
                array('id' => 4404, 'county_id' => '534', 'value' => 'VILLA SERRANA'),
                array('id' => 4405, 'county_id' => '534', 'value' => 'BARRIO LA CORONILLA - ANCAP'),
                array('id' => 4406, 'county_id' => '534', 'value' => 'SAN FRANCISCO DE LAS SIERRAS'),
                array('id' => 4407, 'county_id' => '534', 'value' => 'ILLESCAS'),
                array('id' => 4408, 'county_id' => '535', 'value' => 'MALDONADO'),
                array('id' => 4409, 'county_id' => '535', 'value' => 'SAN CARLOS'),
                array('id' => 4410, 'county_id' => '535', 'value' => 'AIGUA'),
                array('id' => 4411, 'county_id' => '535', 'value' => 'PAN DE AZUCAR'),
                array('id' => 4412, 'county_id' => '535', 'value' => 'PIRIAPOLIS'),
                array('id' => 4413, 'county_id' => '535', 'value' => 'PUNTA DEL ESTE'),
                array('id' => 4414, 'county_id' => '535', 'value' => 'CERRO PELADO'),
                array('id' => 4415, 'county_id' => '535', 'value' => 'GARZON'),
                array('id' => 4416, 'county_id' => '535', 'value' => 'GERONA'),
                array('id' => 4417, 'county_id' => '535', 'value' => 'LAS FLORES - ESTACION'),
                array('id' => 4418, 'county_id' => '535', 'value' => 'LOS TALAS'),
                array('id' => 4419, 'county_id' => '535', 'value' => 'NUEVA CARRARA'),
                array('id' => 4420, 'county_id' => '535', 'value' => 'SOLIS'),
                array('id' => 4421, 'county_id' => '535', 'value' => 'PUEBLO SOLIS'),
                array('id' => 4422, 'county_id' => '535', 'value' => 'PINARES - LAS DELICIAS'),
                array('id' => 4423, 'county_id' => '535', 'value' => 'CHIHUAHUA'),
                array('id' => 4424, 'county_id' => '535', 'value' => 'VILLA DELIA'),
                array('id' => 4425, 'county_id' => '535', 'value' => 'SAN RAFAEL - EL PLACER'),
                array('id' => 4426, 'county_id' => '535', 'value' => 'BARRIO HIPODROMO'),
                array('id' => 4427, 'county_id' => '535', 'value' => 'LOS AROMOS'),
                array('id' => 4428, 'county_id' => '535', 'value' => 'BELLA VISTA'),
                array('id' => 4429, 'county_id' => '535', 'value' => 'CANTERAS DE MARELLI'),
                array('id' => 4430, 'county_id' => '535', 'value' => 'CERROS AZULES'),
                array('id' => 4431, 'county_id' => '535', 'value' => 'EL CHORRO'),
                array('id' => 4432, 'county_id' => '535', 'value' => 'EL EDEN'),
                array('id' => 4433, 'county_id' => '535', 'value' => 'EL TESORO'),
                array('id' => 4434, 'county_id' => '535', 'value' => 'FARO JOSE IGNACIO'),
                array('id' => 4435, 'county_id' => '535', 'value' => 'GREGORIO AZNAREZ'),
                array('id' => 4436, 'county_id' => '535', 'value' => 'LA BARRA'),
                array('id' => 4437, 'county_id' => '535', 'value' => 'LA CAPUERA'),
                array('id' => 4438, 'county_id' => '535', 'value' => 'LAS FLORES'),
                array('id' => 4439, 'county_id' => '535', 'value' => 'MANANTIALES'),
                array('id' => 4440, 'county_id' => '535', 'value' => 'OCEAN PARK'),
                array('id' => 4441, 'county_id' => '535', 'value' => 'PLAYA GRANDE'),
                array('id' => 4442, 'county_id' => '535', 'value' => 'PLAYA HERMOSA'),
                array('id' => 4443, 'county_id' => '535', 'value' => 'PLAYA VERDE'),
                array('id' => 4444, 'county_id' => '535', 'value' => 'PUNTA BALLENA'),
                array('id' => 4445, 'county_id' => '535', 'value' => 'PUNTA COLORADA'),
                array('id' => 4446, 'county_id' => '535', 'value' => 'PUNTA NEGRA'),
                array('id' => 4447, 'county_id' => '535', 'value' => 'RUTA 37 Y 9'),
                array('id' => 4448, 'county_id' => '535', 'value' => 'SAUCE DE PORTEZUELO'),
                array('id' => 4449, 'county_id' => '535', 'value' => 'SAN VICENTE'),
                array('id' => 4450, 'county_id' => '535', 'value' => 'BALNEARIO BUENOS AIRES'),
                array('id' => 4451, 'county_id' => '535', 'value' => 'LAS CUMBRES'),
                array('id' => 4452, 'county_id' => '535', 'value' => 'LOS CORCHOS'),
                array('id' => 4453, 'county_id' => '535', 'value' => 'SANTA MONICA'),
                array('id' => 4454, 'county_id' => '535', 'value' => 'EDEN ROCK'),
                array('id' => 4455, 'county_id' => '535', 'value' => 'PARQUE MEDINA'),
                array('id' => 4456, 'county_id' => '535', 'value' => 'ARENAS DE JOSE IGNACIO'),
                array('id' => 4457, 'county_id' => '535', 'value' => 'LA SONRISA'),
                array('id' => 4458, 'county_id' => '535', 'value' => 'EL QUIJOTE'),
                array('id' => 4459, 'county_id' => '535', 'value' => 'LAGUNA BLANCA'),
                array('id' => 4460, 'county_id' => '536', 'value' => 'PAYSANDU'),
                array('id' => 4461, 'county_id' => '536', 'value' => 'GUICHON'),
                array('id' => 4462, 'county_id' => '536', 'value' => 'NUEVO PAYSANDU'),
                array('id' => 4463, 'county_id' => '536', 'value' => 'QUEBRACHO'),
                array('id' => 4464, 'county_id' => '536', 'value' => 'TAMBORES'),
                array('id' => 4465, 'county_id' => '536', 'value' => 'LORENZO GEYRES'),
                array('id' => 4466, 'county_id' => '536', 'value' => 'MERINOS'),
                array('id' => 4467, 'county_id' => '536', 'value' => 'PORVENIR'),
                array('id' => 4468, 'county_id' => '536', 'value' => 'ARBOLITO'),
                array('id' => 4469, 'county_id' => '536', 'value' => 'BEISSO'),
                array('id' => 4470, 'county_id' => '536', 'value' => 'CASABLANCA'),
                array('id' => 4471, 'county_id' => '536', 'value' => 'CERRO CHATO'),
                array('id' => 4472, 'county_id' => '536', 'value' => 'CONSTANCIA'),
                array('id' => 4473, 'county_id' => '536', 'value' => 'MORATO'),
                array('id' => 4474, 'county_id' => '536', 'value' => 'PIEDRAS COLORADAS'),
                array('id' => 4475, 'county_id' => '536', 'value' => 'PIÑERA'),
                array('id' => 4476, 'county_id' => '536', 'value' => 'SAN FELIX'),
                array('id' => 4477, 'county_id' => '536', 'value' => 'VILLA MARIA (TIATUCURA)'),
                array('id' => 4478, 'county_id' => '536', 'value' => 'PIEDRA SOLA'),
                array('id' => 4479, 'county_id' => '536', 'value' => 'ARAUJO'),
                array('id' => 4480, 'county_id' => '536', 'value' => 'BELLA VISTA'),
                array('id' => 4481, 'county_id' => '536', 'value' => 'CAÑADA DEL PUEBLO'),
                array('id' => 4482, 'county_id' => '536', 'value' => 'CHAPICUY'),
                array('id' => 4483, 'county_id' => '536', 'value' => 'EL EUCALIPTUS'),
                array('id' => 4484, 'county_id' => '536', 'value' => 'ESPERANZA'),
                array('id' => 4485, 'county_id' => '536', 'value' => 'PUEBLO FEDERACION'),
                array('id' => 4486, 'county_id' => '536', 'value' => 'LA TENTACION'),
                array('id' => 4487, 'county_id' => '536', 'value' => 'ORGOROSO'),
                array('id' => 4488, 'county_id' => '536', 'value' => 'CUCHILLA DE BURICAYUPI'),
                array('id' => 4489, 'county_id' => '536', 'value' => 'SOTO'),
                array('id' => 4490, 'county_id' => '536', 'value' => 'ZEBALLOS'),
                array('id' => 4491, 'county_id' => '536', 'value' => 'CHACRAS DE PAYSANDU'),
                array('id' => 4492, 'county_id' => '536', 'value' => 'GALLINAL'),
                array('id' => 4493, 'county_id' => '536', 'value' => 'PUNTAS DE ARROYO NEGRO'),
                array('id' => 4494, 'county_id' => '536', 'value' => 'ESTACION PORVENIR'),
                array('id' => 4495, 'county_id' => '536', 'value' => 'CUCHILLA DE FUEGO'),
                array('id' => 4496, 'county_id' => '536', 'value' => 'PUEBLO ALONZO'),
                array('id' => 4497, 'county_id' => '536', 'value' => 'QUEGUAYAR'),
                array('id' => 4498, 'county_id' => '536', 'value' => 'TERMAS DE GUAVIYU'),
                array('id' => 4499, 'county_id' => '536', 'value' => 'TERMAS DE ALMIRON'),
                array('id' => 4500, 'county_id' => '537', 'value' => 'FRAY BENTOS'),
                array('id' => 4501, 'county_id' => '537', 'value' => 'YOUNG'),
                array('id' => 4502, 'county_id' => '537', 'value' => 'NUEVO BERLIN'),
                array('id' => 4503, 'county_id' => '537', 'value' => 'SAN JAVIER'),
                array('id' => 4504, 'county_id' => '537', 'value' => 'BARRIO ANGLO'),
                array('id' => 4505, 'county_id' => '537', 'value' => 'GRECCO'),
                array('id' => 4506, 'county_id' => '537', 'value' => 'MERINOS'),
                array('id' => 4507, 'county_id' => '537', 'value' => 'ALGORTA'),
                array('id' => 4508, 'county_id' => '537', 'value' => 'EL OMBU'),
                array('id' => 4509, 'county_id' => '537', 'value' => 'PASO DE LOS MELLIZOS'),
                array('id' => 4510, 'county_id' => '537', 'value' => 'SARANDI DE NAVARRO'),
                array('id' => 4511, 'county_id' => '537', 'value' => 'VILLA GENERAL BORGES'),
                array('id' => 4512, 'county_id' => '537', 'value' => 'VILLA MARIA'),
                array('id' => 4513, 'county_id' => '537', 'value' => 'LAS CAÑAS'),
                array('id' => 4514, 'county_id' => '537', 'value' => 'BELLACO'),
                array('id' => 4515, 'county_id' => '537', 'value' => 'LOS ARRAYANES'),
                array('id' => 4516, 'county_id' => '537', 'value' => 'MENAFRA'),
                array('id' => 4517, 'county_id' => '537', 'value' => 'TRES QUINTAS'),
                array('id' => 4518, 'county_id' => '538', 'value' => 'RIVERA'),
                array('id' => 4519, 'county_id' => '538', 'value' => 'MINAS DE CORRALES'),
                array('id' => 4520, 'county_id' => '538', 'value' => 'TRANQUERAS'),
                array('id' => 4521, 'county_id' => '538', 'value' => 'VICHADERO'),
                array('id' => 4522, 'county_id' => '538', 'value' => 'SANTA TERESA'),
                array('id' => 4523, 'county_id' => '538', 'value' => 'ARROYO BLANCO'),
                array('id' => 4524, 'county_id' => '538', 'value' => 'PASO ATAQUES'),
                array('id' => 4525, 'county_id' => '538', 'value' => 'CERRO PELADO'),
                array('id' => 4526, 'county_id' => '538', 'value' => 'PASO HOSPITAL'),
                array('id' => 4527, 'county_id' => '538', 'value' => 'LAPUENTE'),
                array('id' => 4528, 'county_id' => '538', 'value' => 'LAS FLORES'),
                array('id' => 4529, 'county_id' => '538', 'value' => 'MOIRONES'),
                array('id' => 4530, 'county_id' => '538', 'value' => 'LA PEDRERA'),
                array('id' => 4531, 'county_id' => '538', 'value' => 'MANDUBI'),
                array('id' => 4532, 'county_id' => '538', 'value' => 'LAGUNON'),
                array('id' => 4533, 'county_id' => '538', 'value' => 'AMARILLO'),
                array('id' => 4534, 'county_id' => '538', 'value' => 'CERRILLADA'),
                array('id' => 4535, 'county_id' => '538', 'value' => 'CERROS DE LA CALERA'),
                array('id' => 4536, 'county_id' => '538', 'value' => 'LAGOS DEL NORTE'),
                array('id' => 4537, 'county_id' => '538', 'value' => 'MASOLLER'),
                array('id' => 4538, 'county_id' => '539', 'value' => 'ROCHA'),
                array('id' => 4539, 'county_id' => '539', 'value' => 'CASTILLOS'),
                array('id' => 4540, 'county_id' => '539', 'value' => 'LASCANO'),
                array('id' => 4541, 'county_id' => '539', 'value' => 'CHUY'),
                array('id' => 4542, 'county_id' => '539', 'value' => 'CEBOLLATI'),
                array('id' => 4543, 'county_id' => '539', 'value' => 'VELAZQUEZ'),
                array('id' => 4544, 'county_id' => '539', 'value' => '18 DE JULIO'),
                array('id' => 4545, 'county_id' => '539', 'value' => 'LA PALOMA'),
                array('id' => 4546, 'county_id' => '539', 'value' => 'SAN LUIS AL MEDIO'),
                array('id' => 4547, 'county_id' => '539', 'value' => 'LA AGUADA Y COSTA AZUL'),
                array('id' => 4548, 'county_id' => '539', 'value' => '19 DE ABRIL'),
                array('id' => 4549, 'county_id' => '539', 'value' => 'LA CORONILLA'),
                array('id' => 4550, 'county_id' => '539', 'value' => 'BARRIO PEREIRA'),
                array('id' => 4551, 'county_id' => '539', 'value' => 'AGUAS DULCES'),
                array('id' => 4552, 'county_id' => '539', 'value' => 'BARRA DEL CHUY'),
                array('id' => 4553, 'county_id' => '539', 'value' => 'BARRIO TORRES'),
                array('id' => 4554, 'county_id' => '539', 'value' => 'CABO POLONIO'),
                array('id' => 4555, 'county_id' => '539', 'value' => 'CAPACHO'),
                array('id' => 4556, 'county_id' => '539', 'value' => 'BARRA DE VALIZAS'),
                array('id' => 4557, 'county_id' => '539', 'value' => 'LA ESMERALDA'),
                array('id' => 4558, 'county_id' => '539', 'value' => 'LA PEDRERA'),
                array('id' => 4559, 'county_id' => '539', 'value' => 'PARALLE'),
                array('id' => 4560, 'county_id' => '539', 'value' => 'PUERTO DE LOS BOTES'),
                array('id' => 4561, 'county_id' => '539', 'value' => 'PUIMAYEN'),
                array('id' => 4562, 'county_id' => '539', 'value' => 'ARACHANIA'),
                array('id' => 4563, 'county_id' => '539', 'value' => 'PTA. RUBIA Y STA. ISABEL DE LA PED'),
                array('id' => 4564, 'county_id' => '539', 'value' => 'PUNTA DEL DIABLO'),
                array('id' => 4565, 'county_id' => '539', 'value' => 'PALMARES DE LA CORONILLA'),
                array('id' => 4566, 'county_id' => '539', 'value' => 'LA RIBIERA'),
                array('id' => 4567, 'county_id' => '539', 'value' => 'PUENTE VALIZAS'),
                array('id' => 4568, 'county_id' => '539', 'value' => 'OCEANIA DEL POLONIO'),
                array('id' => 4569, 'county_id' => '539', 'value' => 'PUEBLO NUEVO'),
                array('id' => 4570, 'county_id' => '539', 'value' => 'TAJAMARES DE LA PEDRERA'),
                array('id' => 4571, 'county_id' => '539', 'value' => 'SAN ANTONIO'),
                array('id' => 4572, 'county_id' => '540', 'value' => 'SALTO'),
                array('id' => 4573, 'county_id' => '540', 'value' => 'BELEN'),
                array('id' => 4574, 'county_id' => '540', 'value' => 'CONSTITUCION'),
                array('id' => 4575, 'county_id' => '540', 'value' => 'FERNANDEZ'),
                array('id' => 4576, 'county_id' => '540', 'value' => 'SAN ANTONIO'),
                array('id' => 4577, 'county_id' => '540', 'value' => 'CHACRAS DE BELEN'),
                array('id' => 4578, 'county_id' => '540', 'value' => 'ALBISU'),
                array('id' => 4579, 'county_id' => '540', 'value' => 'BIASSINI'),
                array('id' => 4580, 'county_id' => '540', 'value' => 'CAMPO DE TODOS'),
                array('id' => 4581, 'county_id' => '540', 'value' => 'CAYETANO'),
                array('id' => 4582, 'county_id' => '540', 'value' => 'CUCHILLA DE GUAVIYU'),
                array('id' => 4583, 'county_id' => '540', 'value' => 'TERMAS DEL DAYMAN'),
                array('id' => 4584, 'county_id' => '540', 'value' => 'PALOMAS'),
                array('id' => 4585, 'county_id' => '540', 'value' => 'PASO DEL PARQUE DEL DAYMAN'),
                array('id' => 4586, 'county_id' => '540', 'value' => 'QUINTANA'),
                array('id' => 4587, 'county_id' => '540', 'value' => 'SARANDI DE ARAPEY'),
                array('id' => 4588, 'county_id' => '540', 'value' => 'SAUCEDO'),
                array('id' => 4589, 'county_id' => '540', 'value' => 'ARENITAS BLANCAS'),
                array('id' => 4590, 'county_id' => '540', 'value' => 'CELESTE'),
                array('id' => 4591, 'county_id' => '540', 'value' => 'CERROS DE VERA'),
                array('id' => 4592, 'county_id' => '540', 'value' => 'GARIBALDI'),
                array('id' => 4593, 'county_id' => '540', 'value' => 'TERMAS DEL ARAPEY'),
                array('id' => 4594, 'county_id' => '540', 'value' => 'LAS FLORES'),
                array('id' => 4595, 'county_id' => '540', 'value' => 'LAURELES'),
                array('id' => 4596, 'county_id' => '540', 'value' => 'LLUVERAS'),
                array('id' => 4597, 'county_id' => '540', 'value' => 'MIGLIARO'),
                array('id' => 4598, 'county_id' => '540', 'value' => 'OLIVERA'),
                array('id' => 4599, 'county_id' => '540', 'value' => 'PASO DE LAS PIEDRAS DE ARERUNGUA'),
                array('id' => 4600, 'county_id' => '540', 'value' => 'PUNTAS DE VALENTIN'),
                array('id' => 4601, 'county_id' => '540', 'value' => 'RINCON DE VALENTIN'),
                array('id' => 4602, 'county_id' => '540', 'value' => 'COLONIA 18 DE JULIO'),
                array('id' => 4603, 'county_id' => '540', 'value' => 'PARQUE JOSE LUIS'),
                array('id' => 4604, 'county_id' => '540', 'value' => 'COLONIA ITAPEBI'),
                array('id' => 4605, 'county_id' => '540', 'value' => 'GUAVIYU DE ARAPEY'),
                array('id' => 4606, 'county_id' => '540', 'value' => 'RUSSO'),
                array('id' => 4607, 'county_id' => '540', 'value' => 'PASO CEMENTERIO'),
                array('id' => 4608, 'county_id' => '540', 'value' => 'OSIMANI Y LLERENA'),
                array('id' => 4609, 'county_id' => '541', 'value' => 'SAN JOSE DE MAYO'),
                array('id' => 4610, 'county_id' => '541', 'value' => 'LIBERTAD'),
                array('id' => 4611, 'county_id' => '541', 'value' => 'DELTA DEL TIGRE Y VILLAS'),
                array('id' => 4612, 'county_id' => '541', 'value' => 'RODRIGUEZ'),
                array('id' => 4613, 'county_id' => '541', 'value' => 'ITUZAINGO'),
                array('id' => 4614, 'county_id' => '541', 'value' => 'SANTA MONICA'),
                array('id' => 4615, 'county_id' => '541', 'value' => 'PUNTAS DE VALDEZ'),
                array('id' => 4616, 'county_id' => '541', 'value' => 'GONZALEZ'),
                array('id' => 4617, 'county_id' => '541', 'value' => 'MAL ABRIGO'),
                array('id' => 4618, 'county_id' => '541', 'value' => 'PLAYA PASCUAL'),
                array('id' => 4619, 'county_id' => '541', 'value' => '18 DE JULIO (PUEBLO NUEVO)'),
                array('id' => 4620, 'county_id' => '541', 'value' => 'RAFAEL PERAZA'),
                array('id' => 4621, 'county_id' => '541', 'value' => 'RAIGON'),
                array('id' => 4622, 'county_id' => '541', 'value' => 'SAFICI (PARQUE POSTEL)'),
                array('id' => 4623, 'county_id' => '541', 'value' => 'JUAN SOLER'),
                array('id' => 4624, 'county_id' => '541', 'value' => 'BOCA DEL CUFRE'),
                array('id' => 4625, 'county_id' => '541', 'value' => 'CAPURRO'),
                array('id' => 4626, 'county_id' => '541', 'value' => 'VILLA MARIA'),
                array('id' => 4627, 'county_id' => '541', 'value' => 'ECILDA PAULLIER'),
                array('id' => 4628, 'county_id' => '541', 'value' => 'KIYU-ORDEIG'),
                array('id' => 4629, 'county_id' => '541', 'value' => 'LA BOYADA'),
                array('id' => 4630, 'county_id' => '541', 'value' => 'CAÑADA GRANDE'),
                array('id' => 4631, 'county_id' => '541', 'value' => 'RINCON DEL PINO'),
                array('id' => 4632, 'county_id' => '541', 'value' => 'SAN GREGORIO'),
                array('id' => 4633, 'county_id' => '541', 'value' => 'SCAVINO'),
                array('id' => 4634, 'county_id' => '541', 'value' => 'MONTE GRANDE'),
                array('id' => 4635, 'county_id' => '541', 'value' => 'CERAMICAS DEL SUR'),
                array('id' => 4636, 'county_id' => '541', 'value' => 'RADIAL'),
                array('id' => 4637, 'county_id' => '541', 'value' => 'COLOLO TINOSA'),
                array('id' => 4638, 'county_id' => '541', 'value' => 'MANGRULLO'),
                array('id' => 4639, 'county_id' => '541', 'value' => 'CARRETA QUEMADA'),
                array('id' => 4640, 'county_id' => '541', 'value' => 'COSTAS DE PEREIRA'),
                array('id' => 4641, 'county_id' => '541', 'value' => 'COLONIA DELTA'),
                array('id' => 4642, 'county_id' => '542', 'value' => 'MERCEDES'),
                array('id' => 4643, 'county_id' => '542', 'value' => 'DOLORES'),
                array('id' => 4644, 'county_id' => '542', 'value' => 'CARDONA'),
                array('id' => 4645, 'county_id' => '542', 'value' => 'JOSE ENRIQUE RODO'),
                array('id' => 4646, 'county_id' => '542', 'value' => 'PALMITAS'),
                array('id' => 4647, 'county_id' => '542', 'value' => 'VILLA SORIANO'),
                array('id' => 4648, 'county_id' => '542', 'value' => 'PALMAR'),
                array('id' => 4649, 'county_id' => '542', 'value' => 'EGAÑA'),
                array('id' => 4650, 'county_id' => '542', 'value' => 'SANTA CATALINA'),
                array('id' => 4651, 'county_id' => '542', 'value' => 'AGRACIADA'),
                array('id' => 4652, 'county_id' => '542', 'value' => 'CASTILLOS'),
                array('id' => 4653, 'county_id' => '542', 'value' => 'RISSO'),
                array('id' => 4654, 'county_id' => '542', 'value' => 'SACACHISPAS'),
                array('id' => 4655, 'county_id' => '542', 'value' => 'CAÑADA NIETO'),
                array('id' => 4656, 'county_id' => '542', 'value' => 'CUCHILLA DEL PERDIDO'),
                array('id' => 4657, 'county_id' => '542', 'value' => 'EL TALA'),
                array('id' => 4658, 'county_id' => '542', 'value' => 'LA CONCORDIA'),
                array('id' => 4659, 'county_id' => '542', 'value' => 'LA LOMA'),
                array('id' => 4660, 'county_id' => '542', 'value' => 'PALO SOLO'),
                array('id' => 4661, 'county_id' => '542', 'value' => 'CHACRAS DE DOLORES'),
                array('id' => 4662, 'county_id' => '542', 'value' => 'COLONIA CONCORDIA'),
                array('id' => 4663, 'county_id' => '542', 'value' => 'PERSEVERANO'),
                array('id' => 4664, 'county_id' => '542', 'value' => 'LARES'),
                array('id' => 4665, 'county_id' => '543', 'value' => 'TACUAREMBO'),
                array('id' => 4666, 'county_id' => '543', 'value' => 'PASO DE LOS TOROS'),
                array('id' => 4667, 'county_id' => '543', 'value' => 'SAN GREGORIO DE POLANCO'),
                array('id' => 4668, 'county_id' => '543', 'value' => 'TAMBORES'),
                array('id' => 4669, 'county_id' => '543', 'value' => 'ACHAR'),
                array('id' => 4670, 'county_id' => '543', 'value' => 'ANSINA'),
                array('id' => 4671, 'county_id' => '543', 'value' => 'CURTINA'),
                array('id' => 4672, 'county_id' => '543', 'value' => 'PASO DEL CERRO'),
                array('id' => 4673, 'county_id' => '543', 'value' => 'CLARA'),
                array('id' => 4674, 'county_id' => '543', 'value' => 'CUCHILLA DEL OMBU'),
                array('id' => 4675, 'county_id' => '543', 'value' => 'LA HILERA'),
                array('id' => 4676, 'county_id' => '543', 'value' => 'LAS TOSCAS'),
                array('id' => 4677, 'county_id' => '543', 'value' => 'PASO BONILLA'),
                array('id' => 4678, 'county_id' => '543', 'value' => 'PUEBLO DE ARRIBA'),
                array('id' => 4679, 'county_id' => '543', 'value' => 'PUEBLO DEL BARRO'),
                array('id' => 4680, 'county_id' => '543', 'value' => 'RINCON DEL BONETE'),
                array('id' => 4681, 'county_id' => '543', 'value' => 'BALNEARIO IPORA'),
                array('id' => 4682, 'county_id' => '543', 'value' => 'PIEDRA SOLA'),
                array('id' => 4683, 'county_id' => '543', 'value' => 'CARDOZO'),
                array('id' => 4684, 'county_id' => '543', 'value' => 'CHAMBERLAIN'),
                array('id' => 4685, 'county_id' => '543', 'value' => 'CUCHILLA DE PERALTA'),
                array('id' => 4686, 'county_id' => '543', 'value' => 'LA PEDRERA'),
                array('id' => 4687, 'county_id' => '543', 'value' => 'LAURELES'),
                array('id' => 4688, 'county_id' => '543', 'value' => 'MONTEVIDEO CHICO'),
                array('id' => 4689, 'county_id' => '543', 'value' => 'CERRO DE PASTOREO'),
                array('id' => 4690, 'county_id' => '543', 'value' => 'SAUCE DE BATOVI'),
                array('id' => 4691, 'county_id' => '543', 'value' => 'PUNTAS DE CINCO SAUCES'),
                array('id' => 4692, 'county_id' => '543', 'value' => 'RINCON DE PEREIRA'),
                array('id' => 4693, 'county_id' => '543', 'value' => 'PUNTA DE CARRETERA'),
                array('id' => 4694, 'county_id' => '543', 'value' => 'CRUZ DE LOS CAMINOS'),
                array('id' => 4695, 'county_id' => '544', 'value' => 'TREINTA Y TRES'),
                array('id' => 4696, 'county_id' => '544', 'value' => 'SANTA CLARA DE OLIMAR'),
                array('id' => 4697, 'county_id' => '544', 'value' => 'VERGARA'),
                array('id' => 4698, 'county_id' => '544', 'value' => 'ARROZAL TREINTA Y TRES'),
                array('id' => 4699, 'county_id' => '544', 'value' => 'GRAL. ENRIQUE MARTINEZ'),
                array('id' => 4700, 'county_id' => '544', 'value' => 'VILLA SARA'),
                array('id' => 4701, 'county_id' => '544', 'value' => 'CERRO CHATO'),
                array('id' => 4702, 'county_id' => '544', 'value' => 'ESTACION RINCON'),
                array('id' => 4703, 'county_id' => '544', 'value' => 'ISLA PATRULLA (MARIA ISABEL)'),
                array('id' => 4704, 'county_id' => '544', 'value' => 'VALENTINES'),
                array('id' => 4705, 'county_id' => '544', 'value' => 'POBLADO ALONZO'),
                array('id' => 4706, 'county_id' => '544', 'value' => 'ARROCERA RINCON'),
                array('id' => 4707, 'county_id' => '544', 'value' => 'ARROCERA LOS CEIBOS'),
                array('id' => 4708, 'county_id' => '544', 'value' => 'MARIA ALBINA'),
                array('id' => 4709, 'county_id' => '544', 'value' => 'MENDIZABAL (EL ORO)'),
                array('id' => 4710, 'county_id' => '544', 'value' => 'PUNTAS DEL PARAO'),
                array('id' => 4711, 'county_id' => '544', 'value' => 'VILLA PASSANO'),
                array('id' => 4712, 'county_id' => '544', 'value' => 'EJIDO DE TREINTA Y TRES'),
                array('id' => 4713, 'county_id' => '544', 'value' => 'EL BELLACO'),
                array('id' => 4714, 'county_id' => '544', 'value' => 'ARROCERA LOS TEROS'),
                array('id' => 4715, 'county_id' => '544', 'value' => 'ARROCERA BONOMO'),
                array('id' => 4716, 'county_id' => '544', 'value' => 'ARROCERA EL TIGRE'),
                array('id' => 4717, 'county_id' => '544', 'value' => 'ARROCERA LA CATUMBERA'),
                array('id' => 4718, 'county_id' => '544', 'value' => 'ARROCERA LA QUERENCIA'),
                array('id' => 4719, 'county_id' => '544', 'value' => 'ARROCERA LAS PALMAS'),
                array('id' => 4720, 'county_id' => '544', 'value' => 'ARROCERA MINI'),
                array('id' => 4721, 'county_id' => '544', 'value' => 'ARROCERA PROCIPA'),
                array('id' => 4722, 'county_id' => '544', 'value' => 'ARROCERA SAN FERNANDO'),
                array('id' => 4723, 'county_id' => '544', 'value' => 'ARROCERA SANTA FE'),
                array('id' => 4724, 'county_id' => '544', 'value' => 'ARROCERA ZAPATA')
            )
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('cities_table_5', function (Blueprint $table) {
            //
        });
    }
}
